package it.iubar.paghe.logic.common.auto;

/** Class _EnpalsTipolavoratore was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EnpalsTipolavoratore extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOLAVORATORE_PROPERTY = "idtipolavoratore";

    public static final String IDTIPOLAVORATORE_PK_COLUMN = "IDTIPOLAVORATORE";

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }
    
    
    public void setIdtipolavoratore(Short idtipolavoratore) {
        writeProperty("idtipolavoratore", idtipolavoratore);
    }
    public Short getIdtipolavoratore() {
        return (Short)readProperty("idtipolavoratore");
    }
    
    
}
