package it.iubar.paghe.logic.common.auto;

import java.util.List;

/** Class _F24Tipoaltroente was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _F24Tipoaltroente extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDENTE_PROPERTY = "idente";
    public static final String CAUSALEALTROENTE_ARRAY_PROPERTY = "causalealtroenteArray";

    public static final String IDENTE_PK_COLUMN = "IDENTE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }
    
    
    public String getIdente() {
        return (String)readProperty("idente");
    }
    
    
    public void addToCausalealtroenteArray(it.iubar.paghe.logic.common.F24Causalealtroente obj) {
        addToManyTarget("causalealtroenteArray", obj, true);
    }
    public void removeFromCausalealtroenteArray(it.iubar.paghe.logic.common.F24Causalealtroente obj) {
        removeToManyTarget("causalealtroenteArray", obj, true);
    }
    public List getCausalealtroenteArray() {
        return (List)readProperty("causalealtroenteArray");
    }
    
    
}
