package it.iubar.paghe.logic.common.auto;

/** Class _F24Concessione was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _F24Concessione extends org.apache.cayenne.CayenneDataObject {

    public static final String CONCESSIONE_PROPERTY = "concessione";
    public static final String IDCONCESSIONE_PROPERTY = "idconcessione";

    public static final String IDCONCESSIONE_PK_COLUMN = "IDCONCESSIONE";

    public String getConcessione() {
        return (String)readProperty("concessione");
    }
    
    
    public Integer getIdconcessione() {
        return (Integer)readProperty("idconcessione");
    }
    
    
}
