package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.CoEnteprevidenziale;
import it.iubar.paghe.logic.paghe.InpsAliquotaarea;
import it.iubar.paghe.logic.paghe.InpsAliquotatipolavoratore;
import it.iubar.paghe.logic.paghe.InpsTipolavoratore;
import it.iubar.paghe.logic.paghe.Posizioneprevidenziale;
import it.iubar.paghe.logic.paghe.Profiloprevidenziale;

/**
 * Class _Aliquotaprevidenziale was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Aliquotaprevidenziale extends CayenneDataObject {

    public static final String ALIQUOTAAGGIUNTIVA_PROPERTY = "aliquotaaggiuntiva";
    public static final String ALIQUOTATOTDATORE_PROPERTY = "aliquotatotdatore";
    public static final String ALIQUOTATOTLAV_PROPERTY = "aliquotatotlav";
    public static final String CIG_PROPERTY = "cig";
    public static final String CIGS_PROPERTY = "cigs";
    public static final String CIGS2_PROPERTY = "cigs2";
    public static final String CTRADD1_PROPERTY = "ctradd1";
    public static final String CTRADD2_PROPERTY = "ctradd2";
    public static final String CUAF_PROPERTY = "cuaf";
    public static final String CUSTOM_PROPERTY = "custom";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String DS_PROPERTY = "ds";
    public static final String DS2_PROPERTY = "ds2";
    public static final String DS3_PROPERTY = "ds3";
    public static final String FI1_PROPERTY = "fi1";
    public static final String FI2_PROPERTY = "fi2";
    public static final String IDALIQUOTAPREVIDENZIALE_PROPERTY = "idaliquotaprevidenziale";
    public static final String IDALIQUOTATIPOLAV_PROPERTY = "idaliquotatipolav";
    public static final String IDAREA_PROPERTY = "idarea";
    public static final String IDENTEPREVIDENZIALE_PROPERTY = "identeprevidenziale";
    public static final String IDINPSTIPOLAVORATORE_PROPERTY = "idinpstipolavoratore";
    public static final String INPSTABELLA_PROPERTY = "inpstabella";
    public static final String IVS_PROPERTY = "ivs";
    public static final String IVS2_PROPERTY = "ivs2";
    public static final String MALATTIA_PROPERTY = "malattia";
    public static final String MATERNITA_PROPERTY = "maternita";
    public static final String MOBILITA_PROPERTY = "mobilita";
    public static final String NOTE_PROPERTY = "note";
    public static final String PRCT_PROPERTY = "prct";
    public static final String TFR_PROPERTY = "tfr";
    public static final String ULTIMAMODIFICA_PROPERTY = "ultimamodifica";
    public static final String ULTIMAMODIFICAUSER_PROPERTY = "ultimamodificauser";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String POSIZIONEPREVIDENZIALE_ARRAY_PROPERTY = "posizioneprevidenzialeArray";
    public static final String PROFILOPREVIDENZ_ARRAY_PROPERTY = "profiloprevidenzArray";
    public static final String TO_CO_ENTEPREVIDENZIALE_PROPERTY = "toCoEnteprevidenziale";
    public static final String TO_INPS_ALIQUOTAAREA_PROPERTY = "toInpsAliquotaarea";
    public static final String TO_INPS_ALIQUOTATIPOLAV_PROPERTY = "toInpsAliquotatipolav";
    public static final String TO_INPS_TIPOLAVORATORE_PROPERTY = "toInpsTipolavoratore";

    public static final String IDALIQUOTAPREVIDENZIALE_PK_COLUMN = "IDALIQUOTAPREVIDENZIALE";

    public void setAliquotaaggiuntiva(BigDecimal aliquotaaggiuntiva) {
        writeProperty("aliquotaaggiuntiva", aliquotaaggiuntiva);
    }
    public BigDecimal getAliquotaaggiuntiva() {
        return (BigDecimal)readProperty("aliquotaaggiuntiva");
    }

    public void setAliquotatotdatore(BigDecimal aliquotatotdatore) {
        writeProperty("aliquotatotdatore", aliquotatotdatore);
    }
    public BigDecimal getAliquotatotdatore() {
        return (BigDecimal)readProperty("aliquotatotdatore");
    }

    public void setAliquotatotlav(BigDecimal aliquotatotlav) {
        writeProperty("aliquotatotlav", aliquotatotlav);
    }
    public BigDecimal getAliquotatotlav() {
        return (BigDecimal)readProperty("aliquotatotlav");
    }

    public void setCig(BigDecimal cig) {
        writeProperty("cig", cig);
    }
    public BigDecimal getCig() {
        return (BigDecimal)readProperty("cig");
    }

    public void setCigs(BigDecimal cigs) {
        writeProperty("cigs", cigs);
    }
    public BigDecimal getCigs() {
        return (BigDecimal)readProperty("cigs");
    }

    public void setCigs2(BigDecimal cigs2) {
        writeProperty("cigs2", cigs2);
    }
    public BigDecimal getCigs2() {
        return (BigDecimal)readProperty("cigs2");
    }

    public void setCtradd1(BigDecimal ctradd1) {
        writeProperty("ctradd1", ctradd1);
    }
    public BigDecimal getCtradd1() {
        return (BigDecimal)readProperty("ctradd1");
    }

    public void setCtradd2(BigDecimal ctradd2) {
        writeProperty("ctradd2", ctradd2);
    }
    public BigDecimal getCtradd2() {
        return (BigDecimal)readProperty("ctradd2");
    }

    public void setCuaf(BigDecimal cuaf) {
        writeProperty("cuaf", cuaf);
    }
    public BigDecimal getCuaf() {
        return (BigDecimal)readProperty("cuaf");
    }

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setDs(BigDecimal ds) {
        writeProperty("ds", ds);
    }
    public BigDecimal getDs() {
        return (BigDecimal)readProperty("ds");
    }

    public void setDs2(BigDecimal ds2) {
        writeProperty("ds2", ds2);
    }
    public BigDecimal getDs2() {
        return (BigDecimal)readProperty("ds2");
    }

    public void setDs3(BigDecimal ds3) {
        writeProperty("ds3", ds3);
    }
    public BigDecimal getDs3() {
        return (BigDecimal)readProperty("ds3");
    }

    public void setFi1(BigDecimal fi1) {
        writeProperty("fi1", fi1);
    }
    public BigDecimal getFi1() {
        return (BigDecimal)readProperty("fi1");
    }

    public void setFi2(BigDecimal fi2) {
        writeProperty("fi2", fi2);
    }
    public BigDecimal getFi2() {
        return (BigDecimal)readProperty("fi2");
    }

    public void setIdaliquotaprevidenziale(Integer idaliquotaprevidenziale) {
        writeProperty("idaliquotaprevidenziale", idaliquotaprevidenziale);
    }
    public Integer getIdaliquotaprevidenziale() {
        return (Integer)readProperty("idaliquotaprevidenziale");
    }

    public void setIdaliquotatipolav(Integer idaliquotatipolav) {
        writeProperty("idaliquotatipolav", idaliquotatipolav);
    }
    public Integer getIdaliquotatipolav() {
        return (Integer)readProperty("idaliquotatipolav");
    }

    public void setIdarea(Integer idarea) {
        writeProperty("idarea", idarea);
    }
    public Integer getIdarea() {
        return (Integer)readProperty("idarea");
    }

    public void setIdenteprevidenziale(Short identeprevidenziale) {
        writeProperty("identeprevidenziale", identeprevidenziale);
    }
    public Short getIdenteprevidenziale() {
        return (Short)readProperty("identeprevidenziale");
    }

    public void setIdinpstipolavoratore(String idinpstipolavoratore) {
        writeProperty("idinpstipolavoratore", idinpstipolavoratore);
    }
    public String getIdinpstipolavoratore() {
        return (String)readProperty("idinpstipolavoratore");
    }

    public void setInpstabella(String inpstabella) {
        writeProperty("inpstabella", inpstabella);
    }
    public String getInpstabella() {
        return (String)readProperty("inpstabella");
    }

    public void setIvs(BigDecimal ivs) {
        writeProperty("ivs", ivs);
    }
    public BigDecimal getIvs() {
        return (BigDecimal)readProperty("ivs");
    }

    public void setIvs2(BigDecimal ivs2) {
        writeProperty("ivs2", ivs2);
    }
    public BigDecimal getIvs2() {
        return (BigDecimal)readProperty("ivs2");
    }

    public void setMalattia(BigDecimal malattia) {
        writeProperty("malattia", malattia);
    }
    public BigDecimal getMalattia() {
        return (BigDecimal)readProperty("malattia");
    }

    public void setMaternita(BigDecimal maternita) {
        writeProperty("maternita", maternita);
    }
    public BigDecimal getMaternita() {
        return (BigDecimal)readProperty("maternita");
    }

    public void setMobilita(BigDecimal mobilita) {
        writeProperty("mobilita", mobilita);
    }
    public BigDecimal getMobilita() {
        return (BigDecimal)readProperty("mobilita");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setPrct(BigDecimal prct) {
        writeProperty("prct", prct);
    }
    public BigDecimal getPrct() {
        return (BigDecimal)readProperty("prct");
    }

    public void setTfr(BigDecimal tfr) {
        writeProperty("tfr", tfr);
    }
    public BigDecimal getTfr() {
        return (BigDecimal)readProperty("tfr");
    }

    public void setUltimamodifica(Date ultimamodifica) {
        writeProperty("ultimamodifica", ultimamodifica);
    }
    public Date getUltimamodifica() {
        return (Date)readProperty("ultimamodifica");
    }

    public void setUltimamodificauser(String ultimamodificauser) {
        writeProperty("ultimamodificauser", ultimamodificauser);
    }
    public String getUltimamodificauser() {
        return (String)readProperty("ultimamodificauser");
    }

    public void setValidoal(Date validoal) {
        writeProperty("validoal", validoal);
    }
    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToPosizioneprevidenzialeArray(Posizioneprevidenziale obj) {
        addToManyTarget("posizioneprevidenzialeArray", obj, true);
    }
    public void removeFromPosizioneprevidenzialeArray(Posizioneprevidenziale obj) {
        removeToManyTarget("posizioneprevidenzialeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizioneprevidenziale> getPosizioneprevidenzialeArray() {
        return (List<Posizioneprevidenziale>)readProperty("posizioneprevidenzialeArray");
    }


    public void addToProfiloprevidenzArray(Profiloprevidenziale obj) {
        addToManyTarget("profiloprevidenzArray", obj, true);
    }
    public void removeFromProfiloprevidenzArray(Profiloprevidenziale obj) {
        removeToManyTarget("profiloprevidenzArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profiloprevidenziale> getProfiloprevidenzArray() {
        return (List<Profiloprevidenziale>)readProperty("profiloprevidenzArray");
    }


    public void setToCoEnteprevidenziale(CoEnteprevidenziale toCoEnteprevidenziale) {
        setToOneTarget("toCoEnteprevidenziale", toCoEnteprevidenziale, true);
    }

    public CoEnteprevidenziale getToCoEnteprevidenziale() {
        return (CoEnteprevidenziale)readProperty("toCoEnteprevidenziale");
    }


    public void setToInpsAliquotaarea(InpsAliquotaarea toInpsAliquotaarea) {
        setToOneTarget("toInpsAliquotaarea", toInpsAliquotaarea, true);
    }

    public InpsAliquotaarea getToInpsAliquotaarea() {
        return (InpsAliquotaarea)readProperty("toInpsAliquotaarea");
    }


    public void setToInpsAliquotatipolav(InpsAliquotatipolavoratore toInpsAliquotatipolav) {
        setToOneTarget("toInpsAliquotatipolav", toInpsAliquotatipolav, true);
    }

    public InpsAliquotatipolavoratore getToInpsAliquotatipolav() {
        return (InpsAliquotatipolavoratore)readProperty("toInpsAliquotatipolav");
    }


    public void setToInpsTipolavoratore(InpsTipolavoratore toInpsTipolavoratore) {
        setToOneTarget("toInpsTipolavoratore", toInpsTipolavoratore, true);
    }

    public InpsTipolavoratore getToInpsTipolavoratore() {
        return (InpsTipolavoratore)readProperty("toInpsTipolavoratore");
    }


}
