package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Subordinato;
import it.iubar.paghe.logic.paghe.CoTipocontratto;
import it.iubar.paghe.logic.paghe.InpsTipoassunzione;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;

/**
 * Class _Assunzione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Assunzione extends CayenneDataObject {

    public static final String AGRIGGPREVISTE_PROPERTY = "agriggpreviste";
    public static final String AGRITIPOLAVORAZ_PROPERTY = "agritipolavoraz";
    public static final String ASSUNZIONEDATA_PROPERTY = "assunzionedata";
    public static final String DESCFORZAMAGGIORE_PROPERTY = "descforzamaggiore";
    public static final String FINEPROROGA_PROPERTY = "fineproroga";
    public static final String FORZAMAGGIORE_PROPERTY = "forzamaggiore";
    public static final String IDASSUNZIONE_PROPERTY = "idassunzione";
    public static final String IDIMPRESADISTACCO_PROPERTY = "idimpresadistacco";
    public static final String IDINPSTIPOASSUNZIONE_PROPERTY = "idinpstipoassunzione";
    public static final String INPSMATRICOLAPROVENIENZA_PROPERTY = "inpsmatricolaprovenienza";
    public static final String SCADENZACONTRATTO_PROPERTY = "scadenzacontratto";
    public static final String TEMPODETERMINATO_PROPERTY = "tempodeterminato";
    public static final String TRASFORMAZIONE_PROPERTY = "trasformazione";
    public static final String SUBORDINATO_ARRAY_PROPERTY = "subordinatoArray";
    public static final String TO_CO_TIPO_CONTRATTO_PROPERTY = "toCoTipoContratto";
    public static final String TO_INPS_TIPOASSUNZIONE_PROPERTY = "toInpsTipoassunzione";
    public static final String TO_POSIZIONESUBORDINATO_PROPERTY = "toPosizionesubordinato";

    public static final String IDASSUNZIONE_PK_COLUMN = "IDASSUNZIONE";

    public void setAgriggpreviste(Short agriggpreviste) {
        writeProperty("agriggpreviste", agriggpreviste);
    }
    public Short getAgriggpreviste() {
        return (Short)readProperty("agriggpreviste");
    }

    public void setAgritipolavoraz(String agritipolavoraz) {
        writeProperty("agritipolavoraz", agritipolavoraz);
    }
    public String getAgritipolavoraz() {
        return (String)readProperty("agritipolavoraz");
    }

    public void setAssunzionedata(Date assunzionedata) {
        writeProperty("assunzionedata", assunzionedata);
    }
    public Date getAssunzionedata() {
        return (Date)readProperty("assunzionedata");
    }

    public void setDescforzamaggiore(String descforzamaggiore) {
        writeProperty("descforzamaggiore", descforzamaggiore);
    }
    public String getDescforzamaggiore() {
        return (String)readProperty("descforzamaggiore");
    }

    public void setFineproroga(Date fineproroga) {
        writeProperty("fineproroga", fineproroga);
    }
    public Date getFineproroga() {
        return (Date)readProperty("fineproroga");
    }

    public void setForzamaggiore(Short forzamaggiore) {
        writeProperty("forzamaggiore", forzamaggiore);
    }
    public Short getForzamaggiore() {
        return (Short)readProperty("forzamaggiore");
    }

    public void setIdassunzione(Integer idassunzione) {
        writeProperty("idassunzione", idassunzione);
    }
    public Integer getIdassunzione() {
        return (Integer)readProperty("idassunzione");
    }

    public void setIdimpresadistacco(Integer idimpresadistacco) {
        writeProperty("idimpresadistacco", idimpresadistacco);
    }
    public Integer getIdimpresadistacco() {
        return (Integer)readProperty("idimpresadistacco");
    }

    public void setIdinpstipoassunzione(String idinpstipoassunzione) {
        writeProperty("idinpstipoassunzione", idinpstipoassunzione);
    }
    public String getIdinpstipoassunzione() {
        return (String)readProperty("idinpstipoassunzione");
    }

    public void setInpsmatricolaprovenienza(String inpsmatricolaprovenienza) {
        writeProperty("inpsmatricolaprovenienza", inpsmatricolaprovenienza);
    }
    public String getInpsmatricolaprovenienza() {
        return (String)readProperty("inpsmatricolaprovenienza");
    }

    public void setScadenzacontratto(Date scadenzacontratto) {
        writeProperty("scadenzacontratto", scadenzacontratto);
    }
    public Date getScadenzacontratto() {
        return (Date)readProperty("scadenzacontratto");
    }

    public void setTempodeterminato(Short tempodeterminato) {
        writeProperty("tempodeterminato", tempodeterminato);
    }
    public Short getTempodeterminato() {
        return (Short)readProperty("tempodeterminato");
    }

    public void setTrasformazione(Date trasformazione) {
        writeProperty("trasformazione", trasformazione);
    }
    public Date getTrasformazione() {
        return (Date)readProperty("trasformazione");
    }

    public void addToSubordinatoArray(Subordinato obj) {
        addToManyTarget("subordinatoArray", obj, true);
    }
    public void removeFromSubordinatoArray(Subordinato obj) {
        removeToManyTarget("subordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Subordinato> getSubordinatoArray() {
        return (List<Subordinato>)readProperty("subordinatoArray");
    }


    public void setToCoTipoContratto(CoTipocontratto toCoTipoContratto) {
        setToOneTarget("toCoTipoContratto", toCoTipoContratto, true);
    }

    public CoTipocontratto getToCoTipoContratto() {
        return (CoTipocontratto)readProperty("toCoTipoContratto");
    }


    public void setToInpsTipoassunzione(InpsTipoassunzione toInpsTipoassunzione) {
        setToOneTarget("toInpsTipoassunzione", toInpsTipoassunzione, true);
    }

    public InpsTipoassunzione getToInpsTipoassunzione() {
        return (InpsTipoassunzione)readProperty("toInpsTipoassunzione");
    }


    public void addToToPosizionesubordinato(Posizionesubordinato obj) {
        addToManyTarget("toPosizionesubordinato", obj, true);
    }
    public void removeFromToPosizionesubordinato(Posizionesubordinato obj) {
        removeToManyTarget("toPosizionesubordinato", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionesubordinato> getToPosizionesubordinato() {
        return (List<Posizionesubordinato>)readProperty("toPosizionesubordinato");
    }


}
