package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Cigsacredaltre;
import it.iubar.paghe.logic.paghe.Gestionecig;
import it.iubar.paghe.logic.paghe.Orecongcigs;

/**
 * Class _Cigsacredito was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Cigsacredito extends CayenneDataObject {

    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String INDSTRAORDINARIA_PROPERTY = "indstraordinaria";
    public static final String CIGS_ACRED_ALTRE_ARRAY_PROPERTY = "cigsACredAltreArray";
    public static final String ORE_CONG_CIGS_ARRAY_PROPERTY = "oreCongCigsArray";
    public static final String TO_GESTIONE_GIG_PROPERTY = "toGestioneGig";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIndstraordinaria(BigDecimal indstraordinaria) {
        writeProperty("indstraordinaria", indstraordinaria);
    }
    public BigDecimal getIndstraordinaria() {
        return (BigDecimal)readProperty("indstraordinaria");
    }

    public void addToCigsACredAltreArray(Cigsacredaltre obj) {
        addToManyTarget("cigsACredAltreArray", obj, true);
    }
    public void removeFromCigsACredAltreArray(Cigsacredaltre obj) {
        removeToManyTarget("cigsACredAltreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cigsacredaltre> getCigsACredAltreArray() {
        return (List<Cigsacredaltre>)readProperty("cigsACredAltreArray");
    }


    public void addToOreCongCigsArray(Orecongcigs obj) {
        addToManyTarget("oreCongCigsArray", obj, true);
    }
    public void removeFromOreCongCigsArray(Orecongcigs obj) {
        removeToManyTarget("oreCongCigsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Orecongcigs> getOreCongCigsArray() {
        return (List<Orecongcigs>)readProperty("oreCongCigsArray");
    }


    public void setToGestioneGig(Gestionecig toGestioneGig) {
        setToOneTarget("toGestioneGig", toGestioneGig, true);
    }

    public Gestionecig getToGestioneGig() {
        return (Gestionecig)readProperty("toGestioneGig");
    }


}
