package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _CnceOpzioneprevcomp was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CnceOpzioneprevcomp extends CayenneDataObject {

    public static final String CODFONDO_PROPERTY = "codfondo";
    public static final String DATASOTTOSCRTFR_PROPERTY = "datasottoscrtfr";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDTIPOTFR_PROPERTY = "idtipotfr";
    public static final String NUMALBOCOVIP_PROPERTY = "numalbocovip";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setCodfondo(String codfondo) {
        writeProperty("codfondo", codfondo);
    }
    public String getCodfondo() {
        return (String)readProperty("codfondo");
    }

    public void setDatasottoscrtfr(Date datasottoscrtfr) {
        writeProperty("datasottoscrtfr", datasottoscrtfr);
    }
    public Date getDatasottoscrtfr() {
        return (Date)readProperty("datasottoscrtfr");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdtipotfr(String idtipotfr) {
        writeProperty("idtipotfr", idtipotfr);
    }
    public String getIdtipotfr() {
        return (String)readProperty("idtipotfr");
    }

    public void setNumalbocovip(Integer numalbocovip) {
        writeProperty("numalbocovip", numalbocovip);
    }
    public Integer getNumalbocovip() {
        return (Integer)readProperty("numalbocovip");
    }

}
