package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _CnceOpzionetfr was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CnceOpzionetfr extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOTFR_PROPERTY = "idtipotfr";

    public static final String IDTIPOTFR_PK_COLUMN = "IDTIPOTFR";

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setIdtipotfr(String idtipotfr) {
        writeProperty("idtipotfr", idtipotfr);
    }
    public String getIdtipotfr() {
        return (String)readProperty("idtipotfr");
    }

}
