package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.CoArgomento;
import it.iubar.paghe.logic.paghe.CoEnteprevidenziale;
import it.iubar.paghe.logic.paghe.CoTipo;
import it.iubar.paghe.logic.paghe.CoTipocessazione;
import it.iubar.paghe.logic.paghe.CoTipocomunicazione;
import it.iubar.paghe.logic.paghe.CoTipocontratto;
import it.iubar.paghe.logic.paghe.CoTipotrasferimento;
import it.iubar.paghe.logic.paghe.CoTrasformazione;
import it.iubar.paghe.logic.paghe.Dichiarazione;

/**
 * Class _Co was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Co extends CayenneDataObject {

    public static final String ASSUNZIONEDATA_PROPERTY = "assunzionedata";
    public static final String IDDICHIARAZIONE_PROPERTY = "iddichiarazione";
    public static final String IDENTEPREVIDENZIALE_PROPERTY = "identeprevidenziale";
    public static final String IDESITO_PROPERTY = "idesito";
    public static final String IDEXPORT_PROPERTY = "idexport";
    public static final String IDPROFESSIONE_PROPERTY = "idprofessione";
    public static final String IDSOGGETTO_PROPERTY = "idsoggetto";
    public static final String IDSOGGETTOABILITATO_PROPERTY = "idsoggettoabilitato";
    public static final String IDTIPOCESSAZIONE_PROPERTY = "idtipocessazione";
    public static final String IDTIPOCO_PROPERTY = "idtipoco";
    public static final String IDTIPOCONTRATTO_PROPERTY = "idtipocontratto";
    public static final String IDTITOLOSTUDIO_PROPERTY = "idtitolostudio";
    public static final String IDTRASFORMAZIONE_PROPERTY = "idtrasformazione";
    public static final String TO_CO_ARGOMENTO_PROPERTY = "toCoArgomento";
    public static final String TO_CO_ENTEPREVIDENZIALE_PROPERTY = "toCoEnteprevidenziale";
    public static final String TO_CO_TIPO_PROPERTY = "toCoTipo";
    public static final String TO_CO_TIPOCESSAZIONE_PROPERTY = "toCoTipocessazione";
    public static final String TO_CO_TIPOCOMUNICAZIONE_PROPERTY = "toCoTipocomunicazione";
    public static final String TO_CO_TIPOCONTRATTO_PROPERTY = "toCoTipocontratto";
    public static final String TO_CO_TIPOTRASFERIMENTO_PROPERTY = "toCoTipotrasferimento";
    public static final String TO_CO_TRASFORMAZIONE_PROPERTY = "toCoTrasformazione";
    public static final String TO_DICHIARAZIONE_PROPERTY = "toDichiarazione";

    public static final String IDDICHIARAZIONE_PK_COLUMN = "IDDICHIARAZIONE";

    public void setAssunzionedata(Date assunzionedata) {
        writeProperty("assunzionedata", assunzionedata);
    }
    public Date getAssunzionedata() {
        return (Date)readProperty("assunzionedata");
    }

    public void setIddichiarazione(Integer iddichiarazione) {
        writeProperty("iddichiarazione", iddichiarazione);
    }
    public Integer getIddichiarazione() {
        return (Integer)readProperty("iddichiarazione");
    }

    public void setIdenteprevidenziale(Short identeprevidenziale) {
        writeProperty("identeprevidenziale", identeprevidenziale);
    }
    public Short getIdenteprevidenziale() {
        return (Short)readProperty("identeprevidenziale");
    }

    public void setIdesito(Integer idesito) {
        writeProperty("idesito", idesito);
    }
    public Integer getIdesito() {
        return (Integer)readProperty("idesito");
    }

    public void setIdexport(Integer idexport) {
        writeProperty("idexport", idexport);
    }
    public Integer getIdexport() {
        return (Integer)readProperty("idexport");
    }

    public void setIdprofessione(String idprofessione) {
        writeProperty("idprofessione", idprofessione);
    }
    public String getIdprofessione() {
        return (String)readProperty("idprofessione");
    }

    public void setIdsoggetto(Integer idsoggetto) {
        writeProperty("idsoggetto", idsoggetto);
    }
    public Integer getIdsoggetto() {
        return (Integer)readProperty("idsoggetto");
    }

    public void setIdsoggettoabilitato(String idsoggettoabilitato) {
        writeProperty("idsoggettoabilitato", idsoggettoabilitato);
    }
    public String getIdsoggettoabilitato() {
        return (String)readProperty("idsoggettoabilitato");
    }

    public void setIdtipocessazione(String idtipocessazione) {
        writeProperty("idtipocessazione", idtipocessazione);
    }
    public String getIdtipocessazione() {
        return (String)readProperty("idtipocessazione");
    }

    public void setIdtipoco(Short idtipoco) {
        writeProperty("idtipoco", idtipoco);
    }
    public Short getIdtipoco() {
        return (Short)readProperty("idtipoco");
    }

    public void setIdtipocontratto(String idtipocontratto) {
        writeProperty("idtipocontratto", idtipocontratto);
    }
    public String getIdtipocontratto() {
        return (String)readProperty("idtipocontratto");
    }

    public void setIdtitolostudio(String idtitolostudio) {
        writeProperty("idtitolostudio", idtitolostudio);
    }
    public String getIdtitolostudio() {
        return (String)readProperty("idtitolostudio");
    }

    public void setIdtrasformazione(String idtrasformazione) {
        writeProperty("idtrasformazione", idtrasformazione);
    }
    public String getIdtrasformazione() {
        return (String)readProperty("idtrasformazione");
    }

    public void setToCoArgomento(CoArgomento toCoArgomento) {
        setToOneTarget("toCoArgomento", toCoArgomento, true);
    }

    public CoArgomento getToCoArgomento() {
        return (CoArgomento)readProperty("toCoArgomento");
    }


    public void setToCoEnteprevidenziale(CoEnteprevidenziale toCoEnteprevidenziale) {
        setToOneTarget("toCoEnteprevidenziale", toCoEnteprevidenziale, true);
    }

    public CoEnteprevidenziale getToCoEnteprevidenziale() {
        return (CoEnteprevidenziale)readProperty("toCoEnteprevidenziale");
    }


    public void setToCoTipo(CoTipo toCoTipo) {
        setToOneTarget("toCoTipo", toCoTipo, true);
    }

    public CoTipo getToCoTipo() {
        return (CoTipo)readProperty("toCoTipo");
    }


    public void setToCoTipocessazione(CoTipocessazione toCoTipocessazione) {
        setToOneTarget("toCoTipocessazione", toCoTipocessazione, true);
    }

    public CoTipocessazione getToCoTipocessazione() {
        return (CoTipocessazione)readProperty("toCoTipocessazione");
    }


    public void setToCoTipocomunicazione(CoTipocomunicazione toCoTipocomunicazione) {
        setToOneTarget("toCoTipocomunicazione", toCoTipocomunicazione, true);
    }

    public CoTipocomunicazione getToCoTipocomunicazione() {
        return (CoTipocomunicazione)readProperty("toCoTipocomunicazione");
    }


    public void setToCoTipocontratto(CoTipocontratto toCoTipocontratto) {
        setToOneTarget("toCoTipocontratto", toCoTipocontratto, true);
    }

    public CoTipocontratto getToCoTipocontratto() {
        return (CoTipocontratto)readProperty("toCoTipocontratto");
    }


    public void setToCoTipotrasferimento(CoTipotrasferimento toCoTipotrasferimento) {
        setToOneTarget("toCoTipotrasferimento", toCoTipotrasferimento, true);
    }

    public CoTipotrasferimento getToCoTipotrasferimento() {
        return (CoTipotrasferimento)readProperty("toCoTipotrasferimento");
    }


    public void setToCoTrasformazione(CoTrasformazione toCoTrasformazione) {
        setToOneTarget("toCoTrasformazione", toCoTrasformazione, true);
    }

    public CoTrasformazione getToCoTrasformazione() {
        return (CoTrasformazione)readProperty("toCoTrasformazione");
    }


    public void setToDichiarazione(Dichiarazione toDichiarazione) {
        setToOneTarget("toDichiarazione", toDichiarazione, true);
    }

    public Dichiarazione getToDichiarazione() {
        return (Dichiarazione)readProperty("toDichiarazione");
    }


}
