package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Contrattorateovalore;
import it.iubar.paghe.logic.paghe.Contrattoscatto;

/**
 * Class _Contrattoanzianita was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattoanzianita extends CayenneDataObject {

    public static final String ANZIANITAA_PROPERTY = "anzianitaa";
    public static final String ANZIANITADA_PROPERTY = "anzianitada";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDANZIANITA_PROPERTY = "idanzianita";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDUNITAMISURA_PROPERTY = "idunitamisura";
    public static final String CONTRATTORATEOVALORE_ARRAY_PROPERTY = "contrattorateovaloreArray";
    public static final String CONTRATTOSCATTO_ARRAY_PROPERTY = "contrattoscattoArray";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";

    public static final String IDANZIANITA_PK_COLUMN = "IDANZIANITA";
    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";

    public void setAnzianitaa(Short anzianitaa) {
        writeProperty("anzianitaa", anzianitaa);
    }
    public Short getAnzianitaa() {
        return (Short)readProperty("anzianitaa");
    }

    public void setAnzianitada(Short anzianitada) {
        writeProperty("anzianitada", anzianitada);
    }
    public Short getAnzianitada() {
        return (Short)readProperty("anzianitada");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setIdanzianita(Short idanzianita) {
        writeProperty("idanzianita", idanzianita);
    }
    public Short getIdanzianita() {
        return (Short)readProperty("idanzianita");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdunitamisura(Short idunitamisura) {
        writeProperty("idunitamisura", idunitamisura);
    }
    public Short getIdunitamisura() {
        return (Short)readProperty("idunitamisura");
    }

    public void addToContrattorateovaloreArray(Contrattorateovalore obj) {
        addToManyTarget("contrattorateovaloreArray", obj, true);
    }
    public void removeFromContrattorateovaloreArray(Contrattorateovalore obj) {
        removeToManyTarget("contrattorateovaloreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattorateovalore> getContrattorateovaloreArray() {
        return (List<Contrattorateovalore>)readProperty("contrattorateovaloreArray");
    }


    public void addToContrattoscattoArray(Contrattoscatto obj) {
        addToManyTarget("contrattoscattoArray", obj, true);
    }
    public void removeFromContrattoscattoArray(Contrattoscatto obj) {
        removeToManyTarget("contrattoscattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoscatto> getContrattoscattoArray() {
        return (List<Contrattoscatto>)readProperty("contrattoscattoArray");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


}
