package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattoanzianita;
import it.iubar.paghe.logic.paghe.Contrattorateo;
import it.iubar.paghe.logic.paghe.Tiporateo;
import it.iubar.paghe.logic.paghe.Unitamisura;

/**
 * Class _Contrattorateovalore was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattorateovalore extends CayenneDataObject {

    public static final String IDANZIANITA_PROPERTY = "idanzianita";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDRATEO_PROPERTY = "idrateo";
    public static final String IDTIPORATEO_PROPERTY = "idtiporateo";
    public static final String IDUNITAMISURA1_PROPERTY = "idunitamisura1";
    public static final String IDUNITAMISURA2_PROPERTY = "idunitamisura2";
    public static final String VALORE_PROPERTY = "valore";
    public static final String TO_CONTRATTOANZIANITA_PROPERTY = "toContrattoanzianita";
    public static final String TO_CONTRATTORATEO_PROPERTY = "toContrattorateo";
    public static final String TO_TIPORATEO_PROPERTY = "toTiporateo";
    public static final String TO_UNITAMISURA1_PROPERTY = "toUnitamisura1";
    public static final String TO_UNITAMISURA2_PROPERTY = "toUnitamisura2";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDRATEO_PK_COLUMN = "IDRATEO";
    public static final String IDTIPORATEO_PK_COLUMN = "IDTIPORATEO";

    public void setIdanzianita(Short idanzianita) {
        writeProperty("idanzianita", idanzianita);
    }
    public Short getIdanzianita() {
        return (Short)readProperty("idanzianita");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdrateo(Short idrateo) {
        writeProperty("idrateo", idrateo);
    }
    public Short getIdrateo() {
        return (Short)readProperty("idrateo");
    }

    public void setIdtiporateo(Short idtiporateo) {
        writeProperty("idtiporateo", idtiporateo);
    }
    public Short getIdtiporateo() {
        return (Short)readProperty("idtiporateo");
    }

    public void setIdunitamisura1(Short idunitamisura1) {
        writeProperty("idunitamisura1", idunitamisura1);
    }
    public Short getIdunitamisura1() {
        return (Short)readProperty("idunitamisura1");
    }

    public void setIdunitamisura2(Short idunitamisura2) {
        writeProperty("idunitamisura2", idunitamisura2);
    }
    public Short getIdunitamisura2() {
        return (Short)readProperty("idunitamisura2");
    }

    public void setValore(BigDecimal valore) {
        writeProperty("valore", valore);
    }
    public BigDecimal getValore() {
        return (BigDecimal)readProperty("valore");
    }

    public void setToContrattoanzianita(Contrattoanzianita toContrattoanzianita) {
        setToOneTarget("toContrattoanzianita", toContrattoanzianita, true);
    }

    public Contrattoanzianita getToContrattoanzianita() {
        return (Contrattoanzianita)readProperty("toContrattoanzianita");
    }


    public void setToContrattorateo(Contrattorateo toContrattorateo) {
        setToOneTarget("toContrattorateo", toContrattorateo, true);
    }

    public Contrattorateo getToContrattorateo() {
        return (Contrattorateo)readProperty("toContrattorateo");
    }


    public void setToTiporateo(Tiporateo toTiporateo) {
        setToOneTarget("toTiporateo", toTiporateo, true);
    }

    public Tiporateo getToTiporateo() {
        return (Tiporateo)readProperty("toTiporateo");
    }


    public void setToUnitamisura1(Unitamisura toUnitamisura1) {
        setToOneTarget("toUnitamisura1", toUnitamisura1, true);
    }

    public Unitamisura getToUnitamisura1() {
        return (Unitamisura)readProperty("toUnitamisura1");
    }


    public void setToUnitamisura2(Unitamisura toUnitamisura2) {
        setToOneTarget("toUnitamisura2", toUnitamisura2, true);
    }

    public Unitamisura getToUnitamisura2() {
        return (Unitamisura)readProperty("toUnitamisura2");
    }


}
