package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Elementobaseimponibile;
import it.iubar.paghe.logic.paghe.Tipoelementoretributivo;
import it.iubar.paghe.logic.presenze.Presenza;

/**
 * Class _Contrattomaggiorazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattomaggiorazione extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDBASEIMPONIBILE_PROPERTY = "idbaseimponibile";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDMAGGIORAZIONE_PROPERTY = "idmaggiorazione";
    public static final String IDTIPOELEMENTO_PROPERTY = "idtipoelemento";
    public static final String IDTIPOLAVORATORE2_PROPERTY = "idtipolavoratore2";
    public static final String IMPORTO_PROPERTY = "importo";
    public static final String LIMITEOREANNO_PROPERTY = "limiteoreanno";
    public static final String LIMITEOREGIORNO_PROPERTY = "limiteoregiorno";
    public static final String LIMITEOREMESE_PROPERTY = "limiteoremese";
    public static final String LIMITEORESETTIMANA_PROPERTY = "limiteoresettimana";
    public static final String MAGGIORAZIONE_PROPERTY = "maggiorazione";
    public static final String NOTE_PROPERTY = "note";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String PRESENZA_ARRAY_PROPERTY = "presenzaArray";
    public static final String TO_BASEIMPONIBILE_PROPERTY = "toBaseimponibile";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_TIPOELEMENTORETRIBUTIVO_PROPERTY = "toTipoelementoretributivo";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDMAGGIORAZIONE_PK_COLUMN = "IDMAGGIORAZIONE";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setIdbaseimponibile(Integer idbaseimponibile) {
        writeProperty("idbaseimponibile", idbaseimponibile);
    }
    public Integer getIdbaseimponibile() {
        return (Integer)readProperty("idbaseimponibile");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdmaggiorazione(Short idmaggiorazione) {
        writeProperty("idmaggiorazione", idmaggiorazione);
    }
    public Short getIdmaggiorazione() {
        return (Short)readProperty("idmaggiorazione");
    }

    public void setIdtipoelemento(Short idtipoelemento) {
        writeProperty("idtipoelemento", idtipoelemento);
    }
    public Short getIdtipoelemento() {
        return (Short)readProperty("idtipoelemento");
    }

    public void setIdtipolavoratore2(Short idtipolavoratore2) {
        writeProperty("idtipolavoratore2", idtipolavoratore2);
    }
    public Short getIdtipolavoratore2() {
        return (Short)readProperty("idtipolavoratore2");
    }

    public void setImporto(BigDecimal importo) {
        writeProperty("importo", importo);
    }
    public BigDecimal getImporto() {
        return (BigDecimal)readProperty("importo");
    }

    public void setLimiteoreanno(BigDecimal limiteoreanno) {
        writeProperty("limiteoreanno", limiteoreanno);
    }
    public BigDecimal getLimiteoreanno() {
        return (BigDecimal)readProperty("limiteoreanno");
    }

    public void setLimiteoregiorno(BigDecimal limiteoregiorno) {
        writeProperty("limiteoregiorno", limiteoregiorno);
    }
    public BigDecimal getLimiteoregiorno() {
        return (BigDecimal)readProperty("limiteoregiorno");
    }

    public void setLimiteoremese(BigDecimal limiteoremese) {
        writeProperty("limiteoremese", limiteoremese);
    }
    public BigDecimal getLimiteoremese() {
        return (BigDecimal)readProperty("limiteoremese");
    }

    public void setLimiteoresettimana(BigDecimal limiteoresettimana) {
        writeProperty("limiteoresettimana", limiteoresettimana);
    }
    public BigDecimal getLimiteoresettimana() {
        return (BigDecimal)readProperty("limiteoresettimana");
    }

    public void setMaggiorazione(BigDecimal maggiorazione) {
        writeProperty("maggiorazione", maggiorazione);
    }
    public BigDecimal getMaggiorazione() {
        return (BigDecimal)readProperty("maggiorazione");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setValidoal(Date validoal) {
        writeProperty("validoal", validoal);
    }
    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToPresenzaArray(Presenza obj) {
        addToManyTarget("presenzaArray", obj, true);
    }
    public void removeFromPresenzaArray(Presenza obj) {
        removeToManyTarget("presenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Presenza> getPresenzaArray() {
        return (List<Presenza>)readProperty("presenzaArray");
    }


    public void setToBaseimponibile(Elementobaseimponibile toBaseimponibile) {
        setToOneTarget("toBaseimponibile", toBaseimponibile, true);
    }

    public Elementobaseimponibile getToBaseimponibile() {
        return (Elementobaseimponibile)readProperty("toBaseimponibile");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToTipoelementoretributivo(Tipoelementoretributivo toTipoelementoretributivo) {
        setToOneTarget("toTipoelementoretributivo", toTipoelementoretributivo, true);
    }

    public Tipoelementoretributivo getToTipoelementoretributivo() {
        return (Tipoelementoretributivo)readProperty("toTipoelementoretributivo");
    }


}
