package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.ContrattodettElemento;
import it.iubar.paghe.logic.paghe.Contrattodettagliolivellovoce;
import it.iubar.paghe.logic.paghe.Contrattodettagliovoce;
import it.iubar.paghe.logic.paghe.ContrattovoceBaseimp;

/**
 * Class _Contrattovoce was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattovoce extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String DESCRIZIONE2_PROPERTY = "descrizione2";
    public static final String IDCATEGORIA1_PROPERTY = "idcategoria1";
    public static final String IDCATEGORIA2_PROPERTY = "idcategoria2";
    public static final String IDVOCE_PROPERTY = "idvoce";
    public static final String INDICE_PROPERTY = "indice";
    public static final String CONTRATTODETT_ELEMENTO_PROPERTY = "contrattodettElemento";
    public static final String CONTRATTODETTAGLIOIMPORTO_ARRAY_PROPERTY = "contrattodettaglioimportoArray";
    public static final String CONTRATTODETTAGLIOVOCE_ARRAY_PROPERTY = "contrattodettagliovoceArray";
    public static final String VOCE_BASEIMP_ARRAY_PROPERTY = "voceBaseimpArray";

    public static final String IDVOCE_PK_COLUMN = "IDVOCE";

    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getDescrizione2() {
        return (String)readProperty("descrizione2");
    }

    public Short getIdcategoria1() {
        return (Short)readProperty("idcategoria1");
    }

    public Short getIdcategoria2() {
        return (Short)readProperty("idcategoria2");
    }

    public Short getIdvoce() {
        return (Short)readProperty("idvoce");
    }

    public Short getIndice() {
        return (Short)readProperty("indice");
    }

    public void addToContrattodettElemento(ContrattodettElemento obj) {
        addToManyTarget("contrattodettElemento", obj, true);
    }
    public void removeFromContrattodettElemento(ContrattodettElemento obj) {
        removeToManyTarget("contrattodettElemento", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContrattodettElemento> getContrattodettElemento() {
        return (List<ContrattodettElemento>)readProperty("contrattodettElemento");
    }


    public void addToContrattodettaglioimportoArray(Contrattodettagliolivellovoce obj) {
        addToManyTarget("contrattodettaglioimportoArray", obj, true);
    }
    public void removeFromContrattodettaglioimportoArray(Contrattodettagliolivellovoce obj) {
        removeToManyTarget("contrattodettaglioimportoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattodettagliolivellovoce> getContrattodettaglioimportoArray() {
        return (List<Contrattodettagliolivellovoce>)readProperty("contrattodettaglioimportoArray");
    }


    public void addToContrattodettagliovoceArray(Contrattodettagliovoce obj) {
        addToManyTarget("contrattodettagliovoceArray", obj, true);
    }
    public void removeFromContrattodettagliovoceArray(Contrattodettagliovoce obj) {
        removeToManyTarget("contrattodettagliovoceArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattodettagliovoce> getContrattodettagliovoceArray() {
        return (List<Contrattodettagliovoce>)readProperty("contrattodettagliovoceArray");
    }


    public void addToVoceBaseimpArray(ContrattovoceBaseimp obj) {
        addToManyTarget("voceBaseimpArray", obj, true);
    }
    public void removeFromVoceBaseimpArray(ContrattovoceBaseimp obj) {
        removeToManyTarget("voceBaseimpArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContrattovoceBaseimp> getVoceBaseimpArray() {
        return (List<ContrattovoceBaseimp>)readProperty("voceBaseimpArray");
    }


}
