package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Tipolavoratore2;
import it.iubar.paghe.logic.paghe.Contrattocoefficiente;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;
import it.iubar.paghe.logic.paghe.Profilolavoratore;

/**
 * Class _Contrattoferie was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattoferie extends CayenneDataObject {

    public static final String ANZIANITADA_PROPERTY = "anzianitada";
    public static final String ANZIANITAFINO_PROPERTY = "anzianitafino";
    public static final String CUSTOM_PROPERTY = "custom";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String FRAZIONABILI_PROPERTY = "frazionabili";
    public static final String IDCOEFFICIENTE_PROPERTY = "idcoefficiente";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDFERIE_PROPERTY = "idferie";
    public static final String IDLIVELLO_PROPERTY = "idlivello";
    public static final String IDTIPOLAVORATORE2_PROPERTY = "idtipolavoratore2";
    public static final String NOTE_PROPERTY = "note";
    public static final String PERIODOGIORNI_PROPERTY = "periodogiorni";
    public static final String PERIODOSETTIMANE_PROPERTY = "periodosettimane";
    public static final String POSIZIONESUBORDINATO_ARRAY_PROPERTY = "posizionesubordinatoArray";
    public static final String PROFILOSUBORDINATO_ARRAY_PROPERTY = "profilosubordinatoArray";
    public static final String TO_CONTRATTOCOEFFICIENTE_PROPERTY = "toContrattocoefficiente";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_TIPOLAVORATORE2_PROPERTY = "toTipolavoratore2";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDFERIE_PK_COLUMN = "IDFERIE";

    public void setAnzianitada(Short anzianitada) {
        writeProperty("anzianitada", anzianitada);
    }
    public Short getAnzianitada() {
        return (Short)readProperty("anzianitada");
    }

    public void setAnzianitafino(Short anzianitafino) {
        writeProperty("anzianitafino", anzianitafino);
    }
    public Short getAnzianitafino() {
        return (Short)readProperty("anzianitafino");
    }

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setFrazionabili(Short frazionabili) {
        writeProperty("frazionabili", frazionabili);
    }
    public Short getFrazionabili() {
        return (Short)readProperty("frazionabili");
    }

    public void setIdcoefficiente(Short idcoefficiente) {
        writeProperty("idcoefficiente", idcoefficiente);
    }
    public Short getIdcoefficiente() {
        return (Short)readProperty("idcoefficiente");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdferie(Short idferie) {
        writeProperty("idferie", idferie);
    }
    public Short getIdferie() {
        return (Short)readProperty("idferie");
    }

    public void setIdlivello(String idlivello) {
        writeProperty("idlivello", idlivello);
    }
    public String getIdlivello() {
        return (String)readProperty("idlivello");
    }

    public void setIdtipolavoratore2(Short idtipolavoratore2) {
        writeProperty("idtipolavoratore2", idtipolavoratore2);
    }
    public Short getIdtipolavoratore2() {
        return (Short)readProperty("idtipolavoratore2");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setPeriodogiorni(Short periodogiorni) {
        writeProperty("periodogiorni", periodogiorni);
    }
    public Short getPeriodogiorni() {
        return (Short)readProperty("periodogiorni");
    }

    public void setPeriodosettimane(Short periodosettimane) {
        writeProperty("periodosettimane", periodosettimane);
    }
    public Short getPeriodosettimane() {
        return (Short)readProperty("periodosettimane");
    }

    public void addToPosizionesubordinatoArray(Posizionesubordinato obj) {
        addToManyTarget("posizionesubordinatoArray", obj, true);
    }
    public void removeFromPosizionesubordinatoArray(Posizionesubordinato obj) {
        removeToManyTarget("posizionesubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionesubordinato> getPosizionesubordinatoArray() {
        return (List<Posizionesubordinato>)readProperty("posizionesubordinatoArray");
    }


    public void addToProfilosubordinatoArray(Profilolavoratore obj) {
        addToManyTarget("profilosubordinatoArray", obj, true);
    }
    public void removeFromProfilosubordinatoArray(Profilolavoratore obj) {
        removeToManyTarget("profilosubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profilolavoratore> getProfilosubordinatoArray() {
        return (List<Profilolavoratore>)readProperty("profilosubordinatoArray");
    }


    public void setToContrattocoefficiente(Contrattocoefficiente toContrattocoefficiente) {
        setToOneTarget("toContrattocoefficiente", toContrattocoefficiente, true);
    }

    public Contrattocoefficiente getToContrattocoefficiente() {
        return (Contrattocoefficiente)readProperty("toContrattocoefficiente");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToTipolavoratore2(Tipolavoratore2 toTipolavoratore2) {
        setToOneTarget("toTipolavoratore2", toTipolavoratore2, true);
    }

    public Tipolavoratore2 getToTipolavoratore2() {
        return (Tipolavoratore2)readProperty("toTipolavoratore2");
    }


}
