package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Subordinato;
import it.iubar.paghe.logic.paghe.Cedolino;
import it.iubar.paghe.logic.paghe.ContrattoFestivita;
import it.iubar.paghe.logic.paghe.Contrattoanzianita;
import it.iubar.paghe.logic.paghe.Contrattoassenza;
import it.iubar.paghe.logic.paghe.Contrattocoefficiente;
import it.iubar.paghe.logic.paghe.ContrattodettElemento;
import it.iubar.paghe.logic.paghe.Contrattodettagliolivello;
import it.iubar.paghe.logic.paghe.Contrattodettagliovoce;
import it.iubar.paghe.logic.paghe.Contrattoferie;
import it.iubar.paghe.logic.paghe.Contrattoindennita;
import it.iubar.paghe.logic.paghe.Contrattomaggiorazione;
import it.iubar.paghe.logic.paghe.Contrattonota;
import it.iubar.paghe.logic.paghe.Contrattorateo;
import it.iubar.paghe.logic.paghe.Contrattoscatto;
import it.iubar.paghe.logic.paghe.Elementobaseimponibile;
import it.iubar.paghe.logic.paghe.ImpresaContratto;
import it.iubar.paghe.logic.paghe.InpsContratto;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;
import it.iubar.paghe.logic.paghe.Profilolavoratore;
import it.iubar.paghe.logic.paghe.Unitamisura;

/**
 * Class _Contrattodettaglio was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattodettaglio extends CayenneDataObject {

    public static final String BANCAORE_PROPERTY = "bancaore";
    public static final String CONTINGENZA_PROPERTY = "contingenza";
    public static final String CUSTOM_PROPERTY = "custom";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String EDR_PROPERTY = "edr";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDFESTIVITARETRIB_PROPERTY = "idfestivitaretrib";
    public static final String IDINFORTUNIO_PROPERTY = "idinfortunio";
    public static final String IDINPSCONTRATTO_PROPERTY = "idinpscontratto";
    public static final String IDMALATTIA_PROPERTY = "idmalattia";
    public static final String IDUNITAMISURA_PROPERTY = "idunitamisura";
    public static final String INTEGRAZCONGEDOMATR_PROPERTY = "integrazcongedomatr";
    public static final String ISTITUTOSCATTI_PROPERTY = "istitutoscatti";
    public static final String QUATTORDICESIMAGIORNO_PROPERTY = "quattordicesimagiorno";
    public static final String QUATTORDICESIMAMESE_PROPERTY = "quattordicesimamese";
    public static final String SCATTIMESE_PROPERTY = "scattimese";
    public static final String SCATTINUMERO_PROPERTY = "scattinumero";
    public static final String STRAORDINARILIMITEOREANNO_PROPERTY = "straordinarilimiteoreanno";
    public static final String STRAORDINARILIMITEOREGIORNO_PROPERTY = "straordinarilimiteoregiorno";
    public static final String STRAORDINARILIMITEOREMESE_PROPERTY = "straordinarilimiteoremese";
    public static final String STRAORDINARILIMITEORESETTIMANA_PROPERTY = "straordinarilimiteoresettimana";
    public static final String TREDICESIMAGIORNO_PROPERTY = "tredicesimagiorno";
    public static final String TREDICESIMAMESE_PROPERTY = "tredicesimamese";
    public static final String ULTIMAMODIFICA_PROPERTY = "ultimamodifica";
    public static final String ULTIMAMODIFICAUSER_PROPERTY = "ultimamodificauser";
    public static final String BASEIMP_ARRAY_PROPERTY = "baseimpArray";
    public static final String CEDOLINO_ARRAY_PROPERTY = "cedolinoArray";
    public static final String COEFFICIENTE_ARRAY_PROPERTY = "coefficienteArray";
    public static final String CONTRATTO_FESTIVITA_ARRAY_PROPERTY = "contrattoFestivitaArray";
    public static final String CONTRATTOANZIANITA_ARRAY_PROPERTY = "contrattoanzianitaArray";
    public static final String CONTRATTOASSENZA_ARRAY_PROPERTY = "contrattoassenzaArray";
    public static final String CONTRATTODETT_ELEMENTO_ARRAY_PROPERTY = "contrattodettElementoArray";
    public static final String CONTRATTODETTAGLIOLIVELLO_ARRAY_PROPERTY = "contrattodettagliolivelloArray";
    public static final String CONTRATTODETTAGLIOVOCE_ARRAY_PROPERTY = "contrattodettagliovoceArray";
    public static final String CONTRATTOINDENNITA_ARRAY_PROPERTY = "contrattoindennitaArray";
    public static final String CONTRATTONOTA_ARRAY_PROPERTY = "contrattonotaArray";
    public static final String CONTRATTORATEO_ARRAY_PROPERTY = "contrattorateoArray";
    public static final String FERIE_ARRAY_PROPERTY = "ferieArray";
    public static final String IMPRESA_CONTRATTO_ARRAY_PROPERTY = "impresaContrattoArray";
    public static final String LAVSTRAORDINARIO_ARRAY_PROPERTY = "lavstraordinarioArray";
    public static final String POSIZIONESUBORDINATO_ARRAY_PROPERTY = "posizionesubordinatoArray";
    public static final String PROFILOSUBORDINATO_ARRAY_PROPERTY = "profilosubordinatoArray";
    public static final String SCATTO_ARRAY_PROPERTY = "scattoArray";
    public static final String SUBORDINATO_ARRAY_PROPERTY = "subordinatoArray";
    public static final String TO_INPS_CONTRATTO_PROPERTY = "toInpsContratto";
    public static final String TO_UNITAMISURA_PROPERTY = "toUnitamisura";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";

    public void setBancaore(Short bancaore) {
        writeProperty("bancaore", bancaore);
    }
    public Short getBancaore() {
        return (Short)readProperty("bancaore");
    }

    public void setContingenza(Short contingenza) {
        writeProperty("contingenza", contingenza);
    }
    public Short getContingenza() {
        return (Short)readProperty("contingenza");
    }

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setEdr(BigDecimal edr) {
        writeProperty("edr", edr);
    }
    public BigDecimal getEdr() {
        return (BigDecimal)readProperty("edr");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdfestivitaretrib(Short idfestivitaretrib) {
        writeProperty("idfestivitaretrib", idfestivitaretrib);
    }
    public Short getIdfestivitaretrib() {
        return (Short)readProperty("idfestivitaretrib");
    }

    public void setIdinfortunio(Short idinfortunio) {
        writeProperty("idinfortunio", idinfortunio);
    }
    public Short getIdinfortunio() {
        return (Short)readProperty("idinfortunio");
    }

    public void setIdinpscontratto(String idinpscontratto) {
        writeProperty("idinpscontratto", idinpscontratto);
    }
    public String getIdinpscontratto() {
        return (String)readProperty("idinpscontratto");
    }

    public void setIdmalattia(Short idmalattia) {
        writeProperty("idmalattia", idmalattia);
    }
    public Short getIdmalattia() {
        return (Short)readProperty("idmalattia");
    }

    public void setIdunitamisura(Short idunitamisura) {
        writeProperty("idunitamisura", idunitamisura);
    }
    public Short getIdunitamisura() {
        return (Short)readProperty("idunitamisura");
    }

    public void setIntegrazcongedomatr(BigDecimal integrazcongedomatr) {
        writeProperty("integrazcongedomatr", integrazcongedomatr);
    }
    public BigDecimal getIntegrazcongedomatr() {
        return (BigDecimal)readProperty("integrazcongedomatr");
    }

    public void setIstitutoscatti(Short istitutoscatti) {
        writeProperty("istitutoscatti", istitutoscatti);
    }
    public Short getIstitutoscatti() {
        return (Short)readProperty("istitutoscatti");
    }

    public void setQuattordicesimagiorno(Short quattordicesimagiorno) {
        writeProperty("quattordicesimagiorno", quattordicesimagiorno);
    }
    public Short getQuattordicesimagiorno() {
        return (Short)readProperty("quattordicesimagiorno");
    }

    public void setQuattordicesimamese(Short quattordicesimamese) {
        writeProperty("quattordicesimamese", quattordicesimamese);
    }
    public Short getQuattordicesimamese() {
        return (Short)readProperty("quattordicesimamese");
    }

    public void setScattimese(Short scattimese) {
        writeProperty("scattimese", scattimese);
    }
    public Short getScattimese() {
        return (Short)readProperty("scattimese");
    }

    public void setScattinumero(Short scattinumero) {
        writeProperty("scattinumero", scattinumero);
    }
    public Short getScattinumero() {
        return (Short)readProperty("scattinumero");
    }

    public void setStraordinarilimiteoreanno(BigDecimal straordinarilimiteoreanno) {
        writeProperty("straordinarilimiteoreanno", straordinarilimiteoreanno);
    }
    public BigDecimal getStraordinarilimiteoreanno() {
        return (BigDecimal)readProperty("straordinarilimiteoreanno");
    }

    public void setStraordinarilimiteoregiorno(BigDecimal straordinarilimiteoregiorno) {
        writeProperty("straordinarilimiteoregiorno", straordinarilimiteoregiorno);
    }
    public BigDecimal getStraordinarilimiteoregiorno() {
        return (BigDecimal)readProperty("straordinarilimiteoregiorno");
    }

    public void setStraordinarilimiteoremese(BigDecimal straordinarilimiteoremese) {
        writeProperty("straordinarilimiteoremese", straordinarilimiteoremese);
    }
    public BigDecimal getStraordinarilimiteoremese() {
        return (BigDecimal)readProperty("straordinarilimiteoremese");
    }

    public void setStraordinarilimiteoresettimana(BigDecimal straordinarilimiteoresettimana) {
        writeProperty("straordinarilimiteoresettimana", straordinarilimiteoresettimana);
    }
    public BigDecimal getStraordinarilimiteoresettimana() {
        return (BigDecimal)readProperty("straordinarilimiteoresettimana");
    }

    public void setTredicesimagiorno(Short tredicesimagiorno) {
        writeProperty("tredicesimagiorno", tredicesimagiorno);
    }
    public Short getTredicesimagiorno() {
        return (Short)readProperty("tredicesimagiorno");
    }

    public void setTredicesimamese(Short tredicesimamese) {
        writeProperty("tredicesimamese", tredicesimamese);
    }
    public Short getTredicesimamese() {
        return (Short)readProperty("tredicesimamese");
    }

    public void setUltimamodifica(Date ultimamodifica) {
        writeProperty("ultimamodifica", ultimamodifica);
    }
    public Date getUltimamodifica() {
        return (Date)readProperty("ultimamodifica");
    }

    public void setUltimamodificauser(String ultimamodificauser) {
        writeProperty("ultimamodificauser", ultimamodificauser);
    }
    public String getUltimamodificauser() {
        return (String)readProperty("ultimamodificauser");
    }

    public void addToBaseimpArray(Elementobaseimponibile obj) {
        addToManyTarget("baseimpArray", obj, true);
    }
    public void removeFromBaseimpArray(Elementobaseimponibile obj) {
        removeToManyTarget("baseimpArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Elementobaseimponibile> getBaseimpArray() {
        return (List<Elementobaseimponibile>)readProperty("baseimpArray");
    }


    public void addToCedolinoArray(Cedolino obj) {
        addToManyTarget("cedolinoArray", obj, true);
    }
    public void removeFromCedolinoArray(Cedolino obj) {
        removeToManyTarget("cedolinoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cedolino> getCedolinoArray() {
        return (List<Cedolino>)readProperty("cedolinoArray");
    }


    public void addToCoefficienteArray(Contrattocoefficiente obj) {
        addToManyTarget("coefficienteArray", obj, true);
    }
    public void removeFromCoefficienteArray(Contrattocoefficiente obj) {
        removeToManyTarget("coefficienteArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattocoefficiente> getCoefficienteArray() {
        return (List<Contrattocoefficiente>)readProperty("coefficienteArray");
    }


    public void addToContrattoFestivitaArray(ContrattoFestivita obj) {
        addToManyTarget("contrattoFestivitaArray", obj, true);
    }
    public void removeFromContrattoFestivitaArray(ContrattoFestivita obj) {
        removeToManyTarget("contrattoFestivitaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContrattoFestivita> getContrattoFestivitaArray() {
        return (List<ContrattoFestivita>)readProperty("contrattoFestivitaArray");
    }


    public void addToContrattoanzianitaArray(Contrattoanzianita obj) {
        addToManyTarget("contrattoanzianitaArray", obj, true);
    }
    public void removeFromContrattoanzianitaArray(Contrattoanzianita obj) {
        removeToManyTarget("contrattoanzianitaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoanzianita> getContrattoanzianitaArray() {
        return (List<Contrattoanzianita>)readProperty("contrattoanzianitaArray");
    }


    public void addToContrattoassenzaArray(Contrattoassenza obj) {
        addToManyTarget("contrattoassenzaArray", obj, true);
    }
    public void removeFromContrattoassenzaArray(Contrattoassenza obj) {
        removeToManyTarget("contrattoassenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoassenza> getContrattoassenzaArray() {
        return (List<Contrattoassenza>)readProperty("contrattoassenzaArray");
    }


    public void addToContrattodettElementoArray(ContrattodettElemento obj) {
        addToManyTarget("contrattodettElementoArray", obj, true);
    }
    public void removeFromContrattodettElementoArray(ContrattodettElemento obj) {
        removeToManyTarget("contrattodettElementoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContrattodettElemento> getContrattodettElementoArray() {
        return (List<ContrattodettElemento>)readProperty("contrattodettElementoArray");
    }


    public void addToContrattodettagliolivelloArray(Contrattodettagliolivello obj) {
        addToManyTarget("contrattodettagliolivelloArray", obj, true);
    }
    public void removeFromContrattodettagliolivelloArray(Contrattodettagliolivello obj) {
        removeToManyTarget("contrattodettagliolivelloArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattodettagliolivello> getContrattodettagliolivelloArray() {
        return (List<Contrattodettagliolivello>)readProperty("contrattodettagliolivelloArray");
    }


    public void addToContrattodettagliovoceArray(Contrattodettagliovoce obj) {
        addToManyTarget("contrattodettagliovoceArray", obj, true);
    }
    public void removeFromContrattodettagliovoceArray(Contrattodettagliovoce obj) {
        removeToManyTarget("contrattodettagliovoceArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattodettagliovoce> getContrattodettagliovoceArray() {
        return (List<Contrattodettagliovoce>)readProperty("contrattodettagliovoceArray");
    }


    public void addToContrattoindennitaArray(Contrattoindennita obj) {
        addToManyTarget("contrattoindennitaArray", obj, true);
    }
    public void removeFromContrattoindennitaArray(Contrattoindennita obj) {
        removeToManyTarget("contrattoindennitaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoindennita> getContrattoindennitaArray() {
        return (List<Contrattoindennita>)readProperty("contrattoindennitaArray");
    }


    public void addToContrattonotaArray(Contrattonota obj) {
        addToManyTarget("contrattonotaArray", obj, true);
    }
    public void removeFromContrattonotaArray(Contrattonota obj) {
        removeToManyTarget("contrattonotaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattonota> getContrattonotaArray() {
        return (List<Contrattonota>)readProperty("contrattonotaArray");
    }


    public void addToContrattorateoArray(Contrattorateo obj) {
        addToManyTarget("contrattorateoArray", obj, true);
    }
    public void removeFromContrattorateoArray(Contrattorateo obj) {
        removeToManyTarget("contrattorateoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattorateo> getContrattorateoArray() {
        return (List<Contrattorateo>)readProperty("contrattorateoArray");
    }


    public void addToFerieArray(Contrattoferie obj) {
        addToManyTarget("ferieArray", obj, true);
    }
    public void removeFromFerieArray(Contrattoferie obj) {
        removeToManyTarget("ferieArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoferie> getFerieArray() {
        return (List<Contrattoferie>)readProperty("ferieArray");
    }


    public void addToImpresaContrattoArray(ImpresaContratto obj) {
        addToManyTarget("impresaContrattoArray", obj, true);
    }
    public void removeFromImpresaContrattoArray(ImpresaContratto obj) {
        removeToManyTarget("impresaContrattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ImpresaContratto> getImpresaContrattoArray() {
        return (List<ImpresaContratto>)readProperty("impresaContrattoArray");
    }


    public void addToLavstraordinarioArray(Contrattomaggiorazione obj) {
        addToManyTarget("lavstraordinarioArray", obj, true);
    }
    public void removeFromLavstraordinarioArray(Contrattomaggiorazione obj) {
        removeToManyTarget("lavstraordinarioArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattomaggiorazione> getLavstraordinarioArray() {
        return (List<Contrattomaggiorazione>)readProperty("lavstraordinarioArray");
    }


    public void addToPosizionesubordinatoArray(Posizionesubordinato obj) {
        addToManyTarget("posizionesubordinatoArray", obj, true);
    }
    public void removeFromPosizionesubordinatoArray(Posizionesubordinato obj) {
        removeToManyTarget("posizionesubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionesubordinato> getPosizionesubordinatoArray() {
        return (List<Posizionesubordinato>)readProperty("posizionesubordinatoArray");
    }


    public void addToProfilosubordinatoArray(Profilolavoratore obj) {
        addToManyTarget("profilosubordinatoArray", obj, true);
    }
    public void removeFromProfilosubordinatoArray(Profilolavoratore obj) {
        removeToManyTarget("profilosubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profilolavoratore> getProfilosubordinatoArray() {
        return (List<Profilolavoratore>)readProperty("profilosubordinatoArray");
    }


    public void addToScattoArray(Contrattoscatto obj) {
        addToManyTarget("scattoArray", obj, true);
    }
    public void removeFromScattoArray(Contrattoscatto obj) {
        removeToManyTarget("scattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoscatto> getScattoArray() {
        return (List<Contrattoscatto>)readProperty("scattoArray");
    }


    public void addToSubordinatoArray(Subordinato obj) {
        addToManyTarget("subordinatoArray", obj, true);
    }
    public void removeFromSubordinatoArray(Subordinato obj) {
        removeToManyTarget("subordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Subordinato> getSubordinatoArray() {
        return (List<Subordinato>)readProperty("subordinatoArray");
    }


    public void setToInpsContratto(InpsContratto toInpsContratto) {
        setToOneTarget("toInpsContratto", toInpsContratto, true);
    }

    public InpsContratto getToInpsContratto() {
        return (InpsContratto)readProperty("toInpsContratto");
    }


    public void setToUnitamisura(Unitamisura toUnitamisura) {
        setToOneTarget("toUnitamisura", toUnitamisura, true);
    }

    public Unitamisura getToUnitamisura() {
        return (Unitamisura)readProperty("toUnitamisura");
    }


}
