package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattodettagliolivello;
import it.iubar.paghe.logic.paghe.Contrattoindennita;

/**
 * Class _ContrattoindennitaLivello was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContrattoindennitaLivello extends CayenneDataObject {

    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDINDENNITA_PROPERTY = "idindennita";
    public static final String IDLIVELLO_PROPERTY = "idlivello";
    public static final String TO_CONTRATTOINDENNITA_PROPERTY = "toContrattoindennita";
    public static final String TO_LIVELLO_PROPERTY = "toLivello";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDINDENNITA_PK_COLUMN = "IDINDENNITA";
    public static final String IDLIVELLO_PK_COLUMN = "IDLIVELLO";

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdindennita(Short idindennita) {
        writeProperty("idindennita", idindennita);
    }
    public Short getIdindennita() {
        return (Short)readProperty("idindennita");
    }

    public void setIdlivello(String idlivello) {
        writeProperty("idlivello", idlivello);
    }
    public String getIdlivello() {
        return (String)readProperty("idlivello");
    }

    public void setToContrattoindennita(Contrattoindennita toContrattoindennita) {
        setToOneTarget("toContrattoindennita", toContrattoindennita, true);
    }

    public Contrattoindennita getToContrattoindennita() {
        return (Contrattoindennita)readProperty("toContrattoindennita");
    }


    public void setToLivello(Contrattodettagliolivello toLivello) {
        setToOneTarget("toLivello", toLivello, true);
    }

    public Contrattodettagliolivello getToLivello() {
        return (Contrattodettagliolivello)readProperty("toLivello");
    }


}
