package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.ContrattodettagliovoceCedolino;
import it.iubar.paghe.logic.paghe.Contrattovoce;
import it.iubar.paghe.logic.paghe.Elementobaseimponibile;

/**
 * Class _Contrattodettagliovoce was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattodettagliovoce extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String IDBASEIMPONIBILE_PROPERTY = "idbaseimponibile";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDINPSCONTRATTO_PROPERTY = "idinpscontratto";
    public static final String IDVOCE_PROPERTY = "idvoce";
    public static final String INDIRETTO_PROPERTY = "indiretto";
    public static final String INPS_PROPERTY = "inps";
    public static final String IRPEF_PROPERTY = "irpef";
    public static final String MAGGIORAZIONE_PROPERTY = "maggiorazione";
    public static final String MESE_PROPERTY = "mese";
    public static final String TFR_PROPERTY = "tfr";
    public static final String CONTRATTODETTAGLIO_VOCE_ARRAY_PROPERTY = "contrattodettaglioVoceArray";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_CONTRATTOVOCE_PROPERTY = "toContrattovoce";
    public static final String TO_ELEMENTOBAEIMPONIBILE_PROPERTY = "toElementobaeimponibile";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDVOCE_PK_COLUMN = "IDVOCE";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setIdbaseimponibile(Integer idbaseimponibile) {
        writeProperty("idbaseimponibile", idbaseimponibile);
    }
    public Integer getIdbaseimponibile() {
        return (Integer)readProperty("idbaseimponibile");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdinpscontratto(String idinpscontratto) {
        writeProperty("idinpscontratto", idinpscontratto);
    }
    public String getIdinpscontratto() {
        return (String)readProperty("idinpscontratto");
    }

    public void setIdvoce(Short idvoce) {
        writeProperty("idvoce", idvoce);
    }
    public Short getIdvoce() {
        return (Short)readProperty("idvoce");
    }

    public void setIndiretto(Short indiretto) {
        writeProperty("indiretto", indiretto);
    }
    public Short getIndiretto() {
        return (Short)readProperty("indiretto");
    }

    public void setInps(Short inps) {
        writeProperty("inps", inps);
    }
    public Short getInps() {
        return (Short)readProperty("inps");
    }

    public void setIrpef(Short irpef) {
        writeProperty("irpef", irpef);
    }
    public Short getIrpef() {
        return (Short)readProperty("irpef");
    }

    public void setMaggiorazione(Short maggiorazione) {
        writeProperty("maggiorazione", maggiorazione);
    }
    public Short getMaggiorazione() {
        return (Short)readProperty("maggiorazione");
    }

    public void setMese(Short mese) {
        writeProperty("mese", mese);
    }
    public Short getMese() {
        return (Short)readProperty("mese");
    }

    public void setTfr(Short tfr) {
        writeProperty("tfr", tfr);
    }
    public Short getTfr() {
        return (Short)readProperty("tfr");
    }

    public void addToContrattodettaglioVoceArray(ContrattodettagliovoceCedolino obj) {
        addToManyTarget("contrattodettaglioVoceArray", obj, true);
    }
    public void removeFromContrattodettaglioVoceArray(ContrattodettagliovoceCedolino obj) {
        removeToManyTarget("contrattodettaglioVoceArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContrattodettagliovoceCedolino> getContrattodettaglioVoceArray() {
        return (List<ContrattodettagliovoceCedolino>)readProperty("contrattodettaglioVoceArray");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToContrattovoce(Contrattovoce toContrattovoce) {
        setToOneTarget("toContrattovoce", toContrattovoce, true);
    }

    public Contrattovoce getToContrattovoce() {
        return (Contrattovoce)readProperty("toContrattovoce");
    }


    public void setToElementobaeimponibile(Elementobaseimponibile toElementobaeimponibile) {
        setToOneTarget("toElementobaeimponibile", toElementobaeimponibile, true);
    }

    public Elementobaseimponibile getToElementobaeimponibile() {
        return (Elementobaseimponibile)readProperty("toElementobaeimponibile");
    }


}
