package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Cigautorizzata;
import it.iubar.paghe.logic.paghe.Ciginderoga;
import it.iubar.paghe.logic.paghe.Cigord;
import it.iubar.paghe.logic.paghe.Cigstraord;
import it.iubar.paghe.logic.paghe.Denunciaaziendale;
import it.iubar.paghe.logic.paghe.Solidarieta;

/**
 * Class _Conguagliocig was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Conguagliocig extends CayenneDataObject {

    public static final String IDDENUNCIAAZIENDALE_PROPERTY = "iddenunciaaziendale";
    public static final String CIGAUTORIZZATA_ARRAY_PROPERTY = "cigautorizzataArray";
    public static final String CIGINDEROGA_ARRAY_PROPERTY = "ciginderogaArray";
    public static final String CIGORD_ARRAY_PROPERTY = "cigordArray";
    public static final String CIGSTRAORD_ARRAY_PROPERTY = "cigstraordArray";
    public static final String SOLIDARIETA_ARRAY_PROPERTY = "solidarietaArray";
    public static final String TO_DENUNCIAAZIENDALE_PROPERTY = "toDenunciaaziendale";

    public static final String IDDENUNCIAAZIENDALE_PK_COLUMN = "IDDENUNCIAAZIENDALE";

    public void setIddenunciaaziendale(Integer iddenunciaaziendale) {
        writeProperty("iddenunciaaziendale", iddenunciaaziendale);
    }
    public Integer getIddenunciaaziendale() {
        return (Integer)readProperty("iddenunciaaziendale");
    }

    public void addToCigautorizzataArray(Cigautorizzata obj) {
        addToManyTarget("cigautorizzataArray", obj, true);
    }
    public void removeFromCigautorizzataArray(Cigautorizzata obj) {
        removeToManyTarget("cigautorizzataArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cigautorizzata> getCigautorizzataArray() {
        return (List<Cigautorizzata>)readProperty("cigautorizzataArray");
    }


    public void addToCiginderogaArray(Ciginderoga obj) {
        addToManyTarget("ciginderogaArray", obj, true);
    }
    public void removeFromCiginderogaArray(Ciginderoga obj) {
        removeToManyTarget("ciginderogaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Ciginderoga> getCiginderogaArray() {
        return (List<Ciginderoga>)readProperty("ciginderogaArray");
    }


    public void addToCigordArray(Cigord obj) {
        addToManyTarget("cigordArray", obj, true);
    }
    public void removeFromCigordArray(Cigord obj) {
        removeToManyTarget("cigordArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cigord> getCigordArray() {
        return (List<Cigord>)readProperty("cigordArray");
    }


    public void addToCigstraordArray(Cigstraord obj) {
        addToManyTarget("cigstraordArray", obj, true);
    }
    public void removeFromCigstraordArray(Cigstraord obj) {
        removeToManyTarget("cigstraordArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cigstraord> getCigstraordArray() {
        return (List<Cigstraord>)readProperty("cigstraordArray");
    }


    public void addToSolidarietaArray(Solidarieta obj) {
        addToManyTarget("solidarietaArray", obj, true);
    }
    public void removeFromSolidarietaArray(Solidarieta obj) {
        removeToManyTarget("solidarietaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Solidarieta> getSolidarietaArray() {
        return (List<Solidarieta>)readProperty("solidarietaArray");
    }


    public void setToDenunciaaziendale(Denunciaaziendale toDenunciaaziendale) {
        setToOneTarget("toDenunciaaziendale", toDenunciaaziendale, true);
    }

    public Denunciaaziendale getToDenunciaaziendale() {
        return (Denunciaaziendale)readProperty("toDenunciaaziendale");
    }


}
