package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattodettagliolivello;
import it.iubar.paghe.logic.paghe.Contrattovoce;

/**
 * Class _Contrattodettagliolivellovoce was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattodettagliolivellovoce extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String DATAAGGIORNAMENTO_PROPERTY = "dataaggiornamento";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDCONTRATTODETTRIF_PROPERTY = "idcontrattodettrif";
    public static final String IDLIVELLO_PROPERTY = "idlivello";
    public static final String IDLIVELLORIF_PROPERTY = "idlivellorif";
    public static final String IDVOCE_PROPERTY = "idvoce";
    public static final String IDVOCERIF_PROPERTY = "idvocerif";
    public static final String IMPORTO_PROPERTY = "importo";
    public static final String PERCENTUALE_PROPERTY = "percentuale";
    public static final String VALIDOALMESE_PROPERTY = "validoalmese";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String VALIDODALMESE_PROPERTY = "validodalmese";
    public static final String VALIDODALRIF_PROPERTY = "validodalrif";
    public static final String TO_CONTRATTODETTAGLIOLIVELLO_PROPERTY = "toContrattodettagliolivello";
    public static final String TO_CONTRATTOVOCE_PROPERTY = "toContrattovoce";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDLIVELLO_PK_COLUMN = "IDLIVELLO";
    public static final String IDVOCE_PK_COLUMN = "IDVOCE";
    public static final String VALIDODAL_PK_COLUMN = "VALIDODAL";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setDataaggiornamento(Date dataaggiornamento) {
        writeProperty("dataaggiornamento", dataaggiornamento);
    }
    public Date getDataaggiornamento() {
        return (Date)readProperty("dataaggiornamento");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdcontrattodettrif(Integer idcontrattodettrif) {
        writeProperty("idcontrattodettrif", idcontrattodettrif);
    }
    public Integer getIdcontrattodettrif() {
        return (Integer)readProperty("idcontrattodettrif");
    }

    public void setIdlivello(String idlivello) {
        writeProperty("idlivello", idlivello);
    }
    public String getIdlivello() {
        return (String)readProperty("idlivello");
    }

    public void setIdlivellorif(String idlivellorif) {
        writeProperty("idlivellorif", idlivellorif);
    }
    public String getIdlivellorif() {
        return (String)readProperty("idlivellorif");
    }

    public void setIdvoce(Short idvoce) {
        writeProperty("idvoce", idvoce);
    }
    public Short getIdvoce() {
        return (Short)readProperty("idvoce");
    }

    public void setIdvocerif(Short idvocerif) {
        writeProperty("idvocerif", idvocerif);
    }
    public Short getIdvocerif() {
        return (Short)readProperty("idvocerif");
    }

    public void setImporto(BigDecimal importo) {
        writeProperty("importo", importo);
    }
    public BigDecimal getImporto() {
        return (BigDecimal)readProperty("importo");
    }

    public void setPercentuale(BigDecimal percentuale) {
        writeProperty("percentuale", percentuale);
    }
    public BigDecimal getPercentuale() {
        return (BigDecimal)readProperty("percentuale");
    }

    public void setValidoalmese(Short validoalmese) {
        writeProperty("validoalmese", validoalmese);
    }
    public Short getValidoalmese() {
        return (Short)readProperty("validoalmese");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void setValidodalmese(Short validodalmese) {
        writeProperty("validodalmese", validodalmese);
    }
    public Short getValidodalmese() {
        return (Short)readProperty("validodalmese");
    }

    public void setValidodalrif(Date validodalrif) {
        writeProperty("validodalrif", validodalrif);
    }
    public Date getValidodalrif() {
        return (Date)readProperty("validodalrif");
    }

    public void setToContrattodettagliolivello(Contrattodettagliolivello toContrattodettagliolivello) {
        setToOneTarget("toContrattodettagliolivello", toContrattodettagliolivello, true);
    }

    public Contrattodettagliolivello getToContrattodettagliolivello() {
        return (Contrattodettagliolivello)readProperty("toContrattodettagliolivello");
    }


    public void setToContrattovoce(Contrattovoce toContrattovoce) {
        setToOneTarget("toContrattovoce", toContrattovoce, true);
    }

    public Contrattovoce getToContrattovoce() {
        return (Contrattovoce)readProperty("toContrattovoce");
    }


}
