package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Cedolino;
import it.iubar.paghe.logic.paghe.Contrattodettagliovoce;

/**
 * Class _ContrattodettagliovoceCedolino was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContrattodettagliovoceCedolino extends CayenneDataObject {

    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDTIPOFOGLIO_PROPERTY = "idtipofoglio";
    public static final String IDVOCE_PROPERTY = "idvoce";
    public static final String TO_CEDOLINO_PROPERTY = "toCedolino";
    public static final String TO_CONTRATTODETTAGLIOVOCE_PROPERTY = "toContrattodettagliovoce";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";
    public static final String IDTIPOFOGLIO_PK_COLUMN = "IDTIPOFOGLIO";
    public static final String IDVOCE_PK_COLUMN = "IDVOCE";

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdtipofoglio(Short idtipofoglio) {
        writeProperty("idtipofoglio", idtipofoglio);
    }
    public Short getIdtipofoglio() {
        return (Short)readProperty("idtipofoglio");
    }

    public void setIdvoce(Short idvoce) {
        writeProperty("idvoce", idvoce);
    }
    public Short getIdvoce() {
        return (Short)readProperty("idvoce");
    }

    public void setToCedolino(Cedolino toCedolino) {
        setToOneTarget("toCedolino", toCedolino, true);
    }

    public Cedolino getToCedolino() {
        return (Cedolino)readProperty("toCedolino");
    }


    public void setToContrattodettagliovoce(Contrattodettagliovoce toContrattodettagliovoce) {
        setToOneTarget("toContrattodettagliovoce", toContrattodettagliovoce, true);
    }

    public Contrattodettagliovoce getToContrattodettagliovoce() {
        return (Contrattodettagliovoce)readProperty("toContrattodettagliovoce");
    }


}
