package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoparticolare;

/**
 * Class _Contrattoriallineamento was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattoriallineamento extends CayenneDataObject {

    public static final String GIORNIINFMINIMALE_PROPERTY = "giorniinfminimale";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String QUOTARETRIBINFMINIMALE_PROPERTY = "quotaretribinfminimale";
    public static final String DATO_PARTICOLARE_ARRAY_PROPERTY = "datoParticolareArray";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setGiorniinfminimale(Short giorniinfminimale) {
        writeProperty("giorniinfminimale", giorniinfminimale);
    }
    public Short getGiorniinfminimale() {
        return (Short)readProperty("giorniinfminimale");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setQuotaretribinfminimale(BigDecimal quotaretribinfminimale) {
        writeProperty("quotaretribinfminimale", quotaretribinfminimale);
    }
    public BigDecimal getQuotaretribinfminimale() {
        return (BigDecimal)readProperty("quotaretribinfminimale");
    }

    public void addToDatoParticolareArray(Datoparticolare obj) {
        addToManyTarget("datoParticolareArray", obj, true);
    }
    public void removeFromDatoParticolareArray(Datoparticolare obj) {
        removeToManyTarget("datoParticolareArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Datoparticolare> getDatoParticolareArray() {
        return (List<Datoparticolare>)readProperty("datoParticolareArray");
    }


}
