package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Denunciaaziendale;

/**
 * Class _Conguaglioasocred was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Conguaglioasocred extends CayenneDataObject {

    public static final String CREDITO_PROPERTY = "credito";
    public static final String DEBITO_PROPERTY = "debito";
    public static final String IDDENUNCIAAZIENDALE_PROPERTY = "iddenunciaaziendale";
    public static final String NUMAPPROVAZIONE_PROPERTY = "numapprovazione";
    public static final String TO_DENUNCIAAZIENDALE_PROPERTY = "toDenunciaaziendale";

    public static final String IDDENUNCIAAZIENDALE_PK_COLUMN = "IDDENUNCIAAZIENDALE";
    public static final String NUMAPPROVAZIONE_PK_COLUMN = "NUMAPPROVAZIONE";

    public void setCredito(BigDecimal credito) {
        writeProperty("credito", credito);
    }
    public BigDecimal getCredito() {
        return (BigDecimal)readProperty("credito");
    }

    public void setDebito(BigDecimal debito) {
        writeProperty("debito", debito);
    }
    public BigDecimal getDebito() {
        return (BigDecimal)readProperty("debito");
    }

    public void setIddenunciaaziendale(Integer iddenunciaaziendale) {
        writeProperty("iddenunciaaziendale", iddenunciaaziendale);
    }
    public Integer getIddenunciaaziendale() {
        return (Integer)readProperty("iddenunciaaziendale");
    }

    public void setNumapprovazione(String numapprovazione) {
        writeProperty("numapprovazione", numapprovazione);
    }
    public String getNumapprovazione() {
        return (String)readProperty("numapprovazione");
    }

    public void setToDenunciaaziendale(Denunciaaziendale toDenunciaaziendale) {
        setToOneTarget("toDenunciaaziendale", toDenunciaaziendale, true);
    }

    public Denunciaaziendale getToDenunciaaziendale() {
        return (Denunciaaziendale)readProperty("toDenunciaaziendale");
    }


}
