package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DaFondointerprof;

/**
 * Class _DaFondointeradesione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DaFondointeradesione extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDFONDOINTERADESIONE_PROPERTY = "idfondointeradesione";
    public static final String DA_FONDO_INTERPROF1ARRAY_PROPERTY = "daFondoInterprof1Array";
    public static final String DA_FONDO_INTERPROF2ARRAY_PROPERTY = "daFondoInterprof2Array";

    public static final String IDFONDOINTERADESIONE_PK_COLUMN = "IDFONDOINTERADESIONE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdfondointeradesione() {
        return (String)readProperty("idfondointeradesione");
    }

    public void addToDaFondoInterprof1Array(DaFondointerprof obj) {
        addToManyTarget("daFondoInterprof1Array", obj, true);
    }
    public void removeFromDaFondoInterprof1Array(DaFondointerprof obj) {
        removeToManyTarget("daFondoInterprof1Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DaFondointerprof> getDaFondoInterprof1Array() {
        return (List<DaFondointerprof>)readProperty("daFondoInterprof1Array");
    }


    public void addToDaFondoInterprof2Array(DaFondointerprof obj) {
        addToManyTarget("daFondoInterprof2Array", obj, true);
    }
    public void removeFromDaFondoInterprof2Array(DaFondointerprof obj) {
        removeToManyTarget("daFondoInterprof2Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DaFondointerprof> getDaFondoInterprof2Array() {
        return (List<DaFondointerprof>)readProperty("daFondoInterprof2Array");
    }


}
