package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DmagArealav;
import it.iubar.paghe.logic.paghe.DmagTipocontratto;
import it.iubar.paghe.logic.paghe.DmagTipolav;
import it.iubar.paghe.logic.paghe.DmagTiporetribuzione1;
import it.iubar.paghe.logic.paghe.DmagTiporetribuzione2;
import it.iubar.paghe.logic.paghe.DmagZt;

/**
 * Class _DmagLavoratoreprofilo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DmagLavoratoreprofilo extends CayenneDataObject {

    public static final String IDAREALAV_PROPERTY = "idarealav";
    public static final String IDLAVORATORE_PROPERTY = "idlavoratore";
    public static final String IDTIPOCONTRATTO_PROPERTY = "idtipocontratto";
    public static final String IDTIPOLAV_PROPERTY = "idtipolav";
    public static final String IDTIPORETRIBUZIONE1_PROPERTY = "idtiporetribuzione1";
    public static final String IDTIPORETRIBUZIONE2_PROPERTY = "idtiporetribuzione2";
    public static final String IDZT_PROPERTY = "idzt";
    public static final String TO_DMAG_AREALAV_PROPERTY = "toDmagArealav";
    public static final String TO_DMAG_TIPOCONTRATTO_PROPERTY = "toDmagTipocontratto";
    public static final String TO_DMAG_TIPOLAV_PROPERTY = "toDmagTipolav";
    public static final String TO_DMAG_TIPORETRIB1_PROPERTY = "toDmagTiporetrib1";
    public static final String TO_DMAG_TIPORETRIB2_PROPERTY = "toDmagTiporetrib2";
    public static final String TO_DMAG_ZT_PROPERTY = "toDmagZt";

    public static final String IDLAVORATORE_PK_COLUMN = "IDLAVORATORE";

    public void setIdarealav(Short idarealav) {
        writeProperty("idarealav", idarealav);
    }
    public Short getIdarealav() {
        return (Short)readProperty("idarealav");
    }

    public void setIdlavoratore(Integer idlavoratore) {
        writeProperty("idlavoratore", idlavoratore);
    }
    public Integer getIdlavoratore() {
        return (Integer)readProperty("idlavoratore");
    }

    public void setIdtipocontratto(Short idtipocontratto) {
        writeProperty("idtipocontratto", idtipocontratto);
    }
    public Short getIdtipocontratto() {
        return (Short)readProperty("idtipocontratto");
    }

    public void setIdtipolav(Short idtipolav) {
        writeProperty("idtipolav", idtipolav);
    }
    public Short getIdtipolav() {
        return (Short)readProperty("idtipolav");
    }

    public void setIdtiporetribuzione1(Short idtiporetribuzione1) {
        writeProperty("idtiporetribuzione1", idtiporetribuzione1);
    }
    public Short getIdtiporetribuzione1() {
        return (Short)readProperty("idtiporetribuzione1");
    }

    public void setIdtiporetribuzione2(Short idtiporetribuzione2) {
        writeProperty("idtiporetribuzione2", idtiporetribuzione2);
    }
    public Short getIdtiporetribuzione2() {
        return (Short)readProperty("idtiporetribuzione2");
    }

    public void setIdzt(Short idzt) {
        writeProperty("idzt", idzt);
    }
    public Short getIdzt() {
        return (Short)readProperty("idzt");
    }

    public void setToDmagArealav(DmagArealav toDmagArealav) {
        setToOneTarget("toDmagArealav", toDmagArealav, true);
    }

    public DmagArealav getToDmagArealav() {
        return (DmagArealav)readProperty("toDmagArealav");
    }


    public void setToDmagTipocontratto(DmagTipocontratto toDmagTipocontratto) {
        setToOneTarget("toDmagTipocontratto", toDmagTipocontratto, true);
    }

    public DmagTipocontratto getToDmagTipocontratto() {
        return (DmagTipocontratto)readProperty("toDmagTipocontratto");
    }


    public void setToDmagTipolav(DmagTipolav toDmagTipolav) {
        setToOneTarget("toDmagTipolav", toDmagTipolav, true);
    }

    public DmagTipolav getToDmagTipolav() {
        return (DmagTipolav)readProperty("toDmagTipolav");
    }


    public void setToDmagTiporetrib1(DmagTiporetribuzione1 toDmagTiporetrib1) {
        setToOneTarget("toDmagTiporetrib1", toDmagTiporetrib1, true);
    }

    public DmagTiporetribuzione1 getToDmagTiporetrib1() {
        return (DmagTiporetribuzione1)readProperty("toDmagTiporetrib1");
    }


    public void setToDmagTiporetrib2(DmagTiporetribuzione2 toDmagTiporetrib2) {
        setToOneTarget("toDmagTiporetrib2", toDmagTiporetrib2, true);
    }

    public DmagTiporetribuzione2 getToDmagTiporetrib2() {
        return (DmagTiporetribuzione2)readProperty("toDmagTiporetrib2");
    }


    public void setToDmagZt(DmagZt toDmagZt) {
        setToOneTarget("toDmagZt", toDmagZt, true);
    }

    public DmagZt getToDmagZt() {
        return (DmagZt)readProperty("toDmagZt");
    }


}
