package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.blob.Documento;
import it.iubar.paghe.logic.paghe.Dichiarazione;
import it.iubar.paghe.logic.paghe.DmagImpresa;
import it.iubar.paghe.logic.paghe.DmagLavoratore;

/**
 * Class _Dmag was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Dmag extends CayenneDataObject {

    public static final String IDDICHIARAZIONE_PROPERTY = "iddichiarazione";
    public static final String IDDOCUMENTO_PROPERTY = "iddocumento";
    public static final String IDEXPORT_PROPERTY = "idexport";
    public static final String TRIMESTRE_PROPERTY = "trimestre";
    public static final String DMAG_IMPRESA_ARRAY_PROPERTY = "dmagImpresaArray";
    public static final String DMAG_LAVORATORE_ARRAY_PROPERTY = "dmagLavoratoreArray";
    public static final String TO_DICHIARAZIONE_PROPERTY = "toDichiarazione";
    public static final String TO_DOCUMENTO_PROPERTY = "toDocumento";
    public static final String TO_EXPORT_PROPERTY = "toExport";

    public static final String IDDICHIARAZIONE_PK_COLUMN = "IDDICHIARAZIONE";

    public void setIddichiarazione(Integer iddichiarazione) {
        writeProperty("iddichiarazione", iddichiarazione);
    }
    public Integer getIddichiarazione() {
        return (Integer)readProperty("iddichiarazione");
    }

    public void setIddocumento(Integer iddocumento) {
        writeProperty("iddocumento", iddocumento);
    }
    public Integer getIddocumento() {
        return (Integer)readProperty("iddocumento");
    }

    public void setIdexport(Integer idexport) {
        writeProperty("idexport", idexport);
    }
    public Integer getIdexport() {
        return (Integer)readProperty("idexport");
    }

    public void setTrimestre(Short trimestre) {
        writeProperty("trimestre", trimestre);
    }
    public Short getTrimestre() {
        return (Short)readProperty("trimestre");
    }

    public void addToDmagImpresaArray(DmagImpresa obj) {
        addToManyTarget("dmagImpresaArray", obj, true);
    }
    public void removeFromDmagImpresaArray(DmagImpresa obj) {
        removeToManyTarget("dmagImpresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DmagImpresa> getDmagImpresaArray() {
        return (List<DmagImpresa>)readProperty("dmagImpresaArray");
    }


    public void addToDmagLavoratoreArray(DmagLavoratore obj) {
        addToManyTarget("dmagLavoratoreArray", obj, true);
    }
    public void removeFromDmagLavoratoreArray(DmagLavoratore obj) {
        removeToManyTarget("dmagLavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DmagLavoratore> getDmagLavoratoreArray() {
        return (List<DmagLavoratore>)readProperty("dmagLavoratoreArray");
    }


    public void setToDichiarazione(Dichiarazione toDichiarazione) {
        setToOneTarget("toDichiarazione", toDichiarazione, true);
    }

    public Dichiarazione getToDichiarazione() {
        return (Dichiarazione)readProperty("toDichiarazione");
    }


    public void setToDocumento(Documento toDocumento) {
        setToOneTarget("toDocumento", toDocumento, true);
    }

    public Documento getToDocumento() {
        return (Documento)readProperty("toDocumento");
    }


    public void setToExport(Documento toExport) {
        setToOneTarget("toExport", toExport, true);
    }

    public Documento getToExport() {
        return (Documento)readProperty("toExport");
    }


}
