package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoretributivo;

/**
 * Class _DrContribaggiuntiva was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrContribaggiuntiva extends CayenneDataObject {

    public static final String CONTRIB1PERCENTOCONTRIBAGGCORR_PROPERTY = "contrib1percentocontribaggcorr";
    public static final String CONTRIB1PERCENTOIMPCTRAGG_PROPERTY = "contrib1percentoimpctragg";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String REGOLARIZZ1PERCENTOCONTRIBAGG_PROPERTY = "regolarizz1percentocontribagg";
    public static final String REGOLARIZZ1PERCENTORECAGGREG_PROPERTY = "regolarizz1percentorecaggreg";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setContrib1percentocontribaggcorr(BigDecimal contrib1percentocontribaggcorr) {
        writeProperty("contrib1percentocontribaggcorr", contrib1percentocontribaggcorr);
    }
    public BigDecimal getContrib1percentocontribaggcorr() {
        return (BigDecimal)readProperty("contrib1percentocontribaggcorr");
    }

    public void setContrib1percentoimpctragg(BigDecimal contrib1percentoimpctragg) {
        writeProperty("contrib1percentoimpctragg", contrib1percentoimpctragg);
    }
    public BigDecimal getContrib1percentoimpctragg() {
        return (BigDecimal)readProperty("contrib1percentoimpctragg");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setRegolarizz1percentocontribagg(BigDecimal regolarizz1percentocontribagg) {
        writeProperty("regolarizz1percentocontribagg", regolarizz1percentocontribagg);
    }
    public BigDecimal getRegolarizz1percentocontribagg() {
        return (BigDecimal)readProperty("regolarizz1percentocontribagg");
    }

    public void setRegolarizz1percentorecaggreg(BigDecimal regolarizz1percentorecaggreg) {
        writeProperty("regolarizz1percentorecaggreg", regolarizz1percentorecaggreg);
    }
    public BigDecimal getRegolarizz1percentorecaggreg() {
        return (BigDecimal)readProperty("regolarizz1percentorecaggreg");
    }

    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


}
