package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DrMaternitaadebito;

/**
 * Class _DrCausaleversmat was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrCausaleversmat extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDCAUSALEVERSMAT_PROPERTY = "idcausaleversmat";
    public static final String DR_MATERNITA_ADEBITO_ARRAY_PROPERTY = "drMaternitaADebitoArray";

    public static final String IDCAUSALEVERSMAT_PK_COLUMN = "IDCAUSALEVERSMAT";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdcausaleversmat() {
        return (String)readProperty("idcausaleversmat");
    }

    public void addToDrMaternitaADebitoArray(DrMaternitaadebito obj) {
        addToManyTarget("drMaternitaADebitoArray", obj, true);
    }
    public void removeFromDrMaternitaADebitoArray(DrMaternitaadebito obj) {
        removeToManyTarget("drMaternitaADebitoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrMaternitaadebito> getDrMaternitaADebitoArray() {
        return (List<DrMaternitaadebito>)readProperty("drMaternitaADebitoArray");
    }


}
