package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Cigoacredaltre;

/**
 * Class _DrCausalecongcigo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrCausalecongcigo extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDCAUSALECONGCIGO_PROPERTY = "idcausalecongcigo";
    public static final String CIGO_ACRED_ALTRE_ARRAY_PROPERTY = "cigoACredAltreArray";

    public static final String IDCAUSALECONGCIGO_PK_COLUMN = "IDCAUSALECONGCIGO";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdcausalecongcigo() {
        return (String)readProperty("idcausalecongcigo");
    }

    public void addToCigoACredAltreArray(Cigoacredaltre obj) {
        addToManyTarget("cigoACredAltreArray", obj, true);
    }
    public void removeFromCigoACredAltreArray(Cigoacredaltre obj) {
        removeToManyTarget("cigoACredAltreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cigoacredaltre> getCigoACredAltreArray() {
        return (List<Cigoacredaltre>)readProperty("cigoACredAltreArray");
    }


}
