package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoretributivo;

/**
 * Class _DrFondointegrativo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrFondointegrativo extends CayenneDataObject {

    public static final String CONTRIBUTOFONDOINTEGR_PROPERTY = "contributofondointegr";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IMPONIBILEFONDOINTEGR_PROPERTY = "imponibilefondointegr";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setContributofondointegr(BigDecimal contributofondointegr) {
        writeProperty("contributofondointegr", contributofondointegr);
    }
    public BigDecimal getContributofondointegr() {
        return (BigDecimal)readProperty("contributofondointegr");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setImponibilefondointegr(BigDecimal imponibilefondointegr) {
        writeProperty("imponibilefondointegr", imponibilefondointegr);
    }
    public BigDecimal getImponibilefondointegr() {
        return (BigDecimal)readProperty("imponibilefondointegr");
    }

    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


}
