package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DrCausaleversmal;

/**
 * Class _DrMalattiaadebito was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrMalattiaadebito extends CayenneDataObject {

    public static final String IDCAUSALEVERSMAL_PROPERTY = "idcausaleversmal";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IDMALATTIAADEBITO_PROPERTY = "idmalattiaadebito";
    public static final String IMPORTOVERSMAL_PROPERTY = "importoversmal";
    public static final String TO_DR_CAUSALE_VERS_MAL_PROPERTY = "toDrCausaleVersMal";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";
    public static final String IDMALATTIAADEBITO_PK_COLUMN = "IDMALATTIAADEBITO";

    public void setIdcausaleversmal(String idcausaleversmal) {
        writeProperty("idcausaleversmal", idcausaleversmal);
    }
    public String getIdcausaleversmal() {
        return (String)readProperty("idcausaleversmal");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIdmalattiaadebito(Short idmalattiaadebito) {
        writeProperty("idmalattiaadebito", idmalattiaadebito);
    }
    public Short getIdmalattiaadebito() {
        return (Short)readProperty("idmalattiaadebito");
    }

    public void setImportoversmal(BigDecimal importoversmal) {
        writeProperty("importoversmal", importoversmal);
    }
    public BigDecimal getImportoversmal() {
        return (BigDecimal)readProperty("importoversmal");
    }

    public void setToDrCausaleVersMal(DrCausaleversmal toDrCausaleVersMal) {
        setToOneTarget("toDrCausaleVersMal", toDrCausaleVersMal, true);
    }

    public DrCausaleversmal getToDrCausaleVersMal() {
        return (DrCausaleversmal)readProperty("toDrCausaleVersMal");
    }


}
