package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoretributivo;
import it.iubar.paghe.logic.paghe.DrMaternitaacredito;
import it.iubar.paghe.logic.paghe.DrMaternitaadebito;

/**
 * Class _DrMaternita was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrMaternita extends CayenneDataObject {

    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String DR_MATERNITA_ACREDITO_ARRAY_PROPERTY = "drMaternitaACreditoArray";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";
    public static final String TO_DR_MATERNITA_ADEBITO_PROPERTY = "toDrMaternitaADebito";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void addToDrMaternitaACreditoArray(DrMaternitaacredito obj) {
        addToManyTarget("drMaternitaACreditoArray", obj, true);
    }
    public void removeFromDrMaternitaACreditoArray(DrMaternitaacredito obj) {
        removeToManyTarget("drMaternitaACreditoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrMaternitaacredito> getDrMaternitaACreditoArray() {
        return (List<DrMaternitaacredito>)readProperty("drMaternitaACreditoArray");
    }


    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


    public void addToToDrMaternitaADebito(DrMaternitaadebito obj) {
        addToManyTarget("toDrMaternitaADebito", obj, true);
    }
    public void removeFromToDrMaternitaADebito(DrMaternitaadebito obj) {
        removeToManyTarget("toDrMaternitaADebito", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrMaternitaadebito> getToDrMaternitaADebito() {
        return (List<DrMaternitaadebito>)readProperty("toDrMaternitaADebito");
    }


}
