package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoretributivo;
import it.iubar.paghe.logic.paghe.DrMalattiaacredito;
import it.iubar.paghe.logic.paghe.DrMaternitaadebito;

/**
 * Class _DrMalattia was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrMalattia extends CayenneDataObject {

    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String DR_MALATTIA_ACREDITO_ARRAY_PROPERTY = "drMalattiaACreditoArray";
    public static final String DR_MALATTIA_ARRAY_PROPERTY = "drMalattiaArray";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void addToDrMalattiaACreditoArray(DrMalattiaacredito obj) {
        addToManyTarget("drMalattiaACreditoArray", obj, true);
    }
    public void removeFromDrMalattiaACreditoArray(DrMalattiaacredito obj) {
        removeToManyTarget("drMalattiaACreditoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrMalattiaacredito> getDrMalattiaACreditoArray() {
        return (List<DrMalattiaacredito>)readProperty("drMalattiaACreditoArray");
    }


    public void addToDrMalattiaArray(DrMaternitaadebito obj) {
        addToManyTarget("drMalattiaArray", obj, true);
    }
    public void removeFromDrMalattiaArray(DrMaternitaadebito obj) {
        removeToManyTarget("drMalattiaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrMaternitaadebito> getDrMalattiaArray() {
        return (List<DrMaternitaadebito>)readProperty("drMalattiaArray");
    }


    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


}
