package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattoassenza;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Contrattodettagliovoce;
import it.iubar.paghe.logic.paghe.Contrattoindennita;
import it.iubar.paghe.logic.paghe.Contrattomaggiorazione;
import it.iubar.paghe.logic.paghe.Contrattoscatto;
import it.iubar.paghe.logic.paghe.ContrattovoceBaseimp;
import it.iubar.paghe.logic.paghe.ElementobaseimpBaseimp;
import it.iubar.paghe.logic.paghe.Elementoretributivo;
import it.iubar.paghe.logic.paghe.InpsContratto;

/**
 * Class _Elementobaseimponibile was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Elementobaseimponibile extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDBASEIMPONIBILE_PROPERTY = "idbaseimponibile";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDINPSCONTRATTO_PROPERTY = "idinpscontratto";
    public static final String NOTE_PROPERTY = "note";
    public static final String RETRIBUTIVO_PROPERTY = "retributivo";
    public static final String BASEIMPBASEIMP_ARRAY1_PROPERTY = "baseimpbaseimpArray1";
    public static final String BASEIMPBASEIMP_ARRAY2_PROPERTY = "baseimpbaseimpArray2";
    public static final String CONTRATTOASSENZA_ARRAY_PROPERTY = "contrattoassenzaArray";
    public static final String CONTRATTODETTAGLIOVOCE_ARRAY_PROPERTY = "contrattodettagliovoceArray";
    public static final String CONTRATTOINDENNITA_ARRAY_PROPERTY = "contrattoindennitaArray";
    public static final String CONTRATTOSCATTO_ARRAY_PROPERTY = "contrattoscattoArray";
    public static final String ELEMENTORETRIBUTIVO_ARRAY_PROPERTY = "elementoretributivoArray";
    public static final String LAVSTRAORDINARIO_ARRAY_PROPERTY = "lavstraordinarioArray";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_INPS_CONTRATTO_PROPERTY = "toInpsContratto";
    public static final String VOCEBASEIMP_ARRAY_PROPERTY = "vocebaseimpArray";

    public static final String IDBASEIMPONIBILE_PK_COLUMN = "IDBASEIMPONIBILE";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setIdbaseimponibile(Integer idbaseimponibile) {
        writeProperty("idbaseimponibile", idbaseimponibile);
    }
    public Integer getIdbaseimponibile() {
        return (Integer)readProperty("idbaseimponibile");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdinpscontratto(String idinpscontratto) {
        writeProperty("idinpscontratto", idinpscontratto);
    }
    public String getIdinpscontratto() {
        return (String)readProperty("idinpscontratto");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setRetributivo(Short retributivo) {
        writeProperty("retributivo", retributivo);
    }
    public Short getRetributivo() {
        return (Short)readProperty("retributivo");
    }

    public void addToBaseimpbaseimpArray1(ElementobaseimpBaseimp obj) {
        addToManyTarget("baseimpbaseimpArray1", obj, true);
    }
    public void removeFromBaseimpbaseimpArray1(ElementobaseimpBaseimp obj) {
        removeToManyTarget("baseimpbaseimpArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ElementobaseimpBaseimp> getBaseimpbaseimpArray1() {
        return (List<ElementobaseimpBaseimp>)readProperty("baseimpbaseimpArray1");
    }


    public void addToBaseimpbaseimpArray2(ElementobaseimpBaseimp obj) {
        addToManyTarget("baseimpbaseimpArray2", obj, true);
    }
    public void removeFromBaseimpbaseimpArray2(ElementobaseimpBaseimp obj) {
        removeToManyTarget("baseimpbaseimpArray2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ElementobaseimpBaseimp> getBaseimpbaseimpArray2() {
        return (List<ElementobaseimpBaseimp>)readProperty("baseimpbaseimpArray2");
    }


    public void addToContrattoassenzaArray(Contrattoassenza obj) {
        addToManyTarget("contrattoassenzaArray", obj, true);
    }
    public void removeFromContrattoassenzaArray(Contrattoassenza obj) {
        removeToManyTarget("contrattoassenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoassenza> getContrattoassenzaArray() {
        return (List<Contrattoassenza>)readProperty("contrattoassenzaArray");
    }


    public void addToContrattodettagliovoceArray(Contrattodettagliovoce obj) {
        addToManyTarget("contrattodettagliovoceArray", obj, true);
    }
    public void removeFromContrattodettagliovoceArray(Contrattodettagliovoce obj) {
        removeToManyTarget("contrattodettagliovoceArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattodettagliovoce> getContrattodettagliovoceArray() {
        return (List<Contrattodettagliovoce>)readProperty("contrattodettagliovoceArray");
    }


    public void addToContrattoindennitaArray(Contrattoindennita obj) {
        addToManyTarget("contrattoindennitaArray", obj, true);
    }
    public void removeFromContrattoindennitaArray(Contrattoindennita obj) {
        removeToManyTarget("contrattoindennitaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoindennita> getContrattoindennitaArray() {
        return (List<Contrattoindennita>)readProperty("contrattoindennitaArray");
    }


    public void addToContrattoscattoArray(Contrattoscatto obj) {
        addToManyTarget("contrattoscattoArray", obj, true);
    }
    public void removeFromContrattoscattoArray(Contrattoscatto obj) {
        removeToManyTarget("contrattoscattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoscatto> getContrattoscattoArray() {
        return (List<Contrattoscatto>)readProperty("contrattoscattoArray");
    }


    public void addToElementoretributivoArray(Elementoretributivo obj) {
        addToManyTarget("elementoretributivoArray", obj, true);
    }
    public void removeFromElementoretributivoArray(Elementoretributivo obj) {
        removeToManyTarget("elementoretributivoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Elementoretributivo> getElementoretributivoArray() {
        return (List<Elementoretributivo>)readProperty("elementoretributivoArray");
    }


    public void addToLavstraordinarioArray(Contrattomaggiorazione obj) {
        addToManyTarget("lavstraordinarioArray", obj, true);
    }
    public void removeFromLavstraordinarioArray(Contrattomaggiorazione obj) {
        removeToManyTarget("lavstraordinarioArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattomaggiorazione> getLavstraordinarioArray() {
        return (List<Contrattomaggiorazione>)readProperty("lavstraordinarioArray");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToInpsContratto(InpsContratto toInpsContratto) {
        setToOneTarget("toInpsContratto", toInpsContratto, true);
    }

    public InpsContratto getToInpsContratto() {
        return (InpsContratto)readProperty("toInpsContratto");
    }


    public void addToVocebaseimpArray(ContrattovoceBaseimp obj) {
        addToManyTarget("vocebaseimpArray", obj, true);
    }
    public void removeFromVocebaseimpArray(ContrattovoceBaseimp obj) {
        removeToManyTarget("vocebaseimpArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContrattovoceBaseimp> getVocebaseimpArray() {
        return (List<ContrattovoceBaseimp>)readProperty("vocebaseimpArray");
    }


}
