package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Giorno;
import it.iubar.paghe.logic.paghe.InpsTipoeventocig;
import it.iubar.paghe.logic.paghe.InpsTipoeventogiorno;

/**
 * Class _Eventociggg was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Eventociggg extends CayenneDataObject {

    public static final String GG_PROPERTY = "gg";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IDEVENTOCIG_PROPERTY = "ideventocig";
    public static final String IDTIPOEVENTOCIG_PROPERTY = "idtipoeventocig";
    public static final String IDTIPOEVENTOGIORNO_PROPERTY = "idtipoeventogiorno";
    public static final String NUMAPPROVASOCRED_PROPERTY = "numapprovasocred";
    public static final String ORE_PROPERTY = "ore";
    public static final String TO_GIORNO_PROPERTY = "toGiorno";
    public static final String TO_TIPOEVENTOCIG_PROPERTY = "toTipoeventocig";
    public static final String TO_TIPOEVENTOGG_PROPERTY = "toTipoeventogg";

    public static final String GG_PK_COLUMN = "GG";
    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";
    public static final String IDTIPOEVENTOGIORNO_PK_COLUMN = "IDTIPOEVENTOGIORNO";

    public void setGg(Short gg) {
        writeProperty("gg", gg);
    }
    public Short getGg() {
        return (Short)readProperty("gg");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIdeventocig(String ideventocig) {
        writeProperty("ideventocig", ideventocig);
    }
    public String getIdeventocig() {
        return (String)readProperty("ideventocig");
    }

    public void setIdtipoeventocig(String idtipoeventocig) {
        writeProperty("idtipoeventocig", idtipoeventocig);
    }
    public String getIdtipoeventocig() {
        return (String)readProperty("idtipoeventocig");
    }

    public void setIdtipoeventogiorno(String idtipoeventogiorno) {
        writeProperty("idtipoeventogiorno", idtipoeventogiorno);
    }
    public String getIdtipoeventogiorno() {
        return (String)readProperty("idtipoeventogiorno");
    }

    public void setNumapprovasocred(String numapprovasocred) {
        writeProperty("numapprovasocred", numapprovasocred);
    }
    public String getNumapprovasocred() {
        return (String)readProperty("numapprovasocred");
    }

    public void setOre(BigDecimal ore) {
        writeProperty("ore", ore);
    }
    public BigDecimal getOre() {
        return (BigDecimal)readProperty("ore");
    }

    public void setToGiorno(Giorno toGiorno) {
        setToOneTarget("toGiorno", toGiorno, true);
    }

    public Giorno getToGiorno() {
        return (Giorno)readProperty("toGiorno");
    }


    public void setToTipoeventocig(InpsTipoeventocig toTipoeventocig) {
        setToOneTarget("toTipoeventocig", toTipoeventocig, true);
    }

    public InpsTipoeventocig getToTipoeventocig() {
        return (InpsTipoeventocig)readProperty("toTipoeventocig");
    }


    public void setToTipoeventogg(InpsTipoeventogiorno toTipoeventogg) {
        setToOneTarget("toTipoeventogg", toTipoeventogg, true);
    }

    public InpsTipoeventogiorno getToTipoeventogg() {
        return (InpsTipoeventogiorno)readProperty("toTipoeventogg");
    }


}
