package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.F24;

/**
 * Class _F24Altroente was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _F24Altroente extends CayenneDataObject {

    public static final String IDDICHIARAZIONE_PROPERTY = "iddichiarazione";
    public static final String IDF24ALTROENTE_PROPERTY = "idf24altroente";
    public static final String TO_F24_PROPERTY = "toF24";

    public static final String IDDICHIARAZIONE_PK_COLUMN = "IDDICHIARAZIONE";
    public static final String IDF24ALTROENTE_PK_COLUMN = "IDF24ALTROENTE";

    public void setIddichiarazione(Integer iddichiarazione) {
        writeProperty("iddichiarazione", iddichiarazione);
    }
    public Integer getIddichiarazione() {
        return (Integer)readProperty("iddichiarazione");
    }

    public void setIdf24altroente(Short idf24altroente) {
        writeProperty("idf24altroente", idf24altroente);
    }
    public Short getIdf24altroente() {
        return (Short)readProperty("idf24altroente");
    }

    public void setToF24(F24 toF24) {
        setToOneTarget("toF24", toF24, true);
    }

    public F24 getToF24() {
        return (F24)readProperty("toF24");
    }


}
