package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoparticolare;
import it.iubar.paghe.logic.paghe.Fondoante95;
import it.iubar.paghe.logic.paghe.Fondodaziere;
import it.iubar.paghe.logic.paghe.Fondoesattoriale;
import it.iubar.paghe.logic.paghe.Fondofs;
import it.iubar.paghe.logic.paghe.Fondogas;
import it.iubar.paghe.logic.paghe.Fondoportuale;
import it.iubar.paghe.logic.paghe.Fondoprevmarinara;

/**
 * Class _Fondospeciale was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Fondospeciale extends CayenneDataObject {

    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String TO_DATOPARTICOLARE_PROPERTY = "toDatoparticolare";
    public static final String TO_DAZIERE_PROPERTY = "toDaziere";
    public static final String TO_ESATTORIALE_PROPERTY = "toEsattoriale";
    public static final String TO_FONDO_PREV_MARINARA_PROPERTY = "toFondoPrevMarinara";
    public static final String TO_FONDOANTE95_PROPERTY = "toFondoante95";
    public static final String TO_FONDOFS_PROPERTY = "toFondofs";
    public static final String TO_GAS_PROPERTY = "toGas";
    public static final String TO_PORTUALE_PROPERTY = "toPortuale";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setToDatoparticolare(Datoparticolare toDatoparticolare) {
        setToOneTarget("toDatoparticolare", toDatoparticolare, true);
    }

    public Datoparticolare getToDatoparticolare() {
        return (Datoparticolare)readProperty("toDatoparticolare");
    }


    public void setToDaziere(Fondodaziere toDaziere) {
        setToOneTarget("toDaziere", toDaziere, true);
    }

    public Fondodaziere getToDaziere() {
        return (Fondodaziere)readProperty("toDaziere");
    }


    public void setToEsattoriale(Fondoesattoriale toEsattoriale) {
        setToOneTarget("toEsattoriale", toEsattoriale, true);
    }

    public Fondoesattoriale getToEsattoriale() {
        return (Fondoesattoriale)readProperty("toEsattoriale");
    }


    public void setToFondoPrevMarinara(Fondoprevmarinara toFondoPrevMarinara) {
        setToOneTarget("toFondoPrevMarinara", toFondoPrevMarinara, true);
    }

    public Fondoprevmarinara getToFondoPrevMarinara() {
        return (Fondoprevmarinara)readProperty("toFondoPrevMarinara");
    }


    public void setToFondoante95(Fondoante95 toFondoante95) {
        setToOneTarget("toFondoante95", toFondoante95, true);
    }

    public Fondoante95 getToFondoante95() {
        return (Fondoante95)readProperty("toFondoante95");
    }


    public void setToFondofs(Fondofs toFondofs) {
        setToOneTarget("toFondofs", toFondofs, true);
    }

    public Fondofs getToFondofs() {
        return (Fondofs)readProperty("toFondofs");
    }


    public void setToGas(Fondogas toGas) {
        setToOneTarget("toGas", toGas, true);
    }

    public Fondogas getToGas() {
        return (Fondogas)readProperty("toGas");
    }


    public void setToPortuale(Fondoportuale toPortuale) {
        setToOneTarget("toPortuale", toPortuale, true);
    }

    public Fondoportuale getToPortuale() {
        return (Fondoportuale)readProperty("toPortuale");
    }


}
