package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.FondofsContribsindanno;
import it.iubar.paghe.logic.paghe.FondofsMese;
import it.iubar.paghe.logic.paghe.FondofsPreavviso;
import it.iubar.paghe.logic.paghe.Fondospeciale;

/**
 * Class _Fondofs was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Fondofs extends CayenneDataObject {

    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String CONTRIBSINDANNOFS_ARRAY_PROPERTY = "contribsindannofsArray";
    public static final String TO_DATIMESEFS_PROPERTY = "toDatimesefs";
    public static final String TO_FONDOSPECIALE_PROPERTY = "toFondospeciale";
    public static final String TO_PREAVVISOFS_PROPERTY = "toPreavvisofs";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void addToContribsindannofsArray(FondofsContribsindanno obj) {
        addToManyTarget("contribsindannofsArray", obj, true);
    }
    public void removeFromContribsindannofsArray(FondofsContribsindanno obj) {
        removeToManyTarget("contribsindannofsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FondofsContribsindanno> getContribsindannofsArray() {
        return (List<FondofsContribsindanno>)readProperty("contribsindannofsArray");
    }


    public void setToDatimesefs(FondofsMese toDatimesefs) {
        setToOneTarget("toDatimesefs", toDatimesefs, true);
    }

    public FondofsMese getToDatimesefs() {
        return (FondofsMese)readProperty("toDatimesefs");
    }


    public void setToFondospeciale(Fondospeciale toFondospeciale) {
        setToOneTarget("toFondospeciale", toFondospeciale, true);
    }

    public Fondospeciale getToFondospeciale() {
        return (Fondospeciale)readProperty("toFondospeciale");
    }


    public void setToPreavvisofs(FondofsPreavviso toPreavvisofs) {
        setToOneTarget("toPreavvisofs", toPreavvisofs, true);
    }

    public FondofsPreavviso getToPreavvisofs() {
        return (FondofsPreavviso)readProperty("toPreavvisofs");
    }


}
