package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Impresa;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.InpsAliquotaarea;
import it.iubar.paghe.logic.paghe.InpsContratto;
import it.iubar.paghe.logic.paghe.InpsLimitecategoria;
import it.iubar.paghe.logic.paghe.InpsSettore;

/**
 * Class _ImpresaContratto was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ImpresaContratto extends CayenneDataObject {

    public static final String ATTIVO_PROPERTY = "attivo";
    public static final String IDAREA_PROPERTY = "idarea";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDINPSCONTRATTO_PROPERTY = "idinpscontratto";
    public static final String IDINPSSETTORE_PROPERTY = "idinpssettore";
    public static final String IDLIMITECATEGORIA_PROPERTY = "idlimitecategoria";
    public static final String NOTE_PROPERTY = "note";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String TO_AREA_PROPERTY = "toArea";
    public static final String TO_CATEGORIA_PROPERTY = "toCategoria";
    public static final String TO_CONTRATTO_PROPERTY = "toContratto";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_IMPRESA_PROPERTY = "toImpresa";
    public static final String TO_SETTORE_PROPERTY = "toSettore";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";
    public static final String IDINPSCONTRATTO_PK_COLUMN = "IDINPSCONTRATTO";
    public static final String IDINPSSETTORE_PK_COLUMN = "IDINPSSETTORE";

    public void setAttivo(Short attivo) {
        writeProperty("attivo", attivo);
    }
    public Short getAttivo() {
        return (Short)readProperty("attivo");
    }

    public void setIdarea(Integer idarea) {
        writeProperty("idarea", idarea);
    }
    public Integer getIdarea() {
        return (Integer)readProperty("idarea");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdinpscontratto(String idinpscontratto) {
        writeProperty("idinpscontratto", idinpscontratto);
    }
    public String getIdinpscontratto() {
        return (String)readProperty("idinpscontratto");
    }

    public void setIdinpssettore(Integer idinpssettore) {
        writeProperty("idinpssettore", idinpssettore);
    }
    public Integer getIdinpssettore() {
        return (Integer)readProperty("idinpssettore");
    }

    public void setIdlimitecategoria(Short idlimitecategoria) {
        writeProperty("idlimitecategoria", idlimitecategoria);
    }
    public Short getIdlimitecategoria() {
        return (Short)readProperty("idlimitecategoria");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setValidoal(Date validoal) {
        writeProperty("validoal", validoal);
    }
    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void setToArea(InpsAliquotaarea toArea) {
        setToOneTarget("toArea", toArea, true);
    }

    public InpsAliquotaarea getToArea() {
        return (InpsAliquotaarea)readProperty("toArea");
    }


    public void setToCategoria(InpsLimitecategoria toCategoria) {
        setToOneTarget("toCategoria", toCategoria, true);
    }

    public InpsLimitecategoria getToCategoria() {
        return (InpsLimitecategoria)readProperty("toCategoria");
    }


    public void setToContratto(InpsContratto toContratto) {
        setToOneTarget("toContratto", toContratto, true);
    }

    public InpsContratto getToContratto() {
        return (InpsContratto)readProperty("toContratto");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToImpresa(Impresa toImpresa) {
        setToOneTarget("toImpresa", toImpresa, true);
    }

    public Impresa getToImpresa() {
        return (Impresa)readProperty("toImpresa");
    }


    public void setToSettore(InpsSettore toSettore) {
        setToOneTarget("toSettore", toSettore, true);
    }

    public InpsSettore getToSettore() {
        return (InpsSettore)readProperty("toSettore");
    }


}
