package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Parasubordinato;
import it.iubar.paghe.logic.paghe.Posizioneparasubordinato;

/**
 * Class _InailAliquota was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InailAliquota extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDINAILALIQUOTA_PROPERTY = "idinailaliquota";
    public static final String IDTIPO_PROPERTY = "idtipo";
    public static final String INAILALIQUOTAANNO_PROPERTY = "inailaliquotaanno";
    public static final String MASSIMALEANNUALE_PROPERTY = "massimaleannuale";
    public static final String MASSIMALEGIORNALIERO_PROPERTY = "massimalegiornaliero";
    public static final String MASSIMALEMENSILE_PROPERTY = "massimalemensile";
    public static final String MASSIMALEORARIO_PROPERTY = "massimaleorario";
    public static final String MINIMALEANNUALE_PROPERTY = "minimaleannuale";
    public static final String MINIMALEGIORNALIERO_PROPERTY = "minimalegiornaliero";
    public static final String MINIMALEMENSILE_PROPERTY = "minimalemensile";
    public static final String MINIMALEORARIO_PROPERTY = "minimaleorario";
    public static final String NOTE_PROPERTY = "note";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String PARASUBORDINATO_ARRAY_PROPERTY = "parasubordinatoArray";
    public static final String POSIZIONEPARA_ARRAY_PROPERTY = "posizioneparaArray";

    public static final String IDINAILALIQUOTA_PK_COLUMN = "IDINAILALIQUOTA";
    public static final String INAILALIQUOTAANNO_PK_COLUMN = "INAILALIQUOTAANNO";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Integer getIdinailaliquota() {
        return (Integer)readProperty("idinailaliquota");
    }

    public Short getIdtipo() {
        return (Short)readProperty("idtipo");
    }

    public Integer getInailaliquotaanno() {
        return (Integer)readProperty("inailaliquotaanno");
    }

    public BigDecimal getMassimaleannuale() {
        return (BigDecimal)readProperty("massimaleannuale");
    }

    public BigDecimal getMassimalegiornaliero() {
        return (BigDecimal)readProperty("massimalegiornaliero");
    }

    public BigDecimal getMassimalemensile() {
        return (BigDecimal)readProperty("massimalemensile");
    }

    public BigDecimal getMassimaleorario() {
        return (BigDecimal)readProperty("massimaleorario");
    }

    public BigDecimal getMinimaleannuale() {
        return (BigDecimal)readProperty("minimaleannuale");
    }

    public BigDecimal getMinimalegiornaliero() {
        return (BigDecimal)readProperty("minimalegiornaliero");
    }

    public BigDecimal getMinimalemensile() {
        return (BigDecimal)readProperty("minimalemensile");
    }

    public BigDecimal getMinimaleorario() {
        return (BigDecimal)readProperty("minimaleorario");
    }

    public String getNote() {
        return (String)readProperty("note");
    }

    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToParasubordinatoArray(Parasubordinato obj) {
        addToManyTarget("parasubordinatoArray", obj, true);
    }
    public void removeFromParasubordinatoArray(Parasubordinato obj) {
        removeToManyTarget("parasubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Parasubordinato> getParasubordinatoArray() {
        return (List<Parasubordinato>)readProperty("parasubordinatoArray");
    }


    public void addToPosizioneparaArray(Posizioneparasubordinato obj) {
        addToManyTarget("posizioneparaArray", obj, true);
    }
    public void removeFromPosizioneparaArray(Posizioneparasubordinato obj) {
        removeToManyTarget("posizioneparaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizioneparasubordinato> getPosizioneparaArray() {
        return (List<Posizioneparasubordinato>)readProperty("posizioneparaArray");
    }


}
