package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.InailPosizioneimpresa;

/**
 * Class _InailInfmal was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InailInfmal extends CayenneDataObject {

    public static final String ANNO_PROPERTY = "anno";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String PAT_PROPERTY = "pat";
    public static final String RATAAGEVOLAZ_PROPERTY = "rataagevolaz";
    public static final String RATAPREMIO_PROPERTY = "ratapremio";
    public static final String RATARETRIBUZ_PROPERTY = "rataretribuz";
    public static final String RATATASSO_PROPERTY = "ratatasso";
    public static final String REGAGEVOLAZ_PROPERTY = "regagevolaz";
    public static final String REGESENTE_PROPERTY = "regesente";
    public static final String REGOSCILLAZIONE_PROPERTY = "regoscillazione";
    public static final String REGPREMIO_PROPERTY = "regpremio";
    public static final String REGRETRIBUZESENTE_PROPERTY = "regretribuzesente";
    public static final String REGRETRIBUZTOT_PROPERTY = "regretribuztot";
    public static final String REGTASSO_PROPERTY = "regtasso";
    public static final String TO_INAIL_POSIZIONEIMPRESA_PROPERTY = "toInailPosizioneimpresa";

    public static final String ANNO_PK_COLUMN = "ANNO";
    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";
    public static final String PAT_PK_COLUMN = "PAT";

    public void setAnno(Integer anno) {
        writeProperty("anno", anno);
    }
    public Integer getAnno() {
        return (Integer)readProperty("anno");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setPat(String pat) {
        writeProperty("pat", pat);
    }
    public String getPat() {
        return (String)readProperty("pat");
    }

    public void setRataagevolaz(BigDecimal rataagevolaz) {
        writeProperty("rataagevolaz", rataagevolaz);
    }
    public BigDecimal getRataagevolaz() {
        return (BigDecimal)readProperty("rataagevolaz");
    }

    public void setRatapremio(BigDecimal ratapremio) {
        writeProperty("ratapremio", ratapremio);
    }
    public BigDecimal getRatapremio() {
        return (BigDecimal)readProperty("ratapremio");
    }

    public void setRataretribuz(BigDecimal rataretribuz) {
        writeProperty("rataretribuz", rataretribuz);
    }
    public BigDecimal getRataretribuz() {
        return (BigDecimal)readProperty("rataretribuz");
    }

    public void setRatatasso(BigDecimal ratatasso) {
        writeProperty("ratatasso", ratatasso);
    }
    public BigDecimal getRatatasso() {
        return (BigDecimal)readProperty("ratatasso");
    }

    public void setRegagevolaz(BigDecimal regagevolaz) {
        writeProperty("regagevolaz", regagevolaz);
    }
    public BigDecimal getRegagevolaz() {
        return (BigDecimal)readProperty("regagevolaz");
    }

    public void setRegesente(BigDecimal regesente) {
        writeProperty("regesente", regesente);
    }
    public BigDecimal getRegesente() {
        return (BigDecimal)readProperty("regesente");
    }

    public void setRegoscillazione(BigDecimal regoscillazione) {
        writeProperty("regoscillazione", regoscillazione);
    }
    public BigDecimal getRegoscillazione() {
        return (BigDecimal)readProperty("regoscillazione");
    }

    public void setRegpremio(BigDecimal regpremio) {
        writeProperty("regpremio", regpremio);
    }
    public BigDecimal getRegpremio() {
        return (BigDecimal)readProperty("regpremio");
    }

    public void setRegretribuzesente(BigDecimal regretribuzesente) {
        writeProperty("regretribuzesente", regretribuzesente);
    }
    public BigDecimal getRegretribuzesente() {
        return (BigDecimal)readProperty("regretribuzesente");
    }

    public void setRegretribuztot(BigDecimal regretribuztot) {
        writeProperty("regretribuztot", regretribuztot);
    }
    public BigDecimal getRegretribuztot() {
        return (BigDecimal)readProperty("regretribuztot");
    }

    public void setRegtasso(BigDecimal regtasso) {
        writeProperty("regtasso", regtasso);
    }
    public BigDecimal getRegtasso() {
        return (BigDecimal)readProperty("regtasso");
    }

    public void setToInailPosizioneimpresa(InailPosizioneimpresa toInailPosizioneimpresa) {
        setToOneTarget("toInailPosizioneimpresa", toInailPosizioneimpresa, true);
    }

    public InailPosizioneimpresa getToInailPosizioneimpresa() {
        return (InailPosizioneimpresa)readProperty("toInailPosizioneimpresa");
    }


}
