package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Subordinato;
import it.iubar.paghe.logic.paghe.Aliquotaprevidenziale;
import it.iubar.paghe.logic.paghe.Datoretributivo;
import it.iubar.paghe.logic.paghe.InpsTipolavoratoreFondo;

/**
 * Class _InpsTipolavoratore was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsTipolavoratore extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String FONDOSPECIALE_PROPERTY = "fondospeciale";
    public static final String IDINPSTIPOLAVORATORE_PROPERTY = "idinpstipolavoratore";
    public static final String ALIQUOTAPREVIDENZIALE_ARRAY_PROPERTY = "aliquotaprevidenzialeArray";
    public static final String DATORETRIBUTIVO_ARRAY_PROPERTY = "datoretributivoArray";
    public static final String SUBORDINATO_ARRAY_PROPERTY = "subordinatoArray";
    public static final String TIPOLAVORATOREFONDO_ARRAY_PROPERTY = "tipolavoratorefondoArray";

    public static final String IDINPSTIPOLAVORATORE_PK_COLUMN = "IDINPSTIPOLAVORATORE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getFondospeciale() {
        return (Short)readProperty("fondospeciale");
    }

    public String getIdinpstipolavoratore() {
        return (String)readProperty("idinpstipolavoratore");
    }

    public void addToAliquotaprevidenzialeArray(Aliquotaprevidenziale obj) {
        addToManyTarget("aliquotaprevidenzialeArray", obj, true);
    }
    public void removeFromAliquotaprevidenzialeArray(Aliquotaprevidenziale obj) {
        removeToManyTarget("aliquotaprevidenzialeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Aliquotaprevidenziale> getAliquotaprevidenzialeArray() {
        return (List<Aliquotaprevidenziale>)readProperty("aliquotaprevidenzialeArray");
    }


    public void addToDatoretributivoArray(Datoretributivo obj) {
        addToManyTarget("datoretributivoArray", obj, true);
    }
    public void removeFromDatoretributivoArray(Datoretributivo obj) {
        removeToManyTarget("datoretributivoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Datoretributivo> getDatoretributivoArray() {
        return (List<Datoretributivo>)readProperty("datoretributivoArray");
    }


    public void addToSubordinatoArray(Subordinato obj) {
        addToManyTarget("subordinatoArray", obj, true);
    }
    public void removeFromSubordinatoArray(Subordinato obj) {
        removeToManyTarget("subordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Subordinato> getSubordinatoArray() {
        return (List<Subordinato>)readProperty("subordinatoArray");
    }


    public void addToTipolavoratorefondoArray(InpsTipolavoratoreFondo obj) {
        addToManyTarget("tipolavoratorefondoArray", obj, true);
    }
    public void removeFromTipolavoratorefondoArray(InpsTipolavoratoreFondo obj) {
        removeToManyTarget("tipolavoratorefondoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsTipolavoratoreFondo> getTipolavoratorefondoArray() {
        return (List<InpsTipolavoratoreFondo>)readProperty("tipolavoratorefondoArray");
    }


}
