package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Frequenza;
import it.iubar.paghe.logic.paghe.InpsClasseanf;
import it.iubar.paghe.logic.paghe.InpsTipoanf;

/**
 * Class _InpsTipoanf2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsTipoanf2 extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDFREQUENZA_PROPERTY = "idfrequenza";
    public static final String IDINPSTIPOANF_PROPERTY = "idinpstipoanf";
    public static final String IDINPSTIPOANF2_PROPERTY = "idinpstipoanf2";
    public static final String CLASSE_ANF_ARRAY_PROPERTY = "classeAnfArray";
    public static final String TO_FREQUENZA_PROPERTY = "toFrequenza";
    public static final String TO_INPS_TIPOANF_PROPERTY = "toInpsTipoanf";

    public static final String IDINPSTIPOANF2_PK_COLUMN = "IDINPSTIPOANF2";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdfrequenza() {
        return (Short)readProperty("idfrequenza");
    }

    public String getIdinpstipoanf() {
        return (String)readProperty("idinpstipoanf");
    }

    public Short getIdinpstipoanf2() {
        return (Short)readProperty("idinpstipoanf2");
    }

    public void addToClasseAnfArray(InpsClasseanf obj) {
        addToManyTarget("classeAnfArray", obj, true);
    }
    public void removeFromClasseAnfArray(InpsClasseanf obj) {
        removeToManyTarget("classeAnfArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsClasseanf> getClasseAnfArray() {
        return (List<InpsClasseanf>)readProperty("classeAnfArray");
    }



    public Frequenza getToFrequenza() {
        return (Frequenza)readProperty("toFrequenza");
    }



    public InpsTipoanf getToInpsTipoanf() {
        return (InpsTipoanf)readProperty("toInpsTipoanf");
    }


}
