package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Subordinato;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;
import it.iubar.paghe.logic.presenze.Orario;

/**
 * Class _InpsQualifica2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsQualifica2 extends CayenneDataObject {

    public static final String DATASCADENZA_PROPERTY = "datascadenza";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDINPSQUALIFICA2_PROPERTY = "idinpsqualifica2";
    public static final String ORARIO_ARRAY_PROPERTY = "orarioArray";
    public static final String POSIZIONESUBORDINATO_ARRAY_PROPERTY = "posizionesubordinatoArray";
    public static final String SUBORDINATO_ATTUALE_ARRAY_PROPERTY = "subordinatoAttualeArray";

    public static final String IDINPSQUALIFICA2_PK_COLUMN = "IDINPSQUALIFICA2";

    public Date getDatascadenza() {
        return (Date)readProperty("datascadenza");
    }

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdinpsqualifica2() {
        return (String)readProperty("idinpsqualifica2");
    }

    public void addToOrarioArray(Orario obj) {
        addToManyTarget("orarioArray", obj, true);
    }
    public void removeFromOrarioArray(Orario obj) {
        removeToManyTarget("orarioArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Orario> getOrarioArray() {
        return (List<Orario>)readProperty("orarioArray");
    }


    public void addToPosizionesubordinatoArray(Posizionesubordinato obj) {
        addToManyTarget("posizionesubordinatoArray", obj, true);
    }
    public void removeFromPosizionesubordinatoArray(Posizionesubordinato obj) {
        removeToManyTarget("posizionesubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionesubordinato> getPosizionesubordinatoArray() {
        return (List<Posizionesubordinato>)readProperty("posizionesubordinatoArray");
    }


    public void addToSubordinatoAttualeArray(Subordinato obj) {
        addToManyTarget("subordinatoAttualeArray", obj, true);
    }
    public void removeFromSubordinatoAttualeArray(Subordinato obj) {
        removeToManyTarget("subordinatoAttualeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Subordinato> getSubordinatoAttualeArray() {
        return (List<Subordinato>)readProperty("subordinatoAttualeArray");
    }


}
