package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Subordinato;
import it.iubar.paghe.logic.paghe.ImpresaContratto;
import it.iubar.paghe.logic.paghe.InpsSettoreContratto;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;

/**
 * Class _InpsSettore was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsSettore extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDINPSSETTORE_PROPERTY = "idinpssettore";
    public static final String IMPRESA_CONTRATTO_ARRAY_PROPERTY = "impresaContrattoArray";
    public static final String INPS_SETTORE_CONTRATTO_ARRAY_PROPERTY = "inpsSettoreContrattoArray";
    public static final String POSIZIONESUBORDINATO_ARRAY_PROPERTY = "posizionesubordinatoArray";
    public static final String SUBORDINATO_ARRAY_PROPERTY = "subordinatoArray";

    public static final String IDINPSSETTORE_PK_COLUMN = "IDINPSSETTORE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Integer getIdinpssettore() {
        return (Integer)readProperty("idinpssettore");
    }

    public void addToImpresaContrattoArray(ImpresaContratto obj) {
        addToManyTarget("impresaContrattoArray", obj, true);
    }
    public void removeFromImpresaContrattoArray(ImpresaContratto obj) {
        removeToManyTarget("impresaContrattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ImpresaContratto> getImpresaContrattoArray() {
        return (List<ImpresaContratto>)readProperty("impresaContrattoArray");
    }


    public void addToInpsSettoreContrattoArray(InpsSettoreContratto obj) {
        addToManyTarget("inpsSettoreContrattoArray", obj, true);
    }
    public void removeFromInpsSettoreContrattoArray(InpsSettoreContratto obj) {
        removeToManyTarget("inpsSettoreContrattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsSettoreContratto> getInpsSettoreContrattoArray() {
        return (List<InpsSettoreContratto>)readProperty("inpsSettoreContrattoArray");
    }


    public void addToPosizionesubordinatoArray(Posizionesubordinato obj) {
        addToManyTarget("posizionesubordinatoArray", obj, true);
    }
    public void removeFromPosizionesubordinatoArray(Posizionesubordinato obj) {
        removeToManyTarget("posizionesubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionesubordinato> getPosizionesubordinatoArray() {
        return (List<Posizionesubordinato>)readProperty("posizionesubordinatoArray");
    }


    public void addToSubordinatoArray(Subordinato obj) {
        addToManyTarget("subordinatoArray", obj, true);
    }
    public void removeFromSubordinatoArray(Subordinato obj) {
        removeToManyTarget("subordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Subordinato> getSubordinatoArray() {
        return (List<Subordinato>)readProperty("subordinatoArray");
    }


}
