package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattoassenza;
import it.iubar.paghe.logic.paghe.SettimanaEvento;

/**
 * Class _InpsEvento was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsEvento extends CayenneDataObject {

    public static final String ATTIVO_PROPERTY = "attivo";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String DESCRIZIONE2_PROPERTY = "descrizione2";
    public static final String IDINPSEVENTO_PROPERTY = "idinpsevento";
    public static final String CONTRATTOASSENZA_ARRAY_PROPERTY = "contrattoassenzaArray";
    public static final String SETTIMANA_EVENTO_ARRAY_PROPERTY = "settimanaEventoArray";

    public static final String IDINPSEVENTO_PK_COLUMN = "IDINPSEVENTO";

    public Short getAttivo() {
        return (Short)readProperty("attivo");
    }

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getDescrizione2() {
        return (String)readProperty("descrizione2");
    }

    public String getIdinpsevento() {
        return (String)readProperty("idinpsevento");
    }

    public void addToContrattoassenzaArray(Contrattoassenza obj) {
        addToManyTarget("contrattoassenzaArray", obj, true);
    }
    public void removeFromContrattoassenzaArray(Contrattoassenza obj) {
        removeToManyTarget("contrattoassenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoassenza> getContrattoassenzaArray() {
        return (List<Contrattoassenza>)readProperty("contrattoassenzaArray");
    }


    public void addToSettimanaEventoArray(SettimanaEvento obj) {
        addToManyTarget("settimanaEventoArray", obj, true);
    }
    public void removeFromSettimanaEventoArray(SettimanaEvento obj) {
        removeToManyTarget("settimanaEventoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SettimanaEvento> getSettimanaEventoArray() {
        return (List<SettimanaEvento>)readProperty("settimanaEventoArray");
    }


}
