package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.InpsAliquotaareaLavoratore;

/**
 * Class _InpsAliquotatipolavoratore was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsAliquotatipolavoratore extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDALIQUOTATIPOLAV_PROPERTY = "idaliquotatipolav";
    public static final String ALIQUOTAAREA_LAVORATORE_ARRAY_PROPERTY = "aliquotaareaLavoratoreArray";

    public static final String IDALIQUOTATIPOLAV_PK_COLUMN = "IDALIQUOTATIPOLAV";

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setIdaliquotatipolav(Integer idaliquotatipolav) {
        writeProperty("idaliquotatipolav", idaliquotatipolav);
    }
    public Integer getIdaliquotatipolav() {
        return (Integer)readProperty("idaliquotatipolav");
    }

    public void addToAliquotaareaLavoratoreArray(InpsAliquotaareaLavoratore obj) {
        addToManyTarget("aliquotaareaLavoratoreArray", obj, true);
    }
    public void removeFromAliquotaareaLavoratoreArray(InpsAliquotaareaLavoratore obj) {
        removeToManyTarget("aliquotaareaLavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsAliquotaareaLavoratore> getAliquotaareaLavoratoreArray() {
        return (List<InpsAliquotaareaLavoratore>)readProperty("aliquotaareaLavoratoreArray");
    }


}
