package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoretributivo;
import it.iubar.paghe.logic.paghe.Lavpensrimborso;
import it.iubar.paghe.logic.paghe.Lavpenstrattenuta;

/**
 * Class _Lavpensionato was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Lavpensionato extends CayenneDataObject {

    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String LAV_PENS_RIMBORSO_ARRAY_PROPERTY = "lavPensRimborsoArray";
    public static final String LAV_PENS_TRATTENUTA_ARRAY_PROPERTY = "lavPensTrattenutaArray";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void addToLavPensRimborsoArray(Lavpensrimborso obj) {
        addToManyTarget("lavPensRimborsoArray", obj, true);
    }
    public void removeFromLavPensRimborsoArray(Lavpensrimborso obj) {
        removeToManyTarget("lavPensRimborsoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lavpensrimborso> getLavPensRimborsoArray() {
        return (List<Lavpensrimborso>)readProperty("lavPensRimborsoArray");
    }


    public void addToLavPensTrattenutaArray(Lavpenstrattenuta obj) {
        addToManyTarget("lavPensTrattenutaArray", obj, true);
    }
    public void removeFromLavPensTrattenutaArray(Lavpenstrattenuta obj) {
        removeToManyTarget("lavPensTrattenutaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lavpenstrattenuta> getLavPensTrattenutaArray() {
        return (List<Lavpenstrattenuta>)readProperty("lavPensTrattenutaArray");
    }


    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


}
