package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Mut;
import it.iubar.paghe.logic.paghe.MutCantieresituazione;
import it.iubar.paghe.logic.paghe.MutLavoratore;
import it.iubar.paghe.logic.paghe.MutRiepilogo;

/**
 * Class _MutImpresa was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MutImpresa extends CayenneDataObject {

    public static final String CODCASSAEDILE_PROPERTY = "codcassaedile";
    public static final String DESTINAZCE_PROPERTY = "destinazce";
    public static final String GIORNOSITUAZIONE_PROPERTY = "giornosituazione";
    public static final String IDDICHIARAZIONE_PROPERTY = "iddichiarazione";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDSITUAZIONE_PROPERTY = "idsituazione";
    public static final String MUT_CANTIERE_SITUAZ_ARRAY_PROPERTY = "mutCantiereSituazArray";
    public static final String MUT_LAVORATORE_ARRAY_PROPERTY = "mutLavoratoreArray";
    public static final String MUT_RIEPILOGO_ARRAY_PROPERTY = "mutRiepilogoArray";
    public static final String TO_DICHIARAZIONE_PROPERTY = "toDichiarazione";

    public static final String IDDICHIARAZIONE_PK_COLUMN = "IDDICHIARAZIONE";
    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";

    public void setCodcassaedile(String codcassaedile) {
        writeProperty("codcassaedile", codcassaedile);
    }
    public String getCodcassaedile() {
        return (String)readProperty("codcassaedile");
    }

    public void setDestinazce(String destinazce) {
        writeProperty("destinazce", destinazce);
    }
    public String getDestinazce() {
        return (String)readProperty("destinazce");
    }

    public void setGiornosituazione(Short giornosituazione) {
        writeProperty("giornosituazione", giornosituazione);
    }
    public Short getGiornosituazione() {
        return (Short)readProperty("giornosituazione");
    }

    public void setIddichiarazione(Integer iddichiarazione) {
        writeProperty("iddichiarazione", iddichiarazione);
    }
    public Integer getIddichiarazione() {
        return (Integer)readProperty("iddichiarazione");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdsituazione(Short idsituazione) {
        writeProperty("idsituazione", idsituazione);
    }
    public Short getIdsituazione() {
        return (Short)readProperty("idsituazione");
    }

    public void addToMutCantiereSituazArray(MutCantieresituazione obj) {
        addToManyTarget("mutCantiereSituazArray", obj, true);
    }
    public void removeFromMutCantiereSituazArray(MutCantieresituazione obj) {
        removeToManyTarget("mutCantiereSituazArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MutCantieresituazione> getMutCantiereSituazArray() {
        return (List<MutCantieresituazione>)readProperty("mutCantiereSituazArray");
    }


    public void addToMutLavoratoreArray(MutLavoratore obj) {
        addToManyTarget("mutLavoratoreArray", obj, true);
    }
    public void removeFromMutLavoratoreArray(MutLavoratore obj) {
        removeToManyTarget("mutLavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MutLavoratore> getMutLavoratoreArray() {
        return (List<MutLavoratore>)readProperty("mutLavoratoreArray");
    }


    public void addToMutRiepilogoArray(MutRiepilogo obj) {
        addToManyTarget("mutRiepilogoArray", obj, true);
    }
    public void removeFromMutRiepilogoArray(MutRiepilogo obj) {
        removeToManyTarget("mutRiepilogoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MutRiepilogo> getMutRiepilogoArray() {
        return (List<MutRiepilogo>)readProperty("mutRiepilogoArray");
    }


    public void setToDichiarazione(Mut toDichiarazione) {
        setToOneTarget("toDichiarazione", toDichiarazione, true);
    }

    public Mut getToDichiarazione() {
        return (Mut)readProperty("toDichiarazione");
    }


}
