package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.PaTipocontributoaltroente;

/**
 * Class _PaAltroenteversante was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaAltroenteversante extends CayenneDataObject {

    public static final String CONTRIBUTO_PROPERTY = "contributo";
    public static final String IDPAPERIODO_PROPERTY = "idpaperiodo";
    public static final String IDTIPOCONTRIBUTOALTROENTE_PROPERTY = "idtipocontributoaltroente";
    public static final String IENTE_PROPERTY = "iente";
    public static final String IMPONIBILE_PROPERTY = "imponibile";
    public static final String TO_TIPO_CONTRIBUTO_ALTRO_ENTE_PROPERTY = "toTipoContributoAltroEnte";

    public static final String IDPAPERIODO_PK_COLUMN = "IDPAPERIODO";

    public void setContributo(BigDecimal contributo) {
        writeProperty("contributo", contributo);
    }
    public BigDecimal getContributo() {
        return (BigDecimal)readProperty("contributo");
    }

    public void setIdpaperiodo(Integer idpaperiodo) {
        writeProperty("idpaperiodo", idpaperiodo);
    }
    public Integer getIdpaperiodo() {
        return (Integer)readProperty("idpaperiodo");
    }

    public void setIdtipocontributoaltroente(Short idtipocontributoaltroente) {
        writeProperty("idtipocontributoaltroente", idtipocontributoaltroente);
    }
    public Short getIdtipocontributoaltroente() {
        return (Short)readProperty("idtipocontributoaltroente");
    }

    public void setIente(Integer iente) {
        writeProperty("iente", iente);
    }
    public Integer getIente() {
        return (Integer)readProperty("iente");
    }

    public void setImponibile(BigDecimal imponibile) {
        writeProperty("imponibile", imponibile);
    }
    public BigDecimal getImponibile() {
        return (BigDecimal)readProperty("imponibile");
    }

    public void setToTipoContributoAltroEnte(PaTipocontributoaltroente toTipoContributoAltroEnte) {
        setToOneTarget("toTipoContributoAltroEnte", toTipoContributoAltroEnte, true);
    }

    public PaTipocontributoaltroente getToTipoContributoAltroEnte() {
        return (PaTipocontributoaltroente)readProperty("toTipoContributoAltroEnte");
    }


}
