package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.PaTipogestione;
import it.iubar.paghe.logic.paghe.PaTipooperazione;
import it.iubar.paghe.logic.paghe.PaTipopianoammortamento;

/**
 * Class _PaAmmortamento was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaAmmortamento extends CayenneDataObject {

    public static final String AL_PROPERTY = "al";
    public static final String ANNO_PROPERTY = "anno";
    public static final String ANNOSUBENTRO_PROPERTY = "annosubentro";
    public static final String DAL_PROPERTY = "dal";
    public static final String DATARIPRISTINO_PROPERTY = "dataripristino";
    public static final String IDALTROENTEVERSANTE_PROPERTY = "idaltroenteversante";
    public static final String IDAMMORTAMENTO_PROPERTY = "idammortamento";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDTIPOGESTIONE_PROPERTY = "idtipogestione";
    public static final String IDTIPOOPERAZIONE_PROPERTY = "idtipooperazione";
    public static final String IDTIPOPIANO_PROPERTY = "idtipopiano";
    public static final String IMPORTO_PROPERTY = "importo";
    public static final String MESE_PROPERTY = "mese";
    public static final String RATA_PROPERTY = "rata";
    public static final String SCADENZA_PROPERTY = "scadenza";
    public static final String TOTALERATE_PROPERTY = "totalerate";
    public static final String TO_TIPO_GESTIONE_PROPERTY = "toTipoGestione";
    public static final String TO_TIPO_OPERAZIONE_PROPERTY = "toTipoOperazione";
    public static final String TO_TIPO_PIANO_PROPERTY = "toTipoPiano";

    public static final String IDAMMORTAMENTO_PK_COLUMN = "IDAMMORTAMENTO";
    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setAl(Date al) {
        writeProperty("al", al);
    }
    public Date getAl() {
        return (Date)readProperty("al");
    }

    public void setAnno(Integer anno) {
        writeProperty("anno", anno);
    }
    public Integer getAnno() {
        return (Integer)readProperty("anno");
    }

    public void setAnnosubentro(Short annosubentro) {
        writeProperty("annosubentro", annosubentro);
    }
    public Short getAnnosubentro() {
        return (Short)readProperty("annosubentro");
    }

    public void setDal(Date dal) {
        writeProperty("dal", dal);
    }
    public Date getDal() {
        return (Date)readProperty("dal");
    }

    public void setDataripristino(Date dataripristino) {
        writeProperty("dataripristino", dataripristino);
    }
    public Date getDataripristino() {
        return (Date)readProperty("dataripristino");
    }

    public void setIdaltroenteversante(Integer idaltroenteversante) {
        writeProperty("idaltroenteversante", idaltroenteversante);
    }
    public Integer getIdaltroenteversante() {
        return (Integer)readProperty("idaltroenteversante");
    }

    public void setIdammortamento(Short idammortamento) {
        writeProperty("idammortamento", idammortamento);
    }
    public Short getIdammortamento() {
        return (Short)readProperty("idammortamento");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdtipogestione(Short idtipogestione) {
        writeProperty("idtipogestione", idtipogestione);
    }
    public Short getIdtipogestione() {
        return (Short)readProperty("idtipogestione");
    }

    public void setIdtipooperazione(String idtipooperazione) {
        writeProperty("idtipooperazione", idtipooperazione);
    }
    public String getIdtipooperazione() {
        return (String)readProperty("idtipooperazione");
    }

    public void setIdtipopiano(Short idtipopiano) {
        writeProperty("idtipopiano", idtipopiano);
    }
    public Short getIdtipopiano() {
        return (Short)readProperty("idtipopiano");
    }

    public void setImporto(BigDecimal importo) {
        writeProperty("importo", importo);
    }
    public BigDecimal getImporto() {
        return (BigDecimal)readProperty("importo");
    }

    public void setMese(Short mese) {
        writeProperty("mese", mese);
    }
    public Short getMese() {
        return (Short)readProperty("mese");
    }

    public void setRata(Short rata) {
        writeProperty("rata", rata);
    }
    public Short getRata() {
        return (Short)readProperty("rata");
    }

    public void setScadenza(Date scadenza) {
        writeProperty("scadenza", scadenza);
    }
    public Date getScadenza() {
        return (Date)readProperty("scadenza");
    }

    public void setTotalerate(Short totalerate) {
        writeProperty("totalerate", totalerate);
    }
    public Short getTotalerate() {
        return (Short)readProperty("totalerate");
    }

    public void setToTipoGestione(PaTipogestione toTipoGestione) {
        setToOneTarget("toTipoGestione", toTipoGestione, true);
    }

    public PaTipogestione getToTipoGestione() {
        return (PaTipogestione)readProperty("toTipoGestione");
    }


    public void setToTipoOperazione(PaTipooperazione toTipoOperazione) {
        setToOneTarget("toTipoOperazione", toTipoOperazione, true);
    }

    public PaTipooperazione getToTipoOperazione() {
        return (PaTipooperazione)readProperty("toTipoOperazione");
    }


    public void setToTipoPiano(PaTipopianoammortamento toTipoPiano) {
        setToOneTarget("toTipoPiano", toTipoPiano, true);
    }

    public PaTipopianoammortamento getToTipoPiano() {
        return (PaTipopianoammortamento)readProperty("toTipoPiano");
    }


}
