package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.PaGestcredito;
import it.iubar.paghe.logic.paghe.PaGestenam;
import it.iubar.paghe.logic.paghe.PaGestendep;
import it.iubar.paghe.logic.paghe.PaGestpensionistica;
import it.iubar.paghe.logic.paghe.PaGestprevidenziale;
import it.iubar.paghe.logic.paghe.PaPosizioneperiodo;
import it.iubar.paghe.logic.paghe.PaTipogestione;

/**
 * Class _PaGestione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaGestione extends CayenneDataObject {

    public static final String IDGESTCREDITO_PROPERTY = "idgestcredito";
    public static final String IDGESTENAM_PROPERTY = "idgestenam";
    public static final String IDGESTENDEP_PROPERTY = "idgestendep";
    public static final String IDGESTIONE_PROPERTY = "idgestione";
    public static final String IDGESTPENSIONISTICA_PROPERTY = "idgestpensionistica";
    public static final String IDGESTPREVIDENZIALE_PROPERTY = "idgestprevidenziale";
    public static final String IDPAPERIODO_PROPERTY = "idpaperiodo";
    public static final String IDTIPOGESTIONE_PROPERTY = "idtipogestione";
    public static final String TO_GEST_PENSIONISTICA_PROPERTY = "toGestPensionistica";
    public static final String TO_GEST_PREVIDENZIALE_PROPERTY = "toGestPrevidenziale";
    public static final String TO_PA_GEST_CREDITO_PROPERTY = "toPaGestCredito";
    public static final String TO_PA_GEST_ENAM_PROPERTY = "toPaGestEnam";
    public static final String TO_PA_GEST_ENDEP_PROPERTY = "toPaGestEndep";
    public static final String TO_PA_POSIZIONE_PERIODO_PROPERTY = "toPaPosizionePeriodo";
    public static final String TO_PA_TIPO_GESTIONE_PROPERTY = "toPaTipoGestione";

    public static final String IDGESTIONE_PK_COLUMN = "IDGESTIONE";
    public static final String IDPAPERIODO_PK_COLUMN = "IDPAPERIODO";

    public void setIdgestcredito(Integer idgestcredito) {
        writeProperty("idgestcredito", idgestcredito);
    }
    public Integer getIdgestcredito() {
        return (Integer)readProperty("idgestcredito");
    }

    public void setIdgestenam(Integer idgestenam) {
        writeProperty("idgestenam", idgestenam);
    }
    public Integer getIdgestenam() {
        return (Integer)readProperty("idgestenam");
    }

    public void setIdgestendep(Integer idgestendep) {
        writeProperty("idgestendep", idgestendep);
    }
    public Integer getIdgestendep() {
        return (Integer)readProperty("idgestendep");
    }

    public void setIdgestione(Short idgestione) {
        writeProperty("idgestione", idgestione);
    }
    public Short getIdgestione() {
        return (Short)readProperty("idgestione");
    }

    public void setIdgestpensionistica(Integer idgestpensionistica) {
        writeProperty("idgestpensionistica", idgestpensionistica);
    }
    public Integer getIdgestpensionistica() {
        return (Integer)readProperty("idgestpensionistica");
    }

    public void setIdgestprevidenziale(Integer idgestprevidenziale) {
        writeProperty("idgestprevidenziale", idgestprevidenziale);
    }
    public Integer getIdgestprevidenziale() {
        return (Integer)readProperty("idgestprevidenziale");
    }

    public void setIdpaperiodo(Integer idpaperiodo) {
        writeProperty("idpaperiodo", idpaperiodo);
    }
    public Integer getIdpaperiodo() {
        return (Integer)readProperty("idpaperiodo");
    }

    public void setIdtipogestione(Short idtipogestione) {
        writeProperty("idtipogestione", idtipogestione);
    }
    public Short getIdtipogestione() {
        return (Short)readProperty("idtipogestione");
    }

    public void setToGestPensionistica(PaGestpensionistica toGestPensionistica) {
        setToOneTarget("toGestPensionistica", toGestPensionistica, true);
    }

    public PaGestpensionistica getToGestPensionistica() {
        return (PaGestpensionistica)readProperty("toGestPensionistica");
    }


    public void setToGestPrevidenziale(PaGestprevidenziale toGestPrevidenziale) {
        setToOneTarget("toGestPrevidenziale", toGestPrevidenziale, true);
    }

    public PaGestprevidenziale getToGestPrevidenziale() {
        return (PaGestprevidenziale)readProperty("toGestPrevidenziale");
    }


    public void setToPaGestCredito(PaGestcredito toPaGestCredito) {
        setToOneTarget("toPaGestCredito", toPaGestCredito, true);
    }

    public PaGestcredito getToPaGestCredito() {
        return (PaGestcredito)readProperty("toPaGestCredito");
    }


    public void setToPaGestEnam(PaGestenam toPaGestEnam) {
        setToOneTarget("toPaGestEnam", toPaGestEnam, true);
    }

    public PaGestenam getToPaGestEnam() {
        return (PaGestenam)readProperty("toPaGestEnam");
    }


    public void setToPaGestEndep(PaGestendep toPaGestEndep) {
        setToOneTarget("toPaGestEndep", toPaGestEndep, true);
    }

    public PaGestendep getToPaGestEndep() {
        return (PaGestendep)readProperty("toPaGestEndep");
    }


    public void setToPaPosizionePeriodo(PaPosizioneperiodo toPaPosizionePeriodo) {
        setToOneTarget("toPaPosizionePeriodo", toPaPosizionePeriodo, true);
    }

    public PaPosizioneperiodo getToPaPosizionePeriodo() {
        return (PaPosizioneperiodo)readProperty("toPaPosizionePeriodo");
    }


    public void setToPaTipoGestione(PaTipogestione toPaTipoGestione) {
        setToOneTarget("toPaTipoGestione", toPaTipoGestione, true);
    }

    public PaTipogestione getToPaTipoGestione() {
        return (PaTipogestione)readProperty("toPaTipoGestione");
    }


}
