package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.PaGestione;
import it.iubar.paghe.logic.paghe.PaTipomaggiorazione;
import it.iubar.paghe.logic.paghe.PaTiporecupero;

/**
 * Class _PaGestpensionistica was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaGestpensionistica extends CayenneDataObject {

    public static final String CONTRIB1PERC_PROPERTY = "contrib1perc";
    public static final String CONTRIBSOSPCALAM_PROPERTY = "contribsospcalam";
    public static final String CONTRIBUTO_PROPERTY = "contributo";
    public static final String CONTRIBUTOL16691_PROPERTY = "contributol16691";
    public static final String GIORNIUTILI_PROPERTY = "giorniutili";
    public static final String IDGESTIONEPENSIONISTICA_PROPERTY = "idgestionepensionistica";
    public static final String IMPONIBILE_PROPERTY = "imponibile";
    public static final String IMPONIBILEECCMASS_PROPERTY = "imponibileeccmass";
    public static final String MAGGBASEPENSL16597_PROPERTY = "maggbasepensl16597";
    public static final String MAGGGIORNI1_PROPERTY = "magggiorni1";
    public static final String MAGGGIORNI2_PROPERTY = "magggiorni2";
    public static final String MAGGGIORNI3_PROPERTY = "magggiorni3";
    public static final String QUOTADATOREL16691_PROPERTY = "quotadatorel16691";
    public static final String RECUPEROSGRAVI1_PROPERTY = "recuperosgravi1";
    public static final String RECUPEROSGRAVI2_PROPERTY = "recuperosgravi2";
    public static final String RETRIBINDIVANZIANITA_PROPERTY = "retribindivanzianita";
    public static final String RETRIBVIRTUALE_PROPERTY = "retribvirtuale";
    public static final String STIPENDIOTABELLARE_PROPERTY = "stipendiotabellare";
    public static final String VOLOCODIND_PROPERTY = "volocodind";
    public static final String VOLOIMPORTOIND_PROPERTY = "voloimportoind";
    public static final String PA_GESTIONE_ARRAY_PROPERTY = "paGestioneArray";
    public static final String TO_PA_TIPO_MAGGIORAZ1_PROPERTY = "toPaTipoMaggioraz1";
    public static final String TO_PA_TIPO_MAGGIORAZ2_PROPERTY = "toPaTipoMaggioraz2";
    public static final String TO_PA_TIPO_MAGGIORAZ3_PROPERTY = "toPaTipoMaggioraz3";
    public static final String TO_PA_TIPO_RECUPERO1_PROPERTY = "toPaTipoRecupero1";
    public static final String TO_PA_TIPO_RECUPERO2_PROPERTY = "toPaTipoRecupero2";

    public static final String IDGESTPENSIONISTICA_PK_COLUMN = "IDGESTPENSIONISTICA";

    public void setContrib1perc(BigDecimal contrib1perc) {
        writeProperty("contrib1perc", contrib1perc);
    }
    public BigDecimal getContrib1perc() {
        return (BigDecimal)readProperty("contrib1perc");
    }

    public void setContribsospcalam(BigDecimal contribsospcalam) {
        writeProperty("contribsospcalam", contribsospcalam);
    }
    public BigDecimal getContribsospcalam() {
        return (BigDecimal)readProperty("contribsospcalam");
    }

    public void setContributo(BigDecimal contributo) {
        writeProperty("contributo", contributo);
    }
    public BigDecimal getContributo() {
        return (BigDecimal)readProperty("contributo");
    }

    public void setContributol16691(BigDecimal contributol16691) {
        writeProperty("contributol16691", contributol16691);
    }
    public BigDecimal getContributol16691() {
        return (BigDecimal)readProperty("contributol16691");
    }

    public void setGiorniutili(Short giorniutili) {
        writeProperty("giorniutili", giorniutili);
    }
    public Short getGiorniutili() {
        return (Short)readProperty("giorniutili");
    }

    public void setIdgestionepensionistica(Short idgestionepensionistica) {
        writeProperty("idgestionepensionistica", idgestionepensionistica);
    }
    public Short getIdgestionepensionistica() {
        return (Short)readProperty("idgestionepensionistica");
    }

    public void setImponibile(BigDecimal imponibile) {
        writeProperty("imponibile", imponibile);
    }
    public BigDecimal getImponibile() {
        return (BigDecimal)readProperty("imponibile");
    }

    public void setImponibileeccmass(BigDecimal imponibileeccmass) {
        writeProperty("imponibileeccmass", imponibileeccmass);
    }
    public BigDecimal getImponibileeccmass() {
        return (BigDecimal)readProperty("imponibileeccmass");
    }

    public void setMaggbasepensl16597(BigDecimal maggbasepensl16597) {
        writeProperty("maggbasepensl16597", maggbasepensl16597);
    }
    public BigDecimal getMaggbasepensl16597() {
        return (BigDecimal)readProperty("maggbasepensl16597");
    }

    public void setMagggiorni1(Short magggiorni1) {
        writeProperty("magggiorni1", magggiorni1);
    }
    public Short getMagggiorni1() {
        return (Short)readProperty("magggiorni1");
    }

    public void setMagggiorni2(Short magggiorni2) {
        writeProperty("magggiorni2", magggiorni2);
    }
    public Short getMagggiorni2() {
        return (Short)readProperty("magggiorni2");
    }

    public void setMagggiorni3(Short magggiorni3) {
        writeProperty("magggiorni3", magggiorni3);
    }
    public Short getMagggiorni3() {
        return (Short)readProperty("magggiorni3");
    }

    public void setQuotadatorel16691(BigDecimal quotadatorel16691) {
        writeProperty("quotadatorel16691", quotadatorel16691);
    }
    public BigDecimal getQuotadatorel16691() {
        return (BigDecimal)readProperty("quotadatorel16691");
    }

    public void setRecuperosgravi1(BigDecimal recuperosgravi1) {
        writeProperty("recuperosgravi1", recuperosgravi1);
    }
    public BigDecimal getRecuperosgravi1() {
        return (BigDecimal)readProperty("recuperosgravi1");
    }

    public void setRecuperosgravi2(BigDecimal recuperosgravi2) {
        writeProperty("recuperosgravi2", recuperosgravi2);
    }
    public BigDecimal getRecuperosgravi2() {
        return (BigDecimal)readProperty("recuperosgravi2");
    }

    public void setRetribindivanzianita(BigDecimal retribindivanzianita) {
        writeProperty("retribindivanzianita", retribindivanzianita);
    }
    public BigDecimal getRetribindivanzianita() {
        return (BigDecimal)readProperty("retribindivanzianita");
    }

    public void setRetribvirtuale(BigDecimal retribvirtuale) {
        writeProperty("retribvirtuale", retribvirtuale);
    }
    public BigDecimal getRetribvirtuale() {
        return (BigDecimal)readProperty("retribvirtuale");
    }

    public void setStipendiotabellare(BigDecimal stipendiotabellare) {
        writeProperty("stipendiotabellare", stipendiotabellare);
    }
    public BigDecimal getStipendiotabellare() {
        return (BigDecimal)readProperty("stipendiotabellare");
    }

    public void setVolocodind(Short volocodind) {
        writeProperty("volocodind", volocodind);
    }
    public Short getVolocodind() {
        return (Short)readProperty("volocodind");
    }

    public void setVoloimportoind(BigDecimal voloimportoind) {
        writeProperty("voloimportoind", voloimportoind);
    }
    public BigDecimal getVoloimportoind() {
        return (BigDecimal)readProperty("voloimportoind");
    }

    public void addToPaGestioneArray(PaGestione obj) {
        addToManyTarget("paGestioneArray", obj, true);
    }
    public void removeFromPaGestioneArray(PaGestione obj) {
        removeToManyTarget("paGestioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaGestione> getPaGestioneArray() {
        return (List<PaGestione>)readProperty("paGestioneArray");
    }


    public void setToPaTipoMaggioraz1(PaTipomaggiorazione toPaTipoMaggioraz1) {
        setToOneTarget("toPaTipoMaggioraz1", toPaTipoMaggioraz1, true);
    }

    public PaTipomaggiorazione getToPaTipoMaggioraz1() {
        return (PaTipomaggiorazione)readProperty("toPaTipoMaggioraz1");
    }


    public void setToPaTipoMaggioraz2(PaTipomaggiorazione toPaTipoMaggioraz2) {
        setToOneTarget("toPaTipoMaggioraz2", toPaTipoMaggioraz2, true);
    }

    public PaTipomaggiorazione getToPaTipoMaggioraz2() {
        return (PaTipomaggiorazione)readProperty("toPaTipoMaggioraz2");
    }


    public void setToPaTipoMaggioraz3(PaTipomaggiorazione toPaTipoMaggioraz3) {
        setToOneTarget("toPaTipoMaggioraz3", toPaTipoMaggioraz3, true);
    }

    public PaTipomaggiorazione getToPaTipoMaggioraz3() {
        return (PaTipomaggiorazione)readProperty("toPaTipoMaggioraz3");
    }


    public void setToPaTipoRecupero1(PaTiporecupero toPaTipoRecupero1) {
        setToOneTarget("toPaTipoRecupero1", toPaTipoRecupero1, true);
    }

    public PaTiporecupero getToPaTipoRecupero1() {
        return (PaTiporecupero)readProperty("toPaTipoRecupero1");
    }


    public void setToPaTipoRecupero2(PaTiporecupero toPaTipoRecupero2) {
        setToOneTarget("toPaTipoRecupero2", toPaTipoRecupero2, true);
    }

    public PaTiporecupero getToPaTipoRecupero2() {
        return (PaTiporecupero)readProperty("toPaTipoRecupero2");
    }


}
