package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.PaQualifica;
import it.iubar.paghe.logic.paghe.PaRegimefineservizio;
import it.iubar.paghe.logic.paghe.PaTipoimpiego;
import it.iubar.paghe.logic.paghe.PaTiposervizio;
import it.iubar.paghe.logic.paghe.PaTiposervizioaltro;

/**
 * Class _PaInquadramento was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaInquadramento extends CayenneDataObject {

    public static final String IDDIPENDALTROENTE_PROPERTY = "iddipendaltroente";
    public static final String IDPACONTRATTO_PROPERTY = "idpacontratto";
    public static final String IDPAPERIODO_PROPERTY = "idpaperiodo";
    public static final String IDPAQUALIFICA_PROPERTY = "idpaqualifica";
    public static final String IDREGIMEFINESERV_PROPERTY = "idregimefineserv";
    public static final String IDSERVIZIOALTROENTE_PROPERTY = "idservizioaltroente";
    public static final String IDTIPOIMPIEGO_PROPERTY = "idtipoimpiego";
    public static final String IDTIPOSERVIZIO_PROPERTY = "idtiposervizio";
    public static final String IDTIPOSERVIZIOALTRO1_PROPERTY = "idtiposervizioaltro1";
    public static final String IDTIPOSERVIZIOALTRO2_PROPERTY = "idtiposervizioaltro2";
    public static final String ORESETTPERSSCUOLAC_PROPERTY = "oresettpersscuolac";
    public static final String ORESETTPERSSCUOLAR_PROPERTY = "oresettpersscuolar";
    public static final String PERCASPETTATIVA_PROPERTY = "percaspettativa";
    public static final String PERCRETRIBUZIONE_PROPERTY = "percretribuzione";
    public static final String TO_PA_QUALIFICA_PROPERTY = "toPaQualifica";
    public static final String TO_REGIME_FINE_SERV_PROPERTY = "toRegimeFineServ";
    public static final String TO_TIPO_IMPIEGO_PROPERTY = "toTipoImpiego";
    public static final String TO_TIPO_SERVIZIO_PROPERTY = "toTipoServizio";
    public static final String TO_TIPO_SERVIZIO_ALTRO1_PROPERTY = "toTipoServizioAltro1";
    public static final String TO_TIPO_SERVIZIO_ALTRO2_PROPERTY = "toTipoServizioAltro2";

    public static final String IDPAPERIODO_PK_COLUMN = "IDPAPERIODO";

    public void setIddipendaltroente(Integer iddipendaltroente) {
        writeProperty("iddipendaltroente", iddipendaltroente);
    }
    public Integer getIddipendaltroente() {
        return (Integer)readProperty("iddipendaltroente");
    }

    public void setIdpacontratto(String idpacontratto) {
        writeProperty("idpacontratto", idpacontratto);
    }
    public String getIdpacontratto() {
        return (String)readProperty("idpacontratto");
    }

    public void setIdpaperiodo(Integer idpaperiodo) {
        writeProperty("idpaperiodo", idpaperiodo);
    }
    public Integer getIdpaperiodo() {
        return (Integer)readProperty("idpaperiodo");
    }

    public void setIdpaqualifica(String idpaqualifica) {
        writeProperty("idpaqualifica", idpaqualifica);
    }
    public String getIdpaqualifica() {
        return (String)readProperty("idpaqualifica");
    }

    public void setIdregimefineserv(Short idregimefineserv) {
        writeProperty("idregimefineserv", idregimefineserv);
    }
    public Short getIdregimefineserv() {
        return (Short)readProperty("idregimefineserv");
    }

    public void setIdservizioaltroente(Integer idservizioaltroente) {
        writeProperty("idservizioaltroente", idservizioaltroente);
    }
    public Integer getIdservizioaltroente() {
        return (Integer)readProperty("idservizioaltroente");
    }

    public void setIdtipoimpiego(Short idtipoimpiego) {
        writeProperty("idtipoimpiego", idtipoimpiego);
    }
    public Short getIdtipoimpiego() {
        return (Short)readProperty("idtipoimpiego");
    }

    public void setIdtiposervizio(Short idtiposervizio) {
        writeProperty("idtiposervizio", idtiposervizio);
    }
    public Short getIdtiposervizio() {
        return (Short)readProperty("idtiposervizio");
    }

    public void setIdtiposervizioaltro1(Short idtiposervizioaltro1) {
        writeProperty("idtiposervizioaltro1", idtiposervizioaltro1);
    }
    public Short getIdtiposervizioaltro1() {
        return (Short)readProperty("idtiposervizioaltro1");
    }

    public void setIdtiposervizioaltro2(Short idtiposervizioaltro2) {
        writeProperty("idtiposervizioaltro2", idtiposervizioaltro2);
    }
    public Short getIdtiposervizioaltro2() {
        return (Short)readProperty("idtiposervizioaltro2");
    }

    public void setOresettpersscuolac(BigDecimal oresettpersscuolac) {
        writeProperty("oresettpersscuolac", oresettpersscuolac);
    }
    public BigDecimal getOresettpersscuolac() {
        return (BigDecimal)readProperty("oresettpersscuolac");
    }

    public void setOresettpersscuolar(BigDecimal oresettpersscuolar) {
        writeProperty("oresettpersscuolar", oresettpersscuolar);
    }
    public BigDecimal getOresettpersscuolar() {
        return (BigDecimal)readProperty("oresettpersscuolar");
    }

    public void setPercaspettativa(BigDecimal percaspettativa) {
        writeProperty("percaspettativa", percaspettativa);
    }
    public BigDecimal getPercaspettativa() {
        return (BigDecimal)readProperty("percaspettativa");
    }

    public void setPercretribuzione(BigDecimal percretribuzione) {
        writeProperty("percretribuzione", percretribuzione);
    }
    public BigDecimal getPercretribuzione() {
        return (BigDecimal)readProperty("percretribuzione");
    }

    public void setToPaQualifica(PaQualifica toPaQualifica) {
        setToOneTarget("toPaQualifica", toPaQualifica, true);
    }

    public PaQualifica getToPaQualifica() {
        return (PaQualifica)readProperty("toPaQualifica");
    }


    public void setToRegimeFineServ(PaRegimefineservizio toRegimeFineServ) {
        setToOneTarget("toRegimeFineServ", toRegimeFineServ, true);
    }

    public PaRegimefineservizio getToRegimeFineServ() {
        return (PaRegimefineservizio)readProperty("toRegimeFineServ");
    }


    public void setToTipoImpiego(PaTipoimpiego toTipoImpiego) {
        setToOneTarget("toTipoImpiego", toTipoImpiego, true);
    }

    public PaTipoimpiego getToTipoImpiego() {
        return (PaTipoimpiego)readProperty("toTipoImpiego");
    }


    public void setToTipoServizio(PaTiposervizio toTipoServizio) {
        setToOneTarget("toTipoServizio", toTipoServizio, true);
    }

    public PaTiposervizio getToTipoServizio() {
        return (PaTiposervizio)readProperty("toTipoServizio");
    }


    public void setToTipoServizioAltro1(PaTiposervizioaltro toTipoServizioAltro1) {
        setToOneTarget("toTipoServizioAltro1", toTipoServizioAltro1, true);
    }

    public PaTiposervizioaltro getToTipoServizioAltro1() {
        return (PaTiposervizioaltro)readProperty("toTipoServizioAltro1");
    }


    public void setToTipoServizioAltro2(PaTiposervizioaltro toTipoServizioAltro2) {
        setToOneTarget("toTipoServizioAltro2", toTipoServizioAltro2, true);
    }

    public PaTiposervizioaltro getToTipoServizioAltro2() {
        return (PaTiposervizioaltro)readProperty("toTipoServizioAltro2");
    }


}
