package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.PaMotivoutilizzo;
import it.iubar.paghe.logic.paghe.PaTipoaliquotaposprec;
import it.iubar.paghe.logic.paghe.PaTipoiscrfondoprevcompl;
import it.iubar.paghe.logic.paghe.PaTipoutilizzo;
import it.iubar.paghe.logic.paghe.PaTipovariazione;

/**
 * Class _PaPosizionesubordinato was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaPosizionesubordinato extends CayenneDataObject {

    public static final String GIORNOOPZIONETFR_PROPERTY = "giornoopzionetfr";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDTIPOALIQUOTAPOSPREC_PROPERTY = "idtipoaliquotaposprec";
    public static final String IDTIPOISCRFONDOPREVCOMPL_PROPERTY = "idtipoiscrfondoprevcompl";
    public static final String IDTIPOVARIAZIONE_PROPERTY = "idtipovariazione";
    public static final String SILENZIOASSENSO_PROPERTY = "silenzioassenso";
    public static final String TO_PA_MOTIVOUTILIZZO_PROPERTY = "toPaMotivoutilizzo";
    public static final String TO_PA_TIPOUTILIZZO_PROPERTY = "toPaTipoutilizzo";
    public static final String TO_TIPO_ALIQUOTA_POS_PREC_PROPERTY = "toTipoAliquotaPosPrec";
    public static final String TO_TIPO_ISCR_FONDO_PREV_COMPL_PROPERTY = "toTipoIscrFondoPrevCompl";
    public static final String TO_TIPO_VARIAZIONE_PROPERTY = "toTipoVariazione";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setGiornoopzionetfr(Date giornoopzionetfr) {
        writeProperty("giornoopzionetfr", giornoopzionetfr);
    }
    public Date getGiornoopzionetfr() {
        return (Date)readProperty("giornoopzionetfr");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdtipoaliquotaposprec(Short idtipoaliquotaposprec) {
        writeProperty("idtipoaliquotaposprec", idtipoaliquotaposprec);
    }
    public Short getIdtipoaliquotaposprec() {
        return (Short)readProperty("idtipoaliquotaposprec");
    }

    public void setIdtipoiscrfondoprevcompl(Short idtipoiscrfondoprevcompl) {
        writeProperty("idtipoiscrfondoprevcompl", idtipoiscrfondoprevcompl);
    }
    public Short getIdtipoiscrfondoprevcompl() {
        return (Short)readProperty("idtipoiscrfondoprevcompl");
    }

    public void setIdtipovariazione(Short idtipovariazione) {
        writeProperty("idtipovariazione", idtipovariazione);
    }
    public Short getIdtipovariazione() {
        return (Short)readProperty("idtipovariazione");
    }

    public void setSilenzioassenso(Short silenzioassenso) {
        writeProperty("silenzioassenso", silenzioassenso);
    }
    public Short getSilenzioassenso() {
        return (Short)readProperty("silenzioassenso");
    }

    public void setToPaMotivoutilizzo(PaMotivoutilizzo toPaMotivoutilizzo) {
        setToOneTarget("toPaMotivoutilizzo", toPaMotivoutilizzo, true);
    }

    public PaMotivoutilizzo getToPaMotivoutilizzo() {
        return (PaMotivoutilizzo)readProperty("toPaMotivoutilizzo");
    }


    public void setToPaTipoutilizzo(PaTipoutilizzo toPaTipoutilizzo) {
        setToOneTarget("toPaTipoutilizzo", toPaTipoutilizzo, true);
    }

    public PaTipoutilizzo getToPaTipoutilizzo() {
        return (PaTipoutilizzo)readProperty("toPaTipoutilizzo");
    }


    public void setToTipoAliquotaPosPrec(PaTipoaliquotaposprec toTipoAliquotaPosPrec) {
        setToOneTarget("toTipoAliquotaPosPrec", toTipoAliquotaPosPrec, true);
    }

    public PaTipoaliquotaposprec getToTipoAliquotaPosPrec() {
        return (PaTipoaliquotaposprec)readProperty("toTipoAliquotaPosPrec");
    }


    public void setToTipoIscrFondoPrevCompl(PaTipoiscrfondoprevcompl toTipoIscrFondoPrevCompl) {
        setToOneTarget("toTipoIscrFondoPrevCompl", toTipoIscrFondoPrevCompl, true);
    }

    public PaTipoiscrfondoprevcompl getToTipoIscrFondoPrevCompl() {
        return (PaTipoiscrfondoprevcompl)readProperty("toTipoIscrFondoPrevCompl");
    }


    public void setToTipoVariazione(PaTipovariazione toTipoVariazione) {
        setToOneTarget("toTipoVariazione", toTipoVariazione, true);
    }

    public PaTipovariazione getToTipoVariazione() {
        return (PaTipovariazione)readProperty("toTipoVariazione");
    }


}
