package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.PaGestpensionistica;

/**
 * Class _PaTipomaggiorazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaTipomaggiorazione extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOMAGGIORAZIONE_PROPERTY = "idtipomaggiorazione";
    public static final String PA_GESTIONE_PENSIONISTICA_ARRAY1_PROPERTY = "paGestionePensionisticaArray1";
    public static final String PA_GESTIONE_PENSIONISTICA_ARRAY2_PROPERTY = "paGestionePensionisticaArray2";
    public static final String PA_GESTIONE_PENSIONISTICA_ARRAY3_PROPERTY = "paGestionePensionisticaArray3";

    public static final String IDTIPOMAGGIORAZIONE_PK_COLUMN = "IDTIPOMAGGIORAZIONE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdtipomaggiorazione() {
        return (Short)readProperty("idtipomaggiorazione");
    }

    public void addToPaGestionePensionisticaArray1(PaGestpensionistica obj) {
        addToManyTarget("paGestionePensionisticaArray1", obj, true);
    }
    public void removeFromPaGestionePensionisticaArray1(PaGestpensionistica obj) {
        removeToManyTarget("paGestionePensionisticaArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaGestpensionistica> getPaGestionePensionisticaArray1() {
        return (List<PaGestpensionistica>)readProperty("paGestionePensionisticaArray1");
    }


    public void addToPaGestionePensionisticaArray2(PaGestpensionistica obj) {
        addToManyTarget("paGestionePensionisticaArray2", obj, true);
    }
    public void removeFromPaGestionePensionisticaArray2(PaGestpensionistica obj) {
        removeToManyTarget("paGestionePensionisticaArray2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaGestpensionistica> getPaGestionePensionisticaArray2() {
        return (List<PaGestpensionistica>)readProperty("paGestionePensionisticaArray2");
    }


    public void addToPaGestionePensionisticaArray3(PaGestpensionistica obj) {
        addToManyTarget("paGestionePensionisticaArray3", obj, true);
    }
    public void removeFromPaGestionePensionisticaArray3(PaGestpensionistica obj) {
        removeToManyTarget("paGestionePensionisticaArray3", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaGestpensionistica> getPaGestionePensionisticaArray3() {
        return (List<PaGestpensionistica>)readProperty("paGestionePensionisticaArray3");
    }


}
