package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.PaFondopenscompl;

/**
 * Class _PaTipocessazfondo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaTipocessazfondo extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOCESSAZFONDO_PROPERTY = "idtipocessazfondo";
    public static final String PA_FONDO_PENS_COMPL_ARRAY_PROPERTY = "paFondoPensComplArray";

    public static final String IDTIPOCESSAZFONDO_PK_COLUMN = "IDTIPOCESSAZFONDO";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdtipocessazfondo() {
        return (Short)readProperty("idtipocessazfondo");
    }

    public void addToPaFondoPensComplArray(PaFondopenscompl obj) {
        addToManyTarget("paFondoPensComplArray", obj, true);
    }
    public void removeFromPaFondoPensComplArray(PaFondopenscompl obj) {
        removeToManyTarget("paFondoPensComplArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaFondopenscompl> getPaFondoPensComplArray() {
        return (List<PaFondopenscompl>)readProperty("paFondoPensComplArray");
    }


}
