package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Anf;
import it.iubar.paghe.logic.paghe.Assenza;
import it.iubar.paghe.logic.paghe.Assunzione;
import it.iubar.paghe.logic.paghe.Cessazione;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Contrattodettagliolivello;
import it.iubar.paghe.logic.paghe.Contrattoferie;
import it.iubar.paghe.logic.paghe.Contrattofestivitaretrib;
import it.iubar.paghe.logic.paghe.Contrattorateo;
import it.iubar.paghe.logic.paghe.DmagPosizionelav;
import it.iubar.paghe.logic.paghe.InpsQualifica1;
import it.iubar.paghe.logic.paghe.InpsQualifica2;
import it.iubar.paghe.logic.paghe.InpsQualifica3;
import it.iubar.paghe.logic.paghe.InpsSettore;
import it.iubar.paghe.logic.paghe.InpsTipoapprendistato;
import it.iubar.paghe.logic.paghe.InpsTipocontribuzione;
import it.iubar.paghe.logic.paghe.Inquadramento;
import it.iubar.paghe.logic.paghe.PaTipoutilizzo;
import it.iubar.paghe.logic.paghe.Posizionecontrattindividuale;
import it.iubar.paghe.logic.paghe.Posizioneindennita;
import it.iubar.paghe.logic.paghe.Posizionelavoratore;
import it.iubar.paghe.logic.paghe.SpPosizionesubordinato;
import it.iubar.paghe.logic.paghe.TfrMese;
import it.iubar.paghe.logic.paghe.Tipocalcolo;

/**
 * Class _Posizionesubordinato was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Posizionesubordinato extends CayenneDataObject {

    public static final String IDASSUNZIONE_PROPERTY = "idassunzione";
    public static final String IDCESSAZIONE_PROPERTY = "idcessazione";
    public static final String IDCOEFFICIENTE_PROPERTY = "idcoefficiente";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDFERIE_PROPERTY = "idferie";
    public static final String IDFESTIVITARETRIB_PROPERTY = "idfestivitaretrib";
    public static final String IDINPSQUALIFICA1_PROPERTY = "idinpsqualifica1";
    public static final String IDINPSQUALIFICA2_PROPERTY = "idinpsqualifica2";
    public static final String IDINPSQUALIFICA3_PROPERTY = "idinpsqualifica3";
    public static final String IDINPSSETTORE_PROPERTY = "idinpssettore";
    public static final String IDINPSTIPOAPPRENDISTATO_PROPERTY = "idinpstipoapprendistato";
    public static final String IDINPSTIPOCONTRIBUZIONE_PROPERTY = "idinpstipocontribuzione";
    public static final String IDINQUADRAMENTO_PROPERTY = "idinquadramento";
    public static final String IDLIVELLO_PROPERTY = "idlivello";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDRATEO_PROPERTY = "idrateo";
    public static final String IDTIPOCALCOLO_PROPERTY = "idtipocalcolo";
    public static final String PARTTIMECONTRATTO_PROPERTY = "parttimecontratto";
    public static final String PARTTIMEORARIO_PROPERTY = "parttimeorario";
    public static final String TFRACCANTONATO_PROPERTY = "tfraccantonato";
    public static final String TIPOCONSOLIDAMENTO_PROPERTY = "tipoconsolidamento";
    public static final String ASSENZA_ARRAY_PROPERTY = "assenzaArray";
    public static final String DMAG_POSIZIONELAV_ARRAY_PROPERTY = "dmagPosizionelavArray";
    public static final String POSIZCONTRATTINDIVIDUALE_ARRAY_PROPERTY = "posizcontrattindividualeArray";
    public static final String POSIZIONEINDENNITA_ARRAY_PROPERTY = "posizioneindennitaArray";
    public static final String SP_POSIZIONE_SUB_ARRAY_PROPERTY = "spPosizioneSubArray";
    public static final String TO_ASSUNZIONE_PROPERTY = "toAssunzione";
    public static final String TO_CESSAZIONE_PROPERTY = "toCessazione";
    public static final String TO_CONTRATTO_DETTAGLIO_LIVELLO_PROPERTY = "toContrattoDettaglioLivello";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_CONTRATTOFERIE_PROPERTY = "toContrattoferie";
    public static final String TO_CONTRATTOFESTIVITARETRIB_PROPERTY = "toContrattofestivitaretrib";
    public static final String TO_CONTRATTORATEO_PROPERTY = "toContrattorateo";
    public static final String TO_INPS_ANF_PROPERTY = "toInpsAnf";
    public static final String TO_INPS_QUALIFICA1_PROPERTY = "toInpsQualifica1";
    public static final String TO_INPS_QUALIFICA2_PROPERTY = "toInpsQualifica2";
    public static final String TO_INPS_QUALIFICA3_PROPERTY = "toInpsQualifica3";
    public static final String TO_INPS_SETTORE_PROPERTY = "toInpsSettore";
    public static final String TO_INPS_TIPOAPPRENDISTATO_PROPERTY = "toInpsTipoapprendistato";
    public static final String TO_INPS_TIPOCONTRIBUZIONE_PROPERTY = "toInpsTipocontribuzione";
    public static final String TO_INQUADRAMENTO_PROPERTY = "toInquadramento";
    public static final String TO_PA_MOTIVOUTILIZZO_PROPERTY = "toPaMotivoutilizzo";
    public static final String TO_POSIZIONELAVORATORE_PROPERTY = "toPosizionelavoratore";
    public static final String TO_TFR_MESE_PROPERTY = "toTfrMese";
    public static final String TO_TIPOCALCOLO_PROPERTY = "toTipocalcolo";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setIdassunzione(Integer idassunzione) {
        writeProperty("idassunzione", idassunzione);
    }
    public Integer getIdassunzione() {
        return (Integer)readProperty("idassunzione");
    }

    public void setIdcessazione(Integer idcessazione) {
        writeProperty("idcessazione", idcessazione);
    }
    public Integer getIdcessazione() {
        return (Integer)readProperty("idcessazione");
    }

    public void setIdcoefficiente(Short idcoefficiente) {
        writeProperty("idcoefficiente", idcoefficiente);
    }
    public Short getIdcoefficiente() {
        return (Short)readProperty("idcoefficiente");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdferie(Short idferie) {
        writeProperty("idferie", idferie);
    }
    public Short getIdferie() {
        return (Short)readProperty("idferie");
    }

    public void setIdfestivitaretrib(Short idfestivitaretrib) {
        writeProperty("idfestivitaretrib", idfestivitaretrib);
    }
    public Short getIdfestivitaretrib() {
        return (Short)readProperty("idfestivitaretrib");
    }

    public void setIdinpsqualifica1(String idinpsqualifica1) {
        writeProperty("idinpsqualifica1", idinpsqualifica1);
    }
    public String getIdinpsqualifica1() {
        return (String)readProperty("idinpsqualifica1");
    }

    public void setIdinpsqualifica2(String idinpsqualifica2) {
        writeProperty("idinpsqualifica2", idinpsqualifica2);
    }
    public String getIdinpsqualifica2() {
        return (String)readProperty("idinpsqualifica2");
    }

    public void setIdinpsqualifica3(String idinpsqualifica3) {
        writeProperty("idinpsqualifica3", idinpsqualifica3);
    }
    public String getIdinpsqualifica3() {
        return (String)readProperty("idinpsqualifica3");
    }

    public void setIdinpssettore(Integer idinpssettore) {
        writeProperty("idinpssettore", idinpssettore);
    }
    public Integer getIdinpssettore() {
        return (Integer)readProperty("idinpssettore");
    }

    public void setIdinpstipoapprendistato(String idinpstipoapprendistato) {
        writeProperty("idinpstipoapprendistato", idinpstipoapprendistato);
    }
    public String getIdinpstipoapprendistato() {
        return (String)readProperty("idinpstipoapprendistato");
    }

    public void setIdinpstipocontribuzione(String idinpstipocontribuzione) {
        writeProperty("idinpstipocontribuzione", idinpstipocontribuzione);
    }
    public String getIdinpstipocontribuzione() {
        return (String)readProperty("idinpstipocontribuzione");
    }

    public void setIdinquadramento(Integer idinquadramento) {
        writeProperty("idinquadramento", idinquadramento);
    }
    public Integer getIdinquadramento() {
        return (Integer)readProperty("idinquadramento");
    }

    public void setIdlivello(String idlivello) {
        writeProperty("idlivello", idlivello);
    }
    public String getIdlivello() {
        return (String)readProperty("idlivello");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdrateo(Short idrateo) {
        writeProperty("idrateo", idrateo);
    }
    public Short getIdrateo() {
        return (Short)readProperty("idrateo");
    }

    public void setIdtipocalcolo(Short idtipocalcolo) {
        writeProperty("idtipocalcolo", idtipocalcolo);
    }
    public Short getIdtipocalcolo() {
        return (Short)readProperty("idtipocalcolo");
    }

    public void setParttimecontratto(BigDecimal parttimecontratto) {
        writeProperty("parttimecontratto", parttimecontratto);
    }
    public BigDecimal getParttimecontratto() {
        return (BigDecimal)readProperty("parttimecontratto");
    }

    public void setParttimeorario(BigDecimal parttimeorario) {
        writeProperty("parttimeorario", parttimeorario);
    }
    public BigDecimal getParttimeorario() {
        return (BigDecimal)readProperty("parttimeorario");
    }

    public void setTfraccantonato(BigDecimal tfraccantonato) {
        writeProperty("tfraccantonato", tfraccantonato);
    }
    public BigDecimal getTfraccantonato() {
        return (BigDecimal)readProperty("tfraccantonato");
    }

    public void setTipoconsolidamento(String tipoconsolidamento) {
        writeProperty("tipoconsolidamento", tipoconsolidamento);
    }
    public String getTipoconsolidamento() {
        return (String)readProperty("tipoconsolidamento");
    }

    public void addToAssenzaArray(Assenza obj) {
        addToManyTarget("assenzaArray", obj, true);
    }
    public void removeFromAssenzaArray(Assenza obj) {
        removeToManyTarget("assenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Assenza> getAssenzaArray() {
        return (List<Assenza>)readProperty("assenzaArray");
    }


    public void addToDmagPosizionelavArray(DmagPosizionelav obj) {
        addToManyTarget("dmagPosizionelavArray", obj, true);
    }
    public void removeFromDmagPosizionelavArray(DmagPosizionelav obj) {
        removeToManyTarget("dmagPosizionelavArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DmagPosizionelav> getDmagPosizionelavArray() {
        return (List<DmagPosizionelav>)readProperty("dmagPosizionelavArray");
    }


    public void addToPosizcontrattindividualeArray(Posizionecontrattindividuale obj) {
        addToManyTarget("posizcontrattindividualeArray", obj, true);
    }
    public void removeFromPosizcontrattindividualeArray(Posizionecontrattindividuale obj) {
        removeToManyTarget("posizcontrattindividualeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionecontrattindividuale> getPosizcontrattindividualeArray() {
        return (List<Posizionecontrattindividuale>)readProperty("posizcontrattindividualeArray");
    }


    public void addToPosizioneindennitaArray(Posizioneindennita obj) {
        addToManyTarget("posizioneindennitaArray", obj, true);
    }
    public void removeFromPosizioneindennitaArray(Posizioneindennita obj) {
        removeToManyTarget("posizioneindennitaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizioneindennita> getPosizioneindennitaArray() {
        return (List<Posizioneindennita>)readProperty("posizioneindennitaArray");
    }


    public void addToSpPosizioneSubArray(SpPosizionesubordinato obj) {
        addToManyTarget("spPosizioneSubArray", obj, true);
    }
    public void removeFromSpPosizioneSubArray(SpPosizionesubordinato obj) {
        removeToManyTarget("spPosizioneSubArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SpPosizionesubordinato> getSpPosizioneSubArray() {
        return (List<SpPosizionesubordinato>)readProperty("spPosizioneSubArray");
    }


    public void setToAssunzione(Assunzione toAssunzione) {
        setToOneTarget("toAssunzione", toAssunzione, true);
    }

    public Assunzione getToAssunzione() {
        return (Assunzione)readProperty("toAssunzione");
    }


    public void setToCessazione(Cessazione toCessazione) {
        setToOneTarget("toCessazione", toCessazione, true);
    }

    public Cessazione getToCessazione() {
        return (Cessazione)readProperty("toCessazione");
    }


    public void setToContrattoDettaglioLivello(Contrattodettagliolivello toContrattoDettaglioLivello) {
        setToOneTarget("toContrattoDettaglioLivello", toContrattoDettaglioLivello, true);
    }

    public Contrattodettagliolivello getToContrattoDettaglioLivello() {
        return (Contrattodettagliolivello)readProperty("toContrattoDettaglioLivello");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToContrattoferie(Contrattoferie toContrattoferie) {
        setToOneTarget("toContrattoferie", toContrattoferie, true);
    }

    public Contrattoferie getToContrattoferie() {
        return (Contrattoferie)readProperty("toContrattoferie");
    }


    public void setToContrattofestivitaretrib(Contrattofestivitaretrib toContrattofestivitaretrib) {
        setToOneTarget("toContrattofestivitaretrib", toContrattofestivitaretrib, true);
    }

    public Contrattofestivitaretrib getToContrattofestivitaretrib() {
        return (Contrattofestivitaretrib)readProperty("toContrattofestivitaretrib");
    }


    public void setToContrattorateo(Contrattorateo toContrattorateo) {
        setToOneTarget("toContrattorateo", toContrattorateo, true);
    }

    public Contrattorateo getToContrattorateo() {
        return (Contrattorateo)readProperty("toContrattorateo");
    }


    public void setToInpsAnf(Anf toInpsAnf) {
        setToOneTarget("toInpsAnf", toInpsAnf, true);
    }

    public Anf getToInpsAnf() {
        return (Anf)readProperty("toInpsAnf");
    }


    public void setToInpsQualifica1(InpsQualifica1 toInpsQualifica1) {
        setToOneTarget("toInpsQualifica1", toInpsQualifica1, true);
    }

    public InpsQualifica1 getToInpsQualifica1() {
        return (InpsQualifica1)readProperty("toInpsQualifica1");
    }


    public void setToInpsQualifica2(InpsQualifica2 toInpsQualifica2) {
        setToOneTarget("toInpsQualifica2", toInpsQualifica2, true);
    }

    public InpsQualifica2 getToInpsQualifica2() {
        return (InpsQualifica2)readProperty("toInpsQualifica2");
    }


    public void setToInpsQualifica3(InpsQualifica3 toInpsQualifica3) {
        setToOneTarget("toInpsQualifica3", toInpsQualifica3, true);
    }

    public InpsQualifica3 getToInpsQualifica3() {
        return (InpsQualifica3)readProperty("toInpsQualifica3");
    }


    public void setToInpsSettore(InpsSettore toInpsSettore) {
        setToOneTarget("toInpsSettore", toInpsSettore, true);
    }

    public InpsSettore getToInpsSettore() {
        return (InpsSettore)readProperty("toInpsSettore");
    }


    public void setToInpsTipoapprendistato(InpsTipoapprendistato toInpsTipoapprendistato) {
        setToOneTarget("toInpsTipoapprendistato", toInpsTipoapprendistato, true);
    }

    public InpsTipoapprendistato getToInpsTipoapprendistato() {
        return (InpsTipoapprendistato)readProperty("toInpsTipoapprendistato");
    }


    public void setToInpsTipocontribuzione(InpsTipocontribuzione toInpsTipocontribuzione) {
        setToOneTarget("toInpsTipocontribuzione", toInpsTipocontribuzione, true);
    }

    public InpsTipocontribuzione getToInpsTipocontribuzione() {
        return (InpsTipocontribuzione)readProperty("toInpsTipocontribuzione");
    }


    public void setToInquadramento(Inquadramento toInquadramento) {
        setToOneTarget("toInquadramento", toInquadramento, true);
    }

    public Inquadramento getToInquadramento() {
        return (Inquadramento)readProperty("toInquadramento");
    }


    public void setToPaMotivoutilizzo(PaTipoutilizzo toPaMotivoutilizzo) {
        setToOneTarget("toPaMotivoutilizzo", toPaMotivoutilizzo, true);
    }

    public PaTipoutilizzo getToPaMotivoutilizzo() {
        return (PaTipoutilizzo)readProperty("toPaMotivoutilizzo");
    }


    public void setToPosizionelavoratore(Posizionelavoratore toPosizionelavoratore) {
        setToOneTarget("toPosizionelavoratore", toPosizionelavoratore, true);
    }

    public Posizionelavoratore getToPosizionelavoratore() {
        return (Posizionelavoratore)readProperty("toPosizionelavoratore");
    }


    public void setToTfrMese(TfrMese toTfrMese) {
        setToOneTarget("toTfrMese", toTfrMese, true);
    }

    public TfrMese getToTfrMese() {
        return (TfrMese)readProperty("toTfrMese");
    }


    public void setToTipocalcolo(Tipocalcolo toTipocalcolo) {
        setToOneTarget("toTipocalcolo", toTipocalcolo, true);
    }

    public Tipocalcolo getToTipocalcolo() {
        return (Tipocalcolo)readProperty("toTipocalcolo");
    }


}
