package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Posizionelavoratore;
import it.iubar.paghe.logic.paghe.Riduzioneinps;

/**
 * Class _PosizioneRiduzioneinps was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PosizioneRiduzioneinps extends CayenneDataObject {

    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDRIDUZIONE_PROPERTY = "idriduzione";
    public static final String TO_POSIZIONELAVORATORE_PROPERTY = "toPosizionelavoratore";
    public static final String TO_RIDUZIONEINPS_PROPERTY = "toRiduzioneinps";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";
    public static final String IDRIDUZIONE_PK_COLUMN = "IDRIDUZIONE";

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdriduzione(Integer idriduzione) {
        writeProperty("idriduzione", idriduzione);
    }
    public Integer getIdriduzione() {
        return (Integer)readProperty("idriduzione");
    }

    public void setToPosizionelavoratore(Posizionelavoratore toPosizionelavoratore) {
        setToOneTarget("toPosizionelavoratore", toPosizionelavoratore, true);
    }

    public Posizionelavoratore getToPosizionelavoratore() {
        return (Posizionelavoratore)readProperty("toPosizionelavoratore");
    }


    public void setToRiduzioneinps(Riduzioneinps toRiduzioneinps) {
        setToOneTarget("toRiduzioneinps", toRiduzioneinps, true);
    }

    public Riduzioneinps getToRiduzioneinps() {
        return (Riduzioneinps)readProperty("toRiduzioneinps");
    }


}
