package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Profiloprevidenzialealtro was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Profiloprevidenzialealtro extends CayenneDataObject {

    public static final String ALIQUOTATOTCARICODAT_PROPERTY = "aliquotatotcaricodat";
    public static final String ALIQUOTATOTCARICOLAV_PROPERTY = "aliquotatotcaricolav";
    public static final String CONTRIBFISSO_PROPERTY = "contribfisso";
    public static final String CONTRIBTOTCARICODAT_PROPERTY = "contribtotcaricodat";
    public static final String CONTRIBTOTCARICOLAV_PROPERTY = "contribtotcaricolav";
    public static final String IDENTEPREVIDENZIALE_PROPERTY = "identeprevidenziale";
    public static final String IDPROFILO_PROPERTY = "idprofilo";
    public static final String NOTE_PROPERTY = "note";
    public static final String RETRIBMINGG_PROPERTY = "retribmingg";
    public static final String RETRIBMINHH_PROPERTY = "retribminhh";
    public static final String ULTIMAMODIFICA_PROPERTY = "ultimamodifica";
    public static final String ULTIMAMODIFICAUSER_PROPERTY = "ultimamodificauser";

    public static final String IDPROFILO_PK_COLUMN = "IDPROFILO";

    public void setAliquotatotcaricodat(BigDecimal aliquotatotcaricodat) {
        writeProperty("aliquotatotcaricodat", aliquotatotcaricodat);
    }
    public BigDecimal getAliquotatotcaricodat() {
        return (BigDecimal)readProperty("aliquotatotcaricodat");
    }

    public void setAliquotatotcaricolav(BigDecimal aliquotatotcaricolav) {
        writeProperty("aliquotatotcaricolav", aliquotatotcaricolav);
    }
    public BigDecimal getAliquotatotcaricolav() {
        return (BigDecimal)readProperty("aliquotatotcaricolav");
    }

    public void setContribfisso(BigDecimal contribfisso) {
        writeProperty("contribfisso", contribfisso);
    }
    public BigDecimal getContribfisso() {
        return (BigDecimal)readProperty("contribfisso");
    }

    public void setContribtotcaricodat(BigDecimal contribtotcaricodat) {
        writeProperty("contribtotcaricodat", contribtotcaricodat);
    }
    public BigDecimal getContribtotcaricodat() {
        return (BigDecimal)readProperty("contribtotcaricodat");
    }

    public void setContribtotcaricolav(BigDecimal contribtotcaricolav) {
        writeProperty("contribtotcaricolav", contribtotcaricolav);
    }
    public BigDecimal getContribtotcaricolav() {
        return (BigDecimal)readProperty("contribtotcaricolav");
    }

    public void setIdenteprevidenziale(Short identeprevidenziale) {
        writeProperty("identeprevidenziale", identeprevidenziale);
    }
    public Short getIdenteprevidenziale() {
        return (Short)readProperty("identeprevidenziale");
    }

    public void setIdprofilo(Integer idprofilo) {
        writeProperty("idprofilo", idprofilo);
    }
    public Integer getIdprofilo() {
        return (Integer)readProperty("idprofilo");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setRetribmingg(BigDecimal retribmingg) {
        writeProperty("retribmingg", retribmingg);
    }
    public BigDecimal getRetribmingg() {
        return (BigDecimal)readProperty("retribmingg");
    }

    public void setRetribminhh(BigDecimal retribminhh) {
        writeProperty("retribminhh", retribminhh);
    }
    public BigDecimal getRetribminhh() {
        return (BigDecimal)readProperty("retribminhh");
    }

    public void setUltimamodifica(Date ultimamodifica) {
        writeProperty("ultimamodifica", ultimamodifica);
    }
    public Date getUltimamodifica() {
        return (Date)readProperty("ultimamodifica");
    }

    public void setUltimamodificauser(String ultimamodificauser) {
        writeProperty("ultimamodificauser", ultimamodificauser);
    }
    public String getUltimamodificauser() {
        return (String)readProperty("ultimamodificauser");
    }

}
