package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Impresa;
import it.iubar.paghe.logic.anagrafica.Tipolavoratore;
import it.iubar.paghe.logic.anagrafica.Tipolavoratore2;
import it.iubar.paghe.logic.paghe.Frequenza;

/**
 * Class _Scadenza was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Scadenza extends CayenneDataObject {

    public static final String ANNO_PROPERTY = "anno";
    public static final String ATTIVA_PROPERTY = "attiva";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String GIORNO_PROPERTY = "giorno";
    public static final String IDFREQUENZA_PROPERTY = "idfrequenza";
    public static final String IDLAVORATORE_PROPERTY = "idlavoratore";
    public static final String IDSCADENZA_PROPERTY = "idscadenza";
    public static final String IDTIPOLAVORATORE_PROPERTY = "idtipolavoratore";
    public static final String MESE_PROPERTY = "mese";
    public static final String NOTE_PROPERTY = "note";
    public static final String TO_FREQUENZA_PROPERTY = "toFrequenza";
    public static final String TO_IMPRESA_PROPERTY = "toImpresa";
    public static final String TO_TIPOLAVORATORE_PROPERTY = "toTipolavoratore";
    public static final String TO_TIPOLAVORATORE2_PROPERTY = "toTipolavoratore2";

    public static final String IDFREQUENZA_PK_COLUMN = "IDFREQUENZA";
    public static final String IDSCADENZA_PK_COLUMN = "IDSCADENZA";

    public void setAnno(Integer anno) {
        writeProperty("anno", anno);
    }
    public Integer getAnno() {
        return (Integer)readProperty("anno");
    }

    public void setAttiva(Short attiva) {
        writeProperty("attiva", attiva);
    }
    public Short getAttiva() {
        return (Short)readProperty("attiva");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setGiorno(Short giorno) {
        writeProperty("giorno", giorno);
    }
    public Short getGiorno() {
        return (Short)readProperty("giorno");
    }

    public void setIdfrequenza(Short idfrequenza) {
        writeProperty("idfrequenza", idfrequenza);
    }
    public Short getIdfrequenza() {
        return (Short)readProperty("idfrequenza");
    }

    public void setIdlavoratore(Integer idlavoratore) {
        writeProperty("idlavoratore", idlavoratore);
    }
    public Integer getIdlavoratore() {
        return (Integer)readProperty("idlavoratore");
    }

    public void setIdscadenza(Integer idscadenza) {
        writeProperty("idscadenza", idscadenza);
    }
    public Integer getIdscadenza() {
        return (Integer)readProperty("idscadenza");
    }

    public void setIdtipolavoratore(Short idtipolavoratore) {
        writeProperty("idtipolavoratore", idtipolavoratore);
    }
    public Short getIdtipolavoratore() {
        return (Short)readProperty("idtipolavoratore");
    }

    public void setMese(Short mese) {
        writeProperty("mese", mese);
    }
    public Short getMese() {
        return (Short)readProperty("mese");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setToFrequenza(Frequenza toFrequenza) {
        setToOneTarget("toFrequenza", toFrequenza, true);
    }

    public Frequenza getToFrequenza() {
        return (Frequenza)readProperty("toFrequenza");
    }


    public void setToImpresa(Impresa toImpresa) {
        setToOneTarget("toImpresa", toImpresa, true);
    }

    public Impresa getToImpresa() {
        return (Impresa)readProperty("toImpresa");
    }


    public void setToTipolavoratore(Tipolavoratore toTipolavoratore) {
        setToOneTarget("toTipolavoratore", toTipolavoratore, true);
    }

    public Tipolavoratore getToTipolavoratore() {
        return (Tipolavoratore)readProperty("toTipolavoratore");
    }


    public void setToTipolavoratore2(Tipolavoratore2 toTipolavoratore2) {
        setToOneTarget("toTipolavoratore2", toTipolavoratore2, true);
    }

    public Tipolavoratore2 getToTipolavoratore2() {
        return (Tipolavoratore2)readProperty("toTipolavoratore2");
    }


}
