package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.SpCausaleextracontrib;
import it.iubar.paghe.logic.paghe.SpDatoretribuzione;
import it.iubar.paghe.logic.paghe.SpProfilolavoratore;

/**
 * Class _SpAliquota was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpAliquota extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDALIQUOTA_PROPERTY = "idaliquota";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String SP_CAUSALEEXTRACONTRIB_ARRAY_PROPERTY = "spCausaleextracontribArray";
    public static final String SP_DATORETRIBUZIONE_ARRAY_PROPERTY = "spDatoretribuzioneArray";
    public static final String SP_PROFILOLAVORATORE_ARRAY_PROPERTY = "spProfilolavoratoreArray";

    public static final String IDALIQUOTA_PK_COLUMN = "IDALIQUOTA";

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setIdaliquota(String idaliquota) {
        writeProperty("idaliquota", idaliquota);
    }
    public String getIdaliquota() {
        return (String)readProperty("idaliquota");
    }

    public void setValidoal(Date validoal) {
        writeProperty("validoal", validoal);
    }
    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToSpCausaleextracontribArray(SpCausaleextracontrib obj) {
        addToManyTarget("spCausaleextracontribArray", obj, true);
    }
    public void removeFromSpCausaleextracontribArray(SpCausaleextracontrib obj) {
        removeToManyTarget("spCausaleextracontribArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SpCausaleextracontrib> getSpCausaleextracontribArray() {
        return (List<SpCausaleextracontrib>)readProperty("spCausaleextracontribArray");
    }


    public void addToSpDatoretribuzioneArray(SpDatoretribuzione obj) {
        addToManyTarget("spDatoretribuzioneArray", obj, true);
    }
    public void removeFromSpDatoretribuzioneArray(SpDatoretribuzione obj) {
        removeToManyTarget("spDatoretribuzioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SpDatoretribuzione> getSpDatoretribuzioneArray() {
        return (List<SpDatoretribuzione>)readProperty("spDatoretribuzioneArray");
    }


    public void addToSpProfilolavoratoreArray(SpProfilolavoratore obj) {
        addToManyTarget("spProfilolavoratoreArray", obj, true);
    }
    public void removeFromSpProfilolavoratoreArray(SpProfilolavoratore obj) {
        removeToManyTarget("spProfilolavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SpProfilolavoratore> getSpProfilolavoratoreArray() {
        return (List<SpProfilolavoratore>)readProperty("spProfilolavoratoreArray");
    }


}
