package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Albocovip;
import it.iubar.paghe.logic.paghe.TfrDestinazione;
import it.iubar.paghe.logic.paghe.TfrFondotesoreria;
import it.iubar.paghe.logic.paghe.TfrTipoquota;

/**
 * Class _TfrSceltadestinazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TfrSceltadestinazione extends CayenneDataObject {

    public static final String DATAADESIONE_PROPERTY = "dataadesione";
    public static final String DATASCELTA_PROPERTY = "datascelta";
    public static final String IDFONDOTESORERIA_PROPERTY = "idfondotesoreria";
    public static final String IDFORMAPREVCOMPL_PROPERTY = "idformaprevcompl";
    public static final String IDPROFILO_PROPERTY = "idprofilo";
    public static final String IDTIPOQUOTAPREVCOMPL_PROPERTY = "idtipoquotaprevcompl";
    public static final String MISURAPERCPREVCOMPL_PROPERTY = "misurapercprevcompl";
    public static final String TFR_DESTINAZIONE_ARRAY_PROPERTY = "tfrDestinazioneArray";
    public static final String TO_ALBOCOVIP_PROPERTY = "toAlbocovip";
    public static final String TO_TFR_FONDOTESORERIA_PROPERTY = "toTfrFondotesoreria";
    public static final String TO_TFR_TIPOQUOTA_PROPERTY = "toTfrTipoquota";

    public static final String DATASCELTA_PK_COLUMN = "DATASCELTA";
    public static final String IDPROFILO_PK_COLUMN = "IDPROFILO";

    public void setDataadesione(Date dataadesione) {
        writeProperty("dataadesione", dataadesione);
    }
    public Date getDataadesione() {
        return (Date)readProperty("dataadesione");
    }

    public void setDatascelta(Date datascelta) {
        writeProperty("datascelta", datascelta);
    }
    public Date getDatascelta() {
        return (Date)readProperty("datascelta");
    }

    public void setIdfondotesoreria(Short idfondotesoreria) {
        writeProperty("idfondotesoreria", idfondotesoreria);
    }
    public Short getIdfondotesoreria() {
        return (Short)readProperty("idfondotesoreria");
    }

    public void setIdformaprevcompl(Integer idformaprevcompl) {
        writeProperty("idformaprevcompl", idformaprevcompl);
    }
    public Integer getIdformaprevcompl() {
        return (Integer)readProperty("idformaprevcompl");
    }

    public void setIdprofilo(Integer idprofilo) {
        writeProperty("idprofilo", idprofilo);
    }
    public Integer getIdprofilo() {
        return (Integer)readProperty("idprofilo");
    }

    public void setIdtipoquotaprevcompl(String idtipoquotaprevcompl) {
        writeProperty("idtipoquotaprevcompl", idtipoquotaprevcompl);
    }
    public String getIdtipoquotaprevcompl() {
        return (String)readProperty("idtipoquotaprevcompl");
    }

    public void setMisurapercprevcompl(BigDecimal misurapercprevcompl) {
        writeProperty("misurapercprevcompl", misurapercprevcompl);
    }
    public BigDecimal getMisurapercprevcompl() {
        return (BigDecimal)readProperty("misurapercprevcompl");
    }

    public void addToTfrDestinazioneArray(TfrDestinazione obj) {
        addToManyTarget("tfrDestinazioneArray", obj, true);
    }
    public void removeFromTfrDestinazioneArray(TfrDestinazione obj) {
        removeToManyTarget("tfrDestinazioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TfrDestinazione> getTfrDestinazioneArray() {
        return (List<TfrDestinazione>)readProperty("tfrDestinazioneArray");
    }


    public void setToAlbocovip(Albocovip toAlbocovip) {
        setToOneTarget("toAlbocovip", toAlbocovip, true);
    }

    public Albocovip getToAlbocovip() {
        return (Albocovip)readProperty("toAlbocovip");
    }


    public void setToTfrFondotesoreria(TfrFondotesoreria toTfrFondotesoreria) {
        setToOneTarget("toTfrFondotesoreria", toTfrFondotesoreria, true);
    }

    public TfrFondotesoreria getToTfrFondotesoreria() {
        return (TfrFondotesoreria)readProperty("toTfrFondotesoreria");
    }


    public void setToTfrTipoquota(TfrTipoquota toTfrTipoquota) {
        setToOneTarget("toTfrTipoquota", toTfrTipoquota, true);
    }

    public TfrTipoquota getToTfrTipoquota() {
        return (TfrTipoquota)readProperty("toTfrTipoquota");
    }


}
