package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Posizionesubordinato;
import it.iubar.paghe.logic.paghe.TfrFondinps;
import it.iubar.paghe.logic.paghe.TfrMesetesoreria;

/**
 * Class _TfrMese was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TfrMese extends CayenneDataObject {

    public static final String BASECALCOLO_PROPERTY = "basecalcolo";
    public static final String BASECALCOLOPREVCOMPL_PROPERTY = "basecalcoloprevcompl";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String POSIZIONESUB_ARRAY_PROPERTY = "posizionesubArray";
    public static final String TO_TFR_FONDINPS_PROPERTY = "toTfrFondinps";
    public static final String TO_TFR_MESETESORERIA_PROPERTY = "toTfrMesetesoreria";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setBasecalcolo(BigDecimal basecalcolo) {
        writeProperty("basecalcolo", basecalcolo);
    }
    public BigDecimal getBasecalcolo() {
        return (BigDecimal)readProperty("basecalcolo");
    }

    public void setBasecalcoloprevcompl(BigDecimal basecalcoloprevcompl) {
        writeProperty("basecalcoloprevcompl", basecalcoloprevcompl);
    }
    public BigDecimal getBasecalcoloprevcompl() {
        return (BigDecimal)readProperty("basecalcoloprevcompl");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void addToPosizionesubArray(Posizionesubordinato obj) {
        addToManyTarget("posizionesubArray", obj, true);
    }
    public void removeFromPosizionesubArray(Posizionesubordinato obj) {
        removeToManyTarget("posizionesubArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionesubordinato> getPosizionesubArray() {
        return (List<Posizionesubordinato>)readProperty("posizionesubArray");
    }


    public void setToTfrFondinps(TfrFondinps toTfrFondinps) {
        setToOneTarget("toTfrFondinps", toTfrFondinps, true);
    }

    public TfrFondinps getToTfrFondinps() {
        return (TfrFondinps)readProperty("toTfrFondinps");
    }


    public void setToTfrMesetesoreria(TfrMesetesoreria toTfrMesetesoreria) {
        setToOneTarget("toTfrMesetesoreria", toTfrMesetesoreria, true);
    }

    public TfrMesetesoreria getToTfrMesetesoreria() {
        return (TfrMesetesoreria)readProperty("toTfrMesetesoreria");
    }


}
