package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Lavoratore;

/**
 * Class _TfrAnno was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TfrAnno extends CayenneDataObject {

    public static final String ACCANTONAMENTIPREC_PROPERTY = "accantonamentiprec";
    public static final String ACCANTONAMENTIPRECEDENTI_PROPERTY = "accantonamentiprecedenti";
    public static final String ANNO_PROPERTY = "anno";
    public static final String ANTICIPI_PROPERTY = "anticipi";
    public static final String IDLAVORATORE_PROPERTY = "idlavoratore";
    public static final String IMPONIBILEPREVIDENZIALE_PROPERTY = "imponibileprevidenziale";
    public static final String IMPOSTAPAGATASUANTICIPAZ_PROPERTY = "impostapagatasuanticipaz";
    public static final String IMPOSTASURIVALUTAZIONE_PROPERTY = "impostasurivalutazione";
    public static final String INDICERIVALUTAZIONE_PROPERTY = "indicerivalutazione";
    public static final String NORECALC_PROPERTY = "norecalc";
    public static final String ONERISOCIALI_PROPERTY = "onerisociali";
    public static final String QUOTETRASFERITE_PROPERTY = "quotetrasferite";
    public static final String RAD_PROPERTY = "rad";
    public static final String RIVALUTAZLORDA_PROPERTY = "rivalutazlorda";
    public static final String TFRLORDO_PROPERTY = "tfrlordo";
    public static final String TFRNETTO_PROPERTY = "tfrnetto";
    public static final String ULTIMAMODIFICA_PROPERTY = "ultimamodifica";
    public static final String ULTIMAMODIFICAUSER_PROPERTY = "ultimamodificauser";
    public static final String TO_LAVORATORE_PROPERTY = "toLavoratore";

    public static final String ANNO_PK_COLUMN = "ANNO";
    public static final String IDLAVORATORE_PK_COLUMN = "IDLAVORATORE";

    public void setAccantonamentiprec(BigDecimal accantonamentiprec) {
        writeProperty("accantonamentiprec", accantonamentiprec);
    }
    public BigDecimal getAccantonamentiprec() {
        return (BigDecimal)readProperty("accantonamentiprec");
    }

    public void setAccantonamentiprecedenti(BigDecimal accantonamentiprecedenti) {
        writeProperty("accantonamentiprecedenti", accantonamentiprecedenti);
    }
    public BigDecimal getAccantonamentiprecedenti() {
        return (BigDecimal)readProperty("accantonamentiprecedenti");
    }

    public void setAnno(Integer anno) {
        writeProperty("anno", anno);
    }
    public Integer getAnno() {
        return (Integer)readProperty("anno");
    }

    public void setAnticipi(BigDecimal anticipi) {
        writeProperty("anticipi", anticipi);
    }
    public BigDecimal getAnticipi() {
        return (BigDecimal)readProperty("anticipi");
    }

    public void setIdlavoratore(Integer idlavoratore) {
        writeProperty("idlavoratore", idlavoratore);
    }
    public Integer getIdlavoratore() {
        return (Integer)readProperty("idlavoratore");
    }

    public void setImponibileprevidenziale(BigDecimal imponibileprevidenziale) {
        writeProperty("imponibileprevidenziale", imponibileprevidenziale);
    }
    public BigDecimal getImponibileprevidenziale() {
        return (BigDecimal)readProperty("imponibileprevidenziale");
    }

    public void setImpostapagatasuanticipaz(BigDecimal impostapagatasuanticipaz) {
        writeProperty("impostapagatasuanticipaz", impostapagatasuanticipaz);
    }
    public BigDecimal getImpostapagatasuanticipaz() {
        return (BigDecimal)readProperty("impostapagatasuanticipaz");
    }

    public void setImpostasurivalutazione(BigDecimal impostasurivalutazione) {
        writeProperty("impostasurivalutazione", impostasurivalutazione);
    }
    public BigDecimal getImpostasurivalutazione() {
        return (BigDecimal)readProperty("impostasurivalutazione");
    }

    public void setIndicerivalutazione(BigDecimal indicerivalutazione) {
        writeProperty("indicerivalutazione", indicerivalutazione);
    }
    public BigDecimal getIndicerivalutazione() {
        return (BigDecimal)readProperty("indicerivalutazione");
    }

    public void setNorecalc(BigDecimal norecalc) {
        writeProperty("norecalc", norecalc);
    }
    public BigDecimal getNorecalc() {
        return (BigDecimal)readProperty("norecalc");
    }

    public void setOnerisociali(BigDecimal onerisociali) {
        writeProperty("onerisociali", onerisociali);
    }
    public BigDecimal getOnerisociali() {
        return (BigDecimal)readProperty("onerisociali");
    }

    public void setQuotetrasferite(BigDecimal quotetrasferite) {
        writeProperty("quotetrasferite", quotetrasferite);
    }
    public BigDecimal getQuotetrasferite() {
        return (BigDecimal)readProperty("quotetrasferite");
    }

    public void setRad(BigDecimal rad) {
        writeProperty("rad", rad);
    }
    public BigDecimal getRad() {
        return (BigDecimal)readProperty("rad");
    }

    public void setRivalutazlorda(BigDecimal rivalutazlorda) {
        writeProperty("rivalutazlorda", rivalutazlorda);
    }
    public BigDecimal getRivalutazlorda() {
        return (BigDecimal)readProperty("rivalutazlorda");
    }

    public void setTfrlordo(BigDecimal tfrlordo) {
        writeProperty("tfrlordo", tfrlordo);
    }
    public BigDecimal getTfrlordo() {
        return (BigDecimal)readProperty("tfrlordo");
    }

    public void setTfrnetto(BigDecimal tfrnetto) {
        writeProperty("tfrnetto", tfrnetto);
    }
    public BigDecimal getTfrnetto() {
        return (BigDecimal)readProperty("tfrnetto");
    }

    public void setUltimamodifica(Date ultimamodifica) {
        writeProperty("ultimamodifica", ultimamodifica);
    }
    public Date getUltimamodifica() {
        return (Date)readProperty("ultimamodifica");
    }

    public void setUltimamodificauser(String ultimamodificauser) {
        writeProperty("ultimamodificauser", ultimamodificauser);
    }
    public String getUltimamodificauser() {
        return (String)readProperty("ultimamodificauser");
    }

    public void setToLavoratore(Lavoratore toLavoratore) {
        setToOneTarget("toLavoratore", toLavoratore, true);
    }

    public Lavoratore getToLavoratore() {
        return (Lavoratore)readProperty("toLavoratore");
    }


}
