package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattorateovalore;
import it.iubar.paghe.logic.paghe.Posizionerateo;

/**
 * Class _Tiporateo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tiporateo extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPORATEO_PROPERTY = "idtiporateo";
    public static final String CONTRATTOVOCE_ARRAY_PROPERTY = "contrattovoceArray";
    public static final String POSIZIONERATEO_ARRAY_PROPERTY = "posizionerateoArray";

    public static final String IDTIPORATEO_PK_COLUMN = "IDTIPORATEO";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdtiporateo() {
        return (Short)readProperty("idtiporateo");
    }

    public void addToContrattovoceArray(Contrattorateovalore obj) {
        addToManyTarget("contrattovoceArray", obj, true);
    }
    public void removeFromContrattovoceArray(Contrattorateovalore obj) {
        removeToManyTarget("contrattovoceArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattorateovalore> getContrattovoceArray() {
        return (List<Contrattorateovalore>)readProperty("contrattovoceArray");
    }


    public void addToPosizionerateoArray(Posizionerateo obj) {
        addToManyTarget("posizionerateoArray", obj, true);
    }
    public void removeFromPosizionerateoArray(Posizionerateo obj) {
        removeToManyTarget("posizionerateoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionerateo> getPosizionerateoArray() {
        return (List<Posizionerateo>)readProperty("posizionerateoArray");
    }


}
