package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Tipolimite was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tipolimite extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOLIMITE_PROPERTY = "idtipolimite";

    public static final String IDTIPOLIMITE_PK_COLUMN = "IDTIPOLIMITE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdtipolimite() {
        return (Short)readProperty("idtipolimite");
    }

}
