package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

/** Class _Tipocedolino was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Tipocedolino extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOCEDOLINO_PROPERTY = "idtipocedolino";
    public static final String CEDOLINO_ARRAY_PROPERTY = "cedolinoArray";

    public static final String IDTIPOCEDOLINO_PK_COLUMN = "IDTIPOCEDOLINO";

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }
    
    
    public void setIdtipocedolino(Short idtipocedolino) {
        writeProperty("idtipocedolino", idtipocedolino);
    }
    public Short getIdtipocedolino() {
        return (Short)readProperty("idtipocedolino");
    }
    
    
    public void addToCedolinoArray(it.iubar.paghe.logic.paghe.Cedolino obj) {
        addToManyTarget("cedolinoArray", obj, true);
    }
    public void removeFromCedolinoArray(it.iubar.paghe.logic.paghe.Cedolino obj) {
        removeToManyTarget("cedolinoArray", obj, true);
    }
    public List getCedolinoArray() {
        return (List)readProperty("cedolinoArray");
    }
    
    
}
