package it.iubar.paghe.logic.presenze.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Lavoratore;
import it.iubar.paghe.logic.paghe.Contrattomaggiorazione;
import it.iubar.paghe.logic.paghe.InpsQualifica1;

/**
 * Class _Presenza was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Presenza extends CayenneDataObject {

    public static final String DATA_PROPERTY = "data";
    public static final String GIORNOINTERO_PROPERTY = "giornointero";
    public static final String IDCANTIERE_PROPERTY = "idcantiere";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDINPSQUALIFICA1_PROPERTY = "idinpsqualifica1";
    public static final String IDLAVORATORE_PROPERTY = "idlavoratore";
    public static final String IDMAGGIORAZIONE_PROPERTY = "idmaggiorazione";
    public static final String IDSEDEIMPRESA_PROPERTY = "idsedeimpresa";
    public static final String ORE_PROPERTY = "ore";
    public static final String TO_CONTRATTOMAGGIORAZIONE_PROPERTY = "toContrattomaggiorazione";
    public static final String TO_INPS_QUALIFICA1_PROPERTY = "toInpsQualifica1";
    public static final String TO_LAVORATORE_PROPERTY = "toLavoratore";

    public static final String DATA_PK_COLUMN = "DATA";
    public static final String IDLAVORATORE_PK_COLUMN = "IDLAVORATORE";
    public static final String IDMAGGIORAZIONE_PK_COLUMN = "IDMAGGIORAZIONE";

    public void setData(Date data) {
        writeProperty("data", data);
    }
    public Date getData() {
        return (Date)readProperty("data");
    }

    public void setGiornointero(Short giornointero) {
        writeProperty("giornointero", giornointero);
    }
    public Short getGiornointero() {
        return (Short)readProperty("giornointero");
    }

    public void setIdcantiere(Short idcantiere) {
        writeProperty("idcantiere", idcantiere);
    }
    public Short getIdcantiere() {
        return (Short)readProperty("idcantiere");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdinpsqualifica1(String idinpsqualifica1) {
        writeProperty("idinpsqualifica1", idinpsqualifica1);
    }
    public String getIdinpsqualifica1() {
        return (String)readProperty("idinpsqualifica1");
    }

    public void setIdlavoratore(Integer idlavoratore) {
        writeProperty("idlavoratore", idlavoratore);
    }
    public Integer getIdlavoratore() {
        return (Integer)readProperty("idlavoratore");
    }

    public void setIdmaggiorazione(Short idmaggiorazione) {
        writeProperty("idmaggiorazione", idmaggiorazione);
    }
    public Short getIdmaggiorazione() {
        return (Short)readProperty("idmaggiorazione");
    }

    public void setIdsedeimpresa(Short idsedeimpresa) {
        writeProperty("idsedeimpresa", idsedeimpresa);
    }
    public Short getIdsedeimpresa() {
        return (Short)readProperty("idsedeimpresa");
    }

    public void setOre(BigDecimal ore) {
        writeProperty("ore", ore);
    }
    public BigDecimal getOre() {
        return (BigDecimal)readProperty("ore");
    }

    public void setToContrattomaggiorazione(Contrattomaggiorazione toContrattomaggiorazione) {
        setToOneTarget("toContrattomaggiorazione", toContrattomaggiorazione, true);
    }

    public Contrattomaggiorazione getToContrattomaggiorazione() {
        return (Contrattomaggiorazione)readProperty("toContrattomaggiorazione");
    }


    public void setToInpsQualifica1(InpsQualifica1 toInpsQualifica1) {
        setToOneTarget("toInpsQualifica1", toInpsQualifica1, true);
    }

    public InpsQualifica1 getToInpsQualifica1() {
        return (InpsQualifica1)readProperty("toInpsQualifica1");
    }


    public void setToLavoratore(Lavoratore toLavoratore) {
        setToOneTarget("toLavoratore", toLavoratore, true);
    }

    public Lavoratore getToLavoratore() {
        return (Lavoratore)readProperty("toLavoratore");
    }


}
