package it.iubar.paghe.logic.presenze.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.ContrattoFestivita;
import it.iubar.paghe.logic.paghe.Contrattofestivitaretrib2;
import it.iubar.paghe.logic.presenze.Festivita;

/**
 * Class _Tipofestivita was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tipofestivita extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String DILEGGE_PROPERTY = "dilegge";
    public static final String IDTIPOFESTIVITA_PROPERTY = "idtipofestivita";
    public static final String NASCOSTO_PROPERTY = "nascosto";
    public static final String CONTRATTOFESTIVITA_ARRAY_PROPERTY = "contrattofestivitaArray";
    public static final String CONTRATTOFESTIVITARETRIB2ARRAY_PROPERTY = "contrattofestivitaretrib2Array";
    public static final String FESTIVITA_ARRAY_PROPERTY = "festivitaArray";

    public static final String IDTIPOFESTIVITA_PK_COLUMN = "IDTIPOFESTIVITA";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getDilegge() {
        return (Short)readProperty("dilegge");
    }

    public Short getIdtipofestivita() {
        return (Short)readProperty("idtipofestivita");
    }

    public Short getNascosto() {
        return (Short)readProperty("nascosto");
    }

    public void addToContrattofestivitaArray(ContrattoFestivita obj) {
        addToManyTarget("contrattofestivitaArray", obj, true);
    }
    public void removeFromContrattofestivitaArray(ContrattoFestivita obj) {
        removeToManyTarget("contrattofestivitaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContrattoFestivita> getContrattofestivitaArray() {
        return (List<ContrattoFestivita>)readProperty("contrattofestivitaArray");
    }


    public void addToContrattofestivitaretrib2Array(Contrattofestivitaretrib2 obj) {
        addToManyTarget("contrattofestivitaretrib2Array", obj, true);
    }
    public void removeFromContrattofestivitaretrib2Array(Contrattofestivitaretrib2 obj) {
        removeToManyTarget("contrattofestivitaretrib2Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattofestivitaretrib2> getContrattofestivitaretrib2Array() {
        return (List<Contrattofestivitaretrib2>)readProperty("contrattofestivitaretrib2Array");
    }


    public void addToFestivitaArray(Festivita obj) {
        addToManyTarget("festivitaArray", obj, true);
    }
    public void removeFromFestivitaArray(Festivita obj) {
        removeToManyTarget("festivitaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Festivita> getFestivitaArray() {
        return (List<Festivita>)readProperty("festivitaArray");
    }


}
