package it.iubar.paghe.logic.presenze.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Impresa;
import it.iubar.paghe.logic.anagrafica.Tipolavoratore2;
import it.iubar.paghe.logic.paghe.InpsQualifica1;
import it.iubar.paghe.logic.paghe.InpsQualifica2;
import it.iubar.paghe.logic.paghe.Posizionelavoratore;
import it.iubar.paghe.logic.paghe.Profilolavoratore;

/**
 * Class _Orario was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Orario extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String DOM_PROPERTY = "dom";
    public static final String GIO_PROPERTY = "gio";
    public static final String GIORNORIPOSO_PROPERTY = "giornoriposo";
    public static final String GIORNOZEROORE_PROPERTY = "giornozeroore";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDINPSQUALIFICA1_PROPERTY = "idinpsqualifica1";
    public static final String IDINPSQUALIFICA2_PROPERTY = "idinpsqualifica2";
    public static final String IDORARIO_PROPERTY = "idorario";
    public static final String IDTIPOLAVORATORE2_PROPERTY = "idtipolavoratore2";
    public static final String LUN_PROPERTY = "lun";
    public static final String MAR_PROPERTY = "mar";
    public static final String MER_PROPERTY = "mer";
    public static final String NOTE_PROPERTY = "note";
    public static final String OREANNO_PROPERTY = "oreanno";
    public static final String OREMESE_PROPERTY = "oremese";
    public static final String SAB_PROPERTY = "sab";
    public static final String VEN_PROPERTY = "ven";
    public static final String POSIZIONELAVORATORE_ARRAY_PROPERTY = "posizionelavoratoreArray";
    public static final String PROFILOLAVORATORE_ARRAY_PROPERTY = "profilolavoratoreArray";
    public static final String TO_IMPRESA_PROPERTY = "toImpresa";
    public static final String TO_INPSQUALIFICA1_PROPERTY = "toInpsqualifica1";
    public static final String TO_INPSQUALIFICA2_PROPERTY = "toInpsqualifica2";
    public static final String TO_TIPOLAVORATORE2_PROPERTY = "toTipolavoratore2";

    public static final String IDORARIO_PK_COLUMN = "IDORARIO";

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setDom(BigDecimal dom) {
        writeProperty("dom", dom);
    }
    public BigDecimal getDom() {
        return (BigDecimal)readProperty("dom");
    }

    public void setGio(BigDecimal gio) {
        writeProperty("gio", gio);
    }
    public BigDecimal getGio() {
        return (BigDecimal)readProperty("gio");
    }

    public void setGiornoriposo(Short giornoriposo) {
        writeProperty("giornoriposo", giornoriposo);
    }
    public Short getGiornoriposo() {
        return (Short)readProperty("giornoriposo");
    }

    public void setGiornozeroore(Short giornozeroore) {
        writeProperty("giornozeroore", giornozeroore);
    }
    public Short getGiornozeroore() {
        return (Short)readProperty("giornozeroore");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdinpsqualifica1(String idinpsqualifica1) {
        writeProperty("idinpsqualifica1", idinpsqualifica1);
    }
    public String getIdinpsqualifica1() {
        return (String)readProperty("idinpsqualifica1");
    }

    public void setIdinpsqualifica2(String idinpsqualifica2) {
        writeProperty("idinpsqualifica2", idinpsqualifica2);
    }
    public String getIdinpsqualifica2() {
        return (String)readProperty("idinpsqualifica2");
    }

    public void setIdorario(Integer idorario) {
        writeProperty("idorario", idorario);
    }
    public Integer getIdorario() {
        return (Integer)readProperty("idorario");
    }

    public void setIdtipolavoratore2(Short idtipolavoratore2) {
        writeProperty("idtipolavoratore2", idtipolavoratore2);
    }
    public Short getIdtipolavoratore2() {
        return (Short)readProperty("idtipolavoratore2");
    }

    public void setLun(BigDecimal lun) {
        writeProperty("lun", lun);
    }
    public BigDecimal getLun() {
        return (BigDecimal)readProperty("lun");
    }

    public void setMar(BigDecimal mar) {
        writeProperty("mar", mar);
    }
    public BigDecimal getMar() {
        return (BigDecimal)readProperty("mar");
    }

    public void setMer(BigDecimal mer) {
        writeProperty("mer", mer);
    }
    public BigDecimal getMer() {
        return (BigDecimal)readProperty("mer");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setOreanno(BigDecimal oreanno) {
        writeProperty("oreanno", oreanno);
    }
    public BigDecimal getOreanno() {
        return (BigDecimal)readProperty("oreanno");
    }

    public void setOremese(BigDecimal oremese) {
        writeProperty("oremese", oremese);
    }
    public BigDecimal getOremese() {
        return (BigDecimal)readProperty("oremese");
    }

    public void setSab(BigDecimal sab) {
        writeProperty("sab", sab);
    }
    public BigDecimal getSab() {
        return (BigDecimal)readProperty("sab");
    }

    public void setVen(BigDecimal ven) {
        writeProperty("ven", ven);
    }
    public BigDecimal getVen() {
        return (BigDecimal)readProperty("ven");
    }

    public void addToPosizionelavoratoreArray(Posizionelavoratore obj) {
        addToManyTarget("posizionelavoratoreArray", obj, true);
    }
    public void removeFromPosizionelavoratoreArray(Posizionelavoratore obj) {
        removeToManyTarget("posizionelavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionelavoratore> getPosizionelavoratoreArray() {
        return (List<Posizionelavoratore>)readProperty("posizionelavoratoreArray");
    }


    public void addToProfilolavoratoreArray(Profilolavoratore obj) {
        addToManyTarget("profilolavoratoreArray", obj, true);
    }
    public void removeFromProfilolavoratoreArray(Profilolavoratore obj) {
        removeToManyTarget("profilolavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profilolavoratore> getProfilolavoratoreArray() {
        return (List<Profilolavoratore>)readProperty("profilolavoratoreArray");
    }


    public void setToImpresa(Impresa toImpresa) {
        setToOneTarget("toImpresa", toImpresa, true);
    }

    public Impresa getToImpresa() {
        return (Impresa)readProperty("toImpresa");
    }


    public void setToInpsqualifica1(InpsQualifica1 toInpsqualifica1) {
        setToOneTarget("toInpsqualifica1", toInpsqualifica1, true);
    }

    public InpsQualifica1 getToInpsqualifica1() {
        return (InpsQualifica1)readProperty("toInpsqualifica1");
    }


    public void setToInpsqualifica2(InpsQualifica2 toInpsqualifica2) {
        setToOneTarget("toInpsqualifica2", toInpsqualifica2, true);
    }

    public InpsQualifica2 getToInpsqualifica2() {
        return (InpsQualifica2)readProperty("toInpsqualifica2");
    }


    public void setToTipolavoratore2(Tipolavoratore2 toTipolavoratore2) {
        setToOneTarget("toTipolavoratore2", toTipolavoratore2, true);
    }

    public Tipolavoratore2 getToTipolavoratore2() {
        return (Tipolavoratore2)readProperty("toTipolavoratore2");
    }


}
