package it.iubar.paghe.logic.common.auto;

/** Class _F24Ufficio was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _F24Ufficio extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String GRUPPO_PROPERTY = "gruppo";
    public static final String IDUFFICIO_PROPERTY = "idufficio";
    public static final String OGGETTO_PROPERTY = "oggetto";

    public static final String IDUFFICIO_PK_COLUMN = "IDUFFICIO";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }
    
    
    public String getGruppo() {
        return (String)readProperty("gruppo");
    }
    
    
    public String getIdufficio() {
        return (String)readProperty("idufficio");
    }
    
    
    public String getOggetto() {
        return (String)readProperty("oggetto");
    }
    
    
}
