package it.iubar.paghe.logic.common.auto;

/** Class _F24Tributoivaue was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _F24Tributoivaue extends org.apache.cayenne.CayenneDataObject {

    public static final String DATAA_PROPERTY = "dataa";
    public static final String DATADA_PROPERTY = "datada";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String RIFERIMENTO_PROPERTY = "riferimento";
    public static final String TIPO_PROPERTY = "tipo";
    public static final String TRIBUTO_PROPERTY = "tributo";

    public static final String TRIBUTO_PK_COLUMN = "TRIBUTO";

    public String getDataa() {
        return (String)readProperty("dataa");
    }
    
    
    public String getDatada() {
        return (String)readProperty("datada");
    }
    
    
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }
    
    
    public String getRiferimento() {
        return (String)readProperty("riferimento");
    }
    
    
    public String getTipo() {
        return (String)readProperty("tipo");
    }
    
    
    public String getTributo() {
        return (String)readProperty("tributo");
    }
    
    
}
