package it.iubar.paghe.logic.common.auto;

import java.util.List;

/** Class _Helpcontestualelivello2 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Helpcontestualelivello2 extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDLIVELLO1_PROPERTY = "idlivello1";
    public static final String IDLIVELLO2_PROPERTY = "idlivello2";
    public static final String HELPCONTESTUALE_ARRAY_PROPERTY = "helpcontestualeArray";
    public static final String TO_HELPCONTESTUALELIV1_PROPERTY = "toHelpcontestualeliv1";

    public static final String IDLIVELLO1_PK_COLUMN = "IDLIVELLO1";
    public static final String IDLIVELLO2_PK_COLUMN = "IDLIVELLO2";

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }
    
    
    public void setIdlivello1(Short idlivello1) {
        writeProperty("idlivello1", idlivello1);
    }
    public Short getIdlivello1() {
        return (Short)readProperty("idlivello1");
    }
    
    
    public void setIdlivello2(Short idlivello2) {
        writeProperty("idlivello2", idlivello2);
    }
    public Short getIdlivello2() {
        return (Short)readProperty("idlivello2");
    }
    
    
    public void addToHelpcontestualeArray(it.iubar.paghe.logic.common.Helpcontestuale obj) {
        addToManyTarget("helpcontestualeArray", obj, true);
    }
    public void removeFromHelpcontestualeArray(it.iubar.paghe.logic.common.Helpcontestuale obj) {
        removeToManyTarget("helpcontestualeArray", obj, true);
    }
    public List getHelpcontestualeArray() {
        return (List)readProperty("helpcontestualeArray");
    }
    
    
    public void setToHelpcontestualeliv1(it.iubar.paghe.logic.common.Helpcontestualelivello1 toHelpcontestualeliv1) {
        setToOneTarget("toHelpcontestualeliv1", toHelpcontestualeliv1, true);
    }

    public it.iubar.paghe.logic.common.Helpcontestualelivello1 getToHelpcontestualeliv1() {
        return (it.iubar.paghe.logic.common.Helpcontestualelivello1)readProperty("toHelpcontestualeliv1");
    } 
    
    
}
