package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Cantiere;

/**
 * Class _CnceSituazionecantiere was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CnceSituazionecantiere extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDSITUAZIONE_PROPERTY = "idsituazione";
    public static final String CANTIERE_ARRAY_PROPERTY = "cantiereArray";

    public static final String IDSITUAZIONE_PK_COLUMN = "IDSITUAZIONE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdsituazione() {
        return (Short)readProperty("idsituazione");
    }

    public void addToCantiereArray(Cantiere obj) {
        addToManyTarget("cantiereArray", obj, true);
    }
    public void removeFromCantiereArray(Cantiere obj) {
        removeToManyTarget("cantiereArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cantiere> getCantiereArray() {
        return (List<Cantiere>)readProperty("cantiereArray");
    }


}
