package it.iubar.paghe.logic.anagrafica.auto;

/** Class _ImpresaPat was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _ImpresaPat extends org.apache.cayenne.CayenneDataObject {

    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDPAT_PROPERTY = "idpat";
    public static final String IDSEDEIMPRESA_PROPERTY = "idsedeimpresa";
    public static final String TO_IMPRESA_PROPERTY = "toImpresa";
    public static final String TO_PAT_PROPERTY = "toPat";
    public static final String TO_SEDEIMPRESA_PROPERTY = "toSedeimpresa";

    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";
    public static final String IDPAT_PK_COLUMN = "IDPAT";
    public static final String IDSEDEIMPRESA_PK_COLUMN = "IDSEDEIMPRESA";

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }
    
    
    public void setIdpat(String idpat) {
        writeProperty("idpat", idpat);
    }
    public String getIdpat() {
        return (String)readProperty("idpat");
    }
    
    
    public void setIdsedeimpresa(Short idsedeimpresa) {
        writeProperty("idsedeimpresa", idsedeimpresa);
    }
    public Short getIdsedeimpresa() {
        return (Short)readProperty("idsedeimpresa");
    }
    
    
    public void setToImpresa(it.iubar.paghe.logic.anagrafica.Impresa toImpresa) {
        setToOneTarget("toImpresa", toImpresa, true);
    }

    public it.iubar.paghe.logic.anagrafica.Impresa getToImpresa() {
        return (it.iubar.paghe.logic.anagrafica.Impresa)readProperty("toImpresa");
    } 
    
    
    public void setToPat(it.iubar.paghe.logic.anagrafica.Pat toPat) {
        setToOneTarget("toPat", toPat, true);
    }

    public it.iubar.paghe.logic.anagrafica.Pat getToPat() {
        return (it.iubar.paghe.logic.anagrafica.Pat)readProperty("toPat");
    } 
    
    
    public void setToSedeimpresa(it.iubar.paghe.logic.anagrafica.Sedeimpresa toSedeimpresa) {
        setToOneTarget("toSedeimpresa", toSedeimpresa, true);
    }

    public it.iubar.paghe.logic.anagrafica.Sedeimpresa getToSedeimpresa() {
        return (it.iubar.paghe.logic.anagrafica.Sedeimpresa)readProperty("toSedeimpresa");
    } 
    
    
}
