package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.IstatAtecocategoria1;

/**
 * Class _IstatAtecocategoria2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IstatAtecocategoria2 extends CayenneDataObject {

    public static final String ATECOVERSIONE2_PROPERTY = "atecoversione2";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDCATEGORIA2_PROPERTY = "idcategoria2";
    public static final String CATEGORIA1ARRAY_PROPERTY = "categoria1Array";

    public static final String ATECOVERSIONE2_PK_COLUMN = "ATECOVERSIONE2";
    public static final String IDCATEGORIA2_PK_COLUMN = "IDCATEGORIA2";

    public Short getAtecoversione2() {
        return (Short)readProperty("atecoversione2");
    }

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdcategoria2() {
        return (String)readProperty("idcategoria2");
    }

    public void addToCategoria1Array(IstatAtecocategoria1 obj) {
        addToManyTarget("categoria1Array", obj, true);
    }
    public void removeFromCategoria1Array(IstatAtecocategoria1 obj) {
        removeToManyTarget("categoria1Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<IstatAtecocategoria1> getCategoria1Array() {
        return (List<IstatAtecocategoria1>)readProperty("categoria1Array");
    }


}
