package it.iubar.paghe.logic.anagrafica.auto;

/** Class _IstatTipovoceprof was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _IstatTipovoceprof extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOVOCEPROF_PROPERTY = "idtipovoceprof";
    public static final String VERSIONEVOCEPROF_PROPERTY = "versionevoceprof";

    public static final String IDTIPOVOCEPROF_PK_COLUMN = "IDTIPOVOCEPROF";
    public static final String VERSIONEVOCEPROF_PK_COLUMN = "VERSIONEVOCEPROF";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }
    
    
    public String getIdtipovoceprof() {
        return (String)readProperty("idtipovoceprof");
    }
    
    
    public Short getVersionevoceprof() {
        return (Short)readProperty("versionevoceprof");
    }
    
    
}
