package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Impresa;
import it.iubar.paghe.logic.anagrafica.IstatAtecocategoria1;
import it.iubar.paghe.logic.anagrafica.Personagiuridica;
import it.iubar.paghe.logic.anagrafica.Sedeimpresa;

/**
 * Class _IstatAteco was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IstatAteco extends CayenneDataObject {

    public static final String ATECOVERSIONE_PROPERTY = "atecoversione";
    public static final String ATECOVERSIONE1_PROPERTY = "atecoversione1";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDATECO_PROPERTY = "idateco";
    public static final String IDCATEGORIA1_PROPERTY = "idcategoria1";
    public static final String IMPRESA_ARRAY_PROPERTY = "impresaArray";
    public static final String PERSONAGIURIDICA_ARRAY_PROPERTY = "personagiuridicaArray";
    public static final String SEDEIMPRESA_ARRAY_PROPERTY = "sedeimpresaArray";
    public static final String TO_CATEGORIA1_PROPERTY = "toCategoria1";

    public static final String ATECOVERSIONE_PK_COLUMN = "ATECOVERSIONE";
    public static final String IDATECO_PK_COLUMN = "IDATECO";

    public Short getAtecoversione() {
        return (Short)readProperty("atecoversione");
    }

    public Short getAtecoversione1() {
        return (Short)readProperty("atecoversione1");
    }

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdateco() {
        return (String)readProperty("idateco");
    }

    public String getIdcategoria1() {
        return (String)readProperty("idcategoria1");
    }

    public void addToImpresaArray(Impresa obj) {
        addToManyTarget("impresaArray", obj, true);
    }
    public void removeFromImpresaArray(Impresa obj) {
        removeToManyTarget("impresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Impresa> getImpresaArray() {
        return (List<Impresa>)readProperty("impresaArray");
    }


    public void addToPersonagiuridicaArray(Personagiuridica obj) {
        addToManyTarget("personagiuridicaArray", obj, true);
    }
    public void removeFromPersonagiuridicaArray(Personagiuridica obj) {
        removeToManyTarget("personagiuridicaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Personagiuridica> getPersonagiuridicaArray() {
        return (List<Personagiuridica>)readProperty("personagiuridicaArray");
    }


    public void addToSedeimpresaArray(Sedeimpresa obj) {
        addToManyTarget("sedeimpresaArray", obj, true);
    }
    public void removeFromSedeimpresaArray(Sedeimpresa obj) {
        removeToManyTarget("sedeimpresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Sedeimpresa> getSedeimpresaArray() {
        return (List<Sedeimpresa>)readProperty("sedeimpresaArray");
    }



    public IstatAtecocategoria1 getToCategoria1() {
        return (IstatAtecocategoria1)readProperty("toCategoria1");
    }


}
