package it.iubar.paghe.logic.anagrafica.auto;

/** Class _LavoratoreCentrodicosto was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _LavoratoreCentrodicosto extends org.apache.cayenne.CayenneDataObject {

    public static final String ASSUNZIONEDATA_PROPERTY = "assunzionedata";
    public static final String DECORRENZA_PROPERTY = "decorrenza";
    public static final String IDCENTRODICOSTO_PROPERTY = "idcentrodicosto";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDSOGGETTO_PROPERTY = "idsoggetto";
    public static final String PERCENTUALE_PROPERTY = "percentuale";
    public static final String TO_LAVORATORE_PROPERTY = "toLavoratore";

    public static final String ASSUNZIONEDATA_PK_COLUMN = "ASSUNZIONEDATA";
    public static final String IDCENTRODICOSTO_PK_COLUMN = "IDCENTRODICOSTO";
    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";
    public static final String IDSOGGETTO_PK_COLUMN = "IDSOGGETTO";
    public static final String PERCENTUALE_PK_COLUMN = "PERCENTUALE";

    public void setAssunzionedata(java.util.Date assunzionedata) {
        writeProperty("assunzionedata", assunzionedata);
    }
    public java.util.Date getAssunzionedata() {
        return (java.util.Date)readProperty("assunzionedata");
    }
    
    
    public void setDecorrenza(java.util.Date decorrenza) {
        writeProperty("decorrenza", decorrenza);
    }
    public java.util.Date getDecorrenza() {
        return (java.util.Date)readProperty("decorrenza");
    }
    
    
    public void setIdcentrodicosto(Short idcentrodicosto) {
        writeProperty("idcentrodicosto", idcentrodicosto);
    }
    public Short getIdcentrodicosto() {
        return (Short)readProperty("idcentrodicosto");
    }
    
    
    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }
    
    
    public void setIdsoggetto(Integer idsoggetto) {
        writeProperty("idsoggetto", idsoggetto);
    }
    public Integer getIdsoggetto() {
        return (Integer)readProperty("idsoggetto");
    }
    
    
    public void setPercentuale(java.math.BigDecimal percentuale) {
        writeProperty("percentuale", percentuale);
    }
    public java.math.BigDecimal getPercentuale() {
        return (java.math.BigDecimal)readProperty("percentuale");
    }
    
    
    public void setToLavoratore(it.iubar.paghe.logic.anagrafica.Lavoratore toLavoratore) {
        setToOneTarget("toLavoratore", toLavoratore, true);
    }

    public it.iubar.paghe.logic.anagrafica.Lavoratore getToLavoratore() {
        return (it.iubar.paghe.logic.anagrafica.Lavoratore)readProperty("toLavoratore");
    } 
    
    
}
