package it.iubar.paghe.logic.anagrafica.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Lavoratore;
import it.iubar.paghe.logic.paghe.InailAliquota;
import it.iubar.paghe.logic.paghe.InpsAliquotacollaboratore;
import it.iubar.paghe.logic.paghe.InpsAltreass;
import it.iubar.paghe.logic.paghe.InpsAttivita;
import it.iubar.paghe.logic.paghe.InpsCalamita;
import it.iubar.paghe.logic.paghe.InpsCertificazione;
import it.iubar.paghe.logic.paghe.InpsTiporapporto;

/**
 * Class _Parasubordinato was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Parasubordinato extends CayenneDataObject {

    public static final String IDINAILALIQUOTA_PROPERTY = "idinailaliquota";
    public static final String IDINPSALIQUOTA_PROPERTY = "idinpsaliquota";
    public static final String IDINPSALTREASS_PROPERTY = "idinpsaltreass";
    public static final String IDINPSATTIVITA_PROPERTY = "idinpsattivita";
    public static final String IDINPSCALAMITA_PROPERTY = "idinpscalamita";
    public static final String IDINPSCERTIFICAZIONE_PROPERTY = "idinpscertificazione";
    public static final String IDINPSTIPORAPPORTO_PROPERTY = "idinpstiporapporto";
    public static final String IDLAVORATORE_PROPERTY = "idlavoratore";
    public static final String INAILALIQUOTAANNO_PROPERTY = "inailaliquotaanno";
    public static final String INPSALIQUOTAANNO_PROPERTY = "inpsaliquotaanno";
    public static final String ISCRITTOGESTIONESEPARATA_PROPERTY = "iscrittogestioneseparata";
    public static final String PERIODOAL_PROPERTY = "periodoal";
    public static final String PERIODODAL_PROPERTY = "periododal";
    public static final String TO_INAIL_ALIQUOTA_PROPERTY = "toInailAliquota";
    public static final String TO_INPS_ALIQUOTA_PROPERTY = "toInpsAliquota";
    public static final String TO_INPS_ALTREASS_PROPERTY = "toInpsAltreass";
    public static final String TO_INPS_ATTIVITA_PROPERTY = "toInpsAttivita";
    public static final String TO_INPS_CALAMITA_PROPERTY = "toInpsCalamita";
    public static final String TO_INPS_CERTIFICAZIONE_PROPERTY = "toInpsCertificazione";
    public static final String TO_INPS_TIPORAPPORTO_PROPERTY = "toInpsTiporapporto";
    public static final String TO_LAVORATORE_PROPERTY = "toLavoratore";

    public static final String IDLAVORATORE_PK_COLUMN = "IDLAVORATORE";

    public void setIdinailaliquota(Short idinailaliquota) {
        writeProperty("idinailaliquota", idinailaliquota);
    }
    public Short getIdinailaliquota() {
        return (Short)readProperty("idinailaliquota");
    }

    public void setIdinpsaliquota(String idinpsaliquota) {
        writeProperty("idinpsaliquota", idinpsaliquota);
    }
    public String getIdinpsaliquota() {
        return (String)readProperty("idinpsaliquota");
    }

    public void setIdinpsaltreass(String idinpsaltreass) {
        writeProperty("idinpsaltreass", idinpsaltreass);
    }
    public String getIdinpsaltreass() {
        return (String)readProperty("idinpsaltreass");
    }

    public void setIdinpsattivita(String idinpsattivita) {
        writeProperty("idinpsattivita", idinpsattivita);
    }
    public String getIdinpsattivita() {
        return (String)readProperty("idinpsattivita");
    }

    public void setIdinpscalamita(String idinpscalamita) {
        writeProperty("idinpscalamita", idinpscalamita);
    }
    public String getIdinpscalamita() {
        return (String)readProperty("idinpscalamita");
    }

    public void setIdinpscertificazione(String idinpscertificazione) {
        writeProperty("idinpscertificazione", idinpscertificazione);
    }
    public String getIdinpscertificazione() {
        return (String)readProperty("idinpscertificazione");
    }

    public void setIdinpstiporapporto(String idinpstiporapporto) {
        writeProperty("idinpstiporapporto", idinpstiporapporto);
    }
    public String getIdinpstiporapporto() {
        return (String)readProperty("idinpstiporapporto");
    }

    public void setIdlavoratore(Integer idlavoratore) {
        writeProperty("idlavoratore", idlavoratore);
    }
    public Integer getIdlavoratore() {
        return (Integer)readProperty("idlavoratore");
    }

    public void setInailaliquotaanno(Integer inailaliquotaanno) {
        writeProperty("inailaliquotaanno", inailaliquotaanno);
    }
    public Integer getInailaliquotaanno() {
        return (Integer)readProperty("inailaliquotaanno");
    }

    public void setInpsaliquotaanno(Integer inpsaliquotaanno) {
        writeProperty("inpsaliquotaanno", inpsaliquotaanno);
    }
    public Integer getInpsaliquotaanno() {
        return (Integer)readProperty("inpsaliquotaanno");
    }

    public void setIscrittogestioneseparata(Short iscrittogestioneseparata) {
        writeProperty("iscrittogestioneseparata", iscrittogestioneseparata);
    }
    public Short getIscrittogestioneseparata() {
        return (Short)readProperty("iscrittogestioneseparata");
    }

    public void setPeriodoal(Date periodoal) {
        writeProperty("periodoal", periodoal);
    }
    public Date getPeriodoal() {
        return (Date)readProperty("periodoal");
    }

    public void setPeriododal(Date periododal) {
        writeProperty("periododal", periododal);
    }
    public Date getPeriododal() {
        return (Date)readProperty("periododal");
    }

    public void setToInailAliquota(InailAliquota toInailAliquota) {
        setToOneTarget("toInailAliquota", toInailAliquota, true);
    }

    public InailAliquota getToInailAliquota() {
        return (InailAliquota)readProperty("toInailAliquota");
    }


    public void setToInpsAliquota(InpsAliquotacollaboratore toInpsAliquota) {
        setToOneTarget("toInpsAliquota", toInpsAliquota, true);
    }

    public InpsAliquotacollaboratore getToInpsAliquota() {
        return (InpsAliquotacollaboratore)readProperty("toInpsAliquota");
    }


    public void setToInpsAltreass(InpsAltreass toInpsAltreass) {
        setToOneTarget("toInpsAltreass", toInpsAltreass, true);
    }

    public InpsAltreass getToInpsAltreass() {
        return (InpsAltreass)readProperty("toInpsAltreass");
    }


    public void setToInpsAttivita(InpsAttivita toInpsAttivita) {
        setToOneTarget("toInpsAttivita", toInpsAttivita, true);
    }

    public InpsAttivita getToInpsAttivita() {
        return (InpsAttivita)readProperty("toInpsAttivita");
    }


    public void setToInpsCalamita(InpsCalamita toInpsCalamita) {
        setToOneTarget("toInpsCalamita", toInpsCalamita, true);
    }

    public InpsCalamita getToInpsCalamita() {
        return (InpsCalamita)readProperty("toInpsCalamita");
    }


    public void setToInpsCertificazione(InpsCertificazione toInpsCertificazione) {
        setToOneTarget("toInpsCertificazione", toInpsCertificazione, true);
    }

    public InpsCertificazione getToInpsCertificazione() {
        return (InpsCertificazione)readProperty("toInpsCertificazione");
    }


    public void setToInpsTiporapporto(InpsTiporapporto toInpsTiporapporto) {
        setToOneTarget("toInpsTiporapporto", toInpsTiporapporto, true);
    }

    public InpsTiporapporto getToInpsTiporapporto() {
        return (InpsTiporapporto)readProperty("toInpsTiporapporto");
    }


    public void setToLavoratore(Lavoratore toLavoratore) {
        setToOneTarget("toLavoratore", toLavoratore, true);
    }

    public Lavoratore getToLavoratore() {
        return (Lavoratore)readProperty("toLavoratore");
    }


}
