package it.iubar.paghe.logic.anagrafica.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.AeNaturagiuridica;
import it.iubar.paghe.logic.anagrafica.Anagrafica;
import it.iubar.paghe.logic.anagrafica.Contatto;
import it.iubar.paghe.logic.anagrafica.Entepubblico;
import it.iubar.paghe.logic.anagrafica.Indirizzo;
import it.iubar.paghe.logic.anagrafica.IstatAteco;
import it.iubar.paghe.logic.anagrafica.Personafisica;
import it.iubar.paghe.logic.anagrafica.Tipopersonagiuridica;

/**
 * Class _Personagiuridica was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Personagiuridica extends CayenneDataObject {

    public static final String ATECOVERSIONE_PROPERTY = "atecoversione";
    public static final String CF_PROPERTY = "cf";
    public static final String COSTITUZIONEDATA_PROPERTY = "costituzionedata";
    public static final String EMAIL_PROPERTY = "email";
    public static final String FAX_PROPERTY = "fax";
    public static final String IDANAGAFICA_PROPERTY = "idanagafica";
    public static final String IDATECO_PROPERTY = "idateco";
    public static final String IDINDIRIZZOLEGALE_PROPERTY = "idindirizzolegale";
    public static final String IDLEGALERAPP_PROPERTY = "idlegalerapp";
    public static final String IDNATURAGIURIDICA_PROPERTY = "idnaturagiuridica";
    public static final String IDTIPOPERSONAGIURIDICA_PROPERTY = "idtipopersonagiuridica";
    public static final String PEC_PROPERTY = "pec";
    public static final String PIVA_PROPERTY = "piva";
    public static final String RAGIONESOCIALE_PROPERTY = "ragionesociale";
    public static final String TEL_PROPERTY = "tel";
    public static final String WEB_PROPERTY = "web";
    public static final String ENTEPUBBLICO_ARRAY_PROPERTY = "entepubblicoArray";
    public static final String TO_ANAGRAFICA_PROPERTY = "toAnagrafica";
    public static final String TO_ATECO_PROPERTY = "toAteco";
    public static final String TO_CONTATTO_PROPERTY = "toContatto";
    public static final String TO_INDIRIZZOSEDELEGALE_PROPERTY = "toIndirizzosedelegale";
    public static final String TO_LEGALERAPP_PROPERTY = "toLegalerapp";
    public static final String TO_NATURAGIURIDICA_PROPERTY = "toNaturagiuridica";
    public static final String TO_PERSONAFISICA_PROPERTY = "toPersonafisica";
    public static final String TO_TIPO_PROPERTY = "toTipo";

    public static final String IDANAGRAFICA_PK_COLUMN = "IDANAGRAFICA";

    public void setAtecoversione(Short atecoversione) {
        writeProperty("atecoversione", atecoversione);
    }
    public Short getAtecoversione() {
        return (Short)readProperty("atecoversione");
    }

    public void setCf(String cf) {
        writeProperty("cf", cf);
    }
    public String getCf() {
        return (String)readProperty("cf");
    }

    public void setCostituzionedata(Date costituzionedata) {
        writeProperty("costituzionedata", costituzionedata);
    }
    public Date getCostituzionedata() {
        return (Date)readProperty("costituzionedata");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setFax(String fax) {
        writeProperty("fax", fax);
    }
    public String getFax() {
        return (String)readProperty("fax");
    }

    public void setIdanagafica(Integer idanagafica) {
        writeProperty("idanagafica", idanagafica);
    }
    public Integer getIdanagafica() {
        return (Integer)readProperty("idanagafica");
    }

    public void setIdateco(String idateco) {
        writeProperty("idateco", idateco);
    }
    public String getIdateco() {
        return (String)readProperty("idateco");
    }

    public void setIdindirizzolegale(Integer idindirizzolegale) {
        writeProperty("idindirizzolegale", idindirizzolegale);
    }
    public Integer getIdindirizzolegale() {
        return (Integer)readProperty("idindirizzolegale");
    }

    public void setIdlegalerapp(Integer idlegalerapp) {
        writeProperty("idlegalerapp", idlegalerapp);
    }
    public Integer getIdlegalerapp() {
        return (Integer)readProperty("idlegalerapp");
    }

    public void setIdnaturagiuridica(Short idnaturagiuridica) {
        writeProperty("idnaturagiuridica", idnaturagiuridica);
    }
    public Short getIdnaturagiuridica() {
        return (Short)readProperty("idnaturagiuridica");
    }

    public void setIdtipopersonagiuridica(Short idtipopersonagiuridica) {
        writeProperty("idtipopersonagiuridica", idtipopersonagiuridica);
    }
    public Short getIdtipopersonagiuridica() {
        return (Short)readProperty("idtipopersonagiuridica");
    }

    public void setPec(String pec) {
        writeProperty("pec", pec);
    }
    public String getPec() {
        return (String)readProperty("pec");
    }

    public void setPiva(String piva) {
        writeProperty("piva", piva);
    }
    public String getPiva() {
        return (String)readProperty("piva");
    }

    public void setRagionesociale(String ragionesociale) {
        writeProperty("ragionesociale", ragionesociale);
    }
    public String getRagionesociale() {
        return (String)readProperty("ragionesociale");
    }

    public void setTel(String tel) {
        writeProperty("tel", tel);
    }
    public String getTel() {
        return (String)readProperty("tel");
    }

    public void setWeb(String web) {
        writeProperty("web", web);
    }
    public String getWeb() {
        return (String)readProperty("web");
    }

    public void addToEntepubblicoArray(Entepubblico obj) {
        addToManyTarget("entepubblicoArray", obj, true);
    }
    public void removeFromEntepubblicoArray(Entepubblico obj) {
        removeToManyTarget("entepubblicoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Entepubblico> getEntepubblicoArray() {
        return (List<Entepubblico>)readProperty("entepubblicoArray");
    }


    public void setToAnagrafica(Anagrafica toAnagrafica) {
        setToOneTarget("toAnagrafica", toAnagrafica, true);
    }

    public Anagrafica getToAnagrafica() {
        return (Anagrafica)readProperty("toAnagrafica");
    }


    public void setToAteco(IstatAteco toAteco) {
        setToOneTarget("toAteco", toAteco, true);
    }

    public IstatAteco getToAteco() {
        return (IstatAteco)readProperty("toAteco");
    }


    public void setToContatto(Contatto toContatto) {
        setToOneTarget("toContatto", toContatto, true);
    }

    public Contatto getToContatto() {
        return (Contatto)readProperty("toContatto");
    }


    public void setToIndirizzosedelegale(Indirizzo toIndirizzosedelegale) {
        setToOneTarget("toIndirizzosedelegale", toIndirizzosedelegale, true);
    }

    public Indirizzo getToIndirizzosedelegale() {
        return (Indirizzo)readProperty("toIndirizzosedelegale");
    }


    public void setToLegalerapp(Personafisica toLegalerapp) {
        setToOneTarget("toLegalerapp", toLegalerapp, true);
    }

    public Personafisica getToLegalerapp() {
        return (Personafisica)readProperty("toLegalerapp");
    }


    public void setToNaturagiuridica(AeNaturagiuridica toNaturagiuridica) {
        setToOneTarget("toNaturagiuridica", toNaturagiuridica, true);
    }

    public AeNaturagiuridica getToNaturagiuridica() {
        return (AeNaturagiuridica)readProperty("toNaturagiuridica");
    }


    public void setToPersonafisica(Personafisica toPersonafisica) {
        setToOneTarget("toPersonafisica", toPersonafisica, true);
    }

    public Personafisica getToPersonafisica() {
        return (Personafisica)readProperty("toPersonafisica");
    }


    public void setToTipo(Tipopersonagiuridica toTipo) {
        setToOneTarget("toTipo", toTipo, true);
    }

    public Tipopersonagiuridica getToTipo() {
        return (Tipopersonagiuridica)readProperty("toTipo");
    }


}
