package it.iubar.paghe.logic.anagrafica.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Anagrafica;
import it.iubar.paghe.logic.anagrafica.Comune;
import it.iubar.paghe.logic.anagrafica.Contatto;
import it.iubar.paghe.logic.anagrafica.Extrace;
import it.iubar.paghe.logic.anagrafica.Indirizzo;
import it.iubar.paghe.logic.anagrafica.IstatTitolostudio;
import it.iubar.paghe.logic.anagrafica.Lavoratore;
import it.iubar.paghe.logic.anagrafica.Parentela;
import it.iubar.paghe.logic.anagrafica.Personagiuridica;
import it.iubar.paghe.logic.anagrafica.Posizionebancaria;
import it.iubar.paghe.logic.anagrafica.Sesso;
import it.iubar.paghe.logic.anagrafica.Socio;
import it.iubar.paghe.logic.anagrafica.Statocivile;
import it.iubar.paghe.logic.anagrafica.Statoestero;
import it.iubar.paghe.logic.anagrafica.Tipodatore;
import it.iubar.paghe.logic.anagrafica.Tipooccupazione;
import it.iubar.paghe.logic.anagrafica.Tipopersonafisica;
import it.iubar.paghe.logic.anagrafica.Utente;
import it.iubar.paghe.logic.paghe.Posizionefamiliare;

/**
 * Class _Personafisica was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Personafisica extends CayenneDataObject {

    public static final String CELL_PROPERTY = "cell";
    public static final String CF_PROPERTY = "cf";
    public static final String COGNOME_PROPERTY = "cognome";
    public static final String DISABILE_PROPERTY = "disabile";
    public static final String DISABILEPERCENTUALE_PROPERTY = "disabilepercentuale";
    public static final String EMAIL_PROPERTY = "email";
    public static final String FAX_PROPERTY = "fax";
    public static final String IDANAGRAFICA_PROPERTY = "idanagrafica";
    public static final String IDPOSIZIONEBANCARIA_PROPERTY = "idposizionebancaria";
    public static final String IDTIPOOCCUPAZIONE_PROPERTY = "idtipooccupazione";
    public static final String NASCITADATA_PROPERTY = "nascitadata";
    public static final String NASCOSTO_PROPERTY = "nascosto";
    public static final String NOME_PROPERTY = "nome";
    public static final String ORFANO_PROPERTY = "orfano";
    public static final String PENSIONESUPERSTITI_PROPERTY = "pensionesuperstiti";
    public static final String TEL_PROPERTY = "tel";
    public static final String LAVORATORE_ARRAY_PROPERTY = "lavoratoreArray";
    public static final String LEGALEPERSONAGIURIDICA_ARRAY_PROPERTY = "legalepersonagiuridicaArray";
    public static final String PARENTELA_ARRAY1_PROPERTY = "parentelaArray1";
    public static final String PARENTELA_ARRAY2_PROPERTY = "parentelaArray2";
    public static final String PERSONAGIURIDICA_ARRAY_PROPERTY = "personagiuridicaArray";
    public static final String POSIZIONEFAMILIARE_ARRAY_PROPERTY = "posizionefamiliareArray";
    public static final String SOCIO_ARRAY_PROPERTY = "socioArray";
    public static final String TO_ANAGRAFICA_PROPERTY = "toAnagrafica";
    public static final String TO_CITTADINANZA_PROPERTY = "toCittadinanza";
    public static final String TO_COMUNE_NASCITA_PROPERTY = "toComuneNascita";
    public static final String TO_CONTATTO_PROPERTY = "toContatto";
    public static final String TO_EXTRA_CE_PROPERTY = "toExtraCe";
    public static final String TO_INDIRIZZODOMICILIO_PROPERTY = "toIndirizzodomicilio";
    public static final String TO_INDIRIZZORESIDENZA_PROPERTY = "toIndirizzoresidenza";
    public static final String TO_ISTAT_TITOLOSTUDIO_PROPERTY = "toIstatTitolostudio";
    public static final String TO_POSIZIONEBANCARIA_PROPERTY = "toPosizionebancaria";
    public static final String TO_SESSO_PROPERTY = "toSesso";
    public static final String TO_STATO_NASCITA_PROPERTY = "toStatoNascita";
    public static final String TO_STATOCIVILE_PROPERTY = "toStatocivile";
    public static final String TO_TIPO_PROPERTY = "toTipo";
    public static final String TO_TIPO_DATORE_PROPERTY = "toTipoDatore";
    public static final String TO_TIPO_OCCUPAZIONE_PROPERTY = "toTipoOccupazione";
    public static final String TO_UTENTE_PROPERTY = "toUtente";

    public static final String IDANAGRAFICA_PK_COLUMN = "IDANAGRAFICA";

    public void setCell(String cell) {
        writeProperty("cell", cell);
    }
    public String getCell() {
        return (String)readProperty("cell");
    }

    public void setCf(String cf) {
        writeProperty("cf", cf);
    }
    public String getCf() {
        return (String)readProperty("cf");
    }

    public void setCognome(String cognome) {
        writeProperty("cognome", cognome);
    }
    public String getCognome() {
        return (String)readProperty("cognome");
    }

    public void setDisabile(Short disabile) {
        writeProperty("disabile", disabile);
    }
    public Short getDisabile() {
        return (Short)readProperty("disabile");
    }

    public void setDisabilepercentuale(BigDecimal disabilepercentuale) {
        writeProperty("disabilepercentuale", disabilepercentuale);
    }
    public BigDecimal getDisabilepercentuale() {
        return (BigDecimal)readProperty("disabilepercentuale");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setFax(String fax) {
        writeProperty("fax", fax);
    }
    public String getFax() {
        return (String)readProperty("fax");
    }

    public void setIdanagrafica(Integer idanagrafica) {
        writeProperty("idanagrafica", idanagrafica);
    }
    public Integer getIdanagrafica() {
        return (Integer)readProperty("idanagrafica");
    }

    public void setIdposizionebancaria(Integer idposizionebancaria) {
        writeProperty("idposizionebancaria", idposizionebancaria);
    }
    public Integer getIdposizionebancaria() {
        return (Integer)readProperty("idposizionebancaria");
    }

    public void setIdtipooccupazione(Short idtipooccupazione) {
        writeProperty("idtipooccupazione", idtipooccupazione);
    }
    public Short getIdtipooccupazione() {
        return (Short)readProperty("idtipooccupazione");
    }

    public void setNascitadata(Date nascitadata) {
        writeProperty("nascitadata", nascitadata);
    }
    public Date getNascitadata() {
        return (Date)readProperty("nascitadata");
    }

    public void setNascosto(Short nascosto) {
        writeProperty("nascosto", nascosto);
    }
    public Short getNascosto() {
        return (Short)readProperty("nascosto");
    }

    public void setNome(String nome) {
        writeProperty("nome", nome);
    }
    public String getNome() {
        return (String)readProperty("nome");
    }

    public void setOrfano(Short orfano) {
        writeProperty("orfano", orfano);
    }
    public Short getOrfano() {
        return (Short)readProperty("orfano");
    }

    public void setPensionesuperstiti(Short pensionesuperstiti) {
        writeProperty("pensionesuperstiti", pensionesuperstiti);
    }
    public Short getPensionesuperstiti() {
        return (Short)readProperty("pensionesuperstiti");
    }

    public void setTel(String tel) {
        writeProperty("tel", tel);
    }
    public String getTel() {
        return (String)readProperty("tel");
    }

    public void addToLavoratoreArray(Lavoratore obj) {
        addToManyTarget("lavoratoreArray", obj, true);
    }
    public void removeFromLavoratoreArray(Lavoratore obj) {
        removeToManyTarget("lavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lavoratore> getLavoratoreArray() {
        return (List<Lavoratore>)readProperty("lavoratoreArray");
    }


    public void addToLegalepersonagiuridicaArray(Personagiuridica obj) {
        addToManyTarget("legalepersonagiuridicaArray", obj, true);
    }
    public void removeFromLegalepersonagiuridicaArray(Personagiuridica obj) {
        removeToManyTarget("legalepersonagiuridicaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Personagiuridica> getLegalepersonagiuridicaArray() {
        return (List<Personagiuridica>)readProperty("legalepersonagiuridicaArray");
    }


    public void addToParentelaArray1(Parentela obj) {
        addToManyTarget("parentelaArray1", obj, true);
    }
    public void removeFromParentelaArray1(Parentela obj) {
        removeToManyTarget("parentelaArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Parentela> getParentelaArray1() {
        return (List<Parentela>)readProperty("parentelaArray1");
    }


    public void addToParentelaArray2(Parentela obj) {
        addToManyTarget("parentelaArray2", obj, true);
    }
    public void removeFromParentelaArray2(Parentela obj) {
        removeToManyTarget("parentelaArray2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Parentela> getParentelaArray2() {
        return (List<Parentela>)readProperty("parentelaArray2");
    }


    public void addToPersonagiuridicaArray(Personagiuridica obj) {
        addToManyTarget("personagiuridicaArray", obj, true);
    }
    public void removeFromPersonagiuridicaArray(Personagiuridica obj) {
        removeToManyTarget("personagiuridicaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Personagiuridica> getPersonagiuridicaArray() {
        return (List<Personagiuridica>)readProperty("personagiuridicaArray");
    }


    public void addToPosizionefamiliareArray(Posizionefamiliare obj) {
        addToManyTarget("posizionefamiliareArray", obj, true);
    }
    public void removeFromPosizionefamiliareArray(Posizionefamiliare obj) {
        removeToManyTarget("posizionefamiliareArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionefamiliare> getPosizionefamiliareArray() {
        return (List<Posizionefamiliare>)readProperty("posizionefamiliareArray");
    }


    public void addToSocioArray(Socio obj) {
        addToManyTarget("socioArray", obj, true);
    }
    public void removeFromSocioArray(Socio obj) {
        removeToManyTarget("socioArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Socio> getSocioArray() {
        return (List<Socio>)readProperty("socioArray");
    }


    public void setToAnagrafica(Anagrafica toAnagrafica) {
        setToOneTarget("toAnagrafica", toAnagrafica, true);
    }

    public Anagrafica getToAnagrafica() {
        return (Anagrafica)readProperty("toAnagrafica");
    }


    public void setToCittadinanza(Statoestero toCittadinanza) {
        setToOneTarget("toCittadinanza", toCittadinanza, true);
    }

    public Statoestero getToCittadinanza() {
        return (Statoestero)readProperty("toCittadinanza");
    }


    public void setToComuneNascita(Comune toComuneNascita) {
        setToOneTarget("toComuneNascita", toComuneNascita, true);
    }

    public Comune getToComuneNascita() {
        return (Comune)readProperty("toComuneNascita");
    }


    public void setToContatto(Contatto toContatto) {
        setToOneTarget("toContatto", toContatto, true);
    }

    public Contatto getToContatto() {
        return (Contatto)readProperty("toContatto");
    }


    public void setToExtraCe(Extrace toExtraCe) {
        setToOneTarget("toExtraCe", toExtraCe, true);
    }

    public Extrace getToExtraCe() {
        return (Extrace)readProperty("toExtraCe");
    }


    public void setToIndirizzodomicilio(Indirizzo toIndirizzodomicilio) {
        setToOneTarget("toIndirizzodomicilio", toIndirizzodomicilio, true);
    }

    public Indirizzo getToIndirizzodomicilio() {
        return (Indirizzo)readProperty("toIndirizzodomicilio");
    }


    public void setToIndirizzoresidenza(Indirizzo toIndirizzoresidenza) {
        setToOneTarget("toIndirizzoresidenza", toIndirizzoresidenza, true);
    }

    public Indirizzo getToIndirizzoresidenza() {
        return (Indirizzo)readProperty("toIndirizzoresidenza");
    }


    public void setToIstatTitolostudio(IstatTitolostudio toIstatTitolostudio) {
        setToOneTarget("toIstatTitolostudio", toIstatTitolostudio, true);
    }

    public IstatTitolostudio getToIstatTitolostudio() {
        return (IstatTitolostudio)readProperty("toIstatTitolostudio");
    }


    public void setToPosizionebancaria(Posizionebancaria toPosizionebancaria) {
        setToOneTarget("toPosizionebancaria", toPosizionebancaria, true);
    }

    public Posizionebancaria getToPosizionebancaria() {
        return (Posizionebancaria)readProperty("toPosizionebancaria");
    }


    public void setToSesso(Sesso toSesso) {
        setToOneTarget("toSesso", toSesso, true);
    }

    public Sesso getToSesso() {
        return (Sesso)readProperty("toSesso");
    }


    public void setToStatoNascita(Statoestero toStatoNascita) {
        setToOneTarget("toStatoNascita", toStatoNascita, true);
    }

    public Statoestero getToStatoNascita() {
        return (Statoestero)readProperty("toStatoNascita");
    }


    public void setToStatocivile(Statocivile toStatocivile) {
        setToOneTarget("toStatocivile", toStatocivile, true);
    }

    public Statocivile getToStatocivile() {
        return (Statocivile)readProperty("toStatocivile");
    }


    public void setToTipo(Tipopersonafisica toTipo) {
        setToOneTarget("toTipo", toTipo, true);
    }

    public Tipopersonafisica getToTipo() {
        return (Tipopersonafisica)readProperty("toTipo");
    }


    public void setToTipoDatore(Tipodatore toTipoDatore) {
        setToOneTarget("toTipoDatore", toTipoDatore, true);
    }

    public Tipodatore getToTipoDatore() {
        return (Tipodatore)readProperty("toTipoDatore");
    }


    public void setToTipoOccupazione(Tipooccupazione toTipoOccupazione) {
        setToOneTarget("toTipoOccupazione", toTipoOccupazione, true);
    }

    public Tipooccupazione getToTipoOccupazione() {
        return (Tipooccupazione)readProperty("toTipoOccupazione");
    }


    public void addToToUtente(Utente obj) {
        addToManyTarget("toUtente", obj, true);
    }
    public void removeFromToUtente(Utente obj) {
        removeToManyTarget("toUtente", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Utente> getToUtente() {
        return (List<Utente>)readProperty("toUtente");
    }


}
