package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Comune;
import it.iubar.paghe.logic.anagrafica.Regione;
import it.iubar.paghe.logic.anagrafica.Sedeinail;
import it.iubar.paghe.logic.anagrafica.Sedeinps;

/**
 * Class _Provincia was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Provincia extends CayenneDataObject {

    public static final String DENOMINAZIONE_PROPERTY = "denominazione";
    public static final String IDPROVINCIA_PROPERTY = "idprovincia";
    public static final String IDREGIONE_PROPERTY = "idregione";
    public static final String SIGLA_PROPERTY = "sigla";
    public static final String COMUNE_ARRAY_PROPERTY = "comuneArray";
    public static final String SEDE_INAIL_ARRAY_PROPERTY = "sedeInailArray";
    public static final String SEDEINPS_ARRAY_PROPERTY = "sedeinpsArray";
    public static final String TO_REGIONE_PROPERTY = "toRegione";

    public static final String IDPROVINCIA_PK_COLUMN = "IDPROVINCIA";

    public String getDenominazione() {
        return (String)readProperty("denominazione");
    }

    public String getIdprovincia() {
        return (String)readProperty("idprovincia");
    }

    public String getIdregione() {
        return (String)readProperty("idregione");
    }

    public String getSigla() {
        return (String)readProperty("sigla");
    }

    public void addToComuneArray(Comune obj) {
        addToManyTarget("comuneArray", obj, true);
    }
    public void removeFromComuneArray(Comune obj) {
        removeToManyTarget("comuneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Comune> getComuneArray() {
        return (List<Comune>)readProperty("comuneArray");
    }


    public void addToSedeInailArray(Sedeinail obj) {
        addToManyTarget("sedeInailArray", obj, true);
    }
    public void removeFromSedeInailArray(Sedeinail obj) {
        removeToManyTarget("sedeInailArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Sedeinail> getSedeInailArray() {
        return (List<Sedeinail>)readProperty("sedeInailArray");
    }


    public void addToSedeinpsArray(Sedeinps obj) {
        addToManyTarget("sedeinpsArray", obj, true);
    }
    public void removeFromSedeinpsArray(Sedeinps obj) {
        removeToManyTarget("sedeinpsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Sedeinps> getSedeinpsArray() {
        return (List<Sedeinps>)readProperty("sedeinpsArray");
    }



    public Regione getToRegione() {
        return (Regione)readProperty("toRegione");
    }


}
