package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Capoluogo;
import it.iubar.paghe.logic.anagrafica.Provincia;
import it.iubar.paghe.logic.paghe.IrpefAddizionaleregionale;

/**
 * Class _Regione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Regione extends CayenneDataObject {

    public static final String CODAGENZIAENTRATE_PROPERTY = "codagenziaentrate";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDREGIONE_PROPERTY = "idregione";
    public static final String RIPARTIZIONEGEOGRAFICA_PROPERTY = "ripartizionegeografica";
    public static final String ADDIZIONALE_ARRAY_PROPERTY = "addizionaleArray";
    public static final String CAPOLUOGO_ARRAY_PROPERTY = "capoluogoArray";
    public static final String PROVINCIA_ARRAY_PROPERTY = "provinciaArray";

    public static final String IDREGIONE_PK_COLUMN = "IDREGIONE";

    public String getCodagenziaentrate() {
        return (String)readProperty("codagenziaentrate");
    }

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdregione() {
        return (String)readProperty("idregione");
    }

    public String getRipartizionegeografica() {
        return (String)readProperty("ripartizionegeografica");
    }

    public void addToAddizionaleArray(IrpefAddizionaleregionale obj) {
        addToManyTarget("addizionaleArray", obj, true);
    }
    public void removeFromAddizionaleArray(IrpefAddizionaleregionale obj) {
        removeToManyTarget("addizionaleArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<IrpefAddizionaleregionale> getAddizionaleArray() {
        return (List<IrpefAddizionaleregionale>)readProperty("addizionaleArray");
    }


    public void addToCapoluogoArray(Capoluogo obj) {
        addToManyTarget("capoluogoArray", obj, true);
    }
    public void removeFromCapoluogoArray(Capoluogo obj) {
        removeToManyTarget("capoluogoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Capoluogo> getCapoluogoArray() {
        return (List<Capoluogo>)readProperty("capoluogoArray");
    }


    public void addToProvinciaArray(Provincia obj) {
        addToManyTarget("provinciaArray", obj, true);
    }
    public void removeFromProvinciaArray(Provincia obj) {
        removeToManyTarget("provinciaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Provincia> getProvinciaArray() {
        return (List<Provincia>)readProperty("provinciaArray");
    }


}
