package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Utente;

/**
 * Class _Ruolo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Ruolo extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDRUOLO_PROPERTY = "idruolo";
    public static final String NOTE_PROPERTY = "note";
    public static final String UTENTE_ARRAY_PROPERTY = "utenteArray";

    public static final String IDRUOLO_PK_COLUMN = "IDRUOLO";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdruolo() {
        return (Short)readProperty("idruolo");
    }

    public String getNote() {
        return (String)readProperty("note");
    }

    public void addToUtenteArray(Utente obj) {
        addToManyTarget("utenteArray", obj, true);
    }
    public void removeFromUtenteArray(Utente obj) {
        removeToManyTarget("utenteArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Utente> getUtenteArray() {
        return (List<Utente>)readProperty("utenteArray");
    }


}
