package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Provincia;
import it.iubar.paghe.logic.anagrafica.Sedeimpresa;
import it.iubar.paghe.logic.anagrafica.Titolaredati;

/**
 * Class _Sedeinail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Sedeinail extends CayenneDataObject {

    public static final String CAP_PROPERTY = "cap";
    public static final String CITTA_PROPERTY = "citta";
    public static final String DENOMINAZIONE_PROPERTY = "denominazione";
    public static final String IDPROVINCIA_PROPERTY = "idprovincia";
    public static final String IDSEDEINAIL_PROPERTY = "idsedeinail";
    public static final String INDIRIZZO_PROPERTY = "indirizzo";
    public static final String PROVINCIASIGLA_PROPERTY = "provinciasigla";
    public static final String SEDEIMPRESA_ARRAY_PROPERTY = "sedeimpresaArray";
    public static final String TITOLARE_ARRAY_PROPERTY = "titolareArray";
    public static final String TO_PROVINCIA_PROPERTY = "toProvincia";
    public static final String TO_PROVINCIA_BY_SIGLA_PROPERTY = "toProvinciaBySigla";

    public static final String IDSEDEINAIL_PK_COLUMN = "IDSEDEINAIL";

    public String getCap() {
        return (String)readProperty("cap");
    }

    public String getCitta() {
        return (String)readProperty("citta");
    }

    public String getDenominazione() {
        return (String)readProperty("denominazione");
    }

    public String getIdprovincia() {
        return (String)readProperty("idprovincia");
    }

    public Integer getIdsedeinail() {
        return (Integer)readProperty("idsedeinail");
    }

    public String getIndirizzo() {
        return (String)readProperty("indirizzo");
    }

    public String getProvinciasigla() {
        return (String)readProperty("provinciasigla");
    }

    public void addToSedeimpresaArray(Sedeimpresa obj) {
        addToManyTarget("sedeimpresaArray", obj, true);
    }
    public void removeFromSedeimpresaArray(Sedeimpresa obj) {
        removeToManyTarget("sedeimpresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Sedeimpresa> getSedeimpresaArray() {
        return (List<Sedeimpresa>)readProperty("sedeimpresaArray");
    }


    public void addToTitolareArray(Titolaredati obj) {
        addToManyTarget("titolareArray", obj, true);
    }
    public void removeFromTitolareArray(Titolaredati obj) {
        removeToManyTarget("titolareArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Titolaredati> getTitolareArray() {
        return (List<Titolaredati>)readProperty("titolareArray");
    }



    public Provincia getToProvincia() {
        return (Provincia)readProperty("toProvincia");
    }



    public Provincia getToProvinciaBySigla() {
        return (Provincia)readProperty("toProvinciaBySigla");
    }


}
