package it.iubar.paghe.logic.anagrafica.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Sededmag was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Sededmag extends CayenneDataObject {

    public static final String DENOMINAZIONE_PROPERTY = "denominazione";
    public static final String IDSEDEDMAG_PROPERTY = "idsededmag";
    public static final String PROVINCIASIGLA_PROPERTY = "provinciasigla";

    public static final String IDSEDEDMAG_PK_COLUMN = "IDSEDEDMAG";

    public String getDenominazione() {
        return (String)readProperty("denominazione");
    }

    public String getIdsededmag() {
        return (String)readProperty("idsededmag");
    }

    public String getProvinciasigla() {
        return (String)readProperty("provinciasigla");
    }

}
