package it.iubar.paghe.logic.anagrafica.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Entepubblico;

/**
 * Class _Subordinatopa was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Subordinatopa extends CayenneDataObject {

    public static final String IDLAVORATORE_PROPERTY = "idlavoratore";
    public static final String IDPAQUALIFICA_PROPERTY = "idpaqualifica";
    public static final String IDREGIMEFINESERV_PROPERTY = "idregimefineserv";
    public static final String IDTIPOIMPIEGO_PROPERTY = "idtipoimpiego";
    public static final String IDTIPOSERVIZIO_PROPERTY = "idtiposervizio";
    public static final String ORESETTPERSSCUOLAC_PROPERTY = "oresettpersscuolac";
    public static final String ORESETTPERSSCUOLAR_PROPERTY = "oresettpersscuolar";
    public static final String PERCASPETTATIVA_PROPERTY = "percaspettativa";
    public static final String PERCRETRIBUZIONE_PROPERTY = "percretribuzione";
    public static final String TO_ENTE_APPARTENENZA_PROPERTY = "toEnteAppartenenza";
    public static final String TO_SEDE_SERVIZIO_PROPERTY = "toSedeServizio";

    public static final String IDLAVORATORE_PK_COLUMN = "IDLAVORATORE";

    public void setIdlavoratore(Integer idlavoratore) {
        writeProperty("idlavoratore", idlavoratore);
    }
    public Integer getIdlavoratore() {
        return (Integer)readProperty("idlavoratore");
    }

    public void setIdpaqualifica(String idpaqualifica) {
        writeProperty("idpaqualifica", idpaqualifica);
    }
    public String getIdpaqualifica() {
        return (String)readProperty("idpaqualifica");
    }

    public void setIdregimefineserv(Short idregimefineserv) {
        writeProperty("idregimefineserv", idregimefineserv);
    }
    public Short getIdregimefineserv() {
        return (Short)readProperty("idregimefineserv");
    }

    public void setIdtipoimpiego(Short idtipoimpiego) {
        writeProperty("idtipoimpiego", idtipoimpiego);
    }
    public Short getIdtipoimpiego() {
        return (Short)readProperty("idtipoimpiego");
    }

    public void setIdtiposervizio(Short idtiposervizio) {
        writeProperty("idtiposervizio", idtiposervizio);
    }
    public Short getIdtiposervizio() {
        return (Short)readProperty("idtiposervizio");
    }

    public void setOresettpersscuolac(BigDecimal oresettpersscuolac) {
        writeProperty("oresettpersscuolac", oresettpersscuolac);
    }
    public BigDecimal getOresettpersscuolac() {
        return (BigDecimal)readProperty("oresettpersscuolac");
    }

    public void setOresettpersscuolar(BigDecimal oresettpersscuolar) {
        writeProperty("oresettpersscuolar", oresettpersscuolar);
    }
    public BigDecimal getOresettpersscuolar() {
        return (BigDecimal)readProperty("oresettpersscuolar");
    }

    public void setPercaspettativa(BigDecimal percaspettativa) {
        writeProperty("percaspettativa", percaspettativa);
    }
    public BigDecimal getPercaspettativa() {
        return (BigDecimal)readProperty("percaspettativa");
    }

    public void setPercretribuzione(BigDecimal percretribuzione) {
        writeProperty("percretribuzione", percretribuzione);
    }
    public BigDecimal getPercretribuzione() {
        return (BigDecimal)readProperty("percretribuzione");
    }

    public void setToEnteAppartenenza(Entepubblico toEnteAppartenenza) {
        setToOneTarget("toEnteAppartenenza", toEnteAppartenenza, true);
    }

    public Entepubblico getToEnteAppartenenza() {
        return (Entepubblico)readProperty("toEnteAppartenenza");
    }


    public void setToSedeServizio(Entepubblico toSedeServizio) {
        setToOneTarget("toSedeServizio", toSedeServizio, true);
    }

    public Entepubblico getToSedeServizio() {
        return (Entepubblico)readProperty("toSedeServizio");
    }


}
