package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Anagrafica;

/**
 * Class _Tipoanagrafica was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tipoanagrafica extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOANAGRAFICA_PROPERTY = "idtipoanagrafica";
    public static final String ANAGRAFICA_ARRAY_PROPERTY = "anagraficaArray";

    public static final String IDTIPOANAGRAFICA_PK_COLUMN = "IDTIPOANAGRAFICA";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdtipoanagrafica() {
        return (Short)readProperty("idtipoanagrafica");
    }

    public void addToAnagraficaArray(Anagrafica obj) {
        addToManyTarget("anagraficaArray", obj, true);
    }
    public void removeFromAnagraficaArray(Anagrafica obj) {
        removeToManyTarget("anagraficaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Anagrafica> getAnagraficaArray() {
        return (List<Anagrafica>)readProperty("anagraficaArray");
    }


}
