package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Lavoratore;
import it.iubar.paghe.logic.paghe.Contrattoassenza;
import it.iubar.paghe.logic.paghe.Contrattoferie;
import it.iubar.paghe.logic.paghe.Contrattofestivitaretrib;
import it.iubar.paghe.logic.paghe.Contrattoindennita;
import it.iubar.paghe.logic.paghe.Contrattorateo;
import it.iubar.paghe.logic.paghe.Contrattoscatto;
import it.iubar.paghe.logic.paghe.InpsQualifica1;
import it.iubar.paghe.logic.paghe.Profilolavoratore;
import it.iubar.paghe.logic.paghe.Scadenza;
import it.iubar.paghe.logic.presenze.Orario;

/**
 * Class _Tipolavoratore2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tipolavoratore2 extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOLAVORATORE2_PROPERTY = "idtipolavoratore2";
    public static final String CONTRATTOASSENZA_ARRAY_PROPERTY = "contrattoassenzaArray";
    public static final String CONTRATTOFERIE_ARRAY_PROPERTY = "contrattoferieArray";
    public static final String CONTRATTOFESTIVITARETRIB_ARRAY_PROPERTY = "contrattofestivitaretribArray";
    public static final String CONTRATTOINDENNITA_ARRAY_PROPERTY = "contrattoindennitaArray";
    public static final String CONTRATTORATEO_ARRAY_PROPERTY = "contrattorateoArray";
    public static final String CONTRATTOSCATTO_ARRAY_PROPERTY = "contrattoscattoArray";
    public static final String INPS_QUALIFICA1ARRAY_PROPERTY = "inpsQualifica1Array";
    public static final String LAVORATORE_ARRAY_PROPERTY = "lavoratoreArray";
    public static final String ORARIO_ARRAY_PROPERTY = "orarioArray";
    public static final String PROFILOLAVORATORE_ARRAY_PROPERTY = "profilolavoratoreArray";
    public static final String SCADENZA_ARRAY_PROPERTY = "scadenzaArray";

    public static final String IDTIPOLAVORATORE2_PK_COLUMN = "IDTIPOLAVORATORE2";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdtipolavoratore2() {
        return (Short)readProperty("idtipolavoratore2");
    }

    public void addToContrattoassenzaArray(Contrattoassenza obj) {
        addToManyTarget("contrattoassenzaArray", obj, true);
    }
    public void removeFromContrattoassenzaArray(Contrattoassenza obj) {
        removeToManyTarget("contrattoassenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoassenza> getContrattoassenzaArray() {
        return (List<Contrattoassenza>)readProperty("contrattoassenzaArray");
    }


    public void addToContrattoferieArray(Contrattoferie obj) {
        addToManyTarget("contrattoferieArray", obj, true);
    }
    public void removeFromContrattoferieArray(Contrattoferie obj) {
        removeToManyTarget("contrattoferieArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoferie> getContrattoferieArray() {
        return (List<Contrattoferie>)readProperty("contrattoferieArray");
    }


    public void addToContrattofestivitaretribArray(Contrattofestivitaretrib obj) {
        addToManyTarget("contrattofestivitaretribArray", obj, true);
    }
    public void removeFromContrattofestivitaretribArray(Contrattofestivitaretrib obj) {
        removeToManyTarget("contrattofestivitaretribArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattofestivitaretrib> getContrattofestivitaretribArray() {
        return (List<Contrattofestivitaretrib>)readProperty("contrattofestivitaretribArray");
    }


    public void addToContrattoindennitaArray(Contrattoindennita obj) {
        addToManyTarget("contrattoindennitaArray", obj, true);
    }
    public void removeFromContrattoindennitaArray(Contrattoindennita obj) {
        removeToManyTarget("contrattoindennitaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoindennita> getContrattoindennitaArray() {
        return (List<Contrattoindennita>)readProperty("contrattoindennitaArray");
    }


    public void addToContrattorateoArray(Contrattorateo obj) {
        addToManyTarget("contrattorateoArray", obj, true);
    }
    public void removeFromContrattorateoArray(Contrattorateo obj) {
        removeToManyTarget("contrattorateoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattorateo> getContrattorateoArray() {
        return (List<Contrattorateo>)readProperty("contrattorateoArray");
    }


    public void addToContrattoscattoArray(Contrattoscatto obj) {
        addToManyTarget("contrattoscattoArray", obj, true);
    }
    public void removeFromContrattoscattoArray(Contrattoscatto obj) {
        removeToManyTarget("contrattoscattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoscatto> getContrattoscattoArray() {
        return (List<Contrattoscatto>)readProperty("contrattoscattoArray");
    }


    public void addToInpsQualifica1Array(InpsQualifica1 obj) {
        addToManyTarget("inpsQualifica1Array", obj, true);
    }
    public void removeFromInpsQualifica1Array(InpsQualifica1 obj) {
        removeToManyTarget("inpsQualifica1Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsQualifica1> getInpsQualifica1Array() {
        return (List<InpsQualifica1>)readProperty("inpsQualifica1Array");
    }


    public void addToLavoratoreArray(Lavoratore obj) {
        addToManyTarget("lavoratoreArray", obj, true);
    }
    public void removeFromLavoratoreArray(Lavoratore obj) {
        removeToManyTarget("lavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lavoratore> getLavoratoreArray() {
        return (List<Lavoratore>)readProperty("lavoratoreArray");
    }


    public void addToOrarioArray(Orario obj) {
        addToManyTarget("orarioArray", obj, true);
    }
    public void removeFromOrarioArray(Orario obj) {
        removeToManyTarget("orarioArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Orario> getOrarioArray() {
        return (List<Orario>)readProperty("orarioArray");
    }


    public void addToProfilolavoratoreArray(Profilolavoratore obj) {
        addToManyTarget("profilolavoratoreArray", obj, true);
    }
    public void removeFromProfilolavoratoreArray(Profilolavoratore obj) {
        removeToManyTarget("profilolavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profilolavoratore> getProfilolavoratoreArray() {
        return (List<Profilolavoratore>)readProperty("profilolavoratoreArray");
    }


    public void addToScadenzaArray(Scadenza obj) {
        addToManyTarget("scadenzaArray", obj, true);
    }
    public void removeFromScadenzaArray(Scadenza obj) {
        removeToManyTarget("scadenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Scadenza> getScadenzaArray() {
        return (List<Scadenza>)readProperty("scadenzaArray");
    }


}
