package it.iubar.paghe.logic.anagrafica.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Anagrafica;
import it.iubar.paghe.logic.anagrafica.CoSoggetto;
import it.iubar.paghe.logic.anagrafica.Configtitolaredati;
import it.iubar.paghe.logic.anagrafica.Contatto;
import it.iubar.paghe.logic.anagrafica.Impresa;
import it.iubar.paghe.logic.anagrafica.Indirizzo;
import it.iubar.paghe.logic.anagrafica.Posizionebancaria;
import it.iubar.paghe.logic.anagrafica.Sedeinail;
import it.iubar.paghe.logic.anagrafica.Sedeinps;
import it.iubar.paghe.logic.anagrafica.Sesso;
import it.iubar.paghe.logic.anagrafica.Smtpaccount;
import it.iubar.paghe.logic.anagrafica.Tipotitolare;
import it.iubar.paghe.logic.anagrafica.Utente;
import it.iubar.paghe.logic.paghe.Posizionelavoratore;

/**
 * Class _Titolaredati was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Titolaredati extends CayenneDataObject {

    public static final String CELL_PROPERTY = "cell";
    public static final String CF_PROPERTY = "cf";
    public static final String CNCEIDTITOLARE_PROPERTY = "cnceidtitolare";
    public static final String COGNOME_PROPERTY = "cognome";
    public static final String DENOMINAZIONE_PROPERTY = "denominazione";
    public static final String DM10AUTORIZZAZIONE_PROPERTY = "dm10autorizzazione";
    public static final String EMAILINDIRIZZO_PROPERTY = "emailindirizzo";
    public static final String EMAILNOME_PROPERTY = "emailnome";
    public static final String EMAILOGGETTO_PROPERTY = "emailoggetto";
    public static final String EMAILSOLOTESTO_PROPERTY = "emailsolotesto";
    public static final String EMAILTESTO_PROPERTY = "emailtesto";
    public static final String FAX_PROPERTY = "fax";
    public static final String IDCOSOGGETTO_PROPERTY = "idcosoggetto";
    public static final String IDINDIRIZZODOMICILIO_PROPERTY = "idindirizzodomicilio";
    public static final String IDPOSIZIONEBANCARIA_PROPERTY = "idposizionebancaria";
    public static final String IDSMTPACCOUNT_PROPERTY = "idsmtpaccount";
    public static final String IDTIPOTITOLARE_PROPERTY = "idtipotitolare";
    public static final String IDTITOLAREDATI_PROPERTY = "idtitolaredati";
    public static final String INAILNUMUNICAAUTORIZ_PROPERTY = "inailnumunicaautoriz";
    public static final String INAILNUMUNICADATA_PROPERTY = "inailnumunicadata";
    public static final String INAILPROGRESLAST_PROPERTY = "inailprogreslast";
    public static final String INAILPROGRESSTART_PROPERTY = "inailprogresstart";
    public static final String NASCITACOMUNE_PROPERTY = "nascitacomune";
    public static final String NASCITADATA_PROPERTY = "nascitadata";
    public static final String NOME_PROPERTY = "nome";
    public static final String PEC_PROPERTY = "pec";
    public static final String PINSMARTCARD_PROPERTY = "pinsmartcard";
    public static final String PIVA_PROPERTY = "piva";
    public static final String PREDEFINITO_PROPERTY = "predefinito";
    public static final String TEL_PROPERTY = "tel";
    public static final String WEB_PROPERTY = "web";
    public static final String CONFIG_TITOLARE_DATI_ARRAY_PROPERTY = "configTitolareDatiArray";
    public static final String IMPRESA_ARRAY_PROPERTY = "impresaArray";
    public static final String POSIZIONELAVORATORE_ARRAY_PROPERTY = "posizionelavoratoreArray";
    public static final String TO_ANAGRAFICA_PROPERTY = "toAnagrafica";
    public static final String TO_CO_SOGGETTOABILITATO_PROPERTY = "toCoSoggettoabilitato";
    public static final String TO_CONTATTO_PROPERTY = "toContatto";
    public static final String TO_INDIRIZZODOMICILIO_PROPERTY = "toIndirizzodomicilio";
    public static final String TO_POSIZIONEBANCARIA_PROPERTY = "toPosizionebancaria";
    public static final String TO_SEDE_INAIL_PROPERTY = "toSedeInail";
    public static final String TO_SEDE_INPS_PROPERTY = "toSedeInps";
    public static final String TO_SESSO_PROPERTY = "toSesso";
    public static final String TO_SMTPACCOUNT_PROPERTY = "toSmtpaccount";
    public static final String TO_TIPOTITOLARE_PROPERTY = "toTipotitolare";
    public static final String UTENTE_ARRAY_PROPERTY = "utenteArray";

    public static final String IDTITOLAREDATI_PK_COLUMN = "IDTITOLAREDATI";

    public void setCell(String cell) {
        writeProperty("cell", cell);
    }
    public String getCell() {
        return (String)readProperty("cell");
    }

    public void setCf(String cf) {
        writeProperty("cf", cf);
    }
    public String getCf() {
        return (String)readProperty("cf");
    }

    public void setCnceidtitolare(String cnceidtitolare) {
        writeProperty("cnceidtitolare", cnceidtitolare);
    }
    public String getCnceidtitolare() {
        return (String)readProperty("cnceidtitolare");
    }

    public void setCognome(String cognome) {
        writeProperty("cognome", cognome);
    }
    public String getCognome() {
        return (String)readProperty("cognome");
    }

    public void setDenominazione(String denominazione) {
        writeProperty("denominazione", denominazione);
    }
    public String getDenominazione() {
        return (String)readProperty("denominazione");
    }

    public void setDm10autorizzazione(String dm10autorizzazione) {
        writeProperty("dm10autorizzazione", dm10autorizzazione);
    }
    public String getDm10autorizzazione() {
        return (String)readProperty("dm10autorizzazione");
    }

    public void setEmailindirizzo(String emailindirizzo) {
        writeProperty("emailindirizzo", emailindirizzo);
    }
    public String getEmailindirizzo() {
        return (String)readProperty("emailindirizzo");
    }

    public void setEmailnome(String emailnome) {
        writeProperty("emailnome", emailnome);
    }
    public String getEmailnome() {
        return (String)readProperty("emailnome");
    }

    public void setEmailoggetto(String emailoggetto) {
        writeProperty("emailoggetto", emailoggetto);
    }
    public String getEmailoggetto() {
        return (String)readProperty("emailoggetto");
    }

    public void setEmailsolotesto(Short emailsolotesto) {
        writeProperty("emailsolotesto", emailsolotesto);
    }
    public Short getEmailsolotesto() {
        return (Short)readProperty("emailsolotesto");
    }

    public void setEmailtesto(String emailtesto) {
        writeProperty("emailtesto", emailtesto);
    }
    public String getEmailtesto() {
        return (String)readProperty("emailtesto");
    }

    public void setFax(String fax) {
        writeProperty("fax", fax);
    }
    public String getFax() {
        return (String)readProperty("fax");
    }

    public void setIdcosoggetto(Short idcosoggetto) {
        writeProperty("idcosoggetto", idcosoggetto);
    }
    public Short getIdcosoggetto() {
        return (Short)readProperty("idcosoggetto");
    }

    public void setIdindirizzodomicilio(Integer idindirizzodomicilio) {
        writeProperty("idindirizzodomicilio", idindirizzodomicilio);
    }
    public Integer getIdindirizzodomicilio() {
        return (Integer)readProperty("idindirizzodomicilio");
    }

    public void setIdposizionebancaria(Integer idposizionebancaria) {
        writeProperty("idposizionebancaria", idposizionebancaria);
    }
    public Integer getIdposizionebancaria() {
        return (Integer)readProperty("idposizionebancaria");
    }

    public void setIdsmtpaccount(Short idsmtpaccount) {
        writeProperty("idsmtpaccount", idsmtpaccount);
    }
    public Short getIdsmtpaccount() {
        return (Short)readProperty("idsmtpaccount");
    }

    public void setIdtipotitolare(Short idtipotitolare) {
        writeProperty("idtipotitolare", idtipotitolare);
    }
    public Short getIdtipotitolare() {
        return (Short)readProperty("idtipotitolare");
    }

    public void setIdtitolaredati(Integer idtitolaredati) {
        writeProperty("idtitolaredati", idtitolaredati);
    }
    public Integer getIdtitolaredati() {
        return (Integer)readProperty("idtitolaredati");
    }

    public void setInailnumunicaautoriz(String inailnumunicaautoriz) {
        writeProperty("inailnumunicaautoriz", inailnumunicaautoriz);
    }
    public String getInailnumunicaautoriz() {
        return (String)readProperty("inailnumunicaautoriz");
    }

    public void setInailnumunicadata(Date inailnumunicadata) {
        writeProperty("inailnumunicadata", inailnumunicadata);
    }
    public Date getInailnumunicadata() {
        return (Date)readProperty("inailnumunicadata");
    }

    public void setInailprogreslast(Integer inailprogreslast) {
        writeProperty("inailprogreslast", inailprogreslast);
    }
    public Integer getInailprogreslast() {
        return (Integer)readProperty("inailprogreslast");
    }

    public void setInailprogresstart(Integer inailprogresstart) {
        writeProperty("inailprogresstart", inailprogresstart);
    }
    public Integer getInailprogresstart() {
        return (Integer)readProperty("inailprogresstart");
    }

    public void setNascitacomune(String nascitacomune) {
        writeProperty("nascitacomune", nascitacomune);
    }
    public String getNascitacomune() {
        return (String)readProperty("nascitacomune");
    }

    public void setNascitadata(Date nascitadata) {
        writeProperty("nascitadata", nascitadata);
    }
    public Date getNascitadata() {
        return (Date)readProperty("nascitadata");
    }

    public void setNome(String nome) {
        writeProperty("nome", nome);
    }
    public String getNome() {
        return (String)readProperty("nome");
    }

    public void setPec(String pec) {
        writeProperty("pec", pec);
    }
    public String getPec() {
        return (String)readProperty("pec");
    }

    public void setPinsmartcard(String pinsmartcard) {
        writeProperty("pinsmartcard", pinsmartcard);
    }
    public String getPinsmartcard() {
        return (String)readProperty("pinsmartcard");
    }

    public void setPiva(String piva) {
        writeProperty("piva", piva);
    }
    public String getPiva() {
        return (String)readProperty("piva");
    }

    public void setPredefinito(Short predefinito) {
        writeProperty("predefinito", predefinito);
    }
    public Short getPredefinito() {
        return (Short)readProperty("predefinito");
    }

    public void setTel(String tel) {
        writeProperty("tel", tel);
    }
    public String getTel() {
        return (String)readProperty("tel");
    }

    public void setWeb(String web) {
        writeProperty("web", web);
    }
    public String getWeb() {
        return (String)readProperty("web");
    }

    public void addToConfigTitolareDatiArray(Configtitolaredati obj) {
        addToManyTarget("configTitolareDatiArray", obj, true);
    }
    public void removeFromConfigTitolareDatiArray(Configtitolaredati obj) {
        removeToManyTarget("configTitolareDatiArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Configtitolaredati> getConfigTitolareDatiArray() {
        return (List<Configtitolaredati>)readProperty("configTitolareDatiArray");
    }


    public void addToImpresaArray(Impresa obj) {
        addToManyTarget("impresaArray", obj, true);
    }
    public void removeFromImpresaArray(Impresa obj) {
        removeToManyTarget("impresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Impresa> getImpresaArray() {
        return (List<Impresa>)readProperty("impresaArray");
    }


    public void addToPosizionelavoratoreArray(Posizionelavoratore obj) {
        addToManyTarget("posizionelavoratoreArray", obj, true);
    }
    public void removeFromPosizionelavoratoreArray(Posizionelavoratore obj) {
        removeToManyTarget("posizionelavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionelavoratore> getPosizionelavoratoreArray() {
        return (List<Posizionelavoratore>)readProperty("posizionelavoratoreArray");
    }


    public void setToAnagrafica(Anagrafica toAnagrafica) {
        setToOneTarget("toAnagrafica", toAnagrafica, true);
    }

    public Anagrafica getToAnagrafica() {
        return (Anagrafica)readProperty("toAnagrafica");
    }


    public void setToCoSoggettoabilitato(CoSoggetto toCoSoggettoabilitato) {
        setToOneTarget("toCoSoggettoabilitato", toCoSoggettoabilitato, true);
    }

    public CoSoggetto getToCoSoggettoabilitato() {
        return (CoSoggetto)readProperty("toCoSoggettoabilitato");
    }


    public void setToContatto(Contatto toContatto) {
        setToOneTarget("toContatto", toContatto, true);
    }

    public Contatto getToContatto() {
        return (Contatto)readProperty("toContatto");
    }


    public void setToIndirizzodomicilio(Indirizzo toIndirizzodomicilio) {
        setToOneTarget("toIndirizzodomicilio", toIndirizzodomicilio, true);
    }

    public Indirizzo getToIndirizzodomicilio() {
        return (Indirizzo)readProperty("toIndirizzodomicilio");
    }


    public void setToPosizionebancaria(Posizionebancaria toPosizionebancaria) {
        setToOneTarget("toPosizionebancaria", toPosizionebancaria, true);
    }

    public Posizionebancaria getToPosizionebancaria() {
        return (Posizionebancaria)readProperty("toPosizionebancaria");
    }


    public void setToSedeInail(Sedeinail toSedeInail) {
        setToOneTarget("toSedeInail", toSedeInail, true);
    }

    public Sedeinail getToSedeInail() {
        return (Sedeinail)readProperty("toSedeInail");
    }


    public void setToSedeInps(Sedeinps toSedeInps) {
        setToOneTarget("toSedeInps", toSedeInps, true);
    }

    public Sedeinps getToSedeInps() {
        return (Sedeinps)readProperty("toSedeInps");
    }


    public void setToSesso(Sesso toSesso) {
        setToOneTarget("toSesso", toSesso, true);
    }

    public Sesso getToSesso() {
        return (Sesso)readProperty("toSesso");
    }


    public void setToSmtpaccount(Smtpaccount toSmtpaccount) {
        setToOneTarget("toSmtpaccount", toSmtpaccount, true);
    }

    public Smtpaccount getToSmtpaccount() {
        return (Smtpaccount)readProperty("toSmtpaccount");
    }


    public void setToTipotitolare(Tipotitolare toTipotitolare) {
        setToOneTarget("toTipotitolare", toTipotitolare, true);
    }

    public Tipotitolare getToTipotitolare() {
        return (Tipotitolare)readProperty("toTipotitolare");
    }


    public void addToUtenteArray(Utente obj) {
        addToManyTarget("utenteArray", obj, true);
    }
    public void removeFromUtenteArray(Utente obj) {
        removeToManyTarget("utenteArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Utente> getUtenteArray() {
        return (List<Utente>)readProperty("utenteArray");
    }


}
