package it.iubar.paghe.logic.anagrafica.auto;

import java.sql.Timestamp;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Anagrafica;
import it.iubar.paghe.logic.anagrafica.Personafisica;
import it.iubar.paghe.logic.anagrafica.Ruolo;
import it.iubar.paghe.logic.anagrafica.Titolaredati;
import it.iubar.paghe.logic.anagrafica.UtenteAzione;
import it.iubar.paghe.logic.blob.Documento;
import it.iubar.paghe.logic.paghe.Cedolino;
import it.iubar.paghe.logic.paghe.Dichiarazione;
import it.iubar.paghe.logic.paghe.Posizionelavoratore;

/**
 * Class _Utente was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Utente extends CayenneDataObject {

    public static final String ATTIVO_PROPERTY = "attivo";
    public static final String CREAZIONEDATA_PROPERTY = "creazionedata";
    public static final String EMAIL_PROPERTY = "email";
    public static final String IDANAGRAFICA_PROPERTY = "idanagrafica";
    public static final String IDRUOLO_PROPERTY = "idruolo";
    public static final String IDTITOLAREDATI_PROPERTY = "idtitolaredati";
    public static final String PWDHASH_PROPERTY = "pwdhash";
    public static final String PWDSALT_PROPERTY = "pwdsalt";
    public static final String ULTIMOACCESSO_PROPERTY = "ultimoaccesso";
    public static final String USERNAME_PROPERTY = "username";
    public static final String ANAGRAFICA_ARRAY_PROPERTY = "anagraficaArray";
    public static final String CEDOLINO_ARRAY_PROPERTY = "cedolinoArray";
    public static final String DICHIARAZIONE_ARRAY_PROPERTY = "dichiarazioneArray";
    public static final String DOCUMENTO_AUTORE_ARRAY_PROPERTY = "documentoAutoreArray";
    public static final String DOCUMENTO_REVISORE_ARRAY_PROPERTY = "documentoRevisoreArray";
    public static final String POSIZIONELAVORATORE_ARRAY_PROPERTY = "posizionelavoratoreArray";
    public static final String TO_PERSONA_FISICA_PROPERTY = "toPersonaFisica";
    public static final String TO_RUOLO_PROPERTY = "toRuolo";
    public static final String TO_TITOLAREDATI_PROPERTY = "toTitolaredati";
    public static final String UTENTEAZIONE_ARRAY_PROPERTY = "utenteazioneArray";

    public static final String USERNAME_PK_COLUMN = "USERNAME";

    public void setAttivo(Short attivo) {
        writeProperty("attivo", attivo);
    }
    public Short getAttivo() {
        return (Short)readProperty("attivo");
    }

    public void setCreazionedata(Date creazionedata) {
        writeProperty("creazionedata", creazionedata);
    }
    public Date getCreazionedata() {
        return (Date)readProperty("creazionedata");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setIdanagrafica(Integer idanagrafica) {
        writeProperty("idanagrafica", idanagrafica);
    }
    public Integer getIdanagrafica() {
        return (Integer)readProperty("idanagrafica");
    }

    public void setIdruolo(Short idruolo) {
        writeProperty("idruolo", idruolo);
    }
    public Short getIdruolo() {
        return (Short)readProperty("idruolo");
    }

    public void setIdtitolaredati(Integer idtitolaredati) {
        writeProperty("idtitolaredati", idtitolaredati);
    }
    public Integer getIdtitolaredati() {
        return (Integer)readProperty("idtitolaredati");
    }

    public void setPwdhash(String pwdhash) {
        writeProperty("pwdhash", pwdhash);
    }
    public String getPwdhash() {
        return (String)readProperty("pwdhash");
    }

    public void setPwdsalt(String pwdsalt) {
        writeProperty("pwdsalt", pwdsalt);
    }
    public String getPwdsalt() {
        return (String)readProperty("pwdsalt");
    }

    public void setUltimoaccesso(Timestamp ultimoaccesso) {
        writeProperty("ultimoaccesso", ultimoaccesso);
    }
    public Timestamp getUltimoaccesso() {
        return (Timestamp)readProperty("ultimoaccesso");
    }

    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }

    public void addToAnagraficaArray(Anagrafica obj) {
        addToManyTarget("anagraficaArray", obj, true);
    }
    public void removeFromAnagraficaArray(Anagrafica obj) {
        removeToManyTarget("anagraficaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Anagrafica> getAnagraficaArray() {
        return (List<Anagrafica>)readProperty("anagraficaArray");
    }


    public void addToCedolinoArray(Cedolino obj) {
        addToManyTarget("cedolinoArray", obj, true);
    }
    public void removeFromCedolinoArray(Cedolino obj) {
        removeToManyTarget("cedolinoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cedolino> getCedolinoArray() {
        return (List<Cedolino>)readProperty("cedolinoArray");
    }


    public void addToDichiarazioneArray(Dichiarazione obj) {
        addToManyTarget("dichiarazioneArray", obj, true);
    }
    public void removeFromDichiarazioneArray(Dichiarazione obj) {
        removeToManyTarget("dichiarazioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Dichiarazione> getDichiarazioneArray() {
        return (List<Dichiarazione>)readProperty("dichiarazioneArray");
    }


    public void addToDocumentoAutoreArray(Documento obj) {
        addToManyTarget("documentoAutoreArray", obj, true);
    }
    public void removeFromDocumentoAutoreArray(Documento obj) {
        removeToManyTarget("documentoAutoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Documento> getDocumentoAutoreArray() {
        return (List<Documento>)readProperty("documentoAutoreArray");
    }


    public void addToDocumentoRevisoreArray(Documento obj) {
        addToManyTarget("documentoRevisoreArray", obj, true);
    }
    public void removeFromDocumentoRevisoreArray(Documento obj) {
        removeToManyTarget("documentoRevisoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Documento> getDocumentoRevisoreArray() {
        return (List<Documento>)readProperty("documentoRevisoreArray");
    }


    public void addToPosizionelavoratoreArray(Posizionelavoratore obj) {
        addToManyTarget("posizionelavoratoreArray", obj, true);
    }
    public void removeFromPosizionelavoratoreArray(Posizionelavoratore obj) {
        removeToManyTarget("posizionelavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionelavoratore> getPosizionelavoratoreArray() {
        return (List<Posizionelavoratore>)readProperty("posizionelavoratoreArray");
    }


    public void setToPersonaFisica(Personafisica toPersonaFisica) {
        setToOneTarget("toPersonaFisica", toPersonaFisica, true);
    }

    public Personafisica getToPersonaFisica() {
        return (Personafisica)readProperty("toPersonaFisica");
    }


    public void setToRuolo(Ruolo toRuolo) {
        setToOneTarget("toRuolo", toRuolo, true);
    }

    public Ruolo getToRuolo() {
        return (Ruolo)readProperty("toRuolo");
    }


    public void setToTitolaredati(Titolaredati toTitolaredati) {
        setToOneTarget("toTitolaredati", toTitolaredati, true);
    }

    public Titolaredati getToTitolaredati() {
        return (Titolaredati)readProperty("toTitolaredati");
    }


    public void addToUtenteazioneArray(UtenteAzione obj) {
        addToManyTarget("utenteazioneArray", obj, true);
    }
    public void removeFromUtenteazioneArray(UtenteAzione obj) {
        removeToManyTarget("utenteazioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<UtenteAzione> getUtenteazioneArray() {
        return (List<UtenteAzione>)readProperty("utenteazioneArray");
    }


}
