package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DrCausalerestituzanf;
import it.iubar.paghe.logic.paghe.Gestioneanf;

/**
 * Class _Anfadebito was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Anfadebito extends CayenneDataObject {

    public static final String IDANFADEBITO_PROPERTY = "idanfadebito";
    public static final String IDCAUSALERESTITUZANF_PROPERTY = "idcausalerestituzanf";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IMPORTORESTITUZIONEANF_PROPERTY = "importorestituzioneanf";
    public static final String TO_DR_CAUSALE_RESTITUZ_ANF_PROPERTY = "toDrCausaleRestituzAnf";
    public static final String TO_GESTIONE_ANF_PROPERTY = "toGestioneAnf";

    public static final String IDANFADEBITO_PK_COLUMN = "IDANFADEBITO";
    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIdanfadebito(Short idanfadebito) {
        writeProperty("idanfadebito", idanfadebito);
    }
    public Short getIdanfadebito() {
        return (Short)readProperty("idanfadebito");
    }

    public void setIdcausalerestituzanf(String idcausalerestituzanf) {
        writeProperty("idcausalerestituzanf", idcausalerestituzanf);
    }
    public String getIdcausalerestituzanf() {
        return (String)readProperty("idcausalerestituzanf");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setImportorestituzioneanf(BigDecimal importorestituzioneanf) {
        writeProperty("importorestituzioneanf", importorestituzioneanf);
    }
    public BigDecimal getImportorestituzioneanf() {
        return (BigDecimal)readProperty("importorestituzioneanf");
    }

    public void setToDrCausaleRestituzAnf(DrCausalerestituzanf toDrCausaleRestituzAnf) {
        setToOneTarget("toDrCausaleRestituzAnf", toDrCausaleRestituzAnf, true);
    }

    public DrCausalerestituzanf getToDrCausaleRestituzAnf() {
        return (DrCausalerestituzanf)readProperty("toDrCausaleRestituzAnf");
    }


    public void setToGestioneAnf(Gestioneanf toGestioneAnf) {
        setToOneTarget("toGestioneAnf", toGestioneAnf, true);
    }

    public Gestioneanf getToGestioneAnf() {
        return (Gestioneanf)readProperty("toGestioneAnf");
    }


}
