package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.InpsClasseanf;
import it.iubar.paghe.logic.paghe.InpsTipoanf;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;

/**
 * Class _Anf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Anf extends CayenneDataObject {

    public static final String ASSEGNO_PROPERTY = "assegno";
    public static final String IDCLASSEANF_PROPERTY = "idclasseanf";
    public static final String IDINPSTIPOANF_PROPERTY = "idinpstipoanf";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String NOTE_PROPERTY = "note";
    public static final String RIDUZIONE_PROPERTY = "riduzione";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String TO_INPS_CLASSEANF_PROPERTY = "toInpsClasseanf";
    public static final String TO_INPS_TIPOANF_PROPERTY = "toInpsTipoanf";
    public static final String TO_POSIZIONESUBORDINATO_PROPERTY = "toPosizionesubordinato";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    private void setAssegno(BigDecimal assegno) {
        writeProperty("assegno", assegno);
    }
    private BigDecimal getAssegno() {
        return (BigDecimal)readProperty("assegno");
    }

    public void setIdclasseanf(Short idclasseanf) {
        writeProperty("idclasseanf", idclasseanf);
    }
    public Short getIdclasseanf() {
        return (Short)readProperty("idclasseanf");
    }

    public void setIdinpstipoanf(String idinpstipoanf) {
        writeProperty("idinpstipoanf", idinpstipoanf);
    }
    public String getIdinpstipoanf() {
        return (String)readProperty("idinpstipoanf");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setRiduzione(BigDecimal riduzione) {
        writeProperty("riduzione", riduzione);
    }
    public BigDecimal getRiduzione() {
        return (BigDecimal)readProperty("riduzione");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void setToInpsClasseanf(InpsClasseanf toInpsClasseanf) {
        setToOneTarget("toInpsClasseanf", toInpsClasseanf, true);
    }

    public InpsClasseanf getToInpsClasseanf() {
        return (InpsClasseanf)readProperty("toInpsClasseanf");
    }


    public void setToInpsTipoanf(InpsTipoanf toInpsTipoanf) {
        setToOneTarget("toInpsTipoanf", toInpsTipoanf, true);
    }

    public InpsTipoanf getToInpsTipoanf() {
        return (InpsTipoanf)readProperty("toInpsTipoanf");
    }


    public void setToPosizionesubordinato(Posizionesubordinato toPosizionesubordinato) {
        setToOneTarget("toPosizionesubordinato", toPosizionesubordinato, true);
    }

    public Posizionesubordinato getToPosizionesubordinato() {
        return (Posizionesubordinato)readProperty("toPosizionesubordinato");
    }


}
