package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Assenzaopzione;
import it.iubar.paghe.logic.paghe.Datoretributivo;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;
import it.iubar.paghe.logic.paghe.Tipoassenza;

/**
 * Class _Assenza was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Assenza extends CayenneDataObject {

    public static final String GIORNATAINTERA_PROPERTY = "giornataintera";
    public static final String GIORNITOT_PROPERTY = "giornitot";
    public static final String GIORNOAL_PROPERTY = "giornoal";
    public static final String GIORNODAL_PROPERTY = "giornodal";
    public static final String IDASSENZA_PROPERTY = "idassenza";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IDOPZIONE_PROPERTY = "idopzione";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDTIPOASSENZA_PROPERTY = "idtipoassenza";
    public static final String INPSRMG_PROPERTY = "inpsrmg";
    public static final String MEZZAGIORNATA_PROPERTY = "mezzagiornata";
    public static final String OREAL_PROPERTY = "oreal";
    public static final String OREDAL_PROPERTY = "oredal";
    public static final String ORELAVPRIMOGG_PROPERTY = "orelavprimogg";
    public static final String ORETOT_PROPERTY = "oretot";
    public static final String SANZIONABILE_PROPERTY = "sanzionabile";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";
    public static final String TO_OPZIONE_PROPERTY = "toOpzione";
    public static final String TO_POSIZIONESUBORDINATO_PROPERTY = "toPosizionesubordinato";
    public static final String TO_TIPOASSENZA_PROPERTY = "toTipoassenza";

    public static final String IDASSENZA_PK_COLUMN = "IDASSENZA";

    public void setGiornataintera(Short giornataintera) {
        writeProperty("giornataintera", giornataintera);
    }
    public Short getGiornataintera() {
        return (Short)readProperty("giornataintera");
    }

    public void setGiornitot(BigDecimal giornitot) {
        writeProperty("giornitot", giornitot);
    }
    public BigDecimal getGiornitot() {
        return (BigDecimal)readProperty("giornitot");
    }

    public void setGiornoal(Date giornoal) {
        writeProperty("giornoal", giornoal);
    }
    public Date getGiornoal() {
        return (Date)readProperty("giornoal");
    }

    public void setGiornodal(Date giornodal) {
        writeProperty("giornodal", giornodal);
    }
    public Date getGiornodal() {
        return (Date)readProperty("giornodal");
    }

    public void setIdassenza(Integer idassenza) {
        writeProperty("idassenza", idassenza);
    }
    public Integer getIdassenza() {
        return (Integer)readProperty("idassenza");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIdopzione(Short idopzione) {
        writeProperty("idopzione", idopzione);
    }
    public Short getIdopzione() {
        return (Short)readProperty("idopzione");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdtipoassenza(Short idtipoassenza) {
        writeProperty("idtipoassenza", idtipoassenza);
    }
    public Short getIdtipoassenza() {
        return (Short)readProperty("idtipoassenza");
    }

    public void setInpsrmg(BigDecimal inpsrmg) {
        writeProperty("inpsrmg", inpsrmg);
    }
    public BigDecimal getInpsrmg() {
        return (BigDecimal)readProperty("inpsrmg");
    }

    public void setMezzagiornata(Short mezzagiornata) {
        writeProperty("mezzagiornata", mezzagiornata);
    }
    public Short getMezzagiornata() {
        return (Short)readProperty("mezzagiornata");
    }

    public void setOreal(Date oreal) {
        writeProperty("oreal", oreal);
    }
    public Date getOreal() {
        return (Date)readProperty("oreal");
    }

    public void setOredal(Date oredal) {
        writeProperty("oredal", oredal);
    }
    public Date getOredal() {
        return (Date)readProperty("oredal");
    }

    public void setOrelavprimogg(BigDecimal orelavprimogg) {
        writeProperty("orelavprimogg", orelavprimogg);
    }
    public BigDecimal getOrelavprimogg() {
        return (BigDecimal)readProperty("orelavprimogg");
    }

    public void setOretot(BigDecimal oretot) {
        writeProperty("oretot", oretot);
    }
    public BigDecimal getOretot() {
        return (BigDecimal)readProperty("oretot");
    }

    public void setSanzionabile(Short sanzionabile) {
        writeProperty("sanzionabile", sanzionabile);
    }
    public Short getSanzionabile() {
        return (Short)readProperty("sanzionabile");
    }

    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


    public void setToOpzione(Assenzaopzione toOpzione) {
        setToOneTarget("toOpzione", toOpzione, true);
    }

    public Assenzaopzione getToOpzione() {
        return (Assenzaopzione)readProperty("toOpzione");
    }


    public void setToPosizionesubordinato(Posizionesubordinato toPosizionesubordinato) {
        setToOneTarget("toPosizionesubordinato", toPosizionesubordinato, true);
    }

    public Posizionesubordinato getToPosizionesubordinato() {
        return (Posizionesubordinato)readProperty("toPosizionesubordinato");
    }


    public void setToTipoassenza(Tipoassenza toTipoassenza) {
        setToOneTarget("toTipoassenza", toTipoassenza, true);
    }

    public Tipoassenza getToTipoassenza() {
        return (Tipoassenza)readProperty("toTipoassenza");
    }


}
