package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Utente;
import it.iubar.paghe.logic.blob.Documento;
import it.iubar.paghe.logic.paghe.CedolinoElemento;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.ContrattodettagliovoceCedolino;
import it.iubar.paghe.logic.paghe.Numerazioneunica;
import it.iubar.paghe.logic.paghe.Posizionelavoratore;
import it.iubar.paghe.logic.paghe.Tipofoglio;

/**
 * Class _Cedolino was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Cedolino extends CayenneDataObject {

    public static final String ARROTONDAMENTO_PROPERTY = "arrotondamento";
    public static final String ARROTONDAMENTOPREC_PROPERTY = "arrotondamentoprec";
    public static final String GIORNIEFFETTIVI_PROPERTY = "giornieffettivi";
    public static final String GIORNIINPS_PROPERTY = "giorniinps";
    public static final String GIORNIORDINARI_PROPERTY = "giorniordinari";
    public static final String GIORNIRETRIBUITI_PROPERTY = "giorniretribuiti";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDINAIL_PROPERTY = "idinail";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDTIPOFOGLIO_PROPERTY = "idtipofoglio";
    public static final String IDTIPORETRIBUZIONE_PROPERTY = "idtiporetribuzione";
    public static final String MINTABELLARE_PROPERTY = "mintabellare";
    public static final String NOTE_PROPERTY = "note";
    public static final String NUMERAZIONE_PROPERTY = "numerazione";
    public static final String OREEFFETTIVE_PROPERTY = "oreeffettive";
    public static final String OREORDINARIE_PROPERTY = "oreordinarie";
    public static final String ORERETRIBUITE_PROPERTY = "oreretribuite";
    public static final String RETRIBGLOBALEDIFATTO_PROPERTY = "retribglobaledifatto";
    public static final String SETTIMANEINPS_PROPERTY = "settimaneinps";
    public static final String TOTALERETRIBLORDA_PROPERTY = "totaleretriblorda";
    public static final String TOTALERETRIBNETTA_PROPERTY = "totaleretribnetta";
    public static final String ULTIMAELABORAZIONE_PROPERTY = "ultimaelaborazione";
    public static final String ULTIMAELABORAZIONEUSER_PROPERTY = "ultimaelaborazioneuser";
    public static final String CEDOLINO_ELEMENTO_ARRAY_PROPERTY = "cedolinoElementoArray";
    public static final String LIVELLOVOCE_CEDOLINO_ARRAY_PROPERTY = "livellovoceCedolinoArray";
    public static final String NUMERAZIONEUNICA_ARRAY_PROPERTY = "numerazioneunicaArray";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_DOCUMENTO_PROPERTY = "toDocumento";
    public static final String TO_POSIZIONELAVORATORE_PROPERTY = "toPosizionelavoratore";
    public static final String TO_TIPOFOGLIO_PROPERTY = "toTipofoglio";
    public static final String TO_UTENTE_ULTIMAELABORAZIONE_PROPERTY = "toUtenteUltimaelaborazione";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";
    public static final String IDTIPOFOGLIO_PK_COLUMN = "IDTIPOFOGLIO";

    public void setArrotondamento(BigDecimal arrotondamento) {
        writeProperty("arrotondamento", arrotondamento);
    }
    public BigDecimal getArrotondamento() {
        return (BigDecimal)readProperty("arrotondamento");
    }

    public void setArrotondamentoprec(BigDecimal arrotondamentoprec) {
        writeProperty("arrotondamentoprec", arrotondamentoprec);
    }
    public BigDecimal getArrotondamentoprec() {
        return (BigDecimal)readProperty("arrotondamentoprec");
    }

    public void setGiornieffettivi(BigDecimal giornieffettivi) {
        writeProperty("giornieffettivi", giornieffettivi);
    }
    public BigDecimal getGiornieffettivi() {
        return (BigDecimal)readProperty("giornieffettivi");
    }

    public void setGiorniinps(BigDecimal giorniinps) {
        writeProperty("giorniinps", giorniinps);
    }
    public BigDecimal getGiorniinps() {
        return (BigDecimal)readProperty("giorniinps");
    }

    public void setGiorniordinari(BigDecimal giorniordinari) {
        writeProperty("giorniordinari", giorniordinari);
    }
    public BigDecimal getGiorniordinari() {
        return (BigDecimal)readProperty("giorniordinari");
    }

    public void setGiorniretribuiti(BigDecimal giorniretribuiti) {
        writeProperty("giorniretribuiti", giorniretribuiti);
    }
    public BigDecimal getGiorniretribuiti() {
        return (BigDecimal)readProperty("giorniretribuiti");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdinail(Integer idinail) {
        writeProperty("idinail", idinail);
    }
    public Integer getIdinail() {
        return (Integer)readProperty("idinail");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdtipofoglio(Short idtipofoglio) {
        writeProperty("idtipofoglio", idtipofoglio);
    }
    public Short getIdtipofoglio() {
        return (Short)readProperty("idtipofoglio");
    }

    public void setIdtiporetribuzione(Short idtiporetribuzione) {
        writeProperty("idtiporetribuzione", idtiporetribuzione);
    }
    public Short getIdtiporetribuzione() {
        return (Short)readProperty("idtiporetribuzione");
    }

    public void setMintabellare(BigDecimal mintabellare) {
        writeProperty("mintabellare", mintabellare);
    }
    public BigDecimal getMintabellare() {
        return (BigDecimal)readProperty("mintabellare");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setNumerazione(Integer numerazione) {
        writeProperty("numerazione", numerazione);
    }
    public Integer getNumerazione() {
        return (Integer)readProperty("numerazione");
    }

    public void setOreeffettive(BigDecimal oreeffettive) {
        writeProperty("oreeffettive", oreeffettive);
    }
    public BigDecimal getOreeffettive() {
        return (BigDecimal)readProperty("oreeffettive");
    }

    public void setOreordinarie(BigDecimal oreordinarie) {
        writeProperty("oreordinarie", oreordinarie);
    }
    public BigDecimal getOreordinarie() {
        return (BigDecimal)readProperty("oreordinarie");
    }

    public void setOreretribuite(BigDecimal oreretribuite) {
        writeProperty("oreretribuite", oreretribuite);
    }
    public BigDecimal getOreretribuite() {
        return (BigDecimal)readProperty("oreretribuite");
    }

    public void setRetribglobaledifatto(BigDecimal retribglobaledifatto) {
        writeProperty("retribglobaledifatto", retribglobaledifatto);
    }
    public BigDecimal getRetribglobaledifatto() {
        return (BigDecimal)readProperty("retribglobaledifatto");
    }

    public void setSettimaneinps(BigDecimal settimaneinps) {
        writeProperty("settimaneinps", settimaneinps);
    }
    public BigDecimal getSettimaneinps() {
        return (BigDecimal)readProperty("settimaneinps");
    }

    public void setTotaleretriblorda(BigDecimal totaleretriblorda) {
        writeProperty("totaleretriblorda", totaleretriblorda);
    }
    public BigDecimal getTotaleretriblorda() {
        return (BigDecimal)readProperty("totaleretriblorda");
    }

    public void setTotaleretribnetta(BigDecimal totaleretribnetta) {
        writeProperty("totaleretribnetta", totaleretribnetta);
    }
    public BigDecimal getTotaleretribnetta() {
        return (BigDecimal)readProperty("totaleretribnetta");
    }

    public void setUltimaelaborazione(Timestamp ultimaelaborazione) {
        writeProperty("ultimaelaborazione", ultimaelaborazione);
    }
    public Timestamp getUltimaelaborazione() {
        return (Timestamp)readProperty("ultimaelaborazione");
    }

    public void setUltimaelaborazioneuser(String ultimaelaborazioneuser) {
        writeProperty("ultimaelaborazioneuser", ultimaelaborazioneuser);
    }
    public String getUltimaelaborazioneuser() {
        return (String)readProperty("ultimaelaborazioneuser");
    }

    public void addToCedolinoElementoArray(CedolinoElemento obj) {
        addToManyTarget("cedolinoElementoArray", obj, true);
    }
    public void removeFromCedolinoElementoArray(CedolinoElemento obj) {
        removeToManyTarget("cedolinoElementoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CedolinoElemento> getCedolinoElementoArray() {
        return (List<CedolinoElemento>)readProperty("cedolinoElementoArray");
    }


    public void addToLivellovoceCedolinoArray(ContrattodettagliovoceCedolino obj) {
        addToManyTarget("livellovoceCedolinoArray", obj, true);
    }
    public void removeFromLivellovoceCedolinoArray(ContrattodettagliovoceCedolino obj) {
        removeToManyTarget("livellovoceCedolinoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContrattodettagliovoceCedolino> getLivellovoceCedolinoArray() {
        return (List<ContrattodettagliovoceCedolino>)readProperty("livellovoceCedolinoArray");
    }


    public void addToNumerazioneunicaArray(Numerazioneunica obj) {
        addToManyTarget("numerazioneunicaArray", obj, true);
    }
    public void removeFromNumerazioneunicaArray(Numerazioneunica obj) {
        removeToManyTarget("numerazioneunicaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Numerazioneunica> getNumerazioneunicaArray() {
        return (List<Numerazioneunica>)readProperty("numerazioneunicaArray");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToDocumento(Documento toDocumento) {
        setToOneTarget("toDocumento", toDocumento, true);
    }

    public Documento getToDocumento() {
        return (Documento)readProperty("toDocumento");
    }


    public void setToPosizionelavoratore(Posizionelavoratore toPosizionelavoratore) {
        setToOneTarget("toPosizionelavoratore", toPosizionelavoratore, true);
    }

    public Posizionelavoratore getToPosizionelavoratore() {
        return (Posizionelavoratore)readProperty("toPosizionelavoratore");
    }


    public void setToTipofoglio(Tipofoglio toTipofoglio) {
        setToOneTarget("toTipofoglio", toTipofoglio, true);
    }

    public Tipofoglio getToTipofoglio() {
        return (Tipofoglio)readProperty("toTipofoglio");
    }


    public void setToUtenteUltimaelaborazione(Utente toUtenteUltimaelaborazione) {
        setToOneTarget("toUtenteUltimaelaborazione", toUtenteUltimaelaborazione, true);
    }

    public Utente getToUtenteUltimaelaborazione() {
        return (Utente)readProperty("toUtenteUltimaelaborazione");
    }


}
