package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DrCausalecontribaddcigs;
import it.iubar.paghe.logic.paghe.Gestionecig;

/**
 * Class _Cigsadebito was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Cigsadebito extends CayenneDataObject {

    public static final String IDCAUSALECONTRIBADDCIGS_PROPERTY = "idcausalecontribaddcigs";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IMPORTOCONTRADDCIGS_PROPERTY = "importocontraddcigs";
    public static final String TO_DR_CAUSALE_CONTR_ADD_CIGS_PROPERTY = "toDrCausaleContrAddCigs";
    public static final String TO_GESTIONE_CIG_PROPERTY = "toGestioneCig";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIdcausalecontribaddcigs(String idcausalecontribaddcigs) {
        writeProperty("idcausalecontribaddcigs", idcausalecontribaddcigs);
    }
    public String getIdcausalecontribaddcigs() {
        return (String)readProperty("idcausalecontribaddcigs");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setImportocontraddcigs(BigDecimal importocontraddcigs) {
        writeProperty("importocontraddcigs", importocontraddcigs);
    }
    public BigDecimal getImportocontraddcigs() {
        return (BigDecimal)readProperty("importocontraddcigs");
    }

    public void setToDrCausaleContrAddCigs(DrCausalecontribaddcigs toDrCausaleContrAddCigs) {
        setToOneTarget("toDrCausaleContrAddCigs", toDrCausaleContrAddCigs, true);
    }

    public DrCausalecontribaddcigs getToDrCausaleContrAddCigs() {
        return (DrCausalecontribaddcigs)readProperty("toDrCausaleContrAddCigs");
    }


    public void setToGestioneCig(Gestionecig toGestioneCig) {
        setToOneTarget("toGestioneCig", toGestioneCig, true);
    }

    public Gestionecig getToGestioneCig() {
        return (Gestionecig)readProperty("toGestioneCig");
    }


}
