package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.CnceCassaedileconfig;

/**
 * Class _CnceCassaedileperc was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CnceCassaedileperc extends CayenneDataObject {

    public static final String ADESIONECONTRATTNAZ_PROPERTY = "adesionecontrattnaz";
    public static final String ADESIONECONTRATTTERR_PROPERTY = "adesionecontrattterr";
    public static final String APE_PROPERTY = "ape";
    public static final String FONDOSICUREZZA_PROPERTY = "fondosicurezza";
    public static final String IDCARICO_PROPERTY = "idcarico";
    public static final String IDCASSAEDILE_PROPERTY = "idcassaedile";
    public static final String ISTRUZPROF_PROPERTY = "istruzprof";
    public static final String PREVIDENZASOCIALE_PROPERTY = "previdenzasociale";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String TO_CASSA_EDILE_CONFIG_PROPERTY = "toCassaEdileConfig";

    public static final String IDCARICO_PK_COLUMN = "IDCARICO";
    public static final String IDCASSAEDILE_PK_COLUMN = "IDCASSAEDILE";

    public void setAdesionecontrattnaz(BigDecimal adesionecontrattnaz) {
        writeProperty("adesionecontrattnaz", adesionecontrattnaz);
    }
    public BigDecimal getAdesionecontrattnaz() {
        return (BigDecimal)readProperty("adesionecontrattnaz");
    }

    public void setAdesionecontrattterr(BigDecimal adesionecontrattterr) {
        writeProperty("adesionecontrattterr", adesionecontrattterr);
    }
    public BigDecimal getAdesionecontrattterr() {
        return (BigDecimal)readProperty("adesionecontrattterr");
    }

    public void setApe(BigDecimal ape) {
        writeProperty("ape", ape);
    }
    public BigDecimal getApe() {
        return (BigDecimal)readProperty("ape");
    }

    public void setFondosicurezza(BigDecimal fondosicurezza) {
        writeProperty("fondosicurezza", fondosicurezza);
    }
    public BigDecimal getFondosicurezza() {
        return (BigDecimal)readProperty("fondosicurezza");
    }

    public void setIdcarico(Short idcarico) {
        writeProperty("idcarico", idcarico);
    }
    public Short getIdcarico() {
        return (Short)readProperty("idcarico");
    }

    public void setIdcassaedile(String idcassaedile) {
        writeProperty("idcassaedile", idcassaedile);
    }
    public String getIdcassaedile() {
        return (String)readProperty("idcassaedile");
    }

    public void setIstruzprof(BigDecimal istruzprof) {
        writeProperty("istruzprof", istruzprof);
    }
    public BigDecimal getIstruzprof() {
        return (BigDecimal)readProperty("istruzprof");
    }

    public void setPrevidenzasociale(BigDecimal previdenzasociale) {
        writeProperty("previdenzasociale", previdenzasociale);
    }
    public BigDecimal getPrevidenzasociale() {
        return (BigDecimal)readProperty("previdenzasociale");
    }

    public void setValidoal(Date validoal) {
        writeProperty("validoal", validoal);
    }
    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void setToCassaEdileConfig(CnceCassaedileconfig toCassaEdileConfig) {
        setToOneTarget("toCassaEdileConfig", toCassaEdileConfig, true);
    }

    public CnceCassaedileconfig getToCassaEdileConfig() {
        return (CnceCassaedileconfig)readProperty("toCassaEdileConfig");
    }


}
