package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _CncePrevcomptipo2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CncePrevcomptipo2 extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOADESIONE2_PROPERTY = "idtipoadesione2";

    public static final String IDTIPOADESIONE2_PK_COLUMN = "IDTIPOADESIONE2";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdtipoadesione2() {
        return (Short)readProperty("idtipoadesione2");
    }

}
