package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _CncePosizionelavoratore was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CncePosizionelavoratore extends CayenneDataObject {

    public static final String IDCANTIERE_PROPERTY = "idcantiere";
    public static final String IDESENZIONELIMITECCNL_PROPERTY = "idesenzionelimiteccnl";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDLAVORATORE_PROPERTY = "idlavoratore";
    public static final String IDLIVELLOQUALIFICA_PROPERTY = "idlivelloqualifica";
    public static final String IDMANSIONE_PROPERTY = "idmansione";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDTIPOASSUNZIONE_PROPERTY = "idtipoassunzione";
    public static final String IDTIPOCESSAZIONE_PROPERTY = "idtipocessazione";
    public static final String IDTIPORAPPORTO_PROPERTY = "idtiporapporto";
    public static final String ORESETTIMANALI_PROPERTY = "oresettimanali";
    public static final String PARTTIMEORARIO_PROPERTY = "parttimeorario";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setIdcantiere(Short idcantiere) {
        writeProperty("idcantiere", idcantiere);
    }
    public Short getIdcantiere() {
        return (Short)readProperty("idcantiere");
    }

    public void setIdesenzionelimiteccnl(Short idesenzionelimiteccnl) {
        writeProperty("idesenzionelimiteccnl", idesenzionelimiteccnl);
    }
    public Short getIdesenzionelimiteccnl() {
        return (Short)readProperty("idesenzionelimiteccnl");
    }

    public void setIdimpresa(Short idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Short getIdimpresa() {
        return (Short)readProperty("idimpresa");
    }

    public void setIdlavoratore(Integer idlavoratore) {
        writeProperty("idlavoratore", idlavoratore);
    }
    public Integer getIdlavoratore() {
        return (Integer)readProperty("idlavoratore");
    }

    public void setIdlivelloqualifica(String idlivelloqualifica) {
        writeProperty("idlivelloqualifica", idlivelloqualifica);
    }
    public String getIdlivelloqualifica() {
        return (String)readProperty("idlivelloqualifica");
    }

    public void setIdmansione(String idmansione) {
        writeProperty("idmansione", idmansione);
    }
    public String getIdmansione() {
        return (String)readProperty("idmansione");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdtipoassunzione(Short idtipoassunzione) {
        writeProperty("idtipoassunzione", idtipoassunzione);
    }
    public Short getIdtipoassunzione() {
        return (Short)readProperty("idtipoassunzione");
    }

    public void setIdtipocessazione(Short idtipocessazione) {
        writeProperty("idtipocessazione", idtipocessazione);
    }
    public Short getIdtipocessazione() {
        return (Short)readProperty("idtipocessazione");
    }

    public void setIdtiporapporto(Short idtiporapporto) {
        writeProperty("idtiporapporto", idtiporapporto);
    }
    public Short getIdtiporapporto() {
        return (Short)readProperty("idtiporapporto");
    }

    public void setOresettimanali(Short oresettimanali) {
        writeProperty("oresettimanali", oresettimanali);
    }
    public Short getOresettimanali() {
        return (Short)readProperty("oresettimanali");
    }

    public void setParttimeorario(BigDecimal parttimeorario) {
        writeProperty("parttimeorario", parttimeorario);
    }
    public BigDecimal getParttimeorario() {
        return (BigDecimal)readProperty("parttimeorario");
    }

}
