package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Tipolavoratore2;
import it.iubar.paghe.logic.paghe.Contrattoanzianita;
import it.iubar.paghe.logic.paghe.Contrattocoefficiente;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Elementobaseimponibile;
import it.iubar.paghe.logic.paghe.Posizionescatto;
import it.iubar.paghe.logic.paghe.Profilolavoratore;
import it.iubar.paghe.logic.paghe.Profiloscatto;

/**
 * Class _Contrattoscatto was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattoscatto extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String IDBASEIMPONIBILE_PROPERTY = "idbaseimponibile";
    public static final String IDCOEFFICIENTE_PROPERTY = "idcoefficiente";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDLIVELLO_PROPERTY = "idlivello";
    public static final String IDSCATTO_PROPERTY = "idscatto";
    public static final String IDTIPOLAVORATORE2_PROPERTY = "idtipolavoratore2";
    public static final String IMPORTO_PROPERTY = "importo";
    public static final String NOTE_PROPERTY = "note";
    public static final String PERCENTUALE_PROPERTY = "percentuale";
    public static final String SCATTI_PROPERTY = "scatti";
    public static final String SCATTIMESI_PROPERTY = "scattimesi";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String POSIZIONESCATTO_ARRAY_PROPERTY = "posizionescattoArray";
    public static final String PROFILOSCATTO_ARRAY_PROPERTY = "profiloscattoArray";
    public static final String PROFILOSUBORDINATO_ARRAY_PROPERTY = "profilosubordinatoArray";
    public static final String TO_BASEIMPONIBILE_PROPERTY = "toBaseimponibile";
    public static final String TO_CONTRATTOANZIANITA_PROPERTY = "toContrattoanzianita";
    public static final String TO_CONTRATTOCOEFFICIENTE_PROPERTY = "toContrattocoefficiente";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_TIPOLAVORATORE2_PROPERTY = "toTipolavoratore2";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDSCATTO_PK_COLUMN = "IDSCATTO";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setIdbaseimponibile(Integer idbaseimponibile) {
        writeProperty("idbaseimponibile", idbaseimponibile);
    }
    public Integer getIdbaseimponibile() {
        return (Integer)readProperty("idbaseimponibile");
    }

    public void setIdcoefficiente(Short idcoefficiente) {
        writeProperty("idcoefficiente", idcoefficiente);
    }
    public Short getIdcoefficiente() {
        return (Short)readProperty("idcoefficiente");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdlivello(String idlivello) {
        writeProperty("idlivello", idlivello);
    }
    public String getIdlivello() {
        return (String)readProperty("idlivello");
    }

    public void setIdscatto(Short idscatto) {
        writeProperty("idscatto", idscatto);
    }
    public Short getIdscatto() {
        return (Short)readProperty("idscatto");
    }

    public void setIdtipolavoratore2(Short idtipolavoratore2) {
        writeProperty("idtipolavoratore2", idtipolavoratore2);
    }
    public Short getIdtipolavoratore2() {
        return (Short)readProperty("idtipolavoratore2");
    }

    public void setImporto(BigDecimal importo) {
        writeProperty("importo", importo);
    }
    public BigDecimal getImporto() {
        return (BigDecimal)readProperty("importo");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setPercentuale(BigDecimal percentuale) {
        writeProperty("percentuale", percentuale);
    }
    public BigDecimal getPercentuale() {
        return (BigDecimal)readProperty("percentuale");
    }

    public void setScatti(Short scatti) {
        writeProperty("scatti", scatti);
    }
    public Short getScatti() {
        return (Short)readProperty("scatti");
    }

    public void setScattimesi(Short scattimesi) {
        writeProperty("scattimesi", scattimesi);
    }
    public Short getScattimesi() {
        return (Short)readProperty("scattimesi");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToPosizionescattoArray(Posizionescatto obj) {
        addToManyTarget("posizionescattoArray", obj, true);
    }
    public void removeFromPosizionescattoArray(Posizionescatto obj) {
        removeToManyTarget("posizionescattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionescatto> getPosizionescattoArray() {
        return (List<Posizionescatto>)readProperty("posizionescattoArray");
    }


    public void addToProfiloscattoArray(Profiloscatto obj) {
        addToManyTarget("profiloscattoArray", obj, true);
    }
    public void removeFromProfiloscattoArray(Profiloscatto obj) {
        removeToManyTarget("profiloscattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profiloscatto> getProfiloscattoArray() {
        return (List<Profiloscatto>)readProperty("profiloscattoArray");
    }


    public void addToProfilosubordinatoArray(Profilolavoratore obj) {
        addToManyTarget("profilosubordinatoArray", obj, true);
    }
    public void removeFromProfilosubordinatoArray(Profilolavoratore obj) {
        removeToManyTarget("profilosubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profilolavoratore> getProfilosubordinatoArray() {
        return (List<Profilolavoratore>)readProperty("profilosubordinatoArray");
    }


    public void setToBaseimponibile(Elementobaseimponibile toBaseimponibile) {
        setToOneTarget("toBaseimponibile", toBaseimponibile, true);
    }

    public Elementobaseimponibile getToBaseimponibile() {
        return (Elementobaseimponibile)readProperty("toBaseimponibile");
    }


    public void setToContrattoanzianita(Contrattoanzianita toContrattoanzianita) {
        setToOneTarget("toContrattoanzianita", toContrattoanzianita, true);
    }

    public Contrattoanzianita getToContrattoanzianita() {
        return (Contrattoanzianita)readProperty("toContrattoanzianita");
    }


    public void setToContrattocoefficiente(Contrattocoefficiente toContrattocoefficiente) {
        setToOneTarget("toContrattocoefficiente", toContrattocoefficiente, true);
    }

    public Contrattocoefficiente getToContrattocoefficiente() {
        return (Contrattocoefficiente)readProperty("toContrattocoefficiente");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToTipolavoratore2(Tipolavoratore2 toTipolavoratore2) {
        setToOneTarget("toTipolavoratore2", toTipolavoratore2, true);
    }

    public Tipolavoratore2 getToTipolavoratore2() {
        return (Tipolavoratore2)readProperty("toTipolavoratore2");
    }


}
