package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Tipolavoratore2;
import it.iubar.paghe.logic.paghe.Contrattocoefficiente;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Contrattorateovalore;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;
import it.iubar.paghe.logic.paghe.Profilolavoratore;

/**
 * Class _Contrattorateo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattorateo extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String IDCOEFFICIENTE_PROPERTY = "idcoefficiente";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDRATEO_PROPERTY = "idrateo";
    public static final String IDTIPOLAVORATORE2_PROPERTY = "idtipolavoratore2";
    public static final String NOTA_PROPERTY = "nota";
    public static final String CONTRATTORATEOVALORE_ARRAY_PROPERTY = "contrattorateovaloreArray";
    public static final String POSIZIONESUBORDINATO_ARRAY_PROPERTY = "posizionesubordinatoArray";
    public static final String PROFILOSUBORDINATO_ARRAY_PROPERTY = "profilosubordinatoArray";
    public static final String TO_CONTRATTOCOEFFICIENTE_PROPERTY = "toContrattocoefficiente";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_TIPOLAVORATORE2_PROPERTY = "toTipolavoratore2";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDRATEO_PK_COLUMN = "IDRATEO";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setIdcoefficiente(Short idcoefficiente) {
        writeProperty("idcoefficiente", idcoefficiente);
    }
    public Short getIdcoefficiente() {
        return (Short)readProperty("idcoefficiente");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdrateo(Short idrateo) {
        writeProperty("idrateo", idrateo);
    }
    public Short getIdrateo() {
        return (Short)readProperty("idrateo");
    }

    public void setIdtipolavoratore2(Short idtipolavoratore2) {
        writeProperty("idtipolavoratore2", idtipolavoratore2);
    }
    public Short getIdtipolavoratore2() {
        return (Short)readProperty("idtipolavoratore2");
    }

    public void setNota(String nota) {
        writeProperty("nota", nota);
    }
    public String getNota() {
        return (String)readProperty("nota");
    }

    public void addToContrattorateovaloreArray(Contrattorateovalore obj) {
        addToManyTarget("contrattorateovaloreArray", obj, true);
    }
    public void removeFromContrattorateovaloreArray(Contrattorateovalore obj) {
        removeToManyTarget("contrattorateovaloreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattorateovalore> getContrattorateovaloreArray() {
        return (List<Contrattorateovalore>)readProperty("contrattorateovaloreArray");
    }


    public void addToPosizionesubordinatoArray(Posizionesubordinato obj) {
        addToManyTarget("posizionesubordinatoArray", obj, true);
    }
    public void removeFromPosizionesubordinatoArray(Posizionesubordinato obj) {
        removeToManyTarget("posizionesubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionesubordinato> getPosizionesubordinatoArray() {
        return (List<Posizionesubordinato>)readProperty("posizionesubordinatoArray");
    }


    public void addToProfilosubordinatoArray(Profilolavoratore obj) {
        addToManyTarget("profilosubordinatoArray", obj, true);
    }
    public void removeFromProfilosubordinatoArray(Profilolavoratore obj) {
        removeToManyTarget("profilosubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profilolavoratore> getProfilosubordinatoArray() {
        return (List<Profilolavoratore>)readProperty("profilosubordinatoArray");
    }


    public void setToContrattocoefficiente(Contrattocoefficiente toContrattocoefficiente) {
        setToOneTarget("toContrattocoefficiente", toContrattocoefficiente, true);
    }

    public Contrattocoefficiente getToContrattocoefficiente() {
        return (Contrattocoefficiente)readProperty("toContrattocoefficiente");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToTipolavoratore2(Tipolavoratore2 toTipolavoratore2) {
        setToOneTarget("toTipolavoratore2", toTipolavoratore2, true);
    }

    public Tipolavoratore2 getToTipolavoratore2() {
        return (Tipolavoratore2)readProperty("toTipolavoratore2");
    }


}
