package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Tipolavoratore2;
import it.iubar.paghe.logic.paghe.Contrattocoefficiente;
import it.iubar.paghe.logic.paghe.Contrattofestivitaretrib2;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;
import it.iubar.paghe.logic.paghe.Profilolavoratore;

/**
 * Class _Contrattofestivitaretrib was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattofestivitaretrib extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String IDCOEFFICIENTE_PROPERTY = "idcoefficiente";
    public static final String IDFESTIVITARETRIB_PROPERTY = "idfestivitaretrib";
    public static final String IDTIPOLAVORATORE2_PROPERTY = "idtipolavoratore2";
    public static final String NOTE_PROPERTY = "note";
    public static final String OPZIONE_PROPERTY = "opzione";
    public static final String OPZIONEFESTSOPP_PROPERTY = "opzionefestsopp";
    public static final String OPZIONESABATO_PROPERTY = "opzionesabato";
    public static final String CONTRATTOFESTIVITARETRIB2ARRAY_PROPERTY = "contrattofestivitaretrib2Array";
    public static final String POSIZIONESUBORDINATO_ARRAY_PROPERTY = "posizionesubordinatoArray";
    public static final String PROFILOSUBORDINATO_ARRAY_PROPERTY = "profilosubordinatoArray";
    public static final String TO_CONTRATTOCOEFFICIENTE_PROPERTY = "toContrattocoefficiente";
    public static final String TO_TIPOLAVORATORE2_PROPERTY = "toTipolavoratore2";

    public static final String IDFESTIVITARETRIB_PK_COLUMN = "IDFESTIVITARETRIB";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setIdcoefficiente(Short idcoefficiente) {
        writeProperty("idcoefficiente", idcoefficiente);
    }
    public Short getIdcoefficiente() {
        return (Short)readProperty("idcoefficiente");
    }

    public void setIdfestivitaretrib(Short idfestivitaretrib) {
        writeProperty("idfestivitaretrib", idfestivitaretrib);
    }
    public Short getIdfestivitaretrib() {
        return (Short)readProperty("idfestivitaretrib");
    }

    public void setIdtipolavoratore2(Short idtipolavoratore2) {
        writeProperty("idtipolavoratore2", idtipolavoratore2);
    }
    public Short getIdtipolavoratore2() {
        return (Short)readProperty("idtipolavoratore2");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setOpzione(Short opzione) {
        writeProperty("opzione", opzione);
    }
    public Short getOpzione() {
        return (Short)readProperty("opzione");
    }

    public void setOpzionefestsopp(Short opzionefestsopp) {
        writeProperty("opzionefestsopp", opzionefestsopp);
    }
    public Short getOpzionefestsopp() {
        return (Short)readProperty("opzionefestsopp");
    }

    public void setOpzionesabato(Short opzionesabato) {
        writeProperty("opzionesabato", opzionesabato);
    }
    public Short getOpzionesabato() {
        return (Short)readProperty("opzionesabato");
    }

    public void addToContrattofestivitaretrib2Array(Contrattofestivitaretrib2 obj) {
        addToManyTarget("contrattofestivitaretrib2Array", obj, true);
    }
    public void removeFromContrattofestivitaretrib2Array(Contrattofestivitaretrib2 obj) {
        removeToManyTarget("contrattofestivitaretrib2Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattofestivitaretrib2> getContrattofestivitaretrib2Array() {
        return (List<Contrattofestivitaretrib2>)readProperty("contrattofestivitaretrib2Array");
    }


    public void addToPosizionesubordinatoArray(Posizionesubordinato obj) {
        addToManyTarget("posizionesubordinatoArray", obj, true);
    }
    public void removeFromPosizionesubordinatoArray(Posizionesubordinato obj) {
        removeToManyTarget("posizionesubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionesubordinato> getPosizionesubordinatoArray() {
        return (List<Posizionesubordinato>)readProperty("posizionesubordinatoArray");
    }


    public void addToProfilosubordinatoArray(Profilolavoratore obj) {
        addToManyTarget("profilosubordinatoArray", obj, true);
    }
    public void removeFromProfilosubordinatoArray(Profilolavoratore obj) {
        removeToManyTarget("profilosubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profilolavoratore> getProfilosubordinatoArray() {
        return (List<Profilolavoratore>)readProperty("profilosubordinatoArray");
    }


    public void setToContrattocoefficiente(Contrattocoefficiente toContrattocoefficiente) {
        setToOneTarget("toContrattocoefficiente", toContrattocoefficiente, true);
    }

    public Contrattocoefficiente getToContrattocoefficiente() {
        return (Contrattocoefficiente)readProperty("toContrattocoefficiente");
    }


    public void setToTipolavoratore2(Tipolavoratore2 toTipolavoratore2) {
        setToOneTarget("toTipolavoratore2", toTipolavoratore2, true);
    }

    public Tipolavoratore2 getToTipolavoratore2() {
        return (Tipolavoratore2)readProperty("toTipolavoratore2");
    }


}
