package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoparticolare;
import it.iubar.paghe.logic.paghe.InpsCodconv;

/**
 * Class _Convenzbilaterale was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Convenzbilaterale extends CayenneDataObject {

    public static final String IDCODCONV_PROPERTY = "idcodconv";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IMPORTO_PROPERTY = "importo";
    public static final String PERIODO_PROPERTY = "periodo";
    public static final String TO_CODCONV_PROPERTY = "toCodconv";
    public static final String TO_DATOPARTICOLARE_PROPERTY = "toDatoparticolare";

    public static final String IDCODCONV_PK_COLUMN = "IDCODCONV";
    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";
    public static final String PERIODO_PK_COLUMN = "PERIODO";

    public void setIdcodconv(String idcodconv) {
        writeProperty("idcodconv", idcodconv);
    }
    public String getIdcodconv() {
        return (String)readProperty("idcodconv");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setImporto(BigDecimal importo) {
        writeProperty("importo", importo);
    }
    public BigDecimal getImporto() {
        return (BigDecimal)readProperty("importo");
    }

    public void setPeriodo(Date periodo) {
        writeProperty("periodo", periodo);
    }
    public Date getPeriodo() {
        return (Date)readProperty("periodo");
    }

    public void setToCodconv(InpsCodconv toCodconv) {
        setToOneTarget("toCodconv", toCodconv, true);
    }

    public InpsCodconv getToCodconv() {
        return (InpsCodconv)readProperty("toCodconv");
    }


    public void setToDatoparticolare(Datoparticolare toDatoparticolare) {
        setToOneTarget("toDatoparticolare", toDatoparticolare, true);
    }

    public Datoparticolare getToDatoparticolare() {
        return (Datoparticolare)readProperty("toDatoparticolare");
    }


}
