package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Contrattoferie;
import it.iubar.paghe.logic.paghe.Contrattofestivitaretrib;
import it.iubar.paghe.logic.paghe.Contrattorateo;
import it.iubar.paghe.logic.paghe.Contrattoscatto;
import it.iubar.paghe.logic.paghe.Profilolavoratore;
import it.iubar.paghe.logic.paghe.Unitamisura;

/**
 * Class _Contrattocoefficiente was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattocoefficiente extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String GIORNALIERO_PROPERTY = "giornaliero";
    public static final String GIORNISETTIMANA_PROPERTY = "giornisettimana";
    public static final String IDCOEFFICIENTE_PROPERTY = "idcoefficiente";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDTIPOLAVORATORE2_PROPERTY = "idtipolavoratore2";
    public static final String MENSILITA_PROPERTY = "mensilita";
    public static final String MENSILITA1000_PROPERTY = "mensilita1000";
    public static final String MENSILITAAGGIDUM_PROPERTY = "mensilitaaggidum";
    public static final String MENSILITAAGGIUNTIVA_PROPERTY = "mensilitaaggiuntiva";
    public static final String NOTE_PROPERTY = "note";
    public static final String ORARIO_PROPERTY = "orario";
    public static final String ORESETTIMANA_PROPERTY = "oresettimana";
    public static final String SOLODONNAEMINORE_PROPERTY = "solodonnaeminore";
    public static final String ULTIMAMODIFICA_PROPERTY = "ultimamodifica";
    public static final String ULTIMAMODIFICAUSER_PROPERTY = "ultimamodificauser";
    public static final String CONTRATTOFERIE_ARRAY_PROPERTY = "contrattoferieArray";
    public static final String CONTRATTOFESTIVITARETRIB_ARRAY_PROPERTY = "contrattofestivitaretribArray";
    public static final String CONTRATTORATEO_ARRAY_PROPERTY = "contrattorateoArray";
    public static final String CONTRATTOSCATTO_ARRAY_PROPERTY = "contrattoscattoArray";
    public static final String PROFILOSUBORDINATO_ARRAY_PROPERTY = "profilosubordinatoArray";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_UNITAMISURA_PROPERTY = "toUnitamisura";

    public static final String IDCOEFFICIENTE_PK_COLUMN = "IDCOEFFICIENTE";
    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setGiornaliero(BigDecimal giornaliero) {
        writeProperty("giornaliero", giornaliero);
    }
    public BigDecimal getGiornaliero() {
        return (BigDecimal)readProperty("giornaliero");
    }

    public void setGiornisettimana(BigDecimal giornisettimana) {
        writeProperty("giornisettimana", giornisettimana);
    }
    public BigDecimal getGiornisettimana() {
        return (BigDecimal)readProperty("giornisettimana");
    }

    public void setIdcoefficiente(Short idcoefficiente) {
        writeProperty("idcoefficiente", idcoefficiente);
    }
    public Short getIdcoefficiente() {
        return (Short)readProperty("idcoefficiente");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdtipolavoratore2(Short idtipolavoratore2) {
        writeProperty("idtipolavoratore2", idtipolavoratore2);
    }
    public Short getIdtipolavoratore2() {
        return (Short)readProperty("idtipolavoratore2");
    }

    public void setMensilita(Short mensilita) {
        writeProperty("mensilita", mensilita);
    }
    public Short getMensilita() {
        return (Short)readProperty("mensilita");
    }

    public void setMensilita1000(Integer mensilita1000) {
        writeProperty("mensilita1000", mensilita1000);
    }
    public Integer getMensilita1000() {
        return (Integer)readProperty("mensilita1000");
    }

    public void setMensilitaaggidum(Short mensilitaaggidum) {
        writeProperty("mensilitaaggidum", mensilitaaggidum);
    }
    public Short getMensilitaaggidum() {
        return (Short)readProperty("mensilitaaggidum");
    }

    public void setMensilitaaggiuntiva(BigDecimal mensilitaaggiuntiva) {
        writeProperty("mensilitaaggiuntiva", mensilitaaggiuntiva);
    }
    public BigDecimal getMensilitaaggiuntiva() {
        return (BigDecimal)readProperty("mensilitaaggiuntiva");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setOrario(BigDecimal orario) {
        writeProperty("orario", orario);
    }
    public BigDecimal getOrario() {
        return (BigDecimal)readProperty("orario");
    }

    public void setOresettimana(BigDecimal oresettimana) {
        writeProperty("oresettimana", oresettimana);
    }
    public BigDecimal getOresettimana() {
        return (BigDecimal)readProperty("oresettimana");
    }

    public void setSolodonnaeminore(Short solodonnaeminore) {
        writeProperty("solodonnaeminore", solodonnaeminore);
    }
    public Short getSolodonnaeminore() {
        return (Short)readProperty("solodonnaeminore");
    }

    public void setUltimamodifica(Date ultimamodifica) {
        writeProperty("ultimamodifica", ultimamodifica);
    }
    public Date getUltimamodifica() {
        return (Date)readProperty("ultimamodifica");
    }

    public void setUltimamodificauser(String ultimamodificauser) {
        writeProperty("ultimamodificauser", ultimamodificauser);
    }
    public String getUltimamodificauser() {
        return (String)readProperty("ultimamodificauser");
    }

    public void addToContrattoferieArray(Contrattoferie obj) {
        addToManyTarget("contrattoferieArray", obj, true);
    }
    public void removeFromContrattoferieArray(Contrattoferie obj) {
        removeToManyTarget("contrattoferieArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoferie> getContrattoferieArray() {
        return (List<Contrattoferie>)readProperty("contrattoferieArray");
    }


    public void addToContrattofestivitaretribArray(Contrattofestivitaretrib obj) {
        addToManyTarget("contrattofestivitaretribArray", obj, true);
    }
    public void removeFromContrattofestivitaretribArray(Contrattofestivitaretrib obj) {
        removeToManyTarget("contrattofestivitaretribArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattofestivitaretrib> getContrattofestivitaretribArray() {
        return (List<Contrattofestivitaretrib>)readProperty("contrattofestivitaretribArray");
    }


    public void addToContrattorateoArray(Contrattorateo obj) {
        addToManyTarget("contrattorateoArray", obj, true);
    }
    public void removeFromContrattorateoArray(Contrattorateo obj) {
        removeToManyTarget("contrattorateoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattorateo> getContrattorateoArray() {
        return (List<Contrattorateo>)readProperty("contrattorateoArray");
    }


    public void addToContrattoscattoArray(Contrattoscatto obj) {
        addToManyTarget("contrattoscattoArray", obj, true);
    }
    public void removeFromContrattoscattoArray(Contrattoscatto obj) {
        removeToManyTarget("contrattoscattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattoscatto> getContrattoscattoArray() {
        return (List<Contrattoscatto>)readProperty("contrattoscattoArray");
    }


    public void addToProfilosubordinatoArray(Profilolavoratore obj) {
        addToManyTarget("profilosubordinatoArray", obj, true);
    }
    public void removeFromProfilosubordinatoArray(Profilolavoratore obj) {
        removeToManyTarget("profilosubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profilolavoratore> getProfilosubordinatoArray() {
        return (List<Profilolavoratore>)readProperty("profilosubordinatoArray");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToUnitamisura(Unitamisura toUnitamisura) {
        setToOneTarget("toUnitamisura", toUnitamisura, true);
    }

    public Unitamisura getToUnitamisura() {
        return (Unitamisura)readProperty("toUnitamisura");
    }


}
