package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Subordinato;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Contrattodettagliolivellovoce;
import it.iubar.paghe.logic.paghe.ContrattoindennitaLivello;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;

/**
 * Class _Contrattodettagliolivello was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contrattodettagliolivello extends CayenneDataObject {

    public static final String APPRENDISTA_PROPERTY = "apprendista";
    public static final String CUSTOM_PROPERTY = "custom";
    public static final String DATAAGGIORNAMENTO_PROPERTY = "dataaggiornamento";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDCONTRATTODETTFINALE_PROPERTY = "idcontrattodettfinale";
    public static final String IDINPSCONTRATTO_PROPERTY = "idinpscontratto";
    public static final String IDLIVELLO_PROPERTY = "idlivello";
    public static final String IDLIVELLOFINALE_PROPERTY = "idlivellofinale";
    public static final String CONTRATTODETTAGLIO_IMPORTO_ARRAY_PROPERTY = "contrattodettaglioImportoArray";
    public static final String CONTRATTOINDENNITALIVELLO_ARRAY_PROPERTY = "contrattoindennitalivelloArray";
    public static final String POSIZIONESUBORDINATO_ARRAY_PROPERTY = "posizionesubordinatoArray";
    public static final String SUBORDINATOLIVELLO_ARRAY_PROPERTY = "subordinatolivelloArray";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";

    public static final String IDCONTRATTODETTAGLIO_PK_COLUMN = "IDCONTRATTODETTAGLIO";
    public static final String IDLIVELLO_PK_COLUMN = "IDLIVELLO";

    public void setApprendista(Short apprendista) {
        writeProperty("apprendista", apprendista);
    }
    public Short getApprendista() {
        return (Short)readProperty("apprendista");
    }

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setDataaggiornamento(Date dataaggiornamento) {
        writeProperty("dataaggiornamento", dataaggiornamento);
    }
    public Date getDataaggiornamento() {
        return (Date)readProperty("dataaggiornamento");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdcontrattodettfinale(Integer idcontrattodettfinale) {
        writeProperty("idcontrattodettfinale", idcontrattodettfinale);
    }
    public Integer getIdcontrattodettfinale() {
        return (Integer)readProperty("idcontrattodettfinale");
    }

    public void setIdinpscontratto(String idinpscontratto) {
        writeProperty("idinpscontratto", idinpscontratto);
    }
    public String getIdinpscontratto() {
        return (String)readProperty("idinpscontratto");
    }

    public void setIdlivello(String idlivello) {
        writeProperty("idlivello", idlivello);
    }
    public String getIdlivello() {
        return (String)readProperty("idlivello");
    }

    public void setIdlivellofinale(String idlivellofinale) {
        writeProperty("idlivellofinale", idlivellofinale);
    }
    public String getIdlivellofinale() {
        return (String)readProperty("idlivellofinale");
    }

    public void addToContrattodettaglioImportoArray(Contrattodettagliolivellovoce obj) {
        addToManyTarget("contrattodettaglioImportoArray", obj, true);
    }
    public void removeFromContrattodettaglioImportoArray(Contrattodettagliolivellovoce obj) {
        removeToManyTarget("contrattodettaglioImportoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattodettagliolivellovoce> getContrattodettaglioImportoArray() {
        return (List<Contrattodettagliolivellovoce>)readProperty("contrattodettaglioImportoArray");
    }


    public void addToContrattoindennitalivelloArray(ContrattoindennitaLivello obj) {
        addToManyTarget("contrattoindennitalivelloArray", obj, true);
    }
    public void removeFromContrattoindennitalivelloArray(ContrattoindennitaLivello obj) {
        removeToManyTarget("contrattoindennitalivelloArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ContrattoindennitaLivello> getContrattoindennitalivelloArray() {
        return (List<ContrattoindennitaLivello>)readProperty("contrattoindennitalivelloArray");
    }


    public void addToPosizionesubordinatoArray(Posizionesubordinato obj) {
        addToManyTarget("posizionesubordinatoArray", obj, true);
    }
    public void removeFromPosizionesubordinatoArray(Posizionesubordinato obj) {
        removeToManyTarget("posizionesubordinatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionesubordinato> getPosizionesubordinatoArray() {
        return (List<Posizionesubordinato>)readProperty("posizionesubordinatoArray");
    }


    public void addToSubordinatolivelloArray(Subordinato obj) {
        addToManyTarget("subordinatolivelloArray", obj, true);
    }
    public void removeFromSubordinatolivelloArray(Subordinato obj) {
        removeToManyTarget("subordinatolivelloArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Subordinato> getSubordinatolivelloArray() {
        return (List<Subordinato>)readProperty("subordinatolivelloArray");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


}
