package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Assunzione;
import it.iubar.paghe.logic.paghe.Co;

/**
 * Class _CoTipocontratto was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CoTipocontratto extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOCONTRATTO_PROPERTY = "idtipocontratto";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String ASSUNZIONE_ARRAY_PROPERTY = "assunzioneArray";
    public static final String CO_ARRAY_PROPERTY = "coArray";

    public static final String IDTIPOCONTRATTO_PK_COLUMN = "IDTIPOCONTRATTO";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdtipocontratto() {
        return (String)readProperty("idtipocontratto");
    }

    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToAssunzioneArray(Assunzione obj) {
        addToManyTarget("assunzioneArray", obj, true);
    }
    public void removeFromAssunzioneArray(Assunzione obj) {
        removeToManyTarget("assunzioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Assunzione> getAssunzioneArray() {
        return (List<Assunzione>)readProperty("assunzioneArray");
    }


    public void addToCoArray(Co obj) {
        addToManyTarget("coArray", obj, true);
    }
    public void removeFromCoArray(Co obj) {
        removeToManyTarget("coArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Co> getCoArray() {
        return (List<Co>)readProperty("coArray");
    }


}
