package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DaRecuperotfr;
import it.iubar.paghe.logic.paghe.Denunciaaziendale;
import it.iubar.paghe.logic.paghe.TfrCausalevers;

/**
 * Class _DaAziendatfr was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DaAziendatfr extends CayenneDataObject {

    public static final String IDCAUSALEVERS1_PROPERTY = "idcausalevers1";
    public static final String IDCAUSALEVERS2_PROPERTY = "idcausalevers2";
    public static final String IDDENUNCIAAZIENDALE_PROPERTY = "iddenunciaaziendale";
    public static final String IMPORTOVERS1_PROPERTY = "importovers1";
    public static final String IMPORTOVERS2_PROPERTY = "importovers2";
    public static final String DA_RECUPERO_TFR_ARRAY_PROPERTY = "daRecuperoTfrArray";
    public static final String TO_DENUNCIA_AZIENDALE_PROPERTY = "toDenunciaAziendale";
    public static final String TO_TFR_CAUSALE_VERS1_PROPERTY = "toTfrCausaleVers1";
    public static final String TO_TFR_CAUSALE_VERS2_PROPERTY = "toTfrCausaleVers2";

    public static final String IDDENUNCIAAZIENDALE_PK_COLUMN = "IDDENUNCIAAZIENDALE";

    public void setIdcausalevers1(String idcausalevers1) {
        writeProperty("idcausalevers1", idcausalevers1);
    }
    public String getIdcausalevers1() {
        return (String)readProperty("idcausalevers1");
    }

    public void setIdcausalevers2(String idcausalevers2) {
        writeProperty("idcausalevers2", idcausalevers2);
    }
    public String getIdcausalevers2() {
        return (String)readProperty("idcausalevers2");
    }

    public void setIddenunciaaziendale(Integer iddenunciaaziendale) {
        writeProperty("iddenunciaaziendale", iddenunciaaziendale);
    }
    public Integer getIddenunciaaziendale() {
        return (Integer)readProperty("iddenunciaaziendale");
    }

    public void setImportovers1(BigDecimal importovers1) {
        writeProperty("importovers1", importovers1);
    }
    public BigDecimal getImportovers1() {
        return (BigDecimal)readProperty("importovers1");
    }

    public void setImportovers2(BigDecimal importovers2) {
        writeProperty("importovers2", importovers2);
    }
    public BigDecimal getImportovers2() {
        return (BigDecimal)readProperty("importovers2");
    }

    public void addToDaRecuperoTfrArray(DaRecuperotfr obj) {
        addToManyTarget("daRecuperoTfrArray", obj, true);
    }
    public void removeFromDaRecuperoTfrArray(DaRecuperotfr obj) {
        removeToManyTarget("daRecuperoTfrArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DaRecuperotfr> getDaRecuperoTfrArray() {
        return (List<DaRecuperotfr>)readProperty("daRecuperoTfrArray");
    }


    public void setToDenunciaAziendale(Denunciaaziendale toDenunciaAziendale) {
        setToOneTarget("toDenunciaAziendale", toDenunciaAziendale, true);
    }

    public Denunciaaziendale getToDenunciaAziendale() {
        return (Denunciaaziendale)readProperty("toDenunciaAziendale");
    }


    public void setToTfrCausaleVers1(TfrCausalevers toTfrCausaleVers1) {
        setToOneTarget("toTfrCausaleVers1", toTfrCausaleVers1, true);
    }

    public TfrCausalevers getToTfrCausaleVers1() {
        return (TfrCausalevers)readProperty("toTfrCausaleVers1");
    }


    public void setToTfrCausaleVers2(TfrCausalevers toTfrCausaleVers2) {
        setToOneTarget("toTfrCausaleVers2", toTfrCausaleVers2, true);
    }

    public TfrCausalevers getToTfrCausaleVers2() {
        return (TfrCausalevers)readProperty("toTfrCausaleVers2");
    }


}
