package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DaAziendatfr;
import it.iubar.paghe.logic.paghe.TfrCausalerec;

/**
 * Class _DaRecuperotfr was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DaRecuperotfr extends CayenneDataObject {

    public static final String IDCAUSALEREC_PROPERTY = "idcausalerec";
    public static final String IDDENUNCIAAZIENDALE_PROPERTY = "iddenunciaaziendale";
    public static final String IDRECUPEROTFR_PROPERTY = "idrecuperotfr";
    public static final String IMPORTO_PROPERTY = "importo";
    public static final String TO_DA_AZIENDA_TFR_PROPERTY = "toDaAziendaTfr";
    public static final String TO_TFR_CAUSALE_REC_PROPERTY = "toTfrCausaleRec";

    public static final String IDDENUNCIAAZIENDALE_PK_COLUMN = "IDDENUNCIAAZIENDALE";
    public static final String IDRECUPEROTFR_PK_COLUMN = "IDRECUPEROTFR";

    public void setIdcausalerec(String idcausalerec) {
        writeProperty("idcausalerec", idcausalerec);
    }
    public String getIdcausalerec() {
        return (String)readProperty("idcausalerec");
    }

    public void setIddenunciaaziendale(Integer iddenunciaaziendale) {
        writeProperty("iddenunciaaziendale", iddenunciaaziendale);
    }
    public Integer getIddenunciaaziendale() {
        return (Integer)readProperty("iddenunciaaziendale");
    }

    public void setIdrecuperotfr(Short idrecuperotfr) {
        writeProperty("idrecuperotfr", idrecuperotfr);
    }
    public Short getIdrecuperotfr() {
        return (Short)readProperty("idrecuperotfr");
    }

    public void setImporto(BigDecimal importo) {
        writeProperty("importo", importo);
    }
    public BigDecimal getImporto() {
        return (BigDecimal)readProperty("importo");
    }

    public void setToDaAziendaTfr(DaAziendatfr toDaAziendaTfr) {
        setToOneTarget("toDaAziendaTfr", toDaAziendaTfr, true);
    }

    public DaAziendatfr getToDaAziendaTfr() {
        return (DaAziendatfr)readProperty("toDaAziendaTfr");
    }


    public void setToTfrCausaleRec(TfrCausalerec toTfrCausaleRec) {
        setToOneTarget("toTfrCausaleRec", toTfrCausaleRec, true);
    }

    public TfrCausalerec getToTfrCausaleRec() {
        return (TfrCausalerec)readProperty("toTfrCausaleRec");
    }


}
