package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DaCausalerecpens;
import it.iubar.paghe.logic.paghe.DaPrestazbancari;

/**
 * Class _DaRecuperopensbancari was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DaRecuperopensbancari extends CayenneDataObject {

    public static final String IDCAUSALERECPENS_PROPERTY = "idcausalerecpens";
    public static final String IDDENUNCIAAZIENDALE_PROPERTY = "iddenunciaaziendale";
    public static final String IDRECUPEROPENSBANCARI_PROPERTY = "idrecuperopensbancari";
    public static final String IMPORTO_PROPERTY = "importo";
    public static final String TO_DA_CAUSALE_REC_PENS_PROPERTY = "toDaCausaleRecPens";
    public static final String TO_DA_PRESTAZ_BANCARI_PROPERTY = "toDaPrestazBancari";

    public static final String IDDENUNCIAAZIENDALE_PK_COLUMN = "IDDENUNCIAAZIENDALE";
    public static final String IDRECUPEROPENSBANCARI_PK_COLUMN = "IDRECUPEROPENSBANCARI";

    public void setIdcausalerecpens(String idcausalerecpens) {
        writeProperty("idcausalerecpens", idcausalerecpens);
    }
    public String getIdcausalerecpens() {
        return (String)readProperty("idcausalerecpens");
    }

    public void setIddenunciaaziendale(Integer iddenunciaaziendale) {
        writeProperty("iddenunciaaziendale", iddenunciaaziendale);
    }
    public Integer getIddenunciaaziendale() {
        return (Integer)readProperty("iddenunciaaziendale");
    }

    public void setIdrecuperopensbancari(Short idrecuperopensbancari) {
        writeProperty("idrecuperopensbancari", idrecuperopensbancari);
    }
    public Short getIdrecuperopensbancari() {
        return (Short)readProperty("idrecuperopensbancari");
    }

    public void setImporto(BigDecimal importo) {
        writeProperty("importo", importo);
    }
    public BigDecimal getImporto() {
        return (BigDecimal)readProperty("importo");
    }

    public void setToDaCausaleRecPens(DaCausalerecpens toDaCausaleRecPens) {
        setToOneTarget("toDaCausaleRecPens", toDaCausaleRecPens, true);
    }

    public DaCausalerecpens getToDaCausaleRecPens() {
        return (DaCausalerecpens)readProperty("toDaCausaleRecPens");
    }


    public void setToDaPrestazBancari(DaPrestazbancari toDaPrestazBancari) {
        setToOneTarget("toDaPrestazBancari", toDaPrestazBancari, true);
    }

    public DaPrestazbancari getToDaPrestazBancari() {
        return (DaPrestazbancari)readProperty("toDaPrestazBancari");
    }


}
