package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Altreacredito;
import it.iubar.paghe.logic.paghe.Altreadebito;
import it.iubar.paghe.logic.paghe.Assenza;
import it.iubar.paghe.logic.paghe.CedolinoElemento;
import it.iubar.paghe.logic.paghe.Datoparticolare;
import it.iubar.paghe.logic.paghe.Diffaccredito;
import it.iubar.paghe.logic.paghe.DrContribaggiuntiva;
import it.iubar.paghe.logic.paghe.DrFondointegrativo;
import it.iubar.paghe.logic.paghe.DrIncentivo;
import it.iubar.paghe.logic.paghe.DrMalattia;
import it.iubar.paghe.logic.paghe.DrMaternita;
import it.iubar.paghe.logic.paghe.Gestioneanf;
import it.iubar.paghe.logic.paghe.Gestionecig;
import it.iubar.paghe.logic.paghe.Giorno;
import it.iubar.paghe.logic.paghe.InpsTipolavoratore;
import it.iubar.paghe.logic.paghe.Lavdivabile;
import it.iubar.paghe.logic.paghe.Lavpensionato;
import it.iubar.paghe.logic.paghe.Posizionelavoratore;
import it.iubar.paghe.logic.paghe.Settimana;
import it.iubar.paghe.logic.paghe.Variabileretributiva;

/**
 * Class _Datoretributivo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Datoretributivo extends CayenneDataObject {

    public static final String AL_PROPERTY = "al";
    public static final String CONTRIBUTIINPS1_PROPERTY = "contributiinps1";
    public static final String CONTRIBUTIINPS2_PROPERTY = "contributiinps2";
    public static final String CONTRIBUTOFONDOSOST_PROPERTY = "contributofondosost";
    public static final String DAL_PROPERTY = "dal";
    public static final String FONDOINTEGRATIVO_PROPERTY = "fondointegrativo";
    public static final String FORZIMPZERO_PROPERTY = "forzimpzero";
    public static final String GIORNICONTRIBUITI_PROPERTY = "giornicontribuiti";
    public static final String GIORNIDAPRESENZE_PROPERTY = "giornidapresenze";
    public static final String GIORNIINPS_PROPERTY = "giorniinps";
    public static final String GIORNILAVORD_PROPERTY = "giornilavord";
    public static final String GIORNIRETRIBUITI_PROPERTY = "giorniretribuiti";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IDINPSTIPOLAVORATORE_PROPERTY = "idinpstipolavoratore";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDTIPOLAVORATORESTAT_PROPERTY = "idtipolavoratorestat";
    public static final String IMPONIBILEINPS_PROPERTY = "imponibileinps";
    public static final String NOTE_PROPERTY = "note";
    public static final String ORECONTRIBUITE_PROPERTY = "orecontribuite";
    public static final String OREDAPRESENZE_PROPERTY = "oredapresenze";
    public static final String ORELAVORD_PROPERTY = "orelavord";
    public static final String ORERETRIBUITE_PROPERTY = "oreretribuite";
    public static final String RETRIBTEORICA_PROPERTY = "retribteorica";
    public static final String RISPETTOMINIMALE_PROPERTY = "rispettominimale";
    public static final String SETTIMANEINPS_PROPERTY = "settimaneinps";
    public static final String ALTRE_ACREDITO_ARRAY_PROPERTY = "altreACreditoArray";
    public static final String ALTRE_ADEBITO_ARRAY_PROPERTY = "altreADebitoArray";
    public static final String ASSENZA_ARRAY_PROPERTY = "assenzaArray";
    public static final String CEDOLINO_ELEMENTO_ARRAY_PROPERTY = "cedolinoElementoArray";
    public static final String DIFFACCREDITO_ARRAY_PROPERTY = "diffaccreditoArray";
    public static final String DR_CONTRIB_AGGIUNTIVA_ARRAY_PROPERTY = "drContribAggiuntivaArray";
    public static final String DR_FONDO_INTEGRATIVO_ARRAY_PROPERTY = "drFondoIntegrativoArray";
    public static final String DR_INCENTIVO_ARRAY_PROPERTY = "drIncentivoArray";
    public static final String DR_MALATTIA_ARRAY_PROPERTY = "drMalattiaArray";
    public static final String DR_MATERNITA_ARRAY_PROPERTY = "drMaternitaArray";
    public static final String GESTIONE_ANF_ARRAY_PROPERTY = "gestioneAnfArray";
    public static final String GESTIONE_CIG_ARRAY_PROPERTY = "gestioneCigArray";
    public static final String GIORNO_ARRAY_PROPERTY = "giornoArray";
    public static final String LAV_DIV_ABILE_ARRAY_PROPERTY = "lavDivAbileArray";
    public static final String LAV_PENSIONATO_ARRAY_PROPERTY = "lavPensionatoArray";
    public static final String SETTIMANA_ARRAY_PROPERTY = "settimanaArray";
    public static final String TO_DATOPARTICOLARE_PROPERTY = "toDatoparticolare";
    public static final String TO_INPS_TIPOLAVORATORE_PROPERTY = "toInpsTipolavoratore";
    public static final String TO_POSIZIONELAVORATORE_PROPERTY = "toPosizionelavoratore";
    public static final String VARRETRIB_ARRAY_PROPERTY = "varretribArray";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setAl(Date al) {
        writeProperty("al", al);
    }
    public Date getAl() {
        return (Date)readProperty("al");
    }

    public void setContributiinps1(BigDecimal contributiinps1) {
        writeProperty("contributiinps1", contributiinps1);
    }
    public BigDecimal getContributiinps1() {
        return (BigDecimal)readProperty("contributiinps1");
    }

    public void setContributiinps2(BigDecimal contributiinps2) {
        writeProperty("contributiinps2", contributiinps2);
    }
    public BigDecimal getContributiinps2() {
        return (BigDecimal)readProperty("contributiinps2");
    }

    public void setContributofondosost(BigDecimal contributofondosost) {
        writeProperty("contributofondosost", contributofondosost);
    }
    public BigDecimal getContributofondosost() {
        return (BigDecimal)readProperty("contributofondosost");
    }

    public void setDal(Date dal) {
        writeProperty("dal", dal);
    }
    public Date getDal() {
        return (Date)readProperty("dal");
    }

    public void setFondointegrativo(BigDecimal fondointegrativo) {
        writeProperty("fondointegrativo", fondointegrativo);
    }
    public BigDecimal getFondointegrativo() {
        return (BigDecimal)readProperty("fondointegrativo");
    }

    public void setForzimpzero(Short forzimpzero) {
        writeProperty("forzimpzero", forzimpzero);
    }
    public Short getForzimpzero() {
        return (Short)readProperty("forzimpzero");
    }

    public void setGiornicontribuiti(BigDecimal giornicontribuiti) {
        writeProperty("giornicontribuiti", giornicontribuiti);
    }
    public BigDecimal getGiornicontribuiti() {
        return (BigDecimal)readProperty("giornicontribuiti");
    }

    public void setGiornidapresenze(BigDecimal giornidapresenze) {
        writeProperty("giornidapresenze", giornidapresenze);
    }
    public BigDecimal getGiornidapresenze() {
        return (BigDecimal)readProperty("giornidapresenze");
    }

    public void __setGiorniinps(BigDecimal giorniinps) {
        writeProperty("giorniinps", giorniinps);
    }
    public BigDecimal __getGiorniinps() {
        return (BigDecimal)readProperty("giorniinps");
    }

    public void setGiornilavord(BigDecimal giornilavord) {
        writeProperty("giornilavord", giornilavord);
    }
    public BigDecimal getGiornilavord() {
        return (BigDecimal)readProperty("giornilavord");
    }

    public void setGiorniretribuiti(BigDecimal giorniretribuiti) {
        writeProperty("giorniretribuiti", giorniretribuiti);
    }
    public BigDecimal getGiorniretribuiti() {
        return (BigDecimal)readProperty("giorniretribuiti");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIdinpstipolavoratore(String idinpstipolavoratore) {
        writeProperty("idinpstipolavoratore", idinpstipolavoratore);
    }
    public String getIdinpstipolavoratore() {
        return (String)readProperty("idinpstipolavoratore");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdtipolavoratorestat(String idtipolavoratorestat) {
        writeProperty("idtipolavoratorestat", idtipolavoratorestat);
    }
    public String getIdtipolavoratorestat() {
        return (String)readProperty("idtipolavoratorestat");
    }

    public void setImponibileinps(BigDecimal imponibileinps) {
        writeProperty("imponibileinps", imponibileinps);
    }
    public BigDecimal getImponibileinps() {
        return (BigDecimal)readProperty("imponibileinps");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setOrecontribuite(BigDecimal orecontribuite) {
        writeProperty("orecontribuite", orecontribuite);
    }
    public BigDecimal getOrecontribuite() {
        return (BigDecimal)readProperty("orecontribuite");
    }

    public void setOredapresenze(BigDecimal oredapresenze) {
        writeProperty("oredapresenze", oredapresenze);
    }
    public BigDecimal getOredapresenze() {
        return (BigDecimal)readProperty("oredapresenze");
    }

    public void setOrelavord(BigDecimal orelavord) {
        writeProperty("orelavord", orelavord);
    }
    public BigDecimal getOrelavord() {
        return (BigDecimal)readProperty("orelavord");
    }

    public void setOreretribuite(BigDecimal oreretribuite) {
        writeProperty("oreretribuite", oreretribuite);
    }
    public BigDecimal getOreretribuite() {
        return (BigDecimal)readProperty("oreretribuite");
    }

    public void setRetribteorica(BigDecimal retribteorica) {
        writeProperty("retribteorica", retribteorica);
    }
    public BigDecimal getRetribteorica() {
        return (BigDecimal)readProperty("retribteorica");
    }

    public void setRispettominimale(Short rispettominimale) {
        writeProperty("rispettominimale", rispettominimale);
    }
    public Short getRispettominimale() {
        return (Short)readProperty("rispettominimale");
    }

    public void setSettimaneinps(BigDecimal settimaneinps) {
        writeProperty("settimaneinps", settimaneinps);
    }
    public BigDecimal getSettimaneinps() {
        return (BigDecimal)readProperty("settimaneinps");
    }

    public void addToAltreACreditoArray(Altreacredito obj) {
        addToManyTarget("altreACreditoArray", obj, true);
    }
    public void removeFromAltreACreditoArray(Altreacredito obj) {
        removeToManyTarget("altreACreditoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Altreacredito> getAltreACreditoArray() {
        return (List<Altreacredito>)readProperty("altreACreditoArray");
    }


    public void addToAltreADebitoArray(Altreadebito obj) {
        addToManyTarget("altreADebitoArray", obj, true);
    }
    public void removeFromAltreADebitoArray(Altreadebito obj) {
        removeToManyTarget("altreADebitoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Altreadebito> getAltreADebitoArray() {
        return (List<Altreadebito>)readProperty("altreADebitoArray");
    }


    public void addToAssenzaArray(Assenza obj) {
        addToManyTarget("assenzaArray", obj, true);
    }
    public void removeFromAssenzaArray(Assenza obj) {
        removeToManyTarget("assenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Assenza> getAssenzaArray() {
        return (List<Assenza>)readProperty("assenzaArray");
    }


    public void addToCedolinoElementoArray(CedolinoElemento obj) {
        addToManyTarget("cedolinoElementoArray", obj, true);
    }
    public void removeFromCedolinoElementoArray(CedolinoElemento obj) {
        removeToManyTarget("cedolinoElementoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CedolinoElemento> getCedolinoElementoArray() {
        return (List<CedolinoElemento>)readProperty("cedolinoElementoArray");
    }


    public void addToDiffaccreditoArray(Diffaccredito obj) {
        addToManyTarget("diffaccreditoArray", obj, true);
    }
    public void removeFromDiffaccreditoArray(Diffaccredito obj) {
        removeToManyTarget("diffaccreditoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Diffaccredito> getDiffaccreditoArray() {
        return (List<Diffaccredito>)readProperty("diffaccreditoArray");
    }


    public void addToDrContribAggiuntivaArray(DrContribaggiuntiva obj) {
        addToManyTarget("drContribAggiuntivaArray", obj, true);
    }
    public void removeFromDrContribAggiuntivaArray(DrContribaggiuntiva obj) {
        removeToManyTarget("drContribAggiuntivaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrContribaggiuntiva> getDrContribAggiuntivaArray() {
        return (List<DrContribaggiuntiva>)readProperty("drContribAggiuntivaArray");
    }


    public void addToDrFondoIntegrativoArray(DrFondointegrativo obj) {
        addToManyTarget("drFondoIntegrativoArray", obj, true);
    }
    public void removeFromDrFondoIntegrativoArray(DrFondointegrativo obj) {
        removeToManyTarget("drFondoIntegrativoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrFondointegrativo> getDrFondoIntegrativoArray() {
        return (List<DrFondointegrativo>)readProperty("drFondoIntegrativoArray");
    }


    public void addToDrIncentivoArray(DrIncentivo obj) {
        addToManyTarget("drIncentivoArray", obj, true);
    }
    public void removeFromDrIncentivoArray(DrIncentivo obj) {
        removeToManyTarget("drIncentivoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrIncentivo> getDrIncentivoArray() {
        return (List<DrIncentivo>)readProperty("drIncentivoArray");
    }


    public void addToDrMalattiaArray(DrMalattia obj) {
        addToManyTarget("drMalattiaArray", obj, true);
    }
    public void removeFromDrMalattiaArray(DrMalattia obj) {
        removeToManyTarget("drMalattiaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrMalattia> getDrMalattiaArray() {
        return (List<DrMalattia>)readProperty("drMalattiaArray");
    }


    public void addToDrMaternitaArray(DrMaternita obj) {
        addToManyTarget("drMaternitaArray", obj, true);
    }
    public void removeFromDrMaternitaArray(DrMaternita obj) {
        removeToManyTarget("drMaternitaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DrMaternita> getDrMaternitaArray() {
        return (List<DrMaternita>)readProperty("drMaternitaArray");
    }


    public void addToGestioneAnfArray(Gestioneanf obj) {
        addToManyTarget("gestioneAnfArray", obj, true);
    }
    public void removeFromGestioneAnfArray(Gestioneanf obj) {
        removeToManyTarget("gestioneAnfArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Gestioneanf> getGestioneAnfArray() {
        return (List<Gestioneanf>)readProperty("gestioneAnfArray");
    }


    public void addToGestioneCigArray(Gestionecig obj) {
        addToManyTarget("gestioneCigArray", obj, true);
    }
    public void removeFromGestioneCigArray(Gestionecig obj) {
        removeToManyTarget("gestioneCigArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Gestionecig> getGestioneCigArray() {
        return (List<Gestionecig>)readProperty("gestioneCigArray");
    }


    public void addToGiornoArray(Giorno obj) {
        addToManyTarget("giornoArray", obj, true);
    }
    public void removeFromGiornoArray(Giorno obj) {
        removeToManyTarget("giornoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Giorno> getGiornoArray() {
        return (List<Giorno>)readProperty("giornoArray");
    }


    public void addToLavDivAbileArray(Lavdivabile obj) {
        addToManyTarget("lavDivAbileArray", obj, true);
    }
    public void removeFromLavDivAbileArray(Lavdivabile obj) {
        removeToManyTarget("lavDivAbileArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lavdivabile> getLavDivAbileArray() {
        return (List<Lavdivabile>)readProperty("lavDivAbileArray");
    }


    public void addToLavPensionatoArray(Lavpensionato obj) {
        addToManyTarget("lavPensionatoArray", obj, true);
    }
    public void removeFromLavPensionatoArray(Lavpensionato obj) {
        removeToManyTarget("lavPensionatoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lavpensionato> getLavPensionatoArray() {
        return (List<Lavpensionato>)readProperty("lavPensionatoArray");
    }


    public void addToSettimanaArray(Settimana obj) {
        addToManyTarget("settimanaArray", obj, true);
    }
    public void removeFromSettimanaArray(Settimana obj) {
        removeToManyTarget("settimanaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Settimana> getSettimanaArray() {
        return (List<Settimana>)readProperty("settimanaArray");
    }


    public void setToDatoparticolare(Datoparticolare toDatoparticolare) {
        setToOneTarget("toDatoparticolare", toDatoparticolare, true);
    }

    public Datoparticolare getToDatoparticolare() {
        return (Datoparticolare)readProperty("toDatoparticolare");
    }


    public void setToInpsTipolavoratore(InpsTipolavoratore toInpsTipolavoratore) {
        setToOneTarget("toInpsTipolavoratore", toInpsTipolavoratore, true);
    }

    public InpsTipolavoratore getToInpsTipolavoratore() {
        return (InpsTipolavoratore)readProperty("toInpsTipolavoratore");
    }


    public void setToPosizionelavoratore(Posizionelavoratore toPosizionelavoratore) {
        setToOneTarget("toPosizionelavoratore", toPosizionelavoratore, true);
    }

    public Posizionelavoratore getToPosizionelavoratore() {
        return (Posizionelavoratore)readProperty("toPosizionelavoratore");
    }


    public void addToVarretribArray(Variabileretributiva obj) {
        addToManyTarget("varretribArray", obj, true);
    }
    public void removeFromVarretribArray(Variabileretributiva obj) {
        removeToManyTarget("varretribArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Variabileretributiva> getVarretribArray() {
        return (List<Variabileretributiva>)readProperty("varretribArray");
    }


}
