package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Bonus;
import it.iubar.paghe.logic.paghe.Contrattoriallineamento;
import it.iubar.paghe.logic.paghe.Contribatipica;
import it.iubar.paghe.logic.paghe.Contribsindacalista;
import it.iubar.paghe.logic.paghe.Convenzbilaterale;
import it.iubar.paghe.logic.paghe.Datoretributivo;
import it.iubar.paghe.logic.paghe.Dispintermittente;
import it.iubar.paghe.logic.paghe.Dispsomministrati;
import it.iubar.paghe.logic.paghe.Eccedenzamassimale;
import it.iubar.paghe.logic.paghe.Estero;
import it.iubar.paghe.logic.paghe.Fondospeciale;
import it.iubar.paghe.logic.paghe.Formazcig;
import it.iubar.paghe.logic.paghe.Lavdomicilio;
import it.iubar.paghe.logic.paghe.Preavviso;
import it.iubar.paghe.logic.paghe.Premioris;

/**
 * Class _Datoparticolare was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Datoparticolare extends CayenneDataObject {

    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String CONTRIB_SINDACALISTA_ARRAY_PROPERTY = "contribSindacalistaArray";
    public static final String CONVENZBILATERALE_ARRAY_PROPERTY = "convenzbilateraleArray";
    public static final String ESTERO_ARRAY_PROPERTY = "esteroArray";
    public static final String TO_BONUS_PROPERTY = "toBonus";
    public static final String TO_CONTRATTO_RIALLINEAM_PROPERTY = "toContrattoRiallineam";
    public static final String TO_CONTRATTORIALLINEAMENTO_PROPERTY = "toContrattoriallineamento";
    public static final String TO_CONTRIBATIPICA_PROPERTY = "toContribatipica";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";
    public static final String TO_DISP_SOMMINISTRATI_PROPERTY = "toDispSomministrati";
    public static final String TO_DISPINTERMITTENTE_PROPERTY = "toDispintermittente";
    public static final String TO_ECCEDENZA_MASSIM_PROPERTY = "toEccedenzaMassim";
    public static final String TO_FONDOSPECIALE_PROPERTY = "toFondospeciale";
    public static final String TO_FORMAZCIG_PROPERTY = "toFormazcig";
    public static final String TO_LAVDOMICILIO_PROPERTY = "toLavdomicilio";
    public static final String TO_PREAVVISO_PROPERTY = "toPreavviso";
    public static final String TO_PREMIORIS_PROPERTY = "toPremioris";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void addToContribSindacalistaArray(Contribsindacalista obj) {
        addToManyTarget("contribSindacalistaArray", obj, true);
    }
    public void removeFromContribSindacalistaArray(Contribsindacalista obj) {
        removeToManyTarget("contribSindacalistaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contribsindacalista> getContribSindacalistaArray() {
        return (List<Contribsindacalista>)readProperty("contribSindacalistaArray");
    }


    public void addToConvenzbilateraleArray(Convenzbilaterale obj) {
        addToManyTarget("convenzbilateraleArray", obj, true);
    }
    public void removeFromConvenzbilateraleArray(Convenzbilaterale obj) {
        removeToManyTarget("convenzbilateraleArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Convenzbilaterale> getConvenzbilateraleArray() {
        return (List<Convenzbilaterale>)readProperty("convenzbilateraleArray");
    }


    public void addToEsteroArray(Estero obj) {
        addToManyTarget("esteroArray", obj, true);
    }
    public void removeFromEsteroArray(Estero obj) {
        removeToManyTarget("esteroArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Estero> getEsteroArray() {
        return (List<Estero>)readProperty("esteroArray");
    }


    public void setToBonus(Bonus toBonus) {
        setToOneTarget("toBonus", toBonus, true);
    }

    public Bonus getToBonus() {
        return (Bonus)readProperty("toBonus");
    }


    public void setToContrattoRiallineam(Contrattoriallineamento toContrattoRiallineam) {
        setToOneTarget("toContrattoRiallineam", toContrattoRiallineam, true);
    }

    public Contrattoriallineamento getToContrattoRiallineam() {
        return (Contrattoriallineamento)readProperty("toContrattoRiallineam");
    }


    public void setToContrattoriallineamento(Contrattoriallineamento toContrattoriallineamento) {
        setToOneTarget("toContrattoriallineamento", toContrattoriallineamento, true);
    }

    public Contrattoriallineamento getToContrattoriallineamento() {
        return (Contrattoriallineamento)readProperty("toContrattoriallineamento");
    }


    public void setToContribatipica(Contribatipica toContribatipica) {
        setToOneTarget("toContribatipica", toContribatipica, true);
    }

    public Contribatipica getToContribatipica() {
        return (Contribatipica)readProperty("toContribatipica");
    }


    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


    public void setToDispSomministrati(Dispsomministrati toDispSomministrati) {
        setToOneTarget("toDispSomministrati", toDispSomministrati, true);
    }

    public Dispsomministrati getToDispSomministrati() {
        return (Dispsomministrati)readProperty("toDispSomministrati");
    }


    public void setToDispintermittente(Dispintermittente toDispintermittente) {
        setToOneTarget("toDispintermittente", toDispintermittente, true);
    }

    public Dispintermittente getToDispintermittente() {
        return (Dispintermittente)readProperty("toDispintermittente");
    }


    public void setToEccedenzaMassim(Eccedenzamassimale toEccedenzaMassim) {
        setToOneTarget("toEccedenzaMassim", toEccedenzaMassim, true);
    }

    public Eccedenzamassimale getToEccedenzaMassim() {
        return (Eccedenzamassimale)readProperty("toEccedenzaMassim");
    }


    public void setToFondospeciale(Fondospeciale toFondospeciale) {
        setToOneTarget("toFondospeciale", toFondospeciale, true);
    }

    public Fondospeciale getToFondospeciale() {
        return (Fondospeciale)readProperty("toFondospeciale");
    }


    public void setToFormazcig(Formazcig toFormazcig) {
        setToOneTarget("toFormazcig", toFormazcig, true);
    }

    public Formazcig getToFormazcig() {
        return (Formazcig)readProperty("toFormazcig");
    }


    public void setToLavdomicilio(Lavdomicilio toLavdomicilio) {
        setToOneTarget("toLavdomicilio", toLavdomicilio, true);
    }

    public Lavdomicilio getToLavdomicilio() {
        return (Lavdomicilio)readProperty("toLavdomicilio");
    }


    public void setToPreavviso(Preavviso toPreavviso) {
        setToOneTarget("toPreavviso", toPreavviso, true);
    }

    public Preavviso getToPreavviso() {
        return (Preavviso)readProperty("toPreavviso");
    }


    public void setToPremioris(Premioris toPremioris) {
        setToOneTarget("toPremioris", toPremioris, true);
    }

    public Premioris getToPremioris() {
        return (Premioris)readProperty("toPremioris");
    }


}
