package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Utente;
import it.iubar.paghe.logic.paghe.Co;
import it.iubar.paghe.logic.paghe.Cud;
import it.iubar.paghe.logic.paghe.Dmag;
import it.iubar.paghe.logic.paghe.F24;
import it.iubar.paghe.logic.paghe.M770;
import it.iubar.paghe.logic.paghe.Mut;
import it.iubar.paghe.logic.paghe.Statodichiarazione;
import it.iubar.paghe.logic.paghe.Tipodichiarazione;
import it.iubar.paghe.logic.paghe.Uniemens;

/**
 * Class _Dichiarazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Dichiarazione extends CayenneDataObject {

    public static final String ANNO_PROPERTY = "anno";
    public static final String DATACREAZIONE_PROPERTY = "datacreazione";
    public static final String IDAUTORE_PROPERTY = "idautore";
    public static final String IDDICHIARAZIONE_PROPERTY = "iddichiarazione";
    public static final String IDSOGGETTO_PROPERTY = "idsoggetto";
    public static final String IDSTATODICHIARAZIONE_PROPERTY = "idstatodichiarazione";
    public static final String IDTIPODICHIARAZIONE_PROPERTY = "idtipodichiarazione";
    public static final String MESE_PROPERTY = "mese";
    public static final String NOTE_PROPERTY = "note";
    public static final String ULTIMAELABORAZIONE_PROPERTY = "ultimaelaborazione";
    public static final String ULTIMAELABORAZIONEUSER_PROPERTY = "ultimaelaborazioneuser";
    public static final String ULTIMAMODIFICA_PROPERTY = "ultimamodifica";
    public static final String ULTIMAMODIFICAUSER_PROPERTY = "ultimamodificauser";
    public static final String DMAG_ARRAY_PROPERTY = "dmagArray";
    public static final String MUT_ARRAY_PROPERTY = "mutArray";
    public static final String TO_CO_PROPERTY = "toCo";
    public static final String TO_CUD_PROPERTY = "toCud";
    public static final String TO_F24_PROPERTY = "toF24";
    public static final String TO_M770_PROPERTY = "toM770";
    public static final String TO_STATODICHIARAZIONE_PROPERTY = "toStatodichiarazione";
    public static final String TO_TIPODICHIARAZIONE_PROPERTY = "toTipodichiarazione";
    public static final String TO_UTENTE_ULTIMAELABORAZIONE_PROPERTY = "toUtenteUltimaelaborazione";
    public static final String UNIEMENS_ARRAY_PROPERTY = "uniemensArray";

    public static final String IDDICHIARAZIONE_PK_COLUMN = "IDDICHIARAZIONE";

    public void setAnno(Integer anno) {
        writeProperty("anno", anno);
    }
    public Integer getAnno() {
        return (Integer)readProperty("anno");
    }

    public void setDatacreazione(Date datacreazione) {
        writeProperty("datacreazione", datacreazione);
    }
    public Date getDatacreazione() {
        return (Date)readProperty("datacreazione");
    }

    public void setIdautore(Integer idautore) {
        writeProperty("idautore", idautore);
    }
    public Integer getIdautore() {
        return (Integer)readProperty("idautore");
    }

    public void setIddichiarazione(Integer iddichiarazione) {
        writeProperty("iddichiarazione", iddichiarazione);
    }
    public Integer getIddichiarazione() {
        return (Integer)readProperty("iddichiarazione");
    }

    public void setIdsoggetto(Integer idsoggetto) {
        writeProperty("idsoggetto", idsoggetto);
    }
    public Integer getIdsoggetto() {
        return (Integer)readProperty("idsoggetto");
    }

    public void setIdstatodichiarazione(Short idstatodichiarazione) {
        writeProperty("idstatodichiarazione", idstatodichiarazione);
    }
    public Short getIdstatodichiarazione() {
        return (Short)readProperty("idstatodichiarazione");
    }

    public void setIdtipodichiarazione(Short idtipodichiarazione) {
        writeProperty("idtipodichiarazione", idtipodichiarazione);
    }
    public Short getIdtipodichiarazione() {
        return (Short)readProperty("idtipodichiarazione");
    }

    public void setMese(Short mese) {
        writeProperty("mese", mese);
    }
    public Short getMese() {
        return (Short)readProperty("mese");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setUltimaelaborazione(Date ultimaelaborazione) {
        writeProperty("ultimaelaborazione", ultimaelaborazione);
    }
    public Date getUltimaelaborazione() {
        return (Date)readProperty("ultimaelaborazione");
    }

    public void setUltimaelaborazioneuser(String ultimaelaborazioneuser) {
        writeProperty("ultimaelaborazioneuser", ultimaelaborazioneuser);
    }
    public String getUltimaelaborazioneuser() {
        return (String)readProperty("ultimaelaborazioneuser");
    }

    public void setUltimamodifica(Date ultimamodifica) {
        writeProperty("ultimamodifica", ultimamodifica);
    }
    public Date getUltimamodifica() {
        return (Date)readProperty("ultimamodifica");
    }

    public void setUltimamodificauser(String ultimamodificauser) {
        writeProperty("ultimamodificauser", ultimamodificauser);
    }
    public String getUltimamodificauser() {
        return (String)readProperty("ultimamodificauser");
    }

    public void addToDmagArray(Dmag obj) {
        addToManyTarget("dmagArray", obj, true);
    }
    public void removeFromDmagArray(Dmag obj) {
        removeToManyTarget("dmagArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Dmag> getDmagArray() {
        return (List<Dmag>)readProperty("dmagArray");
    }


    public void addToMutArray(Mut obj) {
        addToManyTarget("mutArray", obj, true);
    }
    public void removeFromMutArray(Mut obj) {
        removeToManyTarget("mutArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Mut> getMutArray() {
        return (List<Mut>)readProperty("mutArray");
    }


    public void setToCo(Co toCo) {
        setToOneTarget("toCo", toCo, true);
    }

    public Co getToCo() {
        return (Co)readProperty("toCo");
    }


    public void setToCud(Cud toCud) {
        setToOneTarget("toCud", toCud, true);
    }

    public Cud getToCud() {
        return (Cud)readProperty("toCud");
    }


    public void setToF24(F24 toF24) {
        setToOneTarget("toF24", toF24, true);
    }

    public F24 getToF24() {
        return (F24)readProperty("toF24");
    }


    public void setToM770(M770 toM770) {
        setToOneTarget("toM770", toM770, true);
    }

    public M770 getToM770() {
        return (M770)readProperty("toM770");
    }


    public void setToStatodichiarazione(Statodichiarazione toStatodichiarazione) {
        setToOneTarget("toStatodichiarazione", toStatodichiarazione, true);
    }

    public Statodichiarazione getToStatodichiarazione() {
        return (Statodichiarazione)readProperty("toStatodichiarazione");
    }


    public void setToTipodichiarazione(Tipodichiarazione toTipodichiarazione) {
        setToOneTarget("toTipodichiarazione", toTipodichiarazione, true);
    }

    public Tipodichiarazione getToTipodichiarazione() {
        return (Tipodichiarazione)readProperty("toTipodichiarazione");
    }


    public void setToUtenteUltimaelaborazione(Utente toUtenteUltimaelaborazione) {
        setToOneTarget("toUtenteUltimaelaborazione", toUtenteUltimaelaborazione, true);
    }

    public Utente getToUtenteUltimaelaborazione() {
        return (Utente)readProperty("toUtenteUltimaelaborazione");
    }


    public void addToUniemensArray(Uniemens obj) {
        addToManyTarget("uniemensArray", obj, true);
    }
    public void removeFromUniemensArray(Uniemens obj) {
        removeToManyTarget("uniemensArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Uniemens> getUniemensArray() {
        return (List<Uniemens>)readProperty("uniemensArray");
    }


}
