package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoretributivo;
import it.iubar.paghe.logic.paghe.InpsEvento;

/**
 * Class _Diffaccredito was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Diffaccredito extends CayenneDataObject {

    public static final String DIFFACCREDITO_PROPERTY = "diffaccredito";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IDINPSEVENTO_PROPERTY = "idinpsevento";
    public static final String SETTIMANEINPS_PROPERTY = "settimaneinps";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";
    public static final String TO_INPSEVENTO_PROPERTY = "toInpsevento";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";
    public static final String IDINPSEVENTO_PK_COLUMN = "IDINPSEVENTO";

    public void setDiffaccredito(BigDecimal diffaccredito) {
        writeProperty("diffaccredito", diffaccredito);
    }
    public BigDecimal getDiffaccredito() {
        return (BigDecimal)readProperty("diffaccredito");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIdinpsevento(String idinpsevento) {
        writeProperty("idinpsevento", idinpsevento);
    }
    public String getIdinpsevento() {
        return (String)readProperty("idinpsevento");
    }

    public void setSettimaneinps(BigDecimal settimaneinps) {
        writeProperty("settimaneinps", settimaneinps);
    }
    public BigDecimal getSettimaneinps() {
        return (BigDecimal)readProperty("settimaneinps");
    }

    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


    public void setToInpsevento(InpsEvento toInpsevento) {
        setToOneTarget("toInpsevento", toInpsevento, true);
    }

    public InpsEvento getToInpsevento() {
        return (InpsEvento)readProperty("toInpsevento");
    }


}
