package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DmagLavoratoreprofilo;
import it.iubar.paghe.logic.paghe.DmagPosizionelav;

/**
 * Class _DmagTipocontratto was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DmagTipocontratto extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOCONTRATTO_PROPERTY = "idtipocontratto";
    public static final String DMAG_LAVORTOREPROFILO_ARRAY_PROPERTY = "dmagLavortoreprofiloArray";
    public static final String DMAG_POSIZIONELAV_ARRAY_PROPERTY = "dmagPosizionelavArray";

    public static final String IDTIPOCONTRATTO_PK_COLUMN = "IDTIPOCONTRATTO";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdtipocontratto() {
        return (Short)readProperty("idtipocontratto");
    }

    public void addToDmagLavortoreprofiloArray(DmagLavoratoreprofilo obj) {
        addToManyTarget("dmagLavortoreprofiloArray", obj, true);
    }
    public void removeFromDmagLavortoreprofiloArray(DmagLavoratoreprofilo obj) {
        removeToManyTarget("dmagLavortoreprofiloArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DmagLavoratoreprofilo> getDmagLavortoreprofiloArray() {
        return (List<DmagLavoratoreprofilo>)readProperty("dmagLavortoreprofiloArray");
    }


    public void addToDmagPosizionelavArray(DmagPosizionelav obj) {
        addToManyTarget("dmagPosizionelavArray", obj, true);
    }
    public void removeFromDmagPosizionelavArray(DmagPosizionelav obj) {
        removeToManyTarget("dmagPosizionelavArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DmagPosizionelav> getDmagPosizionelavArray() {
        return (List<DmagPosizionelav>)readProperty("dmagPosizionelavArray");
    }


}
