package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Dmag;
import it.iubar.paghe.logic.paghe.DmagAsscategoria;
import it.iubar.paghe.logic.paghe.DmagTipodichiaraz;
import it.iubar.paghe.logic.paghe.DmagTipoditta1;
import it.iubar.paghe.logic.paghe.DmagTipoditta2;
import it.iubar.paghe.logic.paghe.DmagTipomanodopera;
import it.iubar.paghe.logic.paghe.DmagTipomanodoperadic;

/**
 * Class _DmagImpresa was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DmagImpresa extends CayenneDataObject {

    public static final String ACCENTRAMENTO_PROPERTY = "accentramento";
    public static final String AUTORIZZAZRISCOSSIONE_PROPERTY = "autorizzazriscossione";
    public static final String CIDA_PROPERTY = "cida";
    public static final String DICHIARAANTICIPAZ_PROPERTY = "dichiaraanticipaz";
    public static final String DICHIARABENEFICIO_PROPERTY = "dichiarabeneficio";
    public static final String DICHIARATRATTQUOTALAV_PROPERTY = "dichiaratrattquotalav";
    public static final String EMERSIONE_PROPERTY = "emersione";
    public static final String EMERSIONEAL_PROPERTY = "emersioneal";
    public static final String EMERSIONEDAL_PROPERTY = "emersionedal";
    public static final String IDASSCATEGORIA_PROPERTY = "idasscategoria";
    public static final String IDCOMUNEFONDO_PROPERTY = "idcomunefondo";
    public static final String IDDICHIARAZIONE_PROPERTY = "iddichiarazione";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDIMPRESASOMMINISTRATA_PROPERTY = "idimpresasomministrata";
    public static final String IDTIPODICHIARAZ_PROPERTY = "idtipodichiaraz";
    public static final String IDTIPODITTA1_PROPERTY = "idtipoditta1";
    public static final String IDTIPODITTA2_PROPERTY = "idtipoditta2";
    public static final String IDTIPOMANODOPERA_PROPERTY = "idtipomanodopera";
    public static final String IDTIPOMANODOPERADIC_PROPERTY = "idtipomanodoperadic";
    public static final String LG166LAV_PROPERTY = "lg166lav";
    public static final String LG166RETRIB_PROPERTY = "lg166retrib";
    public static final String PROGRESSIVO_PROPERTY = "progressivo";
    public static final String RIALLINADESIONE_PROPERTY = "riallinadesione";
    public static final String RIALLINCONTRATTO_PROPERTY = "riallincontratto";
    public static final String RIALLINEAMENTO_PROPERTY = "riallineamento";
    public static final String RIALLINSCADENZA_PROPERTY = "riallinscadenza";
    public static final String TO_ASSCATEGORIA_PROPERTY = "toAsscategoria";
    public static final String TO_DMAG_PROPERTY = "toDmag";
    public static final String TO_TIPO_DITTA1_PROPERTY = "toTipoDitta1";
    public static final String TO_TIPO_DITTA2_PROPERTY = "toTipoDitta2";
    public static final String TO_TIPODICHIARAZIONE_PROPERTY = "toTipodichiarazione";
    public static final String TO_TIPOMANODOPERA_PROPERTY = "toTipomanodopera";
    public static final String TO_TIPOMANODOPERADIC_PROPERTY = "toTipomanodoperadic";

    public static final String IDDICHIARAZIONE_PK_COLUMN = "IDDICHIARAZIONE";
    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";

    public void setAccentramento(Short accentramento) {
        writeProperty("accentramento", accentramento);
    }
    public Short getAccentramento() {
        return (Short)readProperty("accentramento");
    }

    public void setAutorizzazriscossione(Short autorizzazriscossione) {
        writeProperty("autorizzazriscossione", autorizzazriscossione);
    }
    public Short getAutorizzazriscossione() {
        return (Short)readProperty("autorizzazriscossione");
    }

    public void setCida(Integer cida) {
        writeProperty("cida", cida);
    }
    public Integer getCida() {
        return (Integer)readProperty("cida");
    }

    public void setDichiaraanticipaz(Short dichiaraanticipaz) {
        writeProperty("dichiaraanticipaz", dichiaraanticipaz);
    }
    public Short getDichiaraanticipaz() {
        return (Short)readProperty("dichiaraanticipaz");
    }

    public void setDichiarabeneficio(Short dichiarabeneficio) {
        writeProperty("dichiarabeneficio", dichiarabeneficio);
    }
    public Short getDichiarabeneficio() {
        return (Short)readProperty("dichiarabeneficio");
    }

    public void setDichiaratrattquotalav(Short dichiaratrattquotalav) {
        writeProperty("dichiaratrattquotalav", dichiaratrattquotalav);
    }
    public Short getDichiaratrattquotalav() {
        return (Short)readProperty("dichiaratrattquotalav");
    }

    public void setEmersione(Short emersione) {
        writeProperty("emersione", emersione);
    }
    public Short getEmersione() {
        return (Short)readProperty("emersione");
    }

    public void setEmersioneal(Date emersioneal) {
        writeProperty("emersioneal", emersioneal);
    }
    public Date getEmersioneal() {
        return (Date)readProperty("emersioneal");
    }

    public void setEmersionedal(Date emersionedal) {
        writeProperty("emersionedal", emersionedal);
    }
    public Date getEmersionedal() {
        return (Date)readProperty("emersionedal");
    }

    public void setIdasscategoria(Short idasscategoria) {
        writeProperty("idasscategoria", idasscategoria);
    }
    public Short getIdasscategoria() {
        return (Short)readProperty("idasscategoria");
    }

    public void setIdcomunefondo(String idcomunefondo) {
        writeProperty("idcomunefondo", idcomunefondo);
    }
    public String getIdcomunefondo() {
        return (String)readProperty("idcomunefondo");
    }

    public void setIddichiarazione(Integer iddichiarazione) {
        writeProperty("iddichiarazione", iddichiarazione);
    }
    public Integer getIddichiarazione() {
        return (Integer)readProperty("iddichiarazione");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdimpresasomministrata(Integer idimpresasomministrata) {
        writeProperty("idimpresasomministrata", idimpresasomministrata);
    }
    public Integer getIdimpresasomministrata() {
        return (Integer)readProperty("idimpresasomministrata");
    }

    public void setIdtipodichiaraz(String idtipodichiaraz) {
        writeProperty("idtipodichiaraz", idtipodichiaraz);
    }
    public String getIdtipodichiaraz() {
        return (String)readProperty("idtipodichiaraz");
    }

    public void setIdtipoditta1(Short idtipoditta1) {
        writeProperty("idtipoditta1", idtipoditta1);
    }
    public Short getIdtipoditta1() {
        return (Short)readProperty("idtipoditta1");
    }

    public void setIdtipoditta2(Short idtipoditta2) {
        writeProperty("idtipoditta2", idtipoditta2);
    }
    public Short getIdtipoditta2() {
        return (Short)readProperty("idtipoditta2");
    }

    public void setIdtipomanodopera(Short idtipomanodopera) {
        writeProperty("idtipomanodopera", idtipomanodopera);
    }
    public Short getIdtipomanodopera() {
        return (Short)readProperty("idtipomanodopera");
    }

    public void setIdtipomanodoperadic(Short idtipomanodoperadic) {
        writeProperty("idtipomanodoperadic", idtipomanodoperadic);
    }
    public Short getIdtipomanodoperadic() {
        return (Short)readProperty("idtipomanodoperadic");
    }

    public void setLg166lav(Short lg166lav) {
        writeProperty("lg166lav", lg166lav);
    }
    public Short getLg166lav() {
        return (Short)readProperty("lg166lav");
    }

    public void setLg166retrib(BigDecimal lg166retrib) {
        writeProperty("lg166retrib", lg166retrib);
    }
    public BigDecimal getLg166retrib() {
        return (BigDecimal)readProperty("lg166retrib");
    }

    public void setProgressivo(Short progressivo) {
        writeProperty("progressivo", progressivo);
    }
    public Short getProgressivo() {
        return (Short)readProperty("progressivo");
    }

    public void setRiallinadesione(Date riallinadesione) {
        writeProperty("riallinadesione", riallinadesione);
    }
    public Date getRiallinadesione() {
        return (Date)readProperty("riallinadesione");
    }

    public void setRiallincontratto(Date riallincontratto) {
        writeProperty("riallincontratto", riallincontratto);
    }
    public Date getRiallincontratto() {
        return (Date)readProperty("riallincontratto");
    }

    public void setRiallineamento(Short riallineamento) {
        writeProperty("riallineamento", riallineamento);
    }
    public Short getRiallineamento() {
        return (Short)readProperty("riallineamento");
    }

    public void setRiallinscadenza(Date riallinscadenza) {
        writeProperty("riallinscadenza", riallinscadenza);
    }
    public Date getRiallinscadenza() {
        return (Date)readProperty("riallinscadenza");
    }

    public void setToAsscategoria(DmagAsscategoria toAsscategoria) {
        setToOneTarget("toAsscategoria", toAsscategoria, true);
    }

    public DmagAsscategoria getToAsscategoria() {
        return (DmagAsscategoria)readProperty("toAsscategoria");
    }


    public void setToDmag(Dmag toDmag) {
        setToOneTarget("toDmag", toDmag, true);
    }

    public Dmag getToDmag() {
        return (Dmag)readProperty("toDmag");
    }


    public void setToTipoDitta1(DmagTipoditta1 toTipoDitta1) {
        setToOneTarget("toTipoDitta1", toTipoDitta1, true);
    }

    public DmagTipoditta1 getToTipoDitta1() {
        return (DmagTipoditta1)readProperty("toTipoDitta1");
    }


    public void setToTipoDitta2(DmagTipoditta2 toTipoDitta2) {
        setToOneTarget("toTipoDitta2", toTipoDitta2, true);
    }

    public DmagTipoditta2 getToTipoDitta2() {
        return (DmagTipoditta2)readProperty("toTipoDitta2");
    }


    public void setToTipodichiarazione(DmagTipodichiaraz toTipodichiarazione) {
        setToOneTarget("toTipodichiarazione", toTipodichiarazione, true);
    }

    public DmagTipodichiaraz getToTipodichiarazione() {
        return (DmagTipodichiaraz)readProperty("toTipodichiarazione");
    }


    public void setToTipomanodopera(DmagTipomanodopera toTipomanodopera) {
        setToOneTarget("toTipomanodopera", toTipomanodopera, true);
    }

    public DmagTipomanodopera getToTipomanodopera() {
        return (DmagTipomanodopera)readProperty("toTipomanodopera");
    }


    public void setToTipomanodoperadic(DmagTipomanodoperadic toTipomanodoperadic) {
        setToOneTarget("toTipomanodoperadic", toTipomanodoperadic, true);
    }

    public DmagTipomanodoperadic getToTipomanodoperadic() {
        return (DmagTipomanodoperadic)readProperty("toTipomanodoperadic");
    }


}
