package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DmagArealav;
import it.iubar.paghe.logic.paghe.DmagTipocategoria;
import it.iubar.paghe.logic.paghe.DmagTipoclassific;
import it.iubar.paghe.logic.paghe.DmagTipocontratto;
import it.iubar.paghe.logic.paghe.DmagTipolav;
import it.iubar.paghe.logic.paghe.DmagTiporetribuzione1;
import it.iubar.paghe.logic.paghe.DmagTiporetribuzione2;
import it.iubar.paghe.logic.paghe.DmagZt;
import it.iubar.paghe.logic.paghe.Posizionesubordinato;

/**
 * Class _DmagPosizionelav was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DmagPosizionelav extends CayenneDataObject {

    public static final String ACCANTONAMENTO_PROPERTY = "accantonamento";
    public static final String EMERSIONE_PROPERTY = "emersione";
    public static final String GIORNI_PROPERTY = "giorni";
    public static final String IDASSUNZIONE_PROPERTY = "idassunzione";
    public static final String IDCESSAZIONE_PROPERTY = "idcessazione";
    public static final String IDCOMUNEFONDO_PROPERTY = "idcomunefondo";
    public static final String IDTIPOCLASSIFIC_PROPERTY = "idtipoclassific";
    public static final String LIVELLO_PROPERTY = "livello";
    public static final String ORE_PROPERTY = "ore";
    public static final String PERPREVCOMPL_PROPERTY = "perprevcompl";
    public static final String RETRIBUZIONE_PROPERTY = "retribuzione";
    public static final String RIALLINEAMENTO_PROPERTY = "riallineamento";
    public static final String TO_DMAG_AREA_LAV_PROPERTY = "toDmagAreaLav";
    public static final String TO_DMAG_TIPO_CAT_PROPERTY = "toDmagTipoCat";
    public static final String TO_DMAG_TIPO_CLASSIFIC_PROPERTY = "toDmagTipoClassific";
    public static final String TO_DMAG_TIPO_CONTRATTO_PROPERTY = "toDmagTipoContratto";
    public static final String TO_DMAG_TIPO_LAV_PROPERTY = "toDmagTipoLav";
    public static final String TO_DMAG_TIPO_RETRIB1_PROPERTY = "toDmagTipoRetrib1";
    public static final String TO_DMAG_TIPO_RETRIB2_PROPERTY = "toDmagTipoRetrib2";
    public static final String TO_DMAG_ZT_PROPERTY = "toDmagZt";
    public static final String TO_POSIZIONESUB_PROPERTY = "toPosizionesub";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setAccantonamento(BigDecimal accantonamento) {
        writeProperty("accantonamento", accantonamento);
    }
    public BigDecimal getAccantonamento() {
        return (BigDecimal)readProperty("accantonamento");
    }

    public void setEmersione(Short emersione) {
        writeProperty("emersione", emersione);
    }
    public Short getEmersione() {
        return (Short)readProperty("emersione");
    }

    public void setGiorni(BigDecimal giorni) {
        writeProperty("giorni", giorni);
    }
    public BigDecimal getGiorni() {
        return (BigDecimal)readProperty("giorni");
    }

    public void setIdassunzione(Integer idassunzione) {
        writeProperty("idassunzione", idassunzione);
    }
    public Integer getIdassunzione() {
        return (Integer)readProperty("idassunzione");
    }

    public void setIdcessazione(Integer idcessazione) {
        writeProperty("idcessazione", idcessazione);
    }
    public Integer getIdcessazione() {
        return (Integer)readProperty("idcessazione");
    }

    public void setIdcomunefondo(String idcomunefondo) {
        writeProperty("idcomunefondo", idcomunefondo);
    }
    public String getIdcomunefondo() {
        return (String)readProperty("idcomunefondo");
    }

    public void setIdtipoclassific(Short idtipoclassific) {
        writeProperty("idtipoclassific", idtipoclassific);
    }
    public Short getIdtipoclassific() {
        return (Short)readProperty("idtipoclassific");
    }

    public void setLivello(String livello) {
        writeProperty("livello", livello);
    }
    public String getLivello() {
        return (String)readProperty("livello");
    }

    public void setOre(BigDecimal ore) {
        writeProperty("ore", ore);
    }
    public BigDecimal getOre() {
        return (BigDecimal)readProperty("ore");
    }

    public void setPerprevcompl(BigDecimal perprevcompl) {
        writeProperty("perprevcompl", perprevcompl);
    }
    public BigDecimal getPerprevcompl() {
        return (BigDecimal)readProperty("perprevcompl");
    }

    public void setRetribuzione(BigDecimal retribuzione) {
        writeProperty("retribuzione", retribuzione);
    }
    public BigDecimal getRetribuzione() {
        return (BigDecimal)readProperty("retribuzione");
    }

    public void setRiallineamento(Short riallineamento) {
        writeProperty("riallineamento", riallineamento);
    }
    public Short getRiallineamento() {
        return (Short)readProperty("riallineamento");
    }

    public void setToDmagAreaLav(DmagArealav toDmagAreaLav) {
        setToOneTarget("toDmagAreaLav", toDmagAreaLav, true);
    }

    public DmagArealav getToDmagAreaLav() {
        return (DmagArealav)readProperty("toDmagAreaLav");
    }


    public void setToDmagTipoCat(DmagTipocategoria toDmagTipoCat) {
        setToOneTarget("toDmagTipoCat", toDmagTipoCat, true);
    }

    public DmagTipocategoria getToDmagTipoCat() {
        return (DmagTipocategoria)readProperty("toDmagTipoCat");
    }


    public void setToDmagTipoClassific(DmagTipoclassific toDmagTipoClassific) {
        setToOneTarget("toDmagTipoClassific", toDmagTipoClassific, true);
    }

    public DmagTipoclassific getToDmagTipoClassific() {
        return (DmagTipoclassific)readProperty("toDmagTipoClassific");
    }


    public void setToDmagTipoContratto(DmagTipocontratto toDmagTipoContratto) {
        setToOneTarget("toDmagTipoContratto", toDmagTipoContratto, true);
    }

    public DmagTipocontratto getToDmagTipoContratto() {
        return (DmagTipocontratto)readProperty("toDmagTipoContratto");
    }


    public void setToDmagTipoLav(DmagTipolav toDmagTipoLav) {
        setToOneTarget("toDmagTipoLav", toDmagTipoLav, true);
    }

    public DmagTipolav getToDmagTipoLav() {
        return (DmagTipolav)readProperty("toDmagTipoLav");
    }


    public void setToDmagTipoRetrib1(DmagTiporetribuzione1 toDmagTipoRetrib1) {
        setToOneTarget("toDmagTipoRetrib1", toDmagTipoRetrib1, true);
    }

    public DmagTiporetribuzione1 getToDmagTipoRetrib1() {
        return (DmagTiporetribuzione1)readProperty("toDmagTipoRetrib1");
    }


    public void setToDmagTipoRetrib2(DmagTiporetribuzione2 toDmagTipoRetrib2) {
        setToOneTarget("toDmagTipoRetrib2", toDmagTipoRetrib2, true);
    }

    public DmagTiporetribuzione2 getToDmagTipoRetrib2() {
        return (DmagTiporetribuzione2)readProperty("toDmagTipoRetrib2");
    }


    public void setToDmagZt(DmagZt toDmagZt) {
        setToOneTarget("toDmagZt", toDmagZt, true);
    }

    public DmagZt getToDmagZt() {
        return (DmagZt)readProperty("toDmagZt");
    }


    public void setToPosizionesub(Posizionesubordinato toPosizionesub) {
        setToOneTarget("toPosizionesub", toPosizionesub, true);
    }

    public Posizionesubordinato getToPosizionesub() {
        return (Posizionesubordinato)readProperty("toPosizionesub");
    }


}
