package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Cigsadebito;

/**
 * Class _DrCausalecontribaddcigs was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrCausalecontribaddcigs extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDCAUSALECONTRADDCIGS_PROPERTY = "idcausalecontraddcigs";
    public static final String CIGS_ADEBITO_ARRAY_PROPERTY = "cigsADebitoArray";

    public static final String IDCAUSALECONTRIBADDCIGS_PK_COLUMN = "IDCAUSALECONTRIBADDCIGS";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdcausalecontraddcigs() {
        return (String)readProperty("idcausalecontraddcigs");
    }

    public void addToCigsADebitoArray(Cigsadebito obj) {
        addToManyTarget("cigsADebitoArray", obj, true);
    }
    public void removeFromCigsADebitoArray(Cigsadebito obj) {
        removeToManyTarget("cigsADebitoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cigsadebito> getCigsADebitoArray() {
        return (List<Cigsadebito>)readProperty("cigsADebitoArray");
    }


}
