package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DrCausaleversmat;
import it.iubar.paghe.logic.paghe.DrMalattia;
import it.iubar.paghe.logic.paghe.DrMaternita;

/**
 * Class _DrMaternitaadebito was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DrMaternitaadebito extends CayenneDataObject {

    public static final String IDCAUSALEVERSMAT_PROPERTY = "idcausaleversmat";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IDMATERNITAADEBITO_PROPERTY = "idmaternitaadebito";
    public static final String IMPORTOVERSMAT_PROPERTY = "importoversmat";
    public static final String TO_DR_CAUSALE_VERS_MAT_PROPERTY = "toDrCausaleVersMat";
    public static final String TO_DR_MALATTIA_PROPERTY = "toDrMalattia";
    public static final String TO_DR_MATERNITA_PROPERTY = "toDrMaternita";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";
    public static final String IDMATERNITAADEBITO_PK_COLUMN = "IDMATERNITAADEBITO";

    public void setIdcausaleversmat(String idcausaleversmat) {
        writeProperty("idcausaleversmat", idcausaleversmat);
    }
    public String getIdcausaleversmat() {
        return (String)readProperty("idcausaleversmat");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIdmaternitaadebito(Short idmaternitaadebito) {
        writeProperty("idmaternitaadebito", idmaternitaadebito);
    }
    public Short getIdmaternitaadebito() {
        return (Short)readProperty("idmaternitaadebito");
    }

    public void setImportoversmat(BigDecimal importoversmat) {
        writeProperty("importoversmat", importoversmat);
    }
    public BigDecimal getImportoversmat() {
        return (BigDecimal)readProperty("importoversmat");
    }

    public void setToDrCausaleVersMat(DrCausaleversmat toDrCausaleVersMat) {
        setToOneTarget("toDrCausaleVersMat", toDrCausaleVersMat, true);
    }

    public DrCausaleversmat getToDrCausaleVersMat() {
        return (DrCausaleversmat)readProperty("toDrCausaleVersMat");
    }


    public void setToDrMalattia(DrMalattia toDrMalattia) {
        setToOneTarget("toDrMalattia", toDrMalattia, true);
    }

    public DrMalattia getToDrMalattia() {
        return (DrMalattia)readProperty("toDrMalattia");
    }


    public void setToDrMaternita(DrMaternita toDrMaternita) {
        setToOneTarget("toDrMaternita", toDrMaternita, true);
    }

    public DrMaternita getToDrMaternita() {
        return (DrMaternita)readProperty("toDrMaternita");
    }


}
