package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoparticolare;
import it.iubar.paghe.logic.paghe.InpsEsterotipoimp;
import it.iubar.paghe.logic.paghe.Tipocontribestero;

/**
 * Class _Estero was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Estero extends CayenneDataObject {

    public static final String CONTRIBUTOESTERO_PROPERTY = "contributoestero";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IDESTEROTIPOIMP_PROPERTY = "idesterotipoimp";
    public static final String IDTIPOCONTRIBESTERO_PROPERTY = "idtipocontribestero";
    public static final String IMPONIBILE_PROPERTY = "imponibile";
    public static final String TO_DATOPARTICOLARE_PROPERTY = "toDatoparticolare";
    public static final String TO_INPS_ESTERO_TIPO_IMP_PROPERTY = "toInpsEsteroTipoImp";
    public static final String TO_TIPOCONTRIBESTERO_PROPERTY = "toTipocontribestero";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";
    public static final String IDTIPOCONTRIBESTERO_PK_COLUMN = "IDTIPOCONTRIBESTERO";

    public void setContributoestero(BigDecimal contributoestero) {
        writeProperty("contributoestero", contributoestero);
    }
    public BigDecimal getContributoestero() {
        return (BigDecimal)readProperty("contributoestero");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIdesterotipoimp(String idesterotipoimp) {
        writeProperty("idesterotipoimp", idesterotipoimp);
    }
    public String getIdesterotipoimp() {
        return (String)readProperty("idesterotipoimp");
    }

    public void setIdtipocontribestero(String idtipocontribestero) {
        writeProperty("idtipocontribestero", idtipocontribestero);
    }
    public String getIdtipocontribestero() {
        return (String)readProperty("idtipocontribestero");
    }

    public void setImponibile(BigDecimal imponibile) {
        writeProperty("imponibile", imponibile);
    }
    public BigDecimal getImponibile() {
        return (BigDecimal)readProperty("imponibile");
    }

    public void addToToDatoparticolare(Datoparticolare obj) {
        addToManyTarget("toDatoparticolare", obj, true);
    }
    public void removeFromToDatoparticolare(Datoparticolare obj) {
        removeToManyTarget("toDatoparticolare", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Datoparticolare> getToDatoparticolare() {
        return (List<Datoparticolare>)readProperty("toDatoparticolare");
    }


    public void setToInpsEsteroTipoImp(InpsEsterotipoimp toInpsEsteroTipoImp) {
        setToOneTarget("toInpsEsteroTipoImp", toInpsEsteroTipoImp, true);
    }

    public InpsEsterotipoimp getToInpsEsteroTipoImp() {
        return (InpsEsterotipoimp)readProperty("toInpsEsteroTipoImp");
    }


    public void setToTipocontribestero(Tipocontribestero toTipocontribestero) {
        setToOneTarget("toTipocontribestero", toTipocontribestero, true);
    }

    public Tipocontribestero getToTipocontribestero() {
        return (Tipocontribestero)readProperty("toTipocontribestero");
    }


}
