package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.blob.Documento;
import it.iubar.paghe.logic.paghe.Dichiarazione;
import it.iubar.paghe.logic.paghe.F24Altroente;
import it.iubar.paghe.logic.paghe.F24Erario;
import it.iubar.paghe.logic.paghe.F24Inps;
import it.iubar.paghe.logic.paghe.F24Regione;

/**
 * Class _F24 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _F24 extends CayenneDataObject {

    public static final String IDDICHIARAZIONE_PROPERTY = "iddichiarazione";
    public static final String IDDOCUMENTO_PROPERTY = "iddocumento";
    public static final String IDEXPORT_PROPERTY = "idexport";
    public static final String IMPORTOCREDITO_PROPERTY = "importocredito";
    public static final String IMPORTODEBITO_PROPERTY = "importodebito";
    public static final String F24ALTRO_ENTE_ARRAY_PROPERTY = "f24AltroEnteArray";
    public static final String F24ERARIO_ARRAY_PROPERTY = "f24ErarioArray";
    public static final String F24INPS_ARRAY_PROPERTY = "f24InpsArray";
    public static final String F24REGIONE_ARRAY_PROPERTY = "f24RegioneArray";
    public static final String TO_DICHIARAZIONE_PROPERTY = "toDichiarazione";
    public static final String TO_DOCUMENTO_PROPERTY = "toDocumento";
    public static final String TO_ESITO_PROPERTY = "toEsito";
    public static final String TO_EXPORT_PROPERTY = "toExport";

    public static final String IDDICHIARAZIONE_PK_COLUMN = "IDDICHIARAZIONE";

    public void setIddichiarazione(Integer iddichiarazione) {
        writeProperty("iddichiarazione", iddichiarazione);
    }
    public Integer getIddichiarazione() {
        return (Integer)readProperty("iddichiarazione");
    }

    public void setIddocumento(Integer iddocumento) {
        writeProperty("iddocumento", iddocumento);
    }
    public Integer getIddocumento() {
        return (Integer)readProperty("iddocumento");
    }

    public void setIdexport(Integer idexport) {
        writeProperty("idexport", idexport);
    }
    public Integer getIdexport() {
        return (Integer)readProperty("idexport");
    }

    public void setImportocredito(BigDecimal importocredito) {
        writeProperty("importocredito", importocredito);
    }
    public BigDecimal getImportocredito() {
        return (BigDecimal)readProperty("importocredito");
    }

    public void setImportodebito(BigDecimal importodebito) {
        writeProperty("importodebito", importodebito);
    }
    public BigDecimal getImportodebito() {
        return (BigDecimal)readProperty("importodebito");
    }

    public void addToF24AltroEnteArray(F24Altroente obj) {
        addToManyTarget("f24AltroEnteArray", obj, true);
    }
    public void removeFromF24AltroEnteArray(F24Altroente obj) {
        removeToManyTarget("f24AltroEnteArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<F24Altroente> getF24AltroEnteArray() {
        return (List<F24Altroente>)readProperty("f24AltroEnteArray");
    }


    public void addToF24ErarioArray(F24Erario obj) {
        addToManyTarget("f24ErarioArray", obj, true);
    }
    public void removeFromF24ErarioArray(F24Erario obj) {
        removeToManyTarget("f24ErarioArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<F24Erario> getF24ErarioArray() {
        return (List<F24Erario>)readProperty("f24ErarioArray");
    }


    public void addToF24InpsArray(F24Inps obj) {
        addToManyTarget("f24InpsArray", obj, true);
    }
    public void removeFromF24InpsArray(F24Inps obj) {
        removeToManyTarget("f24InpsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<F24Inps> getF24InpsArray() {
        return (List<F24Inps>)readProperty("f24InpsArray");
    }


    public void addToF24RegioneArray(F24Regione obj) {
        addToManyTarget("f24RegioneArray", obj, true);
    }
    public void removeFromF24RegioneArray(F24Regione obj) {
        removeToManyTarget("f24RegioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<F24Regione> getF24RegioneArray() {
        return (List<F24Regione>)readProperty("f24RegioneArray");
    }


    public void setToDichiarazione(Dichiarazione toDichiarazione) {
        setToOneTarget("toDichiarazione", toDichiarazione, true);
    }

    public Dichiarazione getToDichiarazione() {
        return (Dichiarazione)readProperty("toDichiarazione");
    }


    public void setToDocumento(Documento toDocumento) {
        setToOneTarget("toDocumento", toDocumento, true);
    }

    public Documento getToDocumento() {
        return (Documento)readProperty("toDocumento");
    }


    public void setToEsito(Documento toEsito) {
        setToOneTarget("toEsito", toEsito, true);
    }

    public Documento getToEsito() {
        return (Documento)readProperty("toEsito");
    }


    public void setToExport(Documento toExport) {
        setToOneTarget("toExport", toExport, true);
    }

    public Documento getToExport() {
        return (Documento)readProperty("toExport");
    }


}
