package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.DrCausaletrattpens;
import it.iubar.paghe.logic.paghe.Lavpenstrattenuta;

/**
 * Class _Fondidiversi was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Fondidiversi extends CayenneDataObject {

    public static final String IDCAUSALETRATTPENS_PROPERTY = "idcausaletrattpens";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IDFONDIDIVERSI_PROPERTY = "idfondidiversi";
    public static final String IMPORTOTRATTPENS_PROPERTY = "importotrattpens";
    public static final String TO_DR_CAUSALE_TRATT_PENS_PROPERTY = "toDrCausaleTrattPens";
    public static final String TO_LAV_PENS_TRATTENUTA_PROPERTY = "toLavPensTrattenuta";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";
    public static final String IDFONDIDIVERSI_PK_COLUMN = "IDFONDIDIVERSI";

    public void setIdcausaletrattpens(String idcausaletrattpens) {
        writeProperty("idcausaletrattpens", idcausaletrattpens);
    }
    public String getIdcausaletrattpens() {
        return (String)readProperty("idcausaletrattpens");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setIdfondidiversi(Short idfondidiversi) {
        writeProperty("idfondidiversi", idfondidiversi);
    }
    public Short getIdfondidiversi() {
        return (Short)readProperty("idfondidiversi");
    }

    public void setImportotrattpens(BigDecimal importotrattpens) {
        writeProperty("importotrattpens", importotrattpens);
    }
    public BigDecimal getImportotrattpens() {
        return (BigDecimal)readProperty("importotrattpens");
    }

    public void setToDrCausaleTrattPens(DrCausaletrattpens toDrCausaleTrattPens) {
        setToOneTarget("toDrCausaleTrattPens", toDrCausaleTrattPens, true);
    }

    public DrCausaletrattpens getToDrCausaleTrattPens() {
        return (DrCausaletrattpens)readProperty("toDrCausaleTrattPens");
    }


    public void setToLavPensTrattenuta(Lavpenstrattenuta toLavPensTrattenuta) {
        setToOneTarget("toLavPensTrattenuta", toLavPensTrattenuta, true);
    }

    public Lavpenstrattenuta getToLavPensTrattenuta() {
        return (Lavpenstrattenuta)readProperty("toLavPensTrattenuta");
    }


}
