package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Anfacredito;
import it.iubar.paghe.logic.paghe.Anfadebito;
import it.iubar.paghe.logic.paghe.Anft4;
import it.iubar.paghe.logic.paghe.Datoretributivo;

/**
 * Class _Gestioneanf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Gestioneanf extends CayenneDataObject {

    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String ANF_ACREDITO_ARRAY_PROPERTY = "anfACreditoArray";
    public static final String ANF_ADEBITO_ARRAY_PROPERTY = "anfADebitoArray";
    public static final String ANT_T4ARRAY_PROPERTY = "antT4Array";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void addToAnfACreditoArray(Anfacredito obj) {
        addToManyTarget("anfACreditoArray", obj, true);
    }
    public void removeFromAnfACreditoArray(Anfacredito obj) {
        removeToManyTarget("anfACreditoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Anfacredito> getAnfACreditoArray() {
        return (List<Anfacredito>)readProperty("anfACreditoArray");
    }


    public void addToAnfADebitoArray(Anfadebito obj) {
        addToManyTarget("anfADebitoArray", obj, true);
    }
    public void removeFromAnfADebitoArray(Anfadebito obj) {
        removeToManyTarget("anfADebitoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Anfadebito> getAnfADebitoArray() {
        return (List<Anfadebito>)readProperty("anfADebitoArray");
    }


    public void addToAntT4Array(Anft4 obj) {
        addToManyTarget("antT4Array", obj, true);
    }
    public void removeFromAntT4Array(Anft4 obj) {
        removeToManyTarget("antT4Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Anft4> getAntT4Array() {
        return (List<Anft4>)readProperty("antT4Array");
    }


    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


}
