package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _InailRischioassicurato was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InailRischioassicurato extends CayenneDataObject {

    public static final String AGEVOLAZIONE_PROPERTY = "agevolazione";
    public static final String ARTIGIANOPREMIO_PROPERTY = "artigianopremio";
    public static final String ARTIGIANORETRIBCONVENZ_PROPERTY = "artigianoretribconvenz";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDRISCHIO_PROPERTY = "idrischio";
    public static final String IDSEDEIMPRESA_PROPERTY = "idsedeimpresa";
    public static final String IDTIPOAGEVOLAZIONE_PROPERTY = "idtipoagevolazione";
    public static final String IDVOCETARIFFA_PROPERTY = "idvocetariffa";
    public static final String OSCILLAZIONESILICOSI_PROPERTY = "oscillazionesilicosi";
    public static final String PAT_PROPERTY = "pat";
    public static final String PERIODOAL_PROPERTY = "periodoal";
    public static final String PERIODODAL_PROPERTY = "periododal";
    public static final String RISCHIOSILASB_PROPERTY = "rischiosilasb";
    public static final String TASSOINFORTUNIAPPLICATO_PROPERTY = "tassoinfortuniapplicato";
    public static final String TASSOINFORTUNITEORICO_PROPERTY = "tassoinfortuniteorico";

    public static final String IDRISCHIO_PK_COLUMN = "IDRISCHIO";

    public void setAgevolazione(BigDecimal agevolazione) {
        writeProperty("agevolazione", agevolazione);
    }
    public BigDecimal getAgevolazione() {
        return (BigDecimal)readProperty("agevolazione");
    }

    public void setArtigianopremio(BigDecimal artigianopremio) {
        writeProperty("artigianopremio", artigianopremio);
    }
    public BigDecimal getArtigianopremio() {
        return (BigDecimal)readProperty("artigianopremio");
    }

    public void setArtigianoretribconvenz(BigDecimal artigianoretribconvenz) {
        writeProperty("artigianoretribconvenz", artigianoretribconvenz);
    }
    public BigDecimal getArtigianoretribconvenz() {
        return (BigDecimal)readProperty("artigianoretribconvenz");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdrischio(Integer idrischio) {
        writeProperty("idrischio", idrischio);
    }
    public Integer getIdrischio() {
        return (Integer)readProperty("idrischio");
    }

    public void setIdsedeimpresa(Short idsedeimpresa) {
        writeProperty("idsedeimpresa", idsedeimpresa);
    }
    public Short getIdsedeimpresa() {
        return (Short)readProperty("idsedeimpresa");
    }

    public void setIdtipoagevolazione(Integer idtipoagevolazione) {
        writeProperty("idtipoagevolazione", idtipoagevolazione);
    }
    public Integer getIdtipoagevolazione() {
        return (Integer)readProperty("idtipoagevolazione");
    }

    public void setIdvocetariffa(Integer idvocetariffa) {
        writeProperty("idvocetariffa", idvocetariffa);
    }
    public Integer getIdvocetariffa() {
        return (Integer)readProperty("idvocetariffa");
    }

    public void setOscillazionesilicosi(BigDecimal oscillazionesilicosi) {
        writeProperty("oscillazionesilicosi", oscillazionesilicosi);
    }
    public BigDecimal getOscillazionesilicosi() {
        return (BigDecimal)readProperty("oscillazionesilicosi");
    }

    public void setPat(String pat) {
        writeProperty("pat", pat);
    }
    public String getPat() {
        return (String)readProperty("pat");
    }

    public void setPeriodoal(Date periodoal) {
        writeProperty("periodoal", periodoal);
    }
    public Date getPeriodoal() {
        return (Date)readProperty("periodoal");
    }

    public void setPeriododal(Date periododal) {
        writeProperty("periododal", periododal);
    }
    public Date getPeriododal() {
        return (Date)readProperty("periododal");
    }

    public void setRischiosilasb(BigDecimal rischiosilasb) {
        writeProperty("rischiosilasb", rischiosilasb);
    }
    public BigDecimal getRischiosilasb() {
        return (BigDecimal)readProperty("rischiosilasb");
    }

    public void setTassoinfortuniapplicato(BigDecimal tassoinfortuniapplicato) {
        writeProperty("tassoinfortuniapplicato", tassoinfortuniapplicato);
    }
    public BigDecimal getTassoinfortuniapplicato() {
        return (BigDecimal)readProperty("tassoinfortuniapplicato");
    }

    public void setTassoinfortuniteorico(BigDecimal tassoinfortuniteorico) {
        writeProperty("tassoinfortuniteorico", tassoinfortuniteorico);
    }
    public BigDecimal getTassoinfortuniteorico() {
        return (BigDecimal)readProperty("tassoinfortuniteorico");
    }

}
