package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.InailArtigiano;
import it.iubar.paghe.logic.paghe.InailContribassociativo;
import it.iubar.paghe.logic.paghe.InailInfmal;
import it.iubar.paghe.logic.paghe.InailRiepilogo;
import it.iubar.paghe.logic.paghe.InailSconto;
import it.iubar.paghe.logic.paghe.InailSilasb;

/**
 * Class _InailPosizioneimpresa was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InailPosizioneimpresa extends CayenneDataObject {

    public static final String ANNO_PROPERTY = "anno";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String PAT_PROPERTY = "pat";
    public static final String INAIL_ARTIGIANO_ARRAY_PROPERTY = "inailArtigianoArray";
    public static final String INAIL_CONTRIBASSOCIATIVO_ARRAY_PROPERTY = "inailContribassociativoArray";
    public static final String INAIL_INFMAL_ARRAY_PROPERTY = "inailInfmalArray";
    public static final String INAIL_RIEPILOGO_ARRAY_PROPERTY = "inailRiepilogoArray";
    public static final String INAIL_SCONTO_ARRAY_PROPERTY = "inailScontoArray";
    public static final String INAIL_SILASB_ARRAY_PROPERTY = "inailSilasbArray";

    public static final String ANNO_PK_COLUMN = "ANNO";
    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";
    public static final String PAT_PK_COLUMN = "PAT";

    public void setAnno(Integer anno) {
        writeProperty("anno", anno);
    }
    public Integer getAnno() {
        return (Integer)readProperty("anno");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setPat(String pat) {
        writeProperty("pat", pat);
    }
    public String getPat() {
        return (String)readProperty("pat");
    }

    public void addToInailArtigianoArray(InailArtigiano obj) {
        addToManyTarget("inailArtigianoArray", obj, true);
    }
    public void removeFromInailArtigianoArray(InailArtigiano obj) {
        removeToManyTarget("inailArtigianoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InailArtigiano> getInailArtigianoArray() {
        return (List<InailArtigiano>)readProperty("inailArtigianoArray");
    }


    public void addToInailContribassociativoArray(InailContribassociativo obj) {
        addToManyTarget("inailContribassociativoArray", obj, true);
    }
    public void removeFromInailContribassociativoArray(InailContribassociativo obj) {
        removeToManyTarget("inailContribassociativoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InailContribassociativo> getInailContribassociativoArray() {
        return (List<InailContribassociativo>)readProperty("inailContribassociativoArray");
    }


    public void addToInailInfmalArray(InailInfmal obj) {
        addToManyTarget("inailInfmalArray", obj, true);
    }
    public void removeFromInailInfmalArray(InailInfmal obj) {
        removeToManyTarget("inailInfmalArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InailInfmal> getInailInfmalArray() {
        return (List<InailInfmal>)readProperty("inailInfmalArray");
    }


    public void addToInailRiepilogoArray(InailRiepilogo obj) {
        addToManyTarget("inailRiepilogoArray", obj, true);
    }
    public void removeFromInailRiepilogoArray(InailRiepilogo obj) {
        removeToManyTarget("inailRiepilogoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InailRiepilogo> getInailRiepilogoArray() {
        return (List<InailRiepilogo>)readProperty("inailRiepilogoArray");
    }


    public void addToInailScontoArray(InailSconto obj) {
        addToManyTarget("inailScontoArray", obj, true);
    }
    public void removeFromInailScontoArray(InailSconto obj) {
        removeToManyTarget("inailScontoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InailSconto> getInailScontoArray() {
        return (List<InailSconto>)readProperty("inailScontoArray");
    }


    public void addToInailSilasbArray(InailSilasb obj) {
        addToManyTarget("inailSilasbArray", obj, true);
    }
    public void removeFromInailSilasbArray(InailSilasb obj) {
        removeToManyTarget("inailSilasbArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InailSilasb> getInailSilasbArray() {
        return (List<InailSilasb>)readProperty("inailSilasbArray");
    }


}
