package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.InpsLimitecategoria;

/**
 * Class _InpsLimitecategoria2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsLimitecategoria2 extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDLIMITECATEGORIA2_PROPERTY = "idlimitecategoria2";
    public static final String INPS_LIMITECATEGORIA_ARRAY_PROPERTY = "inpsLimitecategoriaArray";

    public static final String IDLIMITECATEGORIA2_PK_COLUMN = "IDLIMITECATEGORIA2";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdlimitecategoria2() {
        return (Short)readProperty("idlimitecategoria2");
    }

    public void addToInpsLimitecategoriaArray(InpsLimitecategoria obj) {
        addToManyTarget("inpsLimitecategoriaArray", obj, true);
    }
    public void removeFromInpsLimitecategoriaArray(InpsLimitecategoria obj) {
        removeToManyTarget("inpsLimitecategoriaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsLimitecategoria> getInpsLimitecategoriaArray() {
        return (List<InpsLimitecategoria>)readProperty("inpsLimitecategoriaArray");
    }


}
