package it.iubar.paghe.logic.paghe.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.InpsAliquotagruppo;
import it.iubar.paghe.logic.paghe.InpsContratto;

/**
 * Class _InpsContrattoGruppo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsContrattoGruppo extends CayenneDataObject {

    public static final String IDGRUPPO_PROPERTY = "idgruppo";
    public static final String IDINPSCONTRATTO_PROPERTY = "idinpscontratto";
    public static final String TO_ALIQUOTA_GRUPPO_PROPERTY = "toAliquotaGruppo";
    public static final String TO_INPS_CONTRATTO_PROPERTY = "toInpsContratto";

    public static final String IDGRUPPO_PK_COLUMN = "IDGRUPPO";
    public static final String IDINPSCONTRATTO_PK_COLUMN = "IDINPSCONTRATTO";

    public Short getIdgruppo() {
        return (Short)readProperty("idgruppo");
    }

    public String getIdinpscontratto() {
        return (String)readProperty("idinpscontratto");
    }


    public InpsAliquotagruppo getToAliquotaGruppo() {
        return (InpsAliquotagruppo)readProperty("toAliquotaGruppo");
    }



    public InpsContratto getToInpsContratto() {
        return (InpsContratto)readProperty("toInpsContratto");
    }


}
