package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.InpsAliquotacollaboratore;

/**
 * Class _InpsAliquotacolldettaglio was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsAliquotacolldettaglio extends CayenneDataObject {

    public static final String ALTRAALIQUOTA1_PROPERTY = "altraaliquota1";
    public static final String ALTRAALIQUOTA2_PROPERTY = "altraaliquota2";
    public static final String IDINPSALIQUOTA_PROPERTY = "idinpsaliquota";
    public static final String INPSALIQUOTAANNO_PROPERTY = "inpsaliquotaanno";
    public static final String IVS_PROPERTY = "ivs";
    public static final String MASSIMALEANNUO_PROPERTY = "massimaleannuo";
    public static final String REDDITOA_PROPERTY = "redditoa";
    public static final String REDDITODA_PROPERTY = "redditoda";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String TO_ALIQUOTA_PROPERTY = "toAliquota";

    public static final String IDINPSALIQUOTA_PK_COLUMN = "IDINPSALIQUOTA";
    public static final String INPSALIQUOTAANNO_PK_COLUMN = "INPSALIQUOTAANNO";

    public BigDecimal getAltraaliquota1() {
        return (BigDecimal)readProperty("altraaliquota1");
    }

    public BigDecimal getAltraaliquota2() {
        return (BigDecimal)readProperty("altraaliquota2");
    }

    public String getIdinpsaliquota() {
        return (String)readProperty("idinpsaliquota");
    }

    public Integer getInpsaliquotaanno() {
        return (Integer)readProperty("inpsaliquotaanno");
    }

    public BigDecimal getIvs() {
        return (BigDecimal)readProperty("ivs");
    }

    public BigDecimal getMassimaleannuo() {
        return (BigDecimal)readProperty("massimaleannuo");
    }

    public BigDecimal getRedditoa() {
        return (BigDecimal)readProperty("redditoa");
    }

    public BigDecimal getRedditoda() {
        return (BigDecimal)readProperty("redditoda");
    }

    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToToAliquota(InpsAliquotacollaboratore obj) {
        addToManyTarget("toAliquota", obj, true);
    }
    public void removeFromToAliquota(InpsAliquotacollaboratore obj) {
        removeToManyTarget("toAliquota", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsAliquotacollaboratore> getToAliquota() {
        return (List<InpsAliquotacollaboratore>)readProperty("toAliquota");
    }


}
