package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Agevolazione;

/**
 * Class _InpsTipoagevolazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsTipoagevolazione extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDINPSTIPOAGEVOLAZIONE_PROPERTY = "idinpstipoagevolazione";
    public static final String AGEVOLAZIONE_ARRAY_PROPERTY = "agevolazioneArray";

    public static final String IDINPSTIPOAGEVOLAZIONE_PK_COLUMN = "IDINPSTIPOAGEVOLAZIONE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdinpstipoagevolazione() {
        return (String)readProperty("idinpstipoagevolazione");
    }

    public void addToAgevolazioneArray(Agevolazione obj) {
        addToManyTarget("agevolazioneArray", obj, true);
    }
    public void removeFromAgevolazioneArray(Agevolazione obj) {
        removeToManyTarget("agevolazioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Agevolazione> getAgevolazioneArray() {
        return (List<Agevolazione>)readProperty("agevolazioneArray");
    }


}
