package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Frequenza;
import it.iubar.paghe.logic.paghe.InpsLimitecategoria;
import it.iubar.paghe.logic.paghe.InpsLimitequalifica;
import it.iubar.paghe.logic.paghe.Posizioneprevidenziale;
import it.iubar.paghe.logic.paghe.Profiloprevidenziale;
import it.iubar.paghe.logic.paghe.Unitamisura;

/**
 * Class _InpsLimiteimponibile was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsLimiteimponibile extends CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String FASCIAA_PROPERTY = "fasciaa";
    public static final String FASCIADA_PROPERTY = "fasciada";
    public static final String FASCIADENOMINAZIONE_PROPERTY = "fasciadenominazione";
    public static final String IDLIMITECATEGORIA_PROPERTY = "idlimitecategoria";
    public static final String IDLIMITEIMPONIBILE_PROPERTY = "idlimiteimponibile";
    public static final String IDLIMITEQUALIFICA_PROPERTY = "idlimitequalifica";
    public static final String IDTIPOLIMITE_PROPERTY = "idtipolimite";
    public static final String IDUNITAMISURA_PROPERTY = "idunitamisura";
    public static final String MASSIMO_PROPERTY = "massimo";
    public static final String MINIMO_PROPERTY = "minimo";
    public static final String NOTE_PROPERTY = "note";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String POSIZIONEPREVIDENZIALE_ARRAY_PROPERTY = "posizioneprevidenzialeArray";
    public static final String PROFILOPREVIDENZIALE_ARRAY_PROPERTY = "profiloprevidenzialeArray";
    public static final String TO_FREQUENZA_PROPERTY = "toFrequenza";
    public static final String TO_LIMITECATEGORIA_PROPERTY = "toLimitecategoria";
    public static final String TO_LIMITEQUALIFICA_PROPERTY = "toLimitequalifica";
    public static final String TO_UNITAMISURA_PROPERTY = "toUnitamisura";

    public static final String IDLIMITEIMPONIBILE_PK_COLUMN = "IDLIMITEIMPONIBILE";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }

    public void setFasciaa(BigDecimal fasciaa) {
        writeProperty("fasciaa", fasciaa);
    }
    public BigDecimal getFasciaa() {
        return (BigDecimal)readProperty("fasciaa");
    }

    public void setFasciada(BigDecimal fasciada) {
        writeProperty("fasciada", fasciada);
    }
    public BigDecimal getFasciada() {
        return (BigDecimal)readProperty("fasciada");
    }

    public void setFasciadenominazione(String fasciadenominazione) {
        writeProperty("fasciadenominazione", fasciadenominazione);
    }
    public String getFasciadenominazione() {
        return (String)readProperty("fasciadenominazione");
    }

    public void setIdlimitecategoria(Short idlimitecategoria) {
        writeProperty("idlimitecategoria", idlimitecategoria);
    }
    public Short getIdlimitecategoria() {
        return (Short)readProperty("idlimitecategoria");
    }

    public void setIdlimiteimponibile(Integer idlimiteimponibile) {
        writeProperty("idlimiteimponibile", idlimiteimponibile);
    }
    public Integer getIdlimiteimponibile() {
        return (Integer)readProperty("idlimiteimponibile");
    }

    public void setIdlimitequalifica(Short idlimitequalifica) {
        writeProperty("idlimitequalifica", idlimitequalifica);
    }
    public Short getIdlimitequalifica() {
        return (Short)readProperty("idlimitequalifica");
    }

    public void setIdtipolimite(Short idtipolimite) {
        writeProperty("idtipolimite", idtipolimite);
    }
    public Short getIdtipolimite() {
        return (Short)readProperty("idtipolimite");
    }

    public void setIdunitamisura(Short idunitamisura) {
        writeProperty("idunitamisura", idunitamisura);
    }
    public Short getIdunitamisura() {
        return (Short)readProperty("idunitamisura");
    }

    public void setMassimo(BigDecimal massimo) {
        writeProperty("massimo", massimo);
    }
    public BigDecimal getMassimo() {
        return (BigDecimal)readProperty("massimo");
    }

    public void setMinimo(BigDecimal minimo) {
        writeProperty("minimo", minimo);
    }
    public BigDecimal getMinimo() {
        return (BigDecimal)readProperty("minimo");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setValidoal(Date validoal) {
        writeProperty("validoal", validoal);
    }
    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToPosizioneprevidenzialeArray(Posizioneprevidenziale obj) {
        addToManyTarget("posizioneprevidenzialeArray", obj, true);
    }
    public void removeFromPosizioneprevidenzialeArray(Posizioneprevidenziale obj) {
        removeToManyTarget("posizioneprevidenzialeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizioneprevidenziale> getPosizioneprevidenzialeArray() {
        return (List<Posizioneprevidenziale>)readProperty("posizioneprevidenzialeArray");
    }


    public void addToProfiloprevidenzialeArray(Profiloprevidenziale obj) {
        addToManyTarget("profiloprevidenzialeArray", obj, true);
    }
    public void removeFromProfiloprevidenzialeArray(Profiloprevidenziale obj) {
        removeToManyTarget("profiloprevidenzialeArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profiloprevidenziale> getProfiloprevidenzialeArray() {
        return (List<Profiloprevidenziale>)readProperty("profiloprevidenzialeArray");
    }


    public void setToFrequenza(Frequenza toFrequenza) {
        setToOneTarget("toFrequenza", toFrequenza, true);
    }

    public Frequenza getToFrequenza() {
        return (Frequenza)readProperty("toFrequenza");
    }


    public void setToLimitecategoria(InpsLimitecategoria toLimitecategoria) {
        setToOneTarget("toLimitecategoria", toLimitecategoria, true);
    }

    public InpsLimitecategoria getToLimitecategoria() {
        return (InpsLimitecategoria)readProperty("toLimitecategoria");
    }


    public void setToLimitequalifica(InpsLimitequalifica toLimitequalifica) {
        setToOneTarget("toLimitequalifica", toLimitequalifica, true);
    }

    public InpsLimitequalifica getToLimitequalifica() {
        return (InpsLimitequalifica)readProperty("toLimitequalifica");
    }


    public void setToUnitamisura(Unitamisura toUnitamisura) {
        setToOneTarget("toUnitamisura", toUnitamisura, true);
    }

    public Unitamisura getToUnitamisura() {
        return (Unitamisura)readProperty("toUnitamisura");
    }


}
