package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Anf;
import it.iubar.paghe.logic.paghe.InpsTipoanf;
import it.iubar.paghe.logic.paghe.InpsTipoanf2;

/**
 * Class _InpsClasseanf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsClasseanf extends CayenneDataObject {

    public static final String C1_PROPERTY = "c1";
    public static final String C10_PROPERTY = "c10";
    public static final String C11_PROPERTY = "c11";
    public static final String C12_PROPERTY = "c12";
    public static final String C2_PROPERTY = "c2";
    public static final String C3_PROPERTY = "c3";
    public static final String C4_PROPERTY = "c4";
    public static final String C5_PROPERTY = "c5";
    public static final String C6_PROPERTY = "c6";
    public static final String C7_PROPERTY = "c7";
    public static final String C8_PROPERTY = "c8";
    public static final String C9_PROPERTY = "c9";
    public static final String IDCLASSEANF_PROPERTY = "idclasseanf";
    public static final String IDINPSTIPOANF_PROPERTY = "idinpstipoanf";
    public static final String IDINPSTIPOANF2_PROPERTY = "idinpstipoanf2";
    public static final String NOTE_PROPERTY = "note";
    public static final String REDDITOA_PROPERTY = "redditoa";
    public static final String REDDITODA_PROPERTY = "redditoda";
    public static final String ULTIMOAGGIORNAMENTO_PROPERTY = "ultimoaggiornamento";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String ANF_ARRAY_PROPERTY = "anfArray";
    public static final String TO_INPS_TIPO_ANF_PROPERTY = "toInpsTipoAnf";
    public static final String TO_INPS_TIPO_ANF2_PROPERTY = "toInpsTipoAnf2";

    public static final String IDCLASSEANF_PK_COLUMN = "IDCLASSEANF";
    public static final String IDINPSTIPOANF_PK_COLUMN = "IDINPSTIPOANF";
    public static final String VALIDODAL_PK_COLUMN = "VALIDODAL";

    public void setC1(BigDecimal c1) {
        writeProperty("c1", c1);
    }
    public BigDecimal getC1() {
        return (BigDecimal)readProperty("c1");
    }

    public void setC10(BigDecimal c10) {
        writeProperty("c10", c10);
    }
    public BigDecimal getC10() {
        return (BigDecimal)readProperty("c10");
    }

    public void setC11(BigDecimal c11) {
        writeProperty("c11", c11);
    }
    public BigDecimal getC11() {
        return (BigDecimal)readProperty("c11");
    }

    public void setC12(BigDecimal c12) {
        writeProperty("c12", c12);
    }
    public BigDecimal getC12() {
        return (BigDecimal)readProperty("c12");
    }

    public void setC2(BigDecimal c2) {
        writeProperty("c2", c2);
    }
    public BigDecimal getC2() {
        return (BigDecimal)readProperty("c2");
    }

    public void setC3(BigDecimal c3) {
        writeProperty("c3", c3);
    }
    public BigDecimal getC3() {
        return (BigDecimal)readProperty("c3");
    }

    public void setC4(BigDecimal c4) {
        writeProperty("c4", c4);
    }
    public BigDecimal getC4() {
        return (BigDecimal)readProperty("c4");
    }

    public void setC5(BigDecimal c5) {
        writeProperty("c5", c5);
    }
    public BigDecimal getC5() {
        return (BigDecimal)readProperty("c5");
    }

    public void setC6(BigDecimal c6) {
        writeProperty("c6", c6);
    }
    public BigDecimal getC6() {
        return (BigDecimal)readProperty("c6");
    }

    public void setC7(BigDecimal c7) {
        writeProperty("c7", c7);
    }
    public BigDecimal getC7() {
        return (BigDecimal)readProperty("c7");
    }

    public void setC8(BigDecimal c8) {
        writeProperty("c8", c8);
    }
    public BigDecimal getC8() {
        return (BigDecimal)readProperty("c8");
    }

    public void setC9(BigDecimal c9) {
        writeProperty("c9", c9);
    }
    public BigDecimal getC9() {
        return (BigDecimal)readProperty("c9");
    }

    public void setIdclasseanf(Short idclasseanf) {
        writeProperty("idclasseanf", idclasseanf);
    }
    public Short getIdclasseanf() {
        return (Short)readProperty("idclasseanf");
    }

    public void setIdinpstipoanf(String idinpstipoanf) {
        writeProperty("idinpstipoanf", idinpstipoanf);
    }
    public String getIdinpstipoanf() {
        return (String)readProperty("idinpstipoanf");
    }

    public void setIdinpstipoanf2(Short idinpstipoanf2) {
        writeProperty("idinpstipoanf2", idinpstipoanf2);
    }
    public Short getIdinpstipoanf2() {
        return (Short)readProperty("idinpstipoanf2");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setRedditoa(BigDecimal redditoa) {
        writeProperty("redditoa", redditoa);
    }
    public BigDecimal getRedditoa() {
        return (BigDecimal)readProperty("redditoa");
    }

    public void setRedditoda(BigDecimal redditoda) {
        writeProperty("redditoda", redditoda);
    }
    public BigDecimal getRedditoda() {
        return (BigDecimal)readProperty("redditoda");
    }

    public void setUltimoaggiornamento(Timestamp ultimoaggiornamento) {
        writeProperty("ultimoaggiornamento", ultimoaggiornamento);
    }
    public Timestamp getUltimoaggiornamento() {
        return (Timestamp)readProperty("ultimoaggiornamento");
    }

    public void setValidoal(Date validoal) {
        writeProperty("validoal", validoal);
    }
    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToAnfArray(Anf obj) {
        addToManyTarget("anfArray", obj, true);
    }
    public void removeFromAnfArray(Anf obj) {
        removeToManyTarget("anfArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Anf> getAnfArray() {
        return (List<Anf>)readProperty("anfArray");
    }


    public void setToInpsTipoAnf(InpsTipoanf toInpsTipoAnf) {
        setToOneTarget("toInpsTipoAnf", toInpsTipoAnf, true);
    }

    public InpsTipoanf getToInpsTipoAnf() {
        return (InpsTipoanf)readProperty("toInpsTipoAnf");
    }


    public void setToInpsTipoAnf2(InpsTipoanf2 toInpsTipoAnf2) {
        setToOneTarget("toInpsTipoAnf2", toInpsTipoAnf2, true);
    }

    public InpsTipoanf2 getToInpsTipoAnf2() {
        return (InpsTipoanf2)readProperty("toInpsTipoAnf2");
    }


}
