package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Anf;
import it.iubar.paghe.logic.paghe.InpsAnfnota;
import it.iubar.paghe.logic.paghe.InpsClasseanf;
import it.iubar.paghe.logic.paghe.InpsTipoanf2;
import it.iubar.paghe.logic.paghe.Profiloanf;

/**
 * Class _InpsTipoanf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsTipoanf extends CayenneDataObject {

    public static final String ALMENOFIGLIINABILI_PROPERTY = "almenofigliinabili";
    public static final String ALMENOFIGLIMINORI_PROPERTY = "almenofigliminori";
    public static final String CONIUGI_PROPERTY = "coniugi";
    public static final String DATASCADENZA_PROPERTY = "datascadenza";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDINPSTIPOANF_PROPERTY = "idinpstipoanf";
    public static final String ANF_ARRAY_PROPERTY = "anfArray";
    public static final String INPS_ANFNOTA_ARRAY_PROPERTY = "inpsAnfnotaArray";
    public static final String INPS_CLASSEANF_ARRAY_PROPERTY = "inpsClasseanfArray";
    public static final String INPS_TIPOANF2ARRAY_PROPERTY = "inpsTipoanf2Array";
    public static final String PROFILOANF_ARRAY_PROPERTY = "profiloanfArray";

    public static final String IDINPSTIPOANF_PK_COLUMN = "IDINPSTIPOANF";

    public Short getAlmenofigliinabili() {
        return (Short)readProperty("almenofigliinabili");
    }

    public Short getAlmenofigliminori() {
        return (Short)readProperty("almenofigliminori");
    }

    public Short getConiugi() {
        return (Short)readProperty("coniugi");
    }

    public Date getDatascadenza() {
        return (Date)readProperty("datascadenza");
    }

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdinpstipoanf() {
        return (String)readProperty("idinpstipoanf");
    }

    public void addToAnfArray(Anf obj) {
        addToManyTarget("anfArray", obj, true);
    }
    public void removeFromAnfArray(Anf obj) {
        removeToManyTarget("anfArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Anf> getAnfArray() {
        return (List<Anf>)readProperty("anfArray");
    }


    public void addToInpsAnfnotaArray(InpsAnfnota obj) {
        addToManyTarget("inpsAnfnotaArray", obj, true);
    }
    public void removeFromInpsAnfnotaArray(InpsAnfnota obj) {
        removeToManyTarget("inpsAnfnotaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsAnfnota> getInpsAnfnotaArray() {
        return (List<InpsAnfnota>)readProperty("inpsAnfnotaArray");
    }


    public void addToInpsClasseanfArray(InpsClasseanf obj) {
        addToManyTarget("inpsClasseanfArray", obj, true);
    }
    public void removeFromInpsClasseanfArray(InpsClasseanf obj) {
        removeToManyTarget("inpsClasseanfArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsClasseanf> getInpsClasseanfArray() {
        return (List<InpsClasseanf>)readProperty("inpsClasseanfArray");
    }


    public void addToInpsTipoanf2Array(InpsTipoanf2 obj) {
        addToManyTarget("inpsTipoanf2Array", obj, true);
    }
    public void removeFromInpsTipoanf2Array(InpsTipoanf2 obj) {
        removeToManyTarget("inpsTipoanf2Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InpsTipoanf2> getInpsTipoanf2Array() {
        return (List<InpsTipoanf2>)readProperty("inpsTipoanf2Array");
    }


    public void addToProfiloanfArray(Profiloanf obj) {
        addToManyTarget("profiloanfArray", obj, true);
    }
    public void removeFromProfiloanfArray(Profiloanf obj) {
        removeToManyTarget("profiloanfArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Profiloanf> getProfiloanfArray() {
        return (List<Profiloanf>)readProperty("profiloanfArray");
    }


}
