package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Settimana;

/**
 * Class _InpsTipocopertura was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsTipocopertura extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDINPSTIPOCOPERTURA_PROPERTY = "idinpstipocopertura";
    public static final String SETTIMANA_ARRAY_PROPERTY = "settimanaArray";

    public static final String IDINPSTIPOCOPERTURA_PK_COLUMN = "IDINPSTIPOCOPERTURA";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdinpstipocopertura() {
        return (String)readProperty("idinpstipocopertura");
    }

    public void addToSettimanaArray(Settimana obj) {
        addToManyTarget("settimanaArray", obj, true);
    }
    public void removeFromSettimanaArray(Settimana obj) {
        removeToManyTarget("settimanaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Settimana> getSettimanaArray() {
        return (List<Settimana>)readProperty("settimanaArray");
    }


}
