package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Datoretributivo;
import it.iubar.paghe.logic.paghe.DrBeneficiodivabileregione;
import it.iubar.paghe.logic.paghe.DrCausalestatdivabile;

/**
 * Class _Lavdivabile was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Lavdivabile extends CayenneDataObject {

    public static final String IDBENEFICIODIVABILEREG_PROPERTY = "idbeneficiodivabilereg";
    public static final String IDCAUSALESTATDIVABILE_PROPERTY = "idcausalestatdivabile";
    public static final String IDDATORETRIBUTIVO_PROPERTY = "iddatoretributivo";
    public static final String IMPORTOARRETRATO_PROPERTY = "importoarretrato";
    public static final String IMPORTOCORRENTE_PROPERTY = "importocorrente";
    public static final String TO_BENEFICIO_DIV_ABILE_REGIONE_PROPERTY = "toBeneficioDivAbileRegione";
    public static final String TO_DATORETRIBUTIVO_PROPERTY = "toDatoretributivo";
    public static final String TO_DR_CAUSALE_STAT_DIV_ABILE_PROPERTY = "toDrCausaleStatDivAbile";

    public static final String IDDATORETRIBUTIVO_PK_COLUMN = "IDDATORETRIBUTIVO";

    public void setIdbeneficiodivabilereg(String idbeneficiodivabilereg) {
        writeProperty("idbeneficiodivabilereg", idbeneficiodivabilereg);
    }
    public String getIdbeneficiodivabilereg() {
        return (String)readProperty("idbeneficiodivabilereg");
    }

    public void setIdcausalestatdivabile(String idcausalestatdivabile) {
        writeProperty("idcausalestatdivabile", idcausalestatdivabile);
    }
    public String getIdcausalestatdivabile() {
        return (String)readProperty("idcausalestatdivabile");
    }

    public void setIddatoretributivo(Integer iddatoretributivo) {
        writeProperty("iddatoretributivo", iddatoretributivo);
    }
    public Integer getIddatoretributivo() {
        return (Integer)readProperty("iddatoretributivo");
    }

    public void setImportoarretrato(BigDecimal importoarretrato) {
        writeProperty("importoarretrato", importoarretrato);
    }
    public BigDecimal getImportoarretrato() {
        return (BigDecimal)readProperty("importoarretrato");
    }

    public void setImportocorrente(BigDecimal importocorrente) {
        writeProperty("importocorrente", importocorrente);
    }
    public BigDecimal getImportocorrente() {
        return (BigDecimal)readProperty("importocorrente");
    }

    public void setToBeneficioDivAbileRegione(DrBeneficiodivabileregione toBeneficioDivAbileRegione) {
        setToOneTarget("toBeneficioDivAbileRegione", toBeneficioDivAbileRegione, true);
    }

    public DrBeneficiodivabileregione getToBeneficioDivAbileRegione() {
        return (DrBeneficiodivabileregione)readProperty("toBeneficioDivAbileRegione");
    }


    public void setToDatoretributivo(Datoretributivo toDatoretributivo) {
        setToOneTarget("toDatoretributivo", toDatoretributivo, true);
    }

    public Datoretributivo getToDatoretributivo() {
        return (Datoretributivo)readProperty("toDatoretributivo");
    }


    public void setToDrCausaleStatDivAbile(DrCausalestatdivabile toDrCausaleStatDivAbile) {
        setToOneTarget("toDrCausaleStatDivAbile", toDrCausaleStatDivAbile, true);
    }

    public DrCausalestatdivabile getToDrCausaleStatDivAbile() {
        return (DrCausalestatdivabile)readProperty("toDrCausaleStatDivAbile");
    }


}
