package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Malattiainfortunio was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Malattiainfortunio extends CayenneDataObject {

    public static final String DATAFINEASSOLUTA_PROPERTY = "datafineassoluta";
    public static final String DATAFINEMESE_PROPERTY = "datafinemese";
    public static final String DATAINIZIOASSOLUTO_PROPERTY = "datainizioassoluto";
    public static final String DATAINIZIOMESE_PROPERTY = "datainiziomese";
    public static final String GIORNICARENZA_PROPERTY = "giornicarenza";
    public static final String IDASSENZA_PROPERTY = "idassenza";
    public static final String IDTIPO_PROPERTY = "idtipo";
    public static final String ORECARENZA_PROPERTY = "orecarenza";
    public static final String RICADUTA_PROPERTY = "ricaduta";

    public static final String IDASSENZA_PK_COLUMN = "IDASSENZA";

    public void setDatafineassoluta(Date datafineassoluta) {
        writeProperty("datafineassoluta", datafineassoluta);
    }
    public Date getDatafineassoluta() {
        return (Date)readProperty("datafineassoluta");
    }

    public void setDatafinemese(Date datafinemese) {
        writeProperty("datafinemese", datafinemese);
    }
    public Date getDatafinemese() {
        return (Date)readProperty("datafinemese");
    }

    public void setDatainizioassoluto(Date datainizioassoluto) {
        writeProperty("datainizioassoluto", datainizioassoluto);
    }
    public Date getDatainizioassoluto() {
        return (Date)readProperty("datainizioassoluto");
    }

    public void setDatainiziomese(Date datainiziomese) {
        writeProperty("datainiziomese", datainiziomese);
    }
    public Date getDatainiziomese() {
        return (Date)readProperty("datainiziomese");
    }

    public void setGiornicarenza(BigDecimal giornicarenza) {
        writeProperty("giornicarenza", giornicarenza);
    }
    public BigDecimal getGiornicarenza() {
        return (BigDecimal)readProperty("giornicarenza");
    }

    public void setIdassenza(Integer idassenza) {
        writeProperty("idassenza", idassenza);
    }
    public Integer getIdassenza() {
        return (Integer)readProperty("idassenza");
    }

    public void setIdtipo(Short idtipo) {
        writeProperty("idtipo", idtipo);
    }
    public Short getIdtipo() {
        return (Short)readProperty("idtipo");
    }

    public void setOrecarenza(BigDecimal orecarenza) {
        writeProperty("orecarenza", orecarenza);
    }
    public BigDecimal getOrecarenza() {
        return (BigDecimal)readProperty("orecarenza");
    }

    public void setRicaduta(Short ricaduta) {
        writeProperty("ricaduta", ricaduta);
    }
    public Short getRicaduta() {
        return (Short)readProperty("ricaduta");
    }

}
