package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Cedolino;
import it.iubar.paghe.logic.paghe.Posizionelavoratore;
import it.iubar.paghe.logic.paghe.Tipofoglio;

/**
 * Class _Numerazioneunica was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Numerazioneunica extends CayenneDataObject {

    public static final String ANNULLATO_PROPERTY = "annullato";
    public static final String DATAANNULLAMENTO_PROPERTY = "dataannullamento";
    public static final String DATAELIMINAZIONE_PROPERTY = "dataeliminazione";
    public static final String ELIMINATO_PROPERTY = "eliminato";
    public static final String IDFOGLIO_PROPERTY = "idfoglio";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDTITOLAREDATI_PROPERTY = "idtitolaredati";
    public static final String NUMERAZIONE_PROPERTY = "numerazione";
    public static final String TO_CEDOLINO_PROPERTY = "toCedolino";
    public static final String TO_POSIZIONELAVORATORE_PROPERTY = "toPosizionelavoratore";
    public static final String TO_TIPOFOGLIO_PROPERTY = "toTipofoglio";

    public static final String IDTIPOFOGLIO_PK_COLUMN = "IDTIPOFOGLIO";
    public static final String IDTITOLAREDATI_PK_COLUMN = "IDTITOLAREDATI";
    public static final String NUMERAZIONE_PK_COLUMN = "NUMERAZIONE";

    public void setAnnullato(Short annullato) {
        writeProperty("annullato", annullato);
    }
    public Short getAnnullato() {
        return (Short)readProperty("annullato");
    }

    public void setDataannullamento(Date dataannullamento) {
        writeProperty("dataannullamento", dataannullamento);
    }
    public Date getDataannullamento() {
        return (Date)readProperty("dataannullamento");
    }

    public void setDataeliminazione(Date dataeliminazione) {
        writeProperty("dataeliminazione", dataeliminazione);
    }
    public Date getDataeliminazione() {
        return (Date)readProperty("dataeliminazione");
    }

    public void setEliminato(Short eliminato) {
        writeProperty("eliminato", eliminato);
    }
    public Short getEliminato() {
        return (Short)readProperty("eliminato");
    }

    public void setIdfoglio(Short idfoglio) {
        writeProperty("idfoglio", idfoglio);
    }
    public Short getIdfoglio() {
        return (Short)readProperty("idfoglio");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdtitolaredati(Integer idtitolaredati) {
        writeProperty("idtitolaredati", idtitolaredati);
    }
    public Integer getIdtitolaredati() {
        return (Integer)readProperty("idtitolaredati");
    }

    public void setNumerazione(Integer numerazione) {
        writeProperty("numerazione", numerazione);
    }
    public Integer getNumerazione() {
        return (Integer)readProperty("numerazione");
    }

    public void setToCedolino(Cedolino toCedolino) {
        setToOneTarget("toCedolino", toCedolino, true);
    }

    public Cedolino getToCedolino() {
        return (Cedolino)readProperty("toCedolino");
    }


    public void setToPosizionelavoratore(Posizionelavoratore toPosizionelavoratore) {
        setToOneTarget("toPosizionelavoratore", toPosizionelavoratore, true);
    }

    public Posizionelavoratore getToPosizionelavoratore() {
        return (Posizionelavoratore)readProperty("toPosizionelavoratore");
    }


    public void setToTipofoglio(Tipofoglio toTipofoglio) {
        setToOneTarget("toTipofoglio", toTipofoglio, true);
    }

    public Tipofoglio getToTipofoglio() {
        return (Tipofoglio)readProperty("toTipofoglio");
    }


}
