package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.PaGestione;
import it.iubar.paghe.logic.paghe.PaTipocessazione;

/**
 * Class _PaPosizioneperiodo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaPosizioneperiodo extends CayenneDataObject {

    public static final String AL_PROPERTY = "al";
    public static final String CONGCONTRIBCRED_PROPERTY = "congcontribcred";
    public static final String CONGCONTRIBPENS_PROPERTY = "congcontribpens";
    public static final String CONGIMPORTO_PROPERTY = "congimporto";
    public static final String DAL_PROPERTY = "dal";
    public static final String FINEBENEFICIOCALAMITA_PROPERTY = "finebeneficiocalamita";
    public static final String IDPAPERIODO_PROPERTY = "idpaperiodo";
    public static final String IDPATIPOCESSAZIONE_PROPERTY = "idpatipocessazione";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String MENSILITA_PROPERTY = "mensilita";
    public static final String RETRIBTEORICATABTFR_PROPERTY = "retribteoricatabtfr";
    public static final String RETRIBVALUTABILETFR_PROPERTY = "retribvalutabiletfr";
    public static final String PA_GESTIONE_ARRAY_PROPERTY = "paGestioneArray";
    public static final String TO_PA_TIPO_CESSAZIONE_PROPERTY = "toPaTipoCessazione";

    public static final String IDPAPERIODO_PK_COLUMN = "IDPAPERIODO";

    public void setAl(Date al) {
        writeProperty("al", al);
    }
    public Date getAl() {
        return (Date)readProperty("al");
    }

    public void setCongcontribcred(BigDecimal congcontribcred) {
        writeProperty("congcontribcred", congcontribcred);
    }
    public BigDecimal getCongcontribcred() {
        return (BigDecimal)readProperty("congcontribcred");
    }

    public void setCongcontribpens(BigDecimal congcontribpens) {
        writeProperty("congcontribpens", congcontribpens);
    }
    public BigDecimal getCongcontribpens() {
        return (BigDecimal)readProperty("congcontribpens");
    }

    public void setCongimporto(BigDecimal congimporto) {
        writeProperty("congimporto", congimporto);
    }
    public BigDecimal getCongimporto() {
        return (BigDecimal)readProperty("congimporto");
    }

    public void setDal(Date dal) {
        writeProperty("dal", dal);
    }
    public Date getDal() {
        return (Date)readProperty("dal");
    }

    public void setFinebeneficiocalamita(Date finebeneficiocalamita) {
        writeProperty("finebeneficiocalamita", finebeneficiocalamita);
    }
    public Date getFinebeneficiocalamita() {
        return (Date)readProperty("finebeneficiocalamita");
    }

    public void setIdpaperiodo(Integer idpaperiodo) {
        writeProperty("idpaperiodo", idpaperiodo);
    }
    public Integer getIdpaperiodo() {
        return (Integer)readProperty("idpaperiodo");
    }

    public void setIdpatipocessazione(Short idpatipocessazione) {
        writeProperty("idpatipocessazione", idpatipocessazione);
    }
    public Short getIdpatipocessazione() {
        return (Short)readProperty("idpatipocessazione");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setMensilita(Short mensilita) {
        writeProperty("mensilita", mensilita);
    }
    public Short getMensilita() {
        return (Short)readProperty("mensilita");
    }

    public void setRetribteoricatabtfr(BigDecimal retribteoricatabtfr) {
        writeProperty("retribteoricatabtfr", retribteoricatabtfr);
    }
    public BigDecimal getRetribteoricatabtfr() {
        return (BigDecimal)readProperty("retribteoricatabtfr");
    }

    public void setRetribvalutabiletfr(BigDecimal retribvalutabiletfr) {
        writeProperty("retribvalutabiletfr", retribvalutabiletfr);
    }
    public BigDecimal getRetribvalutabiletfr() {
        return (BigDecimal)readProperty("retribvalutabiletfr");
    }

    public void addToPaGestioneArray(PaGestione obj) {
        addToManyTarget("paGestioneArray", obj, true);
    }
    public void removeFromPaGestioneArray(PaGestione obj) {
        removeToManyTarget("paGestioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaGestione> getPaGestioneArray() {
        return (List<PaGestione>)readProperty("paGestioneArray");
    }


    public void setToPaTipoCessazione(PaTipocessazione toPaTipoCessazione) {
        setToOneTarget("toPaTipoCessazione", toPaTipoCessazione, true);
    }

    public PaTipocessazione getToPaTipoCessazione() {
        return (PaTipocessazione)readProperty("toPaTipoCessazione");
    }


}
