package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.InpsAliquotaarea;
import it.iubar.paghe.logic.paghe.PosizioneRiduzioneinps;

/**
 * Class _Riduzioneinps was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Riduzioneinps extends CayenneDataObject {

    public static final String CIG_PROPERTY = "cig";
    public static final String CIGS_PROPERTY = "cigs";
    public static final String CIGS2_PROPERTY = "cigs2";
    public static final String CUAF_PROPERTY = "cuaf";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String DS_PROPERTY = "ds";
    public static final String DS2_PROPERTY = "ds2";
    public static final String DS3_PROPERTY = "ds3";
    public static final String IDRIDUZIONE_PROPERTY = "idriduzione";
    public static final String IDTIPO_PROPERTY = "idtipo";
    public static final String IMPORTO_PROPERTY = "importo";
    public static final String IVS_PROPERTY = "ivs";
    public static final String IVS2_PROPERTY = "ivs2";
    public static final String LIMITE_PROPERTY = "limite";
    public static final String MALATTIA_PROPERTY = "malattia";
    public static final String MATERNITA_PROPERTY = "maternita";
    public static final String MOBILITA_PROPERTY = "mobilita";
    public static final String NOTE_PROPERTY = "note";
    public static final String SOLIDARIETA_PROPERTY = "solidarieta";
    public static final String TFR_PROPERTY = "tfr";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String POSIZIONE_RIDUZIONEINPS_ARRAY_PROPERTY = "posizioneRiduzioneinpsArray";
    public static final String TO_INPS_ALIQUOTAAREA_PROPERTY = "toInpsAliquotaarea";

    public static final String IDRIDUZIONE_PK_COLUMN = "IDRIDUZIONE";

    public void setCig(BigDecimal cig) {
        writeProperty("cig", cig);
    }
    public BigDecimal getCig() {
        return (BigDecimal)readProperty("cig");
    }

    public void setCigs(BigDecimal cigs) {
        writeProperty("cigs", cigs);
    }
    public BigDecimal getCigs() {
        return (BigDecimal)readProperty("cigs");
    }

    public void setCigs2(BigDecimal cigs2) {
        writeProperty("cigs2", cigs2);
    }
    public BigDecimal getCigs2() {
        return (BigDecimal)readProperty("cigs2");
    }

    public void setCuaf(BigDecimal cuaf) {
        writeProperty("cuaf", cuaf);
    }
    public BigDecimal getCuaf() {
        return (BigDecimal)readProperty("cuaf");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void setDs(BigDecimal ds) {
        writeProperty("ds", ds);
    }
    public BigDecimal getDs() {
        return (BigDecimal)readProperty("ds");
    }

    public void setDs2(BigDecimal ds2) {
        writeProperty("ds2", ds2);
    }
    public BigDecimal getDs2() {
        return (BigDecimal)readProperty("ds2");
    }

    public void setDs3(BigDecimal ds3) {
        writeProperty("ds3", ds3);
    }
    public BigDecimal getDs3() {
        return (BigDecimal)readProperty("ds3");
    }

    public void setIdriduzione(Integer idriduzione) {
        writeProperty("idriduzione", idriduzione);
    }
    public Integer getIdriduzione() {
        return (Integer)readProperty("idriduzione");
    }

    public void setIdtipo(Short idtipo) {
        writeProperty("idtipo", idtipo);
    }
    public Short getIdtipo() {
        return (Short)readProperty("idtipo");
    }

    public void setImporto(BigDecimal importo) {
        writeProperty("importo", importo);
    }
    public BigDecimal getImporto() {
        return (BigDecimal)readProperty("importo");
    }

    public void setIvs(BigDecimal ivs) {
        writeProperty("ivs", ivs);
    }
    public BigDecimal getIvs() {
        return (BigDecimal)readProperty("ivs");
    }

    public void setIvs2(BigDecimal ivs2) {
        writeProperty("ivs2", ivs2);
    }
    public BigDecimal getIvs2() {
        return (BigDecimal)readProperty("ivs2");
    }

    public void setLimite(BigDecimal limite) {
        writeProperty("limite", limite);
    }
    public BigDecimal getLimite() {
        return (BigDecimal)readProperty("limite");
    }

    public void setMalattia(BigDecimal malattia) {
        writeProperty("malattia", malattia);
    }
    public BigDecimal getMalattia() {
        return (BigDecimal)readProperty("malattia");
    }

    public void setMaternita(BigDecimal maternita) {
        writeProperty("maternita", maternita);
    }
    public BigDecimal getMaternita() {
        return (BigDecimal)readProperty("maternita");
    }

    public void setMobilita(BigDecimal mobilita) {
        writeProperty("mobilita", mobilita);
    }
    public BigDecimal getMobilita() {
        return (BigDecimal)readProperty("mobilita");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setSolidarieta(BigDecimal solidarieta) {
        writeProperty("solidarieta", solidarieta);
    }
    public BigDecimal getSolidarieta() {
        return (BigDecimal)readProperty("solidarieta");
    }

    public void setTfr(BigDecimal tfr) {
        writeProperty("tfr", tfr);
    }
    public BigDecimal getTfr() {
        return (BigDecimal)readProperty("tfr");
    }

    public void setValidoal(Date validoal) {
        writeProperty("validoal", validoal);
    }
    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public void setValidodal(Date validodal) {
        writeProperty("validodal", validodal);
    }
    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToPosizioneRiduzioneinpsArray(PosizioneRiduzioneinps obj) {
        addToManyTarget("posizioneRiduzioneinpsArray", obj, true);
    }
    public void removeFromPosizioneRiduzioneinpsArray(PosizioneRiduzioneinps obj) {
        removeToManyTarget("posizioneRiduzioneinpsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PosizioneRiduzioneinps> getPosizioneRiduzioneinpsArray() {
        return (List<PosizioneRiduzioneinps>)readProperty("posizioneRiduzioneinpsArray");
    }


    public void setToInpsAliquotaarea(InpsAliquotaarea toInpsAliquotaarea) {
        setToOneTarget("toInpsAliquotaarea", toInpsAliquotaarea, true);
    }

    public InpsAliquotaarea getToInpsAliquotaarea() {
        return (InpsAliquotaarea)readProperty("toInpsAliquotaarea");
    }


}
