package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.SpAliquota;
import it.iubar.paghe.logic.paghe.SpPosizionesubordinato;
import it.iubar.paghe.logic.paghe.SpTipoextracontrib;

/**
 * Class _SpCausaleextracontrib was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpCausaleextracontrib extends CayenneDataObject {

    public static final String AL_PROPERTY = "al";
    public static final String DAL_PROPERTY = "dal";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IMPORTOAVERE_PROPERTY = "importoavere";
    public static final String IMPORTODARE_PROPERTY = "importodare";
    public static final String IMPORTORIFERIMENTO_PROPERTY = "importoriferimento";
    public static final String TO_SP_ALIQUOTA_PROPERTY = "toSpAliquota";
    public static final String TO_SP_POSIZIONE_PROPERTY = "toSpPosizione";
    public static final String TO_SP_TIPOEXTRACONTRIB_PROPERTY = "toSpTipoextracontrib";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setAl(Date al) {
        writeProperty("al", al);
    }
    public Date getAl() {
        return (Date)readProperty("al");
    }

    public void setDal(Date dal) {
        writeProperty("dal", dal);
    }
    public Date getDal() {
        return (Date)readProperty("dal");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setImportoavere(BigDecimal importoavere) {
        writeProperty("importoavere", importoavere);
    }
    public BigDecimal getImportoavere() {
        return (BigDecimal)readProperty("importoavere");
    }

    public void setImportodare(BigDecimal importodare) {
        writeProperty("importodare", importodare);
    }
    public BigDecimal getImportodare() {
        return (BigDecimal)readProperty("importodare");
    }

    public void setImportoriferimento(BigDecimal importoriferimento) {
        writeProperty("importoriferimento", importoriferimento);
    }
    public BigDecimal getImportoriferimento() {
        return (BigDecimal)readProperty("importoriferimento");
    }

    public void setToSpAliquota(SpAliquota toSpAliquota) {
        setToOneTarget("toSpAliquota", toSpAliquota, true);
    }

    public SpAliquota getToSpAliquota() {
        return (SpAliquota)readProperty("toSpAliquota");
    }


    public void setToSpPosizione(SpPosizionesubordinato toSpPosizione) {
        setToOneTarget("toSpPosizione", toSpPosizione, true);
    }

    public SpPosizionesubordinato getToSpPosizione() {
        return (SpPosizionesubordinato)readProperty("toSpPosizione");
    }


    public void setToSpTipoextracontrib(SpTipoextracontrib toSpTipoextracontrib) {
        setToOneTarget("toSpTipoextracontrib", toSpTipoextracontrib, true);
    }

    public SpTipoextracontrib getToSpTipoextracontrib() {
        return (SpTipoextracontrib)readProperty("toSpTipoextracontrib");
    }


}
