package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.SpAgevolazione;
import it.iubar.paghe.logic.paghe.SpAliquota;
import it.iubar.paghe.logic.paghe.SpPosizionesubordinato;
import it.iubar.paghe.logic.paghe.SpQualifica;
import it.iubar.paghe.logic.paghe.SpTiporapporto;
import it.iubar.paghe.logic.paghe.SpTiporetribuzione;

/**
 * Class _SpDatoretribuzione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpDatoretribuzione extends CayenneDataObject {

    public static final String AL_PROPERTY = "al";
    public static final String CONTRIBUTOAGGIUNTIVO_PROPERTY = "contributoaggiuntivo";
    public static final String CONTRIBUTONORMALE_PROPERTY = "contributonormale";
    public static final String CONTRIBUTOSOLIDARIETA_PROPERTY = "contributosolidarieta";
    public static final String DAL_PROPERTY = "dal";
    public static final String GIORNIFASCIA_PROPERTY = "giornifascia";
    public static final String GVLAVORATORI_PROPERTY = "gvlavoratori";
    public static final String IDBRANO_PROPERTY = "idbrano";
    public static final String IDDATORETRIBUZIONE_PROPERTY = "iddatoretribuzione";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IMPORTOAGEVOLAZIONE_PROPERTY = "importoagevolazione";
    public static final String IMPORTORETRIBUZIONE_PROPERTY = "importoretribuzione";
    public static final String RETRIBUZIONEPREC_PROPERTY = "retribuzioneprec";
    public static final String TRATTENUTEPENSIONI_PROPERTY = "trattenutepensioni";
    public static final String TO_SP_AGEVOLAZIONE_PROPERTY = "toSpAgevolazione";
    public static final String TO_SP_ALIQUOTA_PROPERTY = "toSpAliquota";
    public static final String TO_SP_POSIZIONE_PROPERTY = "toSpPosizione";
    public static final String TO_SP_QUALIFICA_PROPERTY = "toSpQualifica";
    public static final String TO_SP_TIPORAPPORTO_PROPERTY = "toSpTiporapporto";
    public static final String TO_SP_TIPORETRIBUZIONE_PROPERTY = "toSpTiporetribuzione";

    public static final String IDDATORETRIBUZIONE_PK_COLUMN = "IDDATORETRIBUZIONE";
    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setAl(Date al) {
        writeProperty("al", al);
    }
    public Date getAl() {
        return (Date)readProperty("al");
    }

    public void setContributoaggiuntivo(BigDecimal contributoaggiuntivo) {
        writeProperty("contributoaggiuntivo", contributoaggiuntivo);
    }
    public BigDecimal getContributoaggiuntivo() {
        return (BigDecimal)readProperty("contributoaggiuntivo");
    }

    public void setContributonormale(BigDecimal contributonormale) {
        writeProperty("contributonormale", contributonormale);
    }
    public BigDecimal getContributonormale() {
        return (BigDecimal)readProperty("contributonormale");
    }

    public void setContributosolidarieta(BigDecimal contributosolidarieta) {
        writeProperty("contributosolidarieta", contributosolidarieta);
    }
    public BigDecimal getContributosolidarieta() {
        return (BigDecimal)readProperty("contributosolidarieta");
    }

    public void setDal(Date dal) {
        writeProperty("dal", dal);
    }
    public Date getDal() {
        return (Date)readProperty("dal");
    }

    public void setGiornifascia(Short giornifascia) {
        writeProperty("giornifascia", giornifascia);
    }
    public Short getGiornifascia() {
        return (Short)readProperty("giornifascia");
    }

    public void setGvlavoratori(Short gvlavoratori) {
        writeProperty("gvlavoratori", gvlavoratori);
    }
    public Short getGvlavoratori() {
        return (Short)readProperty("gvlavoratori");
    }

    public void setIdbrano(String idbrano) {
        writeProperty("idbrano", idbrano);
    }
    public String getIdbrano() {
        return (String)readProperty("idbrano");
    }

    public void setIddatoretribuzione(Short iddatoretribuzione) {
        writeProperty("iddatoretribuzione", iddatoretribuzione);
    }
    public Short getIddatoretribuzione() {
        return (Short)readProperty("iddatoretribuzione");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setImportoagevolazione(BigDecimal importoagevolazione) {
        writeProperty("importoagevolazione", importoagevolazione);
    }
    public BigDecimal getImportoagevolazione() {
        return (BigDecimal)readProperty("importoagevolazione");
    }

    public void setImportoretribuzione(BigDecimal importoretribuzione) {
        writeProperty("importoretribuzione", importoretribuzione);
    }
    public BigDecimal getImportoretribuzione() {
        return (BigDecimal)readProperty("importoretribuzione");
    }

    public void setRetribuzioneprec(BigDecimal retribuzioneprec) {
        writeProperty("retribuzioneprec", retribuzioneprec);
    }
    public BigDecimal getRetribuzioneprec() {
        return (BigDecimal)readProperty("retribuzioneprec");
    }

    public void setTrattenutepensioni(BigDecimal trattenutepensioni) {
        writeProperty("trattenutepensioni", trattenutepensioni);
    }
    public BigDecimal getTrattenutepensioni() {
        return (BigDecimal)readProperty("trattenutepensioni");
    }

    public void setToSpAgevolazione(SpAgevolazione toSpAgevolazione) {
        setToOneTarget("toSpAgevolazione", toSpAgevolazione, true);
    }

    public SpAgevolazione getToSpAgevolazione() {
        return (SpAgevolazione)readProperty("toSpAgevolazione");
    }


    public void setToSpAliquota(SpAliquota toSpAliquota) {
        setToOneTarget("toSpAliquota", toSpAliquota, true);
    }

    public SpAliquota getToSpAliquota() {
        return (SpAliquota)readProperty("toSpAliquota");
    }


    public void setToSpPosizione(SpPosizionesubordinato toSpPosizione) {
        setToOneTarget("toSpPosizione", toSpPosizione, true);
    }

    public SpPosizionesubordinato getToSpPosizione() {
        return (SpPosizionesubordinato)readProperty("toSpPosizione");
    }


    public void setToSpQualifica(SpQualifica toSpQualifica) {
        setToOneTarget("toSpQualifica", toSpQualifica, true);
    }

    public SpQualifica getToSpQualifica() {
        return (SpQualifica)readProperty("toSpQualifica");
    }


    public void setToSpTiporapporto(SpTiporapporto toSpTiporapporto) {
        setToOneTarget("toSpTiporapporto", toSpTiporapporto, true);
    }

    public SpTiporapporto getToSpTiporapporto() {
        return (SpTiporapporto)readProperty("toSpTiporapporto");
    }


    public void setToSpTiporetribuzione(SpTiporetribuzione toSpTiporetribuzione) {
        setToOneTarget("toSpTiporetribuzione", toSpTiporetribuzione, true);
    }

    public SpTiporetribuzione getToSpTiporetribuzione() {
        return (SpTiporetribuzione)readProperty("toSpTiporetribuzione");
    }


}
