package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Profilolavoratore;
import it.iubar.paghe.logic.paghe.SpAgevolazione;
import it.iubar.paghe.logic.paghe.SpAliquota;
import it.iubar.paghe.logic.paghe.SpQualifica;
import it.iubar.paghe.logic.paghe.SpTiporapporto;
import it.iubar.paghe.logic.paghe.SpTiporetribuzione;

/**
 * Class _SpProfilolavoratore was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpProfilolavoratore extends CayenneDataObject {

    public static final String IDPROFILO_PROPERTY = "idprofilo";
    public static final String IMPORTOAGEVOLAZIONE_PROPERTY = "importoagevolazione";
    public static final String TO_PROFILO_PROPERTY = "toProfilo";
    public static final String TO_SP_AGEVOLAZIONE_PROPERTY = "toSpAgevolazione";
    public static final String TO_SP_ALIQUOTA_PROPERTY = "toSpAliquota";
    public static final String TO_SP_QUALIFICA_PROPERTY = "toSpQualifica";
    public static final String TO_SP_TIPORAPPORTO_PROPERTY = "toSpTiporapporto";
    public static final String TO_SP_TIPORETRIBUZIONE_PROPERTY = "toSpTiporetribuzione";

    public static final String IDPROFILO_PK_COLUMN = "IDPROFILO";

    public void setIdprofilo(Integer idprofilo) {
        writeProperty("idprofilo", idprofilo);
    }
    public Integer getIdprofilo() {
        return (Integer)readProperty("idprofilo");
    }

    public void setImportoagevolazione(BigDecimal importoagevolazione) {
        writeProperty("importoagevolazione", importoagevolazione);
    }
    public BigDecimal getImportoagevolazione() {
        return (BigDecimal)readProperty("importoagevolazione");
    }

    public void setToProfilo(Profilolavoratore toProfilo) {
        setToOneTarget("toProfilo", toProfilo, true);
    }

    public Profilolavoratore getToProfilo() {
        return (Profilolavoratore)readProperty("toProfilo");
    }


    public void setToSpAgevolazione(SpAgevolazione toSpAgevolazione) {
        setToOneTarget("toSpAgevolazione", toSpAgevolazione, true);
    }

    public SpAgevolazione getToSpAgevolazione() {
        return (SpAgevolazione)readProperty("toSpAgevolazione");
    }


    public void setToSpAliquota(SpAliquota toSpAliquota) {
        setToOneTarget("toSpAliquota", toSpAliquota, true);
    }

    public SpAliquota getToSpAliquota() {
        return (SpAliquota)readProperty("toSpAliquota");
    }


    public void setToSpQualifica(SpQualifica toSpQualifica) {
        setToOneTarget("toSpQualifica", toSpQualifica, true);
    }

    public SpQualifica getToSpQualifica() {
        return (SpQualifica)readProperty("toSpQualifica");
    }


    public void setToSpTiporapporto(SpTiporapporto toSpTiporapporto) {
        setToOneTarget("toSpTiporapporto", toSpTiporapporto, true);
    }

    public SpTiporapporto getToSpTiporapporto() {
        return (SpTiporapporto)readProperty("toSpTiporapporto");
    }


    public void setToSpTiporetribuzione(SpTiporetribuzione toSpTiporetribuzione) {
        setToOneTarget("toSpTiporetribuzione", toSpTiporetribuzione, true);
    }

    public SpTiporetribuzione getToSpTiporetribuzione() {
        return (SpTiporetribuzione)readProperty("toSpTiporetribuzione");
    }


}
