package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Posizionesubordinato;
import it.iubar.paghe.logic.paghe.SpCausaleextracontrib;
import it.iubar.paghe.logic.paghe.SpDatoretribuzione;

/**
 * Class _SpPosizionesubordinato was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpPosizionesubordinato extends CayenneDataObject {

    public static final String GIORNIFASCIA_PROPERTY = "giornifascia";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IDPROVINCIALUOGOLAVORO_PROPERTY = "idprovincialuogolavoro";
    public static final String RETRIBPRECEDENTE_PROPERTY = "retribprecedente";
    public static final String SP_CAUSALEEXTRACONTRIB_ARRAY_PROPERTY = "spCausaleextracontribArray";
    public static final String SP_DATORETRIBUZIONE_ARRAY_PROPERTY = "spDatoretribuzioneArray";
    public static final String TO_POSIZIONE_SUBORDINATO_PROPERTY = "toPosizioneSubordinato";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setGiornifascia(Short giornifascia) {
        writeProperty("giornifascia", giornifascia);
    }
    public Short getGiornifascia() {
        return (Short)readProperty("giornifascia");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setIdprovincialuogolavoro(String idprovincialuogolavoro) {
        writeProperty("idprovincialuogolavoro", idprovincialuogolavoro);
    }
    public String getIdprovincialuogolavoro() {
        return (String)readProperty("idprovincialuogolavoro");
    }

    public void setRetribprecedente(BigDecimal retribprecedente) {
        writeProperty("retribprecedente", retribprecedente);
    }
    public BigDecimal getRetribprecedente() {
        return (BigDecimal)readProperty("retribprecedente");
    }

    public void addToSpCausaleextracontribArray(SpCausaleextracontrib obj) {
        addToManyTarget("spCausaleextracontribArray", obj, true);
    }
    public void removeFromSpCausaleextracontribArray(SpCausaleextracontrib obj) {
        removeToManyTarget("spCausaleextracontribArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SpCausaleextracontrib> getSpCausaleextracontribArray() {
        return (List<SpCausaleextracontrib>)readProperty("spCausaleextracontribArray");
    }


    public void addToSpDatoretribuzioneArray(SpDatoretribuzione obj) {
        addToManyTarget("spDatoretribuzioneArray", obj, true);
    }
    public void removeFromSpDatoretribuzioneArray(SpDatoretribuzione obj) {
        removeToManyTarget("spDatoretribuzioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SpDatoretribuzione> getSpDatoretribuzioneArray() {
        return (List<SpDatoretribuzione>)readProperty("spDatoretribuzioneArray");
    }


    public void setToPosizioneSubordinato(Posizionesubordinato toPosizioneSubordinato) {
        setToOneTarget("toPosizioneSubordinato", toPosizioneSubordinato, true);
    }

    public Posizionesubordinato getToPosizioneSubordinato() {
        return (Posizionesubordinato)readProperty("toPosizioneSubordinato");
    }


}
