package it.iubar.paghe.logic.paghe.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.SpCausaleextracontrib;

/**
 * Class _SpTipoextracontrib was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpTipoextracontrib extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDTIPOEXTRACONTRIB_PROPERTY = "idtipoextracontrib";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String SP_CAUSALEEXTRACONTRIB_ARRAY_PROPERTY = "spCausaleextracontribArray";

    public static final String IDTIPOEXTRACONTRIB_PK_COLUMN = "IDTIPOEXTRACONTRIB";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdtipoextracontrib() {
        return (String)readProperty("idtipoextracontrib");
    }

    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToSpCausaleextracontribArray(SpCausaleextracontrib obj) {
        addToManyTarget("spCausaleextracontribArray", obj, true);
    }
    public void removeFromSpCausaleextracontribArray(SpCausaleextracontrib obj) {
        removeToManyTarget("spCausaleextracontribArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SpCausaleextracontrib> getSpCausaleextracontribArray() {
        return (List<SpCausaleextracontrib>)readProperty("spCausaleextracontribArray");
    }


}
