package it.iubar.paghe.logic.paghe.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.TfrCausalemcadeb;
import it.iubar.paghe.logic.paghe.TfrMisurecompensative;

/**
 * Class _TfrMiscompadebito was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TfrMiscompadebito extends CayenneDataObject {

    public static final String IDCAUSALEMCADEB_PROPERTY = "idcausalemcadeb";
    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String IMPORTO_PROPERTY = "importo";
    public static final String TO_TFR_CAUSALE_MC_ADEB_PROPERTY = "toTfrCausaleMcADeb";
    public static final String TO_TFR_MISURE_COMPENSATIVE_PROPERTY = "toTfrMisureCompensative";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setIdcausalemcadeb(String idcausalemcadeb) {
        writeProperty("idcausalemcadeb", idcausalemcadeb);
    }
    public String getIdcausalemcadeb() {
        return (String)readProperty("idcausalemcadeb");
    }

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void setImporto(BigDecimal importo) {
        writeProperty("importo", importo);
    }
    public BigDecimal getImporto() {
        return (BigDecimal)readProperty("importo");
    }

    public void setToTfrCausaleMcADeb(TfrCausalemcadeb toTfrCausaleMcADeb) {
        setToOneTarget("toTfrCausaleMcADeb", toTfrCausaleMcADeb, true);
    }

    public TfrCausalemcadeb getToTfrCausaleMcADeb() {
        return (TfrCausalemcadeb)readProperty("toTfrCausaleMcADeb");
    }


    public void setToTfrMisureCompensative(TfrMisurecompensative toTfrMisureCompensative) {
        setToOneTarget("toTfrMisureCompensative", toTfrMisureCompensative, true);
    }

    public TfrMisurecompensative getToTfrMisureCompensative() {
        return (TfrMisurecompensative)readProperty("toTfrMisureCompensative");
    }


}
