package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.TfrMese;
import it.iubar.paghe.logic.paghe.TfrMiscompacredito;
import it.iubar.paghe.logic.paghe.TfrMiscompadebito;

/**
 * Class _TfrMisurecompensative was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TfrMisurecompensative extends CayenneDataObject {

    public static final String IDPOSIZIONE_PROPERTY = "idposizione";
    public static final String TFR_MIS_COMP_ACREDITO_ARRAY_PROPERTY = "tfrMisCompACreditoArray";
    public static final String TFR_MIS_COMP_ADEBITO_ARRAY_PROPERTY = "tfrMisCompADebitoArray";
    public static final String TO_TFR_MESE_PROPERTY = "toTfrMese";

    public static final String IDPOSIZIONE_PK_COLUMN = "IDPOSIZIONE";

    public void setIdposizione(Integer idposizione) {
        writeProperty("idposizione", idposizione);
    }
    public Integer getIdposizione() {
        return (Integer)readProperty("idposizione");
    }

    public void addToTfrMisCompACreditoArray(TfrMiscompacredito obj) {
        addToManyTarget("tfrMisCompACreditoArray", obj, true);
    }
    public void removeFromTfrMisCompACreditoArray(TfrMiscompacredito obj) {
        removeToManyTarget("tfrMisCompACreditoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TfrMiscompacredito> getTfrMisCompACreditoArray() {
        return (List<TfrMiscompacredito>)readProperty("tfrMisCompACreditoArray");
    }


    public void addToTfrMisCompADebitoArray(TfrMiscompadebito obj) {
        addToManyTarget("tfrMisCompADebitoArray", obj, true);
    }
    public void removeFromTfrMisCompADebitoArray(TfrMiscompadebito obj) {
        removeToManyTarget("tfrMisCompADebitoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TfrMiscompadebito> getTfrMisCompADebitoArray() {
        return (List<TfrMiscompadebito>)readProperty("tfrMisCompADebitoArray");
    }


    public void setToTfrMese(TfrMese toTfrMese) {
        setToOneTarget("toTfrMese", toTfrMese, true);
    }

    public TfrMese getToTfrMese() {
        return (TfrMese)readProperty("toTfrMese");
    }


}
