package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.TfrDestinazione;

/**
 * Class _TfrIscrizioneprevobbl was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TfrIscrizioneprevobbl extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDPREVOBBL_PROPERTY = "idprevobbl";
    public static final String TFR_DESTINAZIONE_ARRAY_PROPERTY = "tfrDestinazioneArray";

    public static final String IDPREVOBBL_PK_COLUMN = "IDPREVOBBL";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdprevobbl() {
        return (String)readProperty("idprevobbl");
    }

    public void addToTfrDestinazioneArray(TfrDestinazione obj) {
        addToManyTarget("tfrDestinazioneArray", obj, true);
    }
    public void removeFromTfrDestinazioneArray(TfrDestinazione obj) {
        removeToManyTarget("tfrDestinazioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TfrDestinazione> getTfrDestinazioneArray() {
        return (List<TfrDestinazione>)readProperty("tfrDestinazioneArray");
    }


}
