package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.Assenza;
import it.iubar.paghe.logic.paghe.Categoriaassenza;
import it.iubar.paghe.logic.paghe.Elementoretributivo;

/**
 * Class _Tipoassenza was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tipoassenza extends CayenneDataObject {

    public static final String ATTIVO_PROPERTY = "attivo";
    public static final String CAUSALE_PROPERTY = "causale";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String DESCRIZIONE2_PROPERTY = "descrizione2";
    public static final String IDELEMENTO_PROPERTY = "idelemento";
    public static final String IDINPSEVENTO_PROPERTY = "idinpsevento";
    public static final String IDTIPOASSENZA_PROPERTY = "idtipoassenza";
    public static final String IDTIPOELEMENTO_PROPERTY = "idtipoelemento";
    public static final String INDIRETTO_PROPERTY = "indiretto";
    public static final String ORDERID_PROPERTY = "orderid";
    public static final String ASSENZA_ARRAY_PROPERTY = "assenzaArray";
    public static final String TO_CATEGORIAASSENZA_PROPERTY = "toCategoriaassenza";
    public static final String TO_ELEMENTORETRIBUTIVO_PROPERTY = "toElementoretributivo";

    public static final String IDTIPOASSENZA_PK_COLUMN = "IDTIPOASSENZA";

    public Short getAttivo() {
        return (Short)readProperty("attivo");
    }

    public String getCausale() {
        return (String)readProperty("causale");
    }

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getDescrizione2() {
        return (String)readProperty("descrizione2");
    }

    public Integer getIdelemento() {
        return (Integer)readProperty("idelemento");
    }

    public String getIdinpsevento() {
        return (String)readProperty("idinpsevento");
    }

    public Short getIdtipoassenza() {
        return (Short)readProperty("idtipoassenza");
    }

    public Short getIdtipoelemento() {
        return (Short)readProperty("idtipoelemento");
    }

    public Short getIndiretto() {
        return (Short)readProperty("indiretto");
    }

    public Short getOrderid() {
        return (Short)readProperty("orderid");
    }

    public void addToAssenzaArray(Assenza obj) {
        addToManyTarget("assenzaArray", obj, true);
    }
    public void removeFromAssenzaArray(Assenza obj) {
        removeToManyTarget("assenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Assenza> getAssenzaArray() {
        return (List<Assenza>)readProperty("assenzaArray");
    }



    public Categoriaassenza getToCategoriaassenza() {
        return (Categoriaassenza)readProperty("toCategoriaassenza");
    }



    public Elementoretributivo getToElementoretributivo() {
        return (Elementoretributivo)readProperty("toElementoretributivo");
    }


}
