package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.blob.Documento;
import it.iubar.paghe.logic.paghe.Denunciaaziendale;
import it.iubar.paghe.logic.paghe.Dichiarazione;
import it.iubar.paghe.logic.paghe.Tipouniemens;
import it.iubar.paghe.logic.paghe.UniemensImpresa;
import it.iubar.paghe.logic.paghe.UniemensPosizione;

/**
 * Class _Uniemens was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Uniemens extends CayenneDataObject {

    public static final String IDDICHIARAZIONE_PROPERTY = "iddichiarazione";
    public static final String IDDOCUMENTO_PROPERTY = "iddocumento";
    public static final String IDESITO_PROPERTY = "idesito";
    public static final String IDEXPORT_PROPERTY = "idexport";
    public static final String IDTIPOCOMPOSIZIONE_PROPERTY = "idtipocomposizione";
    public static final String TO_DICHIARAZIONE_PROPERTY = "toDichiarazione";
    public static final String TO_DOCUMENTO_PROPERTY = "toDocumento";
    public static final String TO_EXPORT_PROPERTY = "toExport";
    public static final String TO_TIPO_UNIEMENS_PROPERTY = "toTipoUniemens";
    public static final String UNIEMENS_ARRAY_PROPERTY = "uniemensArray";
    public static final String UNIEMENS_IMPRESA_ARRAY_PROPERTY = "uniemensImpresaArray";
    public static final String UNIEMENS_POSIZIONE_ARRAY_PROPERTY = "uniemensPosizioneArray";

    public static final String IDDICHIARAZIONE_PK_COLUMN = "IDDICHIARAZIONE";

    public void setIddichiarazione(Integer iddichiarazione) {
        writeProperty("iddichiarazione", iddichiarazione);
    }
    public Integer getIddichiarazione() {
        return (Integer)readProperty("iddichiarazione");
    }

    public void setIddocumento(Integer iddocumento) {
        writeProperty("iddocumento", iddocumento);
    }
    public Integer getIddocumento() {
        return (Integer)readProperty("iddocumento");
    }

    public void setIdesito(Integer idesito) {
        writeProperty("idesito", idesito);
    }
    public Integer getIdesito() {
        return (Integer)readProperty("idesito");
    }

    public void setIdexport(Integer idexport) {
        writeProperty("idexport", idexport);
    }
    public Integer getIdexport() {
        return (Integer)readProperty("idexport");
    }

    public void setIdtipocomposizione(String idtipocomposizione) {
        writeProperty("idtipocomposizione", idtipocomposizione);
    }
    public String getIdtipocomposizione() {
        return (String)readProperty("idtipocomposizione");
    }

    public void setToDichiarazione(Dichiarazione toDichiarazione) {
        setToOneTarget("toDichiarazione", toDichiarazione, true);
    }

    public Dichiarazione getToDichiarazione() {
        return (Dichiarazione)readProperty("toDichiarazione");
    }


    public void setToDocumento(Documento toDocumento) {
        setToOneTarget("toDocumento", toDocumento, true);
    }

    public Documento getToDocumento() {
        return (Documento)readProperty("toDocumento");
    }


    public void setToExport(Documento toExport) {
        setToOneTarget("toExport", toExport, true);
    }

    public Documento getToExport() {
        return (Documento)readProperty("toExport");
    }


    public void setToTipoUniemens(Tipouniemens toTipoUniemens) {
        setToOneTarget("toTipoUniemens", toTipoUniemens, true);
    }

    public Tipouniemens getToTipoUniemens() {
        return (Tipouniemens)readProperty("toTipoUniemens");
    }


    public void addToUniemensArray(Denunciaaziendale obj) {
        addToManyTarget("uniemensArray", obj, true);
    }
    public void removeFromUniemensArray(Denunciaaziendale obj) {
        removeToManyTarget("uniemensArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Denunciaaziendale> getUniemensArray() {
        return (List<Denunciaaziendale>)readProperty("uniemensArray");
    }


    public void addToUniemensImpresaArray(UniemensImpresa obj) {
        addToManyTarget("uniemensImpresaArray", obj, true);
    }
    public void removeFromUniemensImpresaArray(UniemensImpresa obj) {
        removeToManyTarget("uniemensImpresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<UniemensImpresa> getUniemensImpresaArray() {
        return (List<UniemensImpresa>)readProperty("uniemensImpresaArray");
    }


    public void addToUniemensPosizioneArray(UniemensPosizione obj) {
        addToManyTarget("uniemensPosizioneArray", obj, true);
    }
    public void removeFromUniemensPosizioneArray(UniemensPosizione obj) {
        removeToManyTarget("uniemensPosizioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<UniemensPosizione> getUniemensPosizioneArray() {
        return (List<UniemensPosizione>)readProperty("uniemensPosizioneArray");
    }


}
