package it.iubar.paghe.logic.paghe.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.paghe.CedolinoElemento;
import it.iubar.paghe.logic.paghe.Contrattocoefficiente;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Contrattorateovalore;
import it.iubar.paghe.logic.paghe.Posizionerateo;

/**
 * Class _Unitamisura was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Unitamisura extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String DESCRIZIONE2_PROPERTY = "descrizione2";
    public static final String IDUNITAMISURA_PROPERTY = "idunitamisura";
    public static final String CEDOLINO_ELEMENTO_ARRAY_PROPERTY = "cedolinoElementoArray";
    public static final String CONTRATTOCOEFFICIENTE_ARRAY_PROPERTY = "contrattocoefficienteArray";
    public static final String CONTRATTODETTAGLIO_ARRAY_PROPERTY = "contrattodettaglioArray";
    public static final String CONTRATTORATEOVALORE1ARRAY_PROPERTY = "contrattorateovalore1Array";
    public static final String CONTRATTORATEOVALORE2ARRAY_PROPERTY = "contrattorateovalore2Array";
    public static final String POSIZIONERATEO_ARRAY_PROPERTY = "posizionerateoArray";

    public static final String DESCRIZIONE_PK_COLUMN = "DESCRIZIONE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getDescrizione2() {
        return (String)readProperty("descrizione2");
    }

    public Short getIdunitamisura() {
        return (Short)readProperty("idunitamisura");
    }

    public void addToCedolinoElementoArray(CedolinoElemento obj) {
        addToManyTarget("cedolinoElementoArray", obj, true);
    }
    public void removeFromCedolinoElementoArray(CedolinoElemento obj) {
        removeToManyTarget("cedolinoElementoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CedolinoElemento> getCedolinoElementoArray() {
        return (List<CedolinoElemento>)readProperty("cedolinoElementoArray");
    }


    public void addToContrattocoefficienteArray(Contrattocoefficiente obj) {
        addToManyTarget("contrattocoefficienteArray", obj, true);
    }
    public void removeFromContrattocoefficienteArray(Contrattocoefficiente obj) {
        removeToManyTarget("contrattocoefficienteArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattocoefficiente> getContrattocoefficienteArray() {
        return (List<Contrattocoefficiente>)readProperty("contrattocoefficienteArray");
    }


    public void addToContrattodettaglioArray(Contrattodettaglio obj) {
        addToManyTarget("contrattodettaglioArray", obj, true);
    }
    public void removeFromContrattodettaglioArray(Contrattodettaglio obj) {
        removeToManyTarget("contrattodettaglioArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattodettaglio> getContrattodettaglioArray() {
        return (List<Contrattodettaglio>)readProperty("contrattodettaglioArray");
    }


    public void addToContrattorateovalore1Array(Contrattorateovalore obj) {
        addToManyTarget("contrattorateovalore1Array", obj, true);
    }
    public void removeFromContrattorateovalore1Array(Contrattorateovalore obj) {
        removeToManyTarget("contrattorateovalore1Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattorateovalore> getContrattorateovalore1Array() {
        return (List<Contrattorateovalore>)readProperty("contrattorateovalore1Array");
    }


    public void addToContrattorateovalore2Array(Contrattorateovalore obj) {
        addToManyTarget("contrattorateovalore2Array", obj, true);
    }
    public void removeFromContrattorateovalore2Array(Contrattorateovalore obj) {
        removeToManyTarget("contrattorateovalore2Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contrattorateovalore> getContrattorateovalore2Array() {
        return (List<Contrattorateovalore>)readProperty("contrattorateovalore2Array");
    }


    public void addToPosizionerateoArray(Posizionerateo obj) {
        addToManyTarget("posizionerateoArray", obj, true);
    }
    public void removeFromPosizionerateoArray(Posizionerateo obj) {
        removeToManyTarget("posizionerateoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionerateo> getPosizionerateoArray() {
        return (List<Posizionerateo>)readProperty("posizionerateoArray");
    }


}
