package it.iubar.paghe.logic.anagrafica.auto;

import java.sql.Timestamp;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Impresa;
import it.iubar.paghe.logic.anagrafica.Personafisica;
import it.iubar.paghe.logic.anagrafica.Personagiuridica;
import it.iubar.paghe.logic.anagrafica.Tipoanagrafica;
import it.iubar.paghe.logic.anagrafica.Titolaredati;
import it.iubar.paghe.logic.anagrafica.Utente;

/**
 * Class _Anagrafica was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Anagrafica extends CayenneDataObject {

    public static final String IDANAGRAFICA_PROPERTY = "idanagrafica";
    public static final String IDTIPOANAGRAFICA_PROPERTY = "idtipoanagrafica";
    public static final String IMPRESA_PROPERTY = "impresa";
    public static final String ULTIMAMODIFICADATA_PROPERTY = "ultimamodificadata";
    public static final String ULTIMAMODIFICAUSER_PROPERTY = "ultimamodificauser";
    public static final String TO_IMPRESA_PROPERTY = "toImpresa";
    public static final String TO_PERSONAFISICA_PROPERTY = "toPersonafisica";
    public static final String TO_PERSONAGIURIDICA_PROPERTY = "toPersonagiuridica";
    public static final String TO_TIPOANAGRAFICA_PROPERTY = "toTipoanagrafica";
    public static final String TO_TITOLARETRATTAMENTO_PROPERTY = "toTitolaretrattamento";
    public static final String TO_UTENTE_PROPERTY = "toUtente";

    public static final String IDANAGRAFICA_PK_COLUMN = "IDANAGRAFICA";

    public void setIdanagrafica(Integer idanagrafica) {
        writeProperty("idanagrafica", idanagrafica);
    }
    public Integer getIdanagrafica() {
        return (Integer)readProperty("idanagrafica");
    }

    public void setIdtipoanagrafica(Short idtipoanagrafica) {
        writeProperty("idtipoanagrafica", idtipoanagrafica);
    }
    public Short getIdtipoanagrafica() {
        return (Short)readProperty("idtipoanagrafica");
    }

    public void setImpresa(Short impresa) {
        writeProperty("impresa", impresa);
    }
    public Short getImpresa() {
        return (Short)readProperty("impresa");
    }

    public void setUltimamodificadata(Timestamp ultimamodificadata) {
        writeProperty("ultimamodificadata", ultimamodificadata);
    }
    public Timestamp getUltimamodificadata() {
        return (Timestamp)readProperty("ultimamodificadata");
    }

    public void setUltimamodificauser(String ultimamodificauser) {
        writeProperty("ultimamodificauser", ultimamodificauser);
    }
    public String getUltimamodificauser() {
        return (String)readProperty("ultimamodificauser");
    }

    public void setToImpresa(Impresa toImpresa) {
        setToOneTarget("toImpresa", toImpresa, true);
    }

    public Impresa getToImpresa() {
        return (Impresa)readProperty("toImpresa");
    }


    public void setToPersonafisica(Personafisica toPersonafisica) {
        setToOneTarget("toPersonafisica", toPersonafisica, true);
    }

    public Personafisica getToPersonafisica() {
        return (Personafisica)readProperty("toPersonafisica");
    }


    public void setToPersonagiuridica(Personagiuridica toPersonagiuridica) {
        setToOneTarget("toPersonagiuridica", toPersonagiuridica, true);
    }

    public Personagiuridica getToPersonagiuridica() {
        return (Personagiuridica)readProperty("toPersonagiuridica");
    }


    public void setToTipoanagrafica(Tipoanagrafica toTipoanagrafica) {
        setToOneTarget("toTipoanagrafica", toTipoanagrafica, true);
    }

    public Tipoanagrafica getToTipoanagrafica() {
        return (Tipoanagrafica)readProperty("toTipoanagrafica");
    }


    public void setToTitolaretrattamento(Titolaredati toTitolaretrattamento) {
        setToOneTarget("toTitolaretrattamento", toTitolaretrattamento, true);
    }

    public Titolaredati getToTitolaretrattamento() {
        return (Titolaredati)readProperty("toTitolaretrattamento");
    }


    public void setToUtente(Utente toUtente) {
        setToOneTarget("toUtente", toUtente, true);
    }

    public Utente getToUtente() {
        return (Utente)readProperty("toUtente");
    }


}
