package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.UtenteAzione;

/**
 * Class _Azione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Azione extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDAZIONE_PROPERTY = "idazione";
    public static final String NOTE_PROPERTY = "note";
    public static final String UTENTEAZIONE_ARRAY_PROPERTY = "utenteazioneArray";

    public static final String IDAZIONE_PK_COLUMN = "IDAZIONE";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public Short getIdazione() {
        return (Short)readProperty("idazione");
    }

    public String getNote() {
        return (String)readProperty("note");
    }

    public void addToUtenteazioneArray(UtenteAzione obj) {
        addToManyTarget("utenteazioneArray", obj, true);
    }
    public void removeFromUtenteazioneArray(UtenteAzione obj) {
        removeToManyTarget("utenteazioneArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<UtenteAzione> getUtenteazioneArray() {
        return (List<UtenteAzione>)readProperty("utenteazioneArray");
    }


}
