package it.iubar.paghe.logic.anagrafica.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.CnceSituazionecantiere;
import it.iubar.paghe.logic.anagrafica.CnceSubappalto;
import it.iubar.paghe.logic.anagrafica.CnceTipoattivita;
import it.iubar.paghe.logic.anagrafica.CnceTipocommittente;
import it.iubar.paghe.logic.anagrafica.CnceTipolavoro;
import it.iubar.paghe.logic.anagrafica.Impresa;
import it.iubar.paghe.logic.anagrafica.Indirizzo;

/**
 * Class _Cantiere was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Cantiere extends CayenneDataObject {

    public static final String APPALTOCIP_PROPERTY = "appaltocip";
    public static final String APPALTODATA_PROPERTY = "appaltodata";
    public static final String APPALTOPROTOCOLLO_PROPERTY = "appaltoprotocollo";
    public static final String CODCE_PROPERTY = "codce";
    public static final String CODMUT_PROPERTY = "codmut";
    public static final String DATASITUAZIONE_PROPERTY = "datasituazione";
    public static final String DENOMINAZIONE_PROPERTY = "denominazione";
    public static final String FINEANNO_PROPERTY = "fineanno";
    public static final String FINEMESE_PROPERTY = "finemese";
    public static final String IDAPPALTATORE_PROPERTY = "idappaltatore";
    public static final String IDCANTIERE_PROPERTY = "idcantiere";
    public static final String IDCOMMITTENTE_PROPERTY = "idcommittente";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDINDIRIZZO_PROPERTY = "idindirizzo";
    public static final String IDSITUAZIONE_PROPERTY = "idsituazione";
    public static final String IDTIPOATTIVITA_PROPERTY = "idtipoattivita";
    public static final String IDTIPOCOMMITTENTE_PROPERTY = "idtipocommittente";
    public static final String IDTIPOLAVORO_PROPERTY = "idtipolavoro";
    public static final String INIZIOANNO_PROPERTY = "inizioanno";
    public static final String INIZIOMESE_PROPERTY = "iniziomese";
    public static final String INTERINALI_PROPERTY = "interinali";
    public static final String NOTE_PROPERTY = "note";
    public static final String NPCODICE_PROPERTY = "npcodice";
    public static final String NPDATA_PROPERTY = "npdata";
    public static final String OPERADATAFINE_PROPERTY = "operadatafine";
    public static final String OPERAIMPORTO_PROPERTY = "operaimporto";
    public static final String OPERAVALORE_PROPERTY = "operavalore";
    public static final String PREVALENTE_PROPERTY = "prevalente";
    public static final String RETRIBIMPONIBILECE_PROPERTY = "retribimponibilece";
    public static final String RETRIBIMPONIBILEINPS_PROPERTY = "retribimponibileinps";
    public static final String TRASFERTISTI_PROPERTY = "trasfertisti";
    public static final String CNCE_SUBAPPALTO_ARRAY_PROPERTY = "cnceSubappaltoArray";
    public static final String TO_CNCE_SITUAZIONE_PROPERTY = "toCnceSituazione";
    public static final String TO_CNCE_TIPOATTIVITA_PROPERTY = "toCnceTipoattivita";
    public static final String TO_CNCE_TIPOCOMMITENTE_PROPERTY = "toCnceTipocommitente";
    public static final String TO_CNCE_TIPOLAVORO_PROPERTY = "toCnceTipolavoro";
    public static final String TO_IMPRESA_PROPERTY = "toImpresa";
    public static final String TO_INDIRIZZO_PROPERTY = "toIndirizzo";

    public static final String IDCANTIERE_PK_COLUMN = "IDCANTIERE";
    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";

    public void setAppaltocip(String appaltocip) {
        writeProperty("appaltocip", appaltocip);
    }
    public String getAppaltocip() {
        return (String)readProperty("appaltocip");
    }

    public void setAppaltodata(Date appaltodata) {
        writeProperty("appaltodata", appaltodata);
    }
    public Date getAppaltodata() {
        return (Date)readProperty("appaltodata");
    }

    public void setAppaltoprotocollo(String appaltoprotocollo) {
        writeProperty("appaltoprotocollo", appaltoprotocollo);
    }
    public String getAppaltoprotocollo() {
        return (String)readProperty("appaltoprotocollo");
    }

    public void setCodce(String codce) {
        writeProperty("codce", codce);
    }
    public String getCodce() {
        return (String)readProperty("codce");
    }

    public void setCodmut(String codmut) {
        writeProperty("codmut", codmut);
    }
    public String getCodmut() {
        return (String)readProperty("codmut");
    }

    public void setDatasituazione(Date datasituazione) {
        writeProperty("datasituazione", datasituazione);
    }
    public Date getDatasituazione() {
        return (Date)readProperty("datasituazione");
    }

    public void setDenominazione(String denominazione) {
        writeProperty("denominazione", denominazione);
    }
    public String getDenominazione() {
        return (String)readProperty("denominazione");
    }

    public void setFineanno(Integer fineanno) {
        writeProperty("fineanno", fineanno);
    }
    public Integer getFineanno() {
        return (Integer)readProperty("fineanno");
    }

    public void setFinemese(Short finemese) {
        writeProperty("finemese", finemese);
    }
    public Short getFinemese() {
        return (Short)readProperty("finemese");
    }

    public void setIdappaltatore(Integer idappaltatore) {
        writeProperty("idappaltatore", idappaltatore);
    }
    public Integer getIdappaltatore() {
        return (Integer)readProperty("idappaltatore");
    }

    public void setIdcantiere(Short idcantiere) {
        writeProperty("idcantiere", idcantiere);
    }
    public Short getIdcantiere() {
        return (Short)readProperty("idcantiere");
    }

    public void setIdcommittente(Integer idcommittente) {
        writeProperty("idcommittente", idcommittente);
    }
    public Integer getIdcommittente() {
        return (Integer)readProperty("idcommittente");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdindirizzo(Integer idindirizzo) {
        writeProperty("idindirizzo", idindirizzo);
    }
    public Integer getIdindirizzo() {
        return (Integer)readProperty("idindirizzo");
    }

    public void setIdsituazione(Short idsituazione) {
        writeProperty("idsituazione", idsituazione);
    }
    public Short getIdsituazione() {
        return (Short)readProperty("idsituazione");
    }

    public void setIdtipoattivita(Short idtipoattivita) {
        writeProperty("idtipoattivita", idtipoattivita);
    }
    public Short getIdtipoattivita() {
        return (Short)readProperty("idtipoattivita");
    }

    public void setIdtipocommittente(Short idtipocommittente) {
        writeProperty("idtipocommittente", idtipocommittente);
    }
    public Short getIdtipocommittente() {
        return (Short)readProperty("idtipocommittente");
    }

    public void setIdtipolavoro(Short idtipolavoro) {
        writeProperty("idtipolavoro", idtipolavoro);
    }
    public Short getIdtipolavoro() {
        return (Short)readProperty("idtipolavoro");
    }

    public void setInizioanno(Integer inizioanno) {
        writeProperty("inizioanno", inizioanno);
    }
    public Integer getInizioanno() {
        return (Integer)readProperty("inizioanno");
    }

    public void setIniziomese(Short iniziomese) {
        writeProperty("iniziomese", iniziomese);
    }
    public Short getIniziomese() {
        return (Short)readProperty("iniziomese");
    }

    public void setInterinali(Short interinali) {
        writeProperty("interinali", interinali);
    }
    public Short getInterinali() {
        return (Short)readProperty("interinali");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setNpcodice(String npcodice) {
        writeProperty("npcodice", npcodice);
    }
    public String getNpcodice() {
        return (String)readProperty("npcodice");
    }

    public void setNpdata(Date npdata) {
        writeProperty("npdata", npdata);
    }
    public Date getNpdata() {
        return (Date)readProperty("npdata");
    }

    public void setOperadatafine(Date operadatafine) {
        writeProperty("operadatafine", operadatafine);
    }
    public Date getOperadatafine() {
        return (Date)readProperty("operadatafine");
    }

    public void setOperaimporto(BigDecimal operaimporto) {
        writeProperty("operaimporto", operaimporto);
    }
    public BigDecimal getOperaimporto() {
        return (BigDecimal)readProperty("operaimporto");
    }

    public void setOperavalore(BigDecimal operavalore) {
        writeProperty("operavalore", operavalore);
    }
    public BigDecimal getOperavalore() {
        return (BigDecimal)readProperty("operavalore");
    }

    public void setPrevalente(Short prevalente) {
        writeProperty("prevalente", prevalente);
    }
    public Short getPrevalente() {
        return (Short)readProperty("prevalente");
    }

    public void setRetribimponibilece(BigDecimal retribimponibilece) {
        writeProperty("retribimponibilece", retribimponibilece);
    }
    public BigDecimal getRetribimponibilece() {
        return (BigDecimal)readProperty("retribimponibilece");
    }

    public void setRetribimponibileinps(BigDecimal retribimponibileinps) {
        writeProperty("retribimponibileinps", retribimponibileinps);
    }
    public BigDecimal getRetribimponibileinps() {
        return (BigDecimal)readProperty("retribimponibileinps");
    }

    public void setTrasfertisti(Short trasfertisti) {
        writeProperty("trasfertisti", trasfertisti);
    }
    public Short getTrasfertisti() {
        return (Short)readProperty("trasfertisti");
    }

    public void addToCnceSubappaltoArray(CnceSubappalto obj) {
        addToManyTarget("cnceSubappaltoArray", obj, true);
    }
    public void removeFromCnceSubappaltoArray(CnceSubappalto obj) {
        removeToManyTarget("cnceSubappaltoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CnceSubappalto> getCnceSubappaltoArray() {
        return (List<CnceSubappalto>)readProperty("cnceSubappaltoArray");
    }


    public void setToCnceSituazione(CnceSituazionecantiere toCnceSituazione) {
        setToOneTarget("toCnceSituazione", toCnceSituazione, true);
    }

    public CnceSituazionecantiere getToCnceSituazione() {
        return (CnceSituazionecantiere)readProperty("toCnceSituazione");
    }


    public void setToCnceTipoattivita(CnceTipoattivita toCnceTipoattivita) {
        setToOneTarget("toCnceTipoattivita", toCnceTipoattivita, true);
    }

    public CnceTipoattivita getToCnceTipoattivita() {
        return (CnceTipoattivita)readProperty("toCnceTipoattivita");
    }


    public void setToCnceTipocommitente(CnceTipocommittente toCnceTipocommitente) {
        setToOneTarget("toCnceTipocommitente", toCnceTipocommitente, true);
    }

    public CnceTipocommittente getToCnceTipocommitente() {
        return (CnceTipocommittente)readProperty("toCnceTipocommitente");
    }


    public void setToCnceTipolavoro(CnceTipolavoro toCnceTipolavoro) {
        setToOneTarget("toCnceTipolavoro", toCnceTipolavoro, true);
    }

    public CnceTipolavoro getToCnceTipolavoro() {
        return (CnceTipolavoro)readProperty("toCnceTipolavoro");
    }


    public void setToImpresa(Impresa toImpresa) {
        setToOneTarget("toImpresa", toImpresa, true);
    }

    public Impresa getToImpresa() {
        return (Impresa)readProperty("toImpresa");
    }


    public void setToIndirizzo(Indirizzo toIndirizzo) {
        setToOneTarget("toIndirizzo", toIndirizzo, true);
    }

    public Indirizzo getToIndirizzo() {
        return (Indirizzo)readProperty("toIndirizzo");
    }


}
