package it.iubar.paghe.logic.anagrafica.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Centrodicosto;
import it.iubar.paghe.logic.anagrafica.Lavoratore;

/**
 * Class _CentrodicostoLavoratore was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CentrodicostoLavoratore extends CayenneDataObject {

    public static final String DECORRENZA_PROPERTY = "decorrenza";
    public static final String IDCENTRODICOSTO_PROPERTY = "idcentrodicosto";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDLAVORATORE_PROPERTY = "idlavoratore";
    public static final String PERCENTUALE_PROPERTY = "percentuale";
    public static final String TO_CENTRODICOSTO_PROPERTY = "toCentrodicosto";
    public static final String TO_LAVORATORE_PROPERTY = "toLavoratore";

    public static final String IDCENTRODICOSTO_PK_COLUMN = "IDCENTRODICOSTO";
    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";
    public static final String IDLAVORATORE_PK_COLUMN = "IDLAVORATORE";
    public static final String PERCENTUALE_PK_COLUMN = "PERCENTUALE";

    public void setDecorrenza(Date decorrenza) {
        writeProperty("decorrenza", decorrenza);
    }
    public Date getDecorrenza() {
        return (Date)readProperty("decorrenza");
    }

    public void setIdcentrodicosto(Short idcentrodicosto) {
        writeProperty("idcentrodicosto", idcentrodicosto);
    }
    public Short getIdcentrodicosto() {
        return (Short)readProperty("idcentrodicosto");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdlavoratore(Integer idlavoratore) {
        writeProperty("idlavoratore", idlavoratore);
    }
    public Integer getIdlavoratore() {
        return (Integer)readProperty("idlavoratore");
    }

    public void setPercentuale(BigDecimal percentuale) {
        writeProperty("percentuale", percentuale);
    }
    public BigDecimal getPercentuale() {
        return (BigDecimal)readProperty("percentuale");
    }

    public void setToCentrodicosto(Centrodicosto toCentrodicosto) {
        setToOneTarget("toCentrodicosto", toCentrodicosto, true);
    }

    public Centrodicosto getToCentrodicosto() {
        return (Centrodicosto)readProperty("toCentrodicosto");
    }


    public void setToLavoratore(Lavoratore toLavoratore) {
        setToOneTarget("toLavoratore", toLavoratore, true);
    }

    public Lavoratore getToLavoratore() {
        return (Lavoratore)readProperty("toLavoratore");
    }


}
