package it.iubar.paghe.logic.anagrafica.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.CoPermessosoggiorno;
import it.iubar.paghe.logic.anagrafica.CoStatusstraniero;
import it.iubar.paghe.logic.anagrafica.Personafisica;
import it.iubar.paghe.logic.anagrafica.Questura;

/**
 * Class _Extrace was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Extrace extends CayenneDataObject {

    public static final String IDEXTRACE_PROPERTY = "idextrace";
    public static final String IMPEGNORIMPATRIO_PROPERTY = "impegnorimpatrio";
    public static final String NUMERO_PROPERTY = "numero";
    public static final String SCADENZA_PROPERTY = "scadenza";
    public static final String SUSSISTENZAABITATIVA_PROPERTY = "sussistenzaabitativa";
    public static final String PERSONAFISICA_ARRAY_PROPERTY = "personafisicaArray";
    public static final String TO_CO_PERMESSO_SOGGIORNO_PROPERTY = "toCoPermessoSoggiorno";
    public static final String TO_CO_STATUS_STRANIERO_PROPERTY = "toCoStatusStraniero";
    public static final String TO_QUESTURA_PROPERTY = "toQuestura";

    public static final String IDEXTRACE_PK_COLUMN = "IDEXTRACE";

    public void setIdextrace(Integer idextrace) {
        writeProperty("idextrace", idextrace);
    }
    public Integer getIdextrace() {
        return (Integer)readProperty("idextrace");
    }

    public void setImpegnorimpatrio(Short impegnorimpatrio) {
        writeProperty("impegnorimpatrio", impegnorimpatrio);
    }
    public Short getImpegnorimpatrio() {
        return (Short)readProperty("impegnorimpatrio");
    }

    public void setNumero(String numero) {
        writeProperty("numero", numero);
    }
    public String getNumero() {
        return (String)readProperty("numero");
    }

    public void setScadenza(Date scadenza) {
        writeProperty("scadenza", scadenza);
    }
    public Date getScadenza() {
        return (Date)readProperty("scadenza");
    }

    public void setSussistenzaabitativa(Short sussistenzaabitativa) {
        writeProperty("sussistenzaabitativa", sussistenzaabitativa);
    }
    public Short getSussistenzaabitativa() {
        return (Short)readProperty("sussistenzaabitativa");
    }

    public void addToPersonafisicaArray(Personafisica obj) {
        addToManyTarget("personafisicaArray", obj, true);
    }
    public void removeFromPersonafisicaArray(Personafisica obj) {
        removeToManyTarget("personafisicaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Personafisica> getPersonafisicaArray() {
        return (List<Personafisica>)readProperty("personafisicaArray");
    }


    public void setToCoPermessoSoggiorno(CoPermessosoggiorno toCoPermessoSoggiorno) {
        setToOneTarget("toCoPermessoSoggiorno", toCoPermessoSoggiorno, true);
    }

    public CoPermessosoggiorno getToCoPermessoSoggiorno() {
        return (CoPermessosoggiorno)readProperty("toCoPermessoSoggiorno");
    }


    public void setToCoStatusStraniero(CoStatusstraniero toCoStatusStraniero) {
        setToOneTarget("toCoStatusStraniero", toCoStatusStraniero, true);
    }

    public CoStatusstraniero getToCoStatusStraniero() {
        return (CoStatusstraniero)readProperty("toCoStatusStraniero");
    }


    public void setToQuestura(Questura toQuestura) {
        setToOneTarget("toQuestura", toQuestura, true);
    }

    public Questura getToQuestura() {
        return (Questura)readProperty("toQuestura");
    }


}
