package it.iubar.paghe.logic.anagrafica.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.AeStatosocietario;
import it.iubar.paghe.logic.anagrafica.Anagrafica;
import it.iubar.paghe.logic.anagrafica.Cantiere;
import it.iubar.paghe.logic.anagrafica.Centrodicosto;
import it.iubar.paghe.logic.anagrafica.CentrodicostoSedeimpresa;
import it.iubar.paghe.logic.anagrafica.ConfigImpresa;
import it.iubar.paghe.logic.anagrafica.Formagiuridica;
import it.iubar.paghe.logic.anagrafica.ImpresaBanca;
import it.iubar.paghe.logic.anagrafica.IstatAteco;
import it.iubar.paghe.logic.anagrafica.Lavoratore;
import it.iubar.paghe.logic.anagrafica.Sedeimpresa;
import it.iubar.paghe.logic.anagrafica.SedeimpresaCodinpslav;
import it.iubar.paghe.logic.anagrafica.SedeimpresaPat;
import it.iubar.paghe.logic.anagrafica.Socio;
import it.iubar.paghe.logic.anagrafica.Tipodatore;
import it.iubar.paghe.logic.anagrafica.Titolaredati;
import it.iubar.paghe.logic.paghe.Elementoretributivo;
import it.iubar.paghe.logic.paghe.ImpresaContratto;
import it.iubar.paghe.logic.paghe.Posizionelavoratore;
import it.iubar.paghe.logic.paghe.Scadenza;
import it.iubar.paghe.logic.presenze.Orario;
import it.iubar.paghe.logic.presenze.Rilevatore;

/**
 * Class _Impresa was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Impresa extends CayenneDataObject {

    public static final String ATTIVA_PROPERTY = "attiva";
    public static final String ATTIVITACESSAZIONEDATA_PROPERTY = "attivitacessazionedata";
    public static final String ATTIVITAINIZIODATA_PROPERTY = "attivitainiziodata";
    public static final String CCIAADATA_PROPERTY = "cciaadata";
    public static final String CCIAANUMERO_PROPERTY = "cciaanumero";
    public static final String CF_PROPERTY = "cf";
    public static final String DENOMINAZIONE_PROPERTY = "denominazione";
    public static final String FATTURATO_PROPERTY = "fatturato";
    public static final String IDATECO_PROPERTY = "idateco";
    public static final String IDFORMAGIURIDICA_PROPERTY = "idformagiuridica";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDSTATOIMPRESA_PROPERTY = "idstatoimpresa";
    public static final String IDSTATOSOCIETARIO_PROPERTY = "idstatosocietario";
    public static final String IDTIPODATORE_PROPERTY = "idtipodatore";
    public static final String IDTIPOGESTIONE_PROPERTY = "idtipogestione";
    public static final String IDTITOLAREDATI_PROPERTY = "idtitolaredati";
    public static final String INAILCODDITTA_PROPERTY = "inailcodditta";
    public static final String INAILCONTROCOD_PROPERTY = "inailcontrocod";
    public static final String INAILPIN_PROPERTY = "inailpin";
    public static final String INAILRATEAZIONE_PROPERTY = "inailrateazione";
    public static final String NOTE_PROPERTY = "note";
    public static final String PIVA_PROPERTY = "piva";
    public static final String BANCA_ARRAY_PROPERTY = "bancaArray";
    public static final String CANTIERE_ARRAY_PROPERTY = "cantiereArray";
    public static final String CENTRODICOSTO_ARRAY_PROPERTY = "centrodicostoArray";
    public static final String CENTRODICOSTOSEDEIMPRESA_ARRAY_PROPERTY = "centrodicostosedeimpresaArray";
    public static final String CONFIG_IMPRESA_ARRAY_PROPERTY = "configImpresaArray";
    public static final String ELEMENTORETRIBUTIVO_ARRAY_PROPERTY = "elementoretributivoArray";
    public static final String IMPRESA_CONTRATTO_ARRAY_PROPERTY = "impresaContrattoArray";
    public static final String LAVORATORE_ARRAY_PROPERTY = "lavoratoreArray";
    public static final String ORARIO_ARRAY_PROPERTY = "orarioArray";
    public static final String PAT_ARRAY_PROPERTY = "patArray";
    public static final String POSIZIONELAVORATORE_ARRAY_PROPERTY = "posizionelavoratoreArray";
    public static final String RILEVATORE_ARRAY_PROPERTY = "rilevatoreArray";
    public static final String SCADENZA_ARRAY_PROPERTY = "scadenzaArray";
    public static final String SEDEIMPRESA_ARRAY_PROPERTY = "sedeimpresaArray";
    public static final String SEDEINPRESA_CODINPSLAV_ARRAY_PROPERTY = "sedeinpresaCodinpslavArray";
    public static final String SOCIO_ARRAY_PROPERTY = "socioArray";
    public static final String TO_ANAGRAFICA_PROPERTY = "toAnagrafica";
    public static final String TO_ATECO_PROPERTY = "toAteco";
    public static final String TO_FORMAGIURIDICA_PROPERTY = "toFormagiuridica";
    public static final String TO_STATOSOCIETARIO_PROPERTY = "toStatosocietario";
    public static final String TO_TIPODATORE_PROPERTY = "toTipodatore";
    public static final String TO_TITOLAREDATI_PROPERTY = "toTitolaredati";

    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";

    public void setAttiva(Short attiva) {
        writeProperty("attiva", attiva);
    }
    public Short getAttiva() {
        return (Short)readProperty("attiva");
    }

    public void setAttivitacessazionedata(Date attivitacessazionedata) {
        writeProperty("attivitacessazionedata", attivitacessazionedata);
    }
    public Date getAttivitacessazionedata() {
        return (Date)readProperty("attivitacessazionedata");
    }

    public void setAttivitainiziodata(Date attivitainiziodata) {
        writeProperty("attivitainiziodata", attivitainiziodata);
    }
    public Date getAttivitainiziodata() {
        return (Date)readProperty("attivitainiziodata");
    }

    public void setCciaadata(Date cciaadata) {
        writeProperty("cciaadata", cciaadata);
    }
    public Date getCciaadata() {
        return (Date)readProperty("cciaadata");
    }

    public void setCciaanumero(Integer cciaanumero) {
        writeProperty("cciaanumero", cciaanumero);
    }
    public Integer getCciaanumero() {
        return (Integer)readProperty("cciaanumero");
    }

    public void setCf(String cf) {
        writeProperty("cf", cf);
    }
    public String getCf() {
        return (String)readProperty("cf");
    }

    public void setDenominazione(String denominazione) {
        writeProperty("denominazione", denominazione);
    }
    public String getDenominazione() {
        return (String)readProperty("denominazione");
    }

    public void setFatturato(BigDecimal fatturato) {
        writeProperty("fatturato", fatturato);
    }
    public BigDecimal getFatturato() {
        return (BigDecimal)readProperty("fatturato");
    }

    public void setIdateco(String idateco) {
        writeProperty("idateco", idateco);
    }
    public String getIdateco() {
        return (String)readProperty("idateco");
    }

    public void setIdformagiuridica(Short idformagiuridica) {
        writeProperty("idformagiuridica", idformagiuridica);
    }
    public Short getIdformagiuridica() {
        return (Short)readProperty("idformagiuridica");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdstatoimpresa(Short idstatoimpresa) {
        writeProperty("idstatoimpresa", idstatoimpresa);
    }
    public Short getIdstatoimpresa() {
        return (Short)readProperty("idstatoimpresa");
    }

    public void setIdstatosocietario(Short idstatosocietario) {
        writeProperty("idstatosocietario", idstatosocietario);
    }
    public Short getIdstatosocietario() {
        return (Short)readProperty("idstatosocietario");
    }

    public void setIdtipodatore(Short idtipodatore) {
        writeProperty("idtipodatore", idtipodatore);
    }
    public Short getIdtipodatore() {
        return (Short)readProperty("idtipodatore");
    }

    public void setIdtipogestione(Short idtipogestione) {
        writeProperty("idtipogestione", idtipogestione);
    }
    public Short getIdtipogestione() {
        return (Short)readProperty("idtipogestione");
    }

    public void setIdtitolaredati(Integer idtitolaredati) {
        writeProperty("idtitolaredati", idtitolaredati);
    }
    public Integer getIdtitolaredati() {
        return (Integer)readProperty("idtitolaredati");
    }

    public void setInailcodditta(String inailcodditta) {
        writeProperty("inailcodditta", inailcodditta);
    }
    public String getInailcodditta() {
        return (String)readProperty("inailcodditta");
    }

    public void setInailcontrocod(String inailcontrocod) {
        writeProperty("inailcontrocod", inailcontrocod);
    }
    public String getInailcontrocod() {
        return (String)readProperty("inailcontrocod");
    }

    public void setInailpin(String inailpin) {
        writeProperty("inailpin", inailpin);
    }
    public String getInailpin() {
        return (String)readProperty("inailpin");
    }

    public void setInailrateazione(Short inailrateazione) {
        writeProperty("inailrateazione", inailrateazione);
    }
    public Short getInailrateazione() {
        return (Short)readProperty("inailrateazione");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setPiva(String piva) {
        writeProperty("piva", piva);
    }
    public String getPiva() {
        return (String)readProperty("piva");
    }

    public void addToBancaArray(ImpresaBanca obj) {
        addToManyTarget("bancaArray", obj, true);
    }
    public void removeFromBancaArray(ImpresaBanca obj) {
        removeToManyTarget("bancaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ImpresaBanca> getBancaArray() {
        return (List<ImpresaBanca>)readProperty("bancaArray");
    }


    public void addToCantiereArray(Cantiere obj) {
        addToManyTarget("cantiereArray", obj, true);
    }
    public void removeFromCantiereArray(Cantiere obj) {
        removeToManyTarget("cantiereArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cantiere> getCantiereArray() {
        return (List<Cantiere>)readProperty("cantiereArray");
    }


    public void addToCentrodicostoArray(Centrodicosto obj) {
        addToManyTarget("centrodicostoArray", obj, true);
    }
    public void removeFromCentrodicostoArray(Centrodicosto obj) {
        removeToManyTarget("centrodicostoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Centrodicosto> getCentrodicostoArray() {
        return (List<Centrodicosto>)readProperty("centrodicostoArray");
    }


    public void addToCentrodicostosedeimpresaArray(CentrodicostoSedeimpresa obj) {
        addToManyTarget("centrodicostosedeimpresaArray", obj, true);
    }
    public void removeFromCentrodicostosedeimpresaArray(CentrodicostoSedeimpresa obj) {
        removeToManyTarget("centrodicostosedeimpresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CentrodicostoSedeimpresa> getCentrodicostosedeimpresaArray() {
        return (List<CentrodicostoSedeimpresa>)readProperty("centrodicostosedeimpresaArray");
    }


    public void addToConfigImpresaArray(ConfigImpresa obj) {
        addToManyTarget("configImpresaArray", obj, true);
    }
    public void removeFromConfigImpresaArray(ConfigImpresa obj) {
        removeToManyTarget("configImpresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ConfigImpresa> getConfigImpresaArray() {
        return (List<ConfigImpresa>)readProperty("configImpresaArray");
    }


    public void addToElementoretributivoArray(Elementoretributivo obj) {
        addToManyTarget("elementoretributivoArray", obj, true);
    }
    public void removeFromElementoretributivoArray(Elementoretributivo obj) {
        removeToManyTarget("elementoretributivoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Elementoretributivo> getElementoretributivoArray() {
        return (List<Elementoretributivo>)readProperty("elementoretributivoArray");
    }


    public void addToImpresaContrattoArray(ImpresaContratto obj) {
        addToManyTarget("impresaContrattoArray", obj, true);
    }
    public void removeFromImpresaContrattoArray(ImpresaContratto obj) {
        removeToManyTarget("impresaContrattoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ImpresaContratto> getImpresaContrattoArray() {
        return (List<ImpresaContratto>)readProperty("impresaContrattoArray");
    }


    public void addToLavoratoreArray(Lavoratore obj) {
        addToManyTarget("lavoratoreArray", obj, true);
    }
    public void removeFromLavoratoreArray(Lavoratore obj) {
        removeToManyTarget("lavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lavoratore> getLavoratoreArray() {
        return (List<Lavoratore>)readProperty("lavoratoreArray");
    }


    public void addToOrarioArray(Orario obj) {
        addToManyTarget("orarioArray", obj, true);
    }
    public void removeFromOrarioArray(Orario obj) {
        removeToManyTarget("orarioArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Orario> getOrarioArray() {
        return (List<Orario>)readProperty("orarioArray");
    }


    public void addToPatArray(SedeimpresaPat obj) {
        addToManyTarget("patArray", obj, true);
    }
    public void removeFromPatArray(SedeimpresaPat obj) {
        removeToManyTarget("patArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SedeimpresaPat> getPatArray() {
        return (List<SedeimpresaPat>)readProperty("patArray");
    }


    public void addToPosizionelavoratoreArray(Posizionelavoratore obj) {
        addToManyTarget("posizionelavoratoreArray", obj, true);
    }
    public void removeFromPosizionelavoratoreArray(Posizionelavoratore obj) {
        removeToManyTarget("posizionelavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionelavoratore> getPosizionelavoratoreArray() {
        return (List<Posizionelavoratore>)readProperty("posizionelavoratoreArray");
    }


    public void addToRilevatoreArray(Rilevatore obj) {
        addToManyTarget("rilevatoreArray", obj, true);
    }
    public void removeFromRilevatoreArray(Rilevatore obj) {
        removeToManyTarget("rilevatoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Rilevatore> getRilevatoreArray() {
        return (List<Rilevatore>)readProperty("rilevatoreArray");
    }


    public void addToScadenzaArray(Scadenza obj) {
        addToManyTarget("scadenzaArray", obj, true);
    }
    public void removeFromScadenzaArray(Scadenza obj) {
        removeToManyTarget("scadenzaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Scadenza> getScadenzaArray() {
        return (List<Scadenza>)readProperty("scadenzaArray");
    }


    public void addToSedeimpresaArray(Sedeimpresa obj) {
        addToManyTarget("sedeimpresaArray", obj, true);
    }
    public void removeFromSedeimpresaArray(Sedeimpresa obj) {
        removeToManyTarget("sedeimpresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Sedeimpresa> getSedeimpresaArray() {
        return (List<Sedeimpresa>)readProperty("sedeimpresaArray");
    }


    public void addToSedeinpresaCodinpslavArray(SedeimpresaCodinpslav obj) {
        addToManyTarget("sedeinpresaCodinpslavArray", obj, true);
    }
    public void removeFromSedeinpresaCodinpslavArray(SedeimpresaCodinpslav obj) {
        removeToManyTarget("sedeinpresaCodinpslavArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SedeimpresaCodinpslav> getSedeinpresaCodinpslavArray() {
        return (List<SedeimpresaCodinpslav>)readProperty("sedeinpresaCodinpslavArray");
    }


    public void addToSocioArray(Socio obj) {
        addToManyTarget("socioArray", obj, true);
    }
    public void removeFromSocioArray(Socio obj) {
        removeToManyTarget("socioArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Socio> getSocioArray() {
        return (List<Socio>)readProperty("socioArray");
    }


    public void setToAnagrafica(Anagrafica toAnagrafica) {
        setToOneTarget("toAnagrafica", toAnagrafica, true);
    }

    public Anagrafica getToAnagrafica() {
        return (Anagrafica)readProperty("toAnagrafica");
    }


    public void setToAteco(IstatAteco toAteco) {
        setToOneTarget("toAteco", toAteco, true);
    }

    public IstatAteco getToAteco() {
        return (IstatAteco)readProperty("toAteco");
    }


    public void setToFormagiuridica(Formagiuridica toFormagiuridica) {
        setToOneTarget("toFormagiuridica", toFormagiuridica, true);
    }

    public Formagiuridica getToFormagiuridica() {
        return (Formagiuridica)readProperty("toFormagiuridica");
    }


    public void setToStatosocietario(AeStatosocietario toStatosocietario) {
        setToOneTarget("toStatosocietario", toStatosocietario, true);
    }

    public AeStatosocietario getToStatosocietario() {
        return (AeStatosocietario)readProperty("toStatosocietario");
    }


    public void setToTipodatore(Tipodatore toTipodatore) {
        setToOneTarget("toTipodatore", toTipodatore, true);
    }

    public Tipodatore getToTipodatore() {
        return (Tipodatore)readProperty("toTipodatore");
    }


    public void setToTitolaredati(Titolaredati toTitolaredati) {
        setToOneTarget("toTitolaredati", toTitolaredati, true);
    }

    public Titolaredati getToTitolaredati() {
        return (Titolaredati)readProperty("toTitolaredati");
    }


}
