package it.iubar.paghe.logic.anagrafica.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.SedeimpresaAutorizzazione;

/**
 * Class _InpsAutorizzazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InpsAutorizzazione extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String INPSCA_PROPERTY = "inpsca";
    public static final String NOTE_PROPERTY = "note";
    public static final String VALIDOAL_PROPERTY = "validoal";
    public static final String VALIDODAL_PROPERTY = "validodal";
    public static final String INPSCARATTERISTICA_ARRAY_PROPERTY = "inpscaratteristicaArray";

    public static final String INPSCA_PK_COLUMN = "INPSCA";
    public static final String VALIDODAL_PK_COLUMN = "VALIDODAL";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getInpsca() {
        return (String)readProperty("inpsca");
    }

    public String getNote() {
        return (String)readProperty("note");
    }

    public Date getValidoal() {
        return (Date)readProperty("validoal");
    }

    public Date getValidodal() {
        return (Date)readProperty("validodal");
    }

    public void addToInpscaratteristicaArray(SedeimpresaAutorizzazione obj) {
        addToManyTarget("inpscaratteristicaArray", obj, true);
    }
    public void removeFromInpscaratteristicaArray(SedeimpresaAutorizzazione obj) {
        removeToManyTarget("inpscaratteristicaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SedeimpresaAutorizzazione> getInpscaratteristicaArray() {
        return (List<SedeimpresaAutorizzazione>)readProperty("inpscaratteristicaArray");
    }


}
