package it.iubar.paghe.logic.anagrafica.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Personafisica;
import it.iubar.paghe.logic.anagrafica.Rapportoparentela;
import it.iubar.paghe.logic.anagrafica.Statoparentela;

/**
 * Class _Parentela was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Parentela extends CayenneDataObject {

    public static final String ACARICO_PROPERTY = "acarico";
    public static final String ACARICOAL_PROPERTY = "acaricoal";
    public static final String ACARICODAL_PROPERTY = "acaricodal";
    public static final String ACARICOPERCENTUALE_PROPERTY = "acaricopercentuale";
    public static final String CONVIVENTE_PROPERTY = "convivente";
    public static final String IDANAGRAFICA1_PROPERTY = "idanagrafica1";
    public static final String IDANAGRAFICA2_PROPERTY = "idanagrafica2";
    public static final String IDRAPPORTOPARENTELA_PROPERTY = "idrapportoparentela";
    public static final String IDSTATOPARENTELA_PROPERTY = "idstatoparentela";
    public static final String OPZIONE_PROPERTY = "opzione";
    public static final String RAPPORTOAL_PROPERTY = "rapportoal";
    public static final String RAPPORTODAL_PROPERTY = "rapportodal";
    public static final String REDDITOANNO_PROPERTY = "redditoanno";
    public static final String RICEVEASSEGNO_PROPERTY = "riceveassegno";
    public static final String TO_PERSONAFISICA1_PROPERTY = "toPersonafisica1";
    public static final String TO_PERSONAFISICA2_PROPERTY = "toPersonafisica2";
    public static final String TO_RAPPORTO_PARENTELA_PROPERTY = "toRapportoParentela";
    public static final String TO_STATO_PARENTELA_PROPERTY = "toStatoParentela";

    public static final String IDANAGRAFICA1_PK_COLUMN = "IDANAGRAFICA1";
    public static final String IDANAGRAFICA2_PK_COLUMN = "IDANAGRAFICA2";
    public static final String IDRAPPORTOPARENTELA_PK_COLUMN = "IDRAPPORTOPARENTELA";

    public void setAcarico(Short acarico) {
        writeProperty("acarico", acarico);
    }
    public Short getAcarico() {
        return (Short)readProperty("acarico");
    }

    public void setAcaricoal(Date acaricoal) {
        writeProperty("acaricoal", acaricoal);
    }
    public Date getAcaricoal() {
        return (Date)readProperty("acaricoal");
    }

    public void setAcaricodal(Date acaricodal) {
        writeProperty("acaricodal", acaricodal);
    }
    public Date getAcaricodal() {
        return (Date)readProperty("acaricodal");
    }

    public void setAcaricopercentuale(BigDecimal acaricopercentuale) {
        writeProperty("acaricopercentuale", acaricopercentuale);
    }
    public BigDecimal getAcaricopercentuale() {
        return (BigDecimal)readProperty("acaricopercentuale");
    }

    public void setConvivente(Short convivente) {
        writeProperty("convivente", convivente);
    }
    public Short getConvivente() {
        return (Short)readProperty("convivente");
    }

    public void setIdanagrafica1(Integer idanagrafica1) {
        writeProperty("idanagrafica1", idanagrafica1);
    }
    public Integer getIdanagrafica1() {
        return (Integer)readProperty("idanagrafica1");
    }

    public void setIdanagrafica2(Integer idanagrafica2) {
        writeProperty("idanagrafica2", idanagrafica2);
    }
    public Integer getIdanagrafica2() {
        return (Integer)readProperty("idanagrafica2");
    }

    public void setIdrapportoparentela(Short idrapportoparentela) {
        writeProperty("idrapportoparentela", idrapportoparentela);
    }
    public Short getIdrapportoparentela() {
        return (Short)readProperty("idrapportoparentela");
    }

    public void setIdstatoparentela(Short idstatoparentela) {
        writeProperty("idstatoparentela", idstatoparentela);
    }
    public Short getIdstatoparentela() {
        return (Short)readProperty("idstatoparentela");
    }

    public void setOpzione(Short opzione) {
        writeProperty("opzione", opzione);
    }
    public Short getOpzione() {
        return (Short)readProperty("opzione");
    }

    public void setRapportoal(Date rapportoal) {
        writeProperty("rapportoal", rapportoal);
    }
    public Date getRapportoal() {
        return (Date)readProperty("rapportoal");
    }

    public void setRapportodal(Date rapportodal) {
        writeProperty("rapportodal", rapportodal);
    }
    public Date getRapportodal() {
        return (Date)readProperty("rapportodal");
    }

    public void setRedditoanno(BigDecimal redditoanno) {
        writeProperty("redditoanno", redditoanno);
    }
    public BigDecimal getRedditoanno() {
        return (BigDecimal)readProperty("redditoanno");
    }

    public void setRiceveassegno(Short riceveassegno) {
        writeProperty("riceveassegno", riceveassegno);
    }
    public Short getRiceveassegno() {
        return (Short)readProperty("riceveassegno");
    }

    public void setToPersonafisica1(Personafisica toPersonafisica1) {
        setToOneTarget("toPersonafisica1", toPersonafisica1, true);
    }

    public Personafisica getToPersonafisica1() {
        return (Personafisica)readProperty("toPersonafisica1");
    }


    public void setToPersonafisica2(Personafisica toPersonafisica2) {
        setToOneTarget("toPersonafisica2", toPersonafisica2, true);
    }

    public Personafisica getToPersonafisica2() {
        return (Personafisica)readProperty("toPersonafisica2");
    }


    public void setToRapportoParentela(Rapportoparentela toRapportoParentela) {
        setToOneTarget("toRapportoParentela", toRapportoParentela, true);
    }

    public Rapportoparentela getToRapportoParentela() {
        return (Rapportoparentela)readProperty("toRapportoParentela");
    }


    public void setToStatoParentela(Statoparentela toStatoParentela) {
        setToOneTarget("toStatoParentela", toStatoParentela, true);
    }

    public Statoparentela getToStatoParentela() {
        return (Statoparentela)readProperty("toStatoParentela");
    }


}
