package it.iubar.paghe.logic.anagrafica.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.SedeimpresaPat;

/**
 * Class _SedeimpresapatVoce was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SedeimpresapatVoce extends CayenneDataObject {

    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String IDSEDEIMPRESA_PROPERTY = "idsedeimpresa";
    public static final String IDVOCETARIFFA_PROPERTY = "idvocetariffa";
    public static final String PAT_PROPERTY = "pat";
    public static final String VOCETARIFFA_PROPERTY = "vocetariffa";
    public static final String TO_SEDEIMPRESA_PAT_PROPERTY = "toSedeimpresaPat";

    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";
    public static final String IDSEDEIMPRESA_PK_COLUMN = "IDSEDEIMPRESA";
    public static final String PAT_PK_COLUMN = "PAT";
    public static final String VOCETARIFFA_PK_COLUMN = "VOCETARIFFA";

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setIdsedeimpresa(Short idsedeimpresa) {
        writeProperty("idsedeimpresa", idsedeimpresa);
    }
    public Short getIdsedeimpresa() {
        return (Short)readProperty("idsedeimpresa");
    }

    public void setIdvocetariffa(Integer idvocetariffa) {
        writeProperty("idvocetariffa", idvocetariffa);
    }
    public Integer getIdvocetariffa() {
        return (Integer)readProperty("idvocetariffa");
    }

    public void setPat(String pat) {
        writeProperty("pat", pat);
    }
    public String getPat() {
        return (String)readProperty("pat");
    }

    public void setVocetariffa(String vocetariffa) {
        writeProperty("vocetariffa", vocetariffa);
    }
    public String getVocetariffa() {
        return (String)readProperty("vocetariffa");
    }

    public void setToSedeimpresaPat(SedeimpresaPat toSedeimpresaPat) {
        setToOneTarget("toSedeimpresaPat", toSedeimpresaPat, true);
    }

    public SedeimpresaPat getToSedeimpresaPat() {
        return (SedeimpresaPat)readProperty("toSedeimpresaPat");
    }


}
