package it.iubar.paghe.logic.anagrafica.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Sedeenpals was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Sedeenpals extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String IDSEDEENPALS_PROPERTY = "idsedeenpals";
    public static final String PROVINCIASIGLA_PROPERTY = "provinciasigla";

    public static final String IDSEDEENPALS_PK_COLUMN = "IDSEDEENPALS";

    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public String getIdsedeenpals() {
        return (String)readProperty("idsedeenpals");
    }

    public String getProvinciasigla() {
        return (String)readProperty("provinciasigla");
    }

}
