package it.iubar.paghe.logic.anagrafica.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Provincia;
import it.iubar.paghe.logic.anagrafica.Sedeimpresa;
import it.iubar.paghe.logic.anagrafica.Titolaredati;

/**
 * Class _Sedeinps was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Sedeinps extends CayenneDataObject {

    public static final String DENOMINAZIONE_PROPERTY = "denominazione";
    public static final String IDPROVINCIA_PROPERTY = "idprovincia";
    public static final String IDSEDEINPS_PROPERTY = "idsedeinps";
    public static final String PROVINCIASIGLA_PROPERTY = "provinciasigla";
    public static final String SEDEIMPRESA_ARRAY_PROPERTY = "sedeimpresaArray";
    public static final String TITOLAREDATI_ARRAY_PROPERTY = "titolaredatiArray";
    public static final String TO_PROVINCIA_PROPERTY = "toProvincia";
    public static final String TO_PROVINCIA_BY_SIGLA_PROPERTY = "toProvinciaBySigla";

    public static final String IDSEDEINPS_PK_COLUMN = "IDSEDEINPS";

    public String getDenominazione() {
        return (String)readProperty("denominazione");
    }

    public String getIdprovincia() {
        return (String)readProperty("idprovincia");
    }

    public String getIdsedeinps() {
        return (String)readProperty("idsedeinps");
    }

    public String getProvinciasigla() {
        return (String)readProperty("provinciasigla");
    }

    public void addToSedeimpresaArray(Sedeimpresa obj) {
        addToManyTarget("sedeimpresaArray", obj, true);
    }
    public void removeFromSedeimpresaArray(Sedeimpresa obj) {
        removeToManyTarget("sedeimpresaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Sedeimpresa> getSedeimpresaArray() {
        return (List<Sedeimpresa>)readProperty("sedeimpresaArray");
    }


    public void addToTitolaredatiArray(Titolaredati obj) {
        addToManyTarget("titolaredatiArray", obj, true);
    }
    public void removeFromTitolaredatiArray(Titolaredati obj) {
        removeToManyTarget("titolaredatiArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Titolaredati> getTitolaredatiArray() {
        return (List<Titolaredati>)readProperty("titolaredatiArray");
    }



    public Provincia getToProvincia() {
        return (Provincia)readProperty("toProvincia");
    }



    public Provincia getToProvinciaBySigla() {
        return (Provincia)readProperty("toProvinciaBySigla");
    }


}
