package it.iubar.paghe.logic.anagrafica.auto;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Impresa;
import it.iubar.paghe.logic.anagrafica.SpCategoria;

/**
 * Class _SpImpresa was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpImpresa extends CayenneDataObject {

    public static final String CODICEGRUPPO_PROPERTY = "codicegruppo";
    public static final String IDIMPRESA_PROPERTY = "idimpresa";
    public static final String NUMEROATTIVITA_PROPERTY = "numeroattivita";
    public static final String TO_IMPRESA_PROPERTY = "toImpresa";
    public static final String TO_SP_CATEGORIA_PROPERTY = "toSpCategoria";

    public static final String IDIMPRESA_PK_COLUMN = "IDIMPRESA";

    public void setCodicegruppo(String codicegruppo) {
        writeProperty("codicegruppo", codicegruppo);
    }
    public String getCodicegruppo() {
        return (String)readProperty("codicegruppo");
    }

    public void setIdimpresa(Integer idimpresa) {
        writeProperty("idimpresa", idimpresa);
    }
    public Integer getIdimpresa() {
        return (Integer)readProperty("idimpresa");
    }

    public void setNumeroattivita(Short numeroattivita) {
        writeProperty("numeroattivita", numeroattivita);
    }
    public Short getNumeroattivita() {
        return (Short)readProperty("numeroattivita");
    }

    public void setToImpresa(Impresa toImpresa) {
        setToOneTarget("toImpresa", toImpresa, true);
    }

    public Impresa getToImpresa() {
        return (Impresa)readProperty("toImpresa");
    }


    public void setToSpCategoria(SpCategoria toSpCategoria) {
        setToOneTarget("toSpCategoria", toSpCategoria, true);
    }

    public SpCategoria getToSpCategoria() {
        return (SpCategoria)readProperty("toSpCategoria");
    }


}
