package it.iubar.paghe.logic.anagrafica.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Indirizzo;
import it.iubar.paghe.logic.anagrafica.Lavoratore;
import it.iubar.paghe.logic.anagrafica.Personafisica;
import it.iubar.paghe.logic.anagrafica.Statoarea;
import it.iubar.paghe.logic.paghe.Posizionelavoratore;

/**
 * Class _Statoestero was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Statoestero extends CayenneDataObject {

    public static final String CITTADINANZA_PROPERTY = "cittadinanza";
    public static final String CITTADINANZA2_PROPERTY = "cittadinanza2";
    public static final String DENOMINAZIONE_PROPERTY = "denominazione";
    public static final String DENOMINAZIONE2_PROPERTY = "denominazione2";
    public static final String FINANZECOD_PROPERTY = "finanzecod";
    public static final String FINANZECODDATA_PROPERTY = "finanzecoddata";
    public static final String IDAGENZIAENTRATE_PROPERTY = "idagenziaentrate";
    public static final String IDAREA_PROPERTY = "idarea";
    public static final String IDSTATOESTERO_PROPERTY = "idstatoestero";
    public static final String IDSTATOESTEROCO_PROPERTY = "idstatoesteroco";
    public static final String IDSTATOESTEROINAIL_PROPERTY = "idstatoesteroinail";
    public static final String UE_PROPERTY = "ue";
    public static final String INDIRIZZO_ARRAY_PROPERTY = "indirizzoArray";
    public static final String LAVORATORE_ARRAY_PROPERTY = "lavoratoreArray";
    public static final String PERSONAFISICA_ARRAY_PROPERTY = "personafisicaArray";
    public static final String PERSONAFISICA_ARRAY1_PROPERTY = "personafisicaArray1";
    public static final String POSIZIONELAVORATORE_ARRAY_PROPERTY = "posizionelavoratoreArray";
    public static final String TO_STATOAREA_PROPERTY = "toStatoarea";

    public static final String IDSTATOESTERO_PK_COLUMN = "IDSTATOESTERO";

    public String getCittadinanza() {
        return (String)readProperty("cittadinanza");
    }

    public String getCittadinanza2() {
        return (String)readProperty("cittadinanza2");
    }

    public String getDenominazione() {
        return (String)readProperty("denominazione");
    }

    public String getDenominazione2() {
        return (String)readProperty("denominazione2");
    }

    public String getFinanzecod() {
        return (String)readProperty("finanzecod");
    }

    public Date getFinanzecoddata() {
        return (Date)readProperty("finanzecoddata");
    }

    public Integer getIdagenziaentrate() {
        return (Integer)readProperty("idagenziaentrate");
    }

    public Short getIdarea() {
        return (Short)readProperty("idarea");
    }

    public Integer getIdstatoestero() {
        return (Integer)readProperty("idstatoestero");
    }

    public String getIdstatoesteroco() {
        return (String)readProperty("idstatoesteroco");
    }

    public String getIdstatoesteroinail() {
        return (String)readProperty("idstatoesteroinail");
    }

    public Short getUe() {
        return (Short)readProperty("ue");
    }

    public void addToIndirizzoArray(Indirizzo obj) {
        addToManyTarget("indirizzoArray", obj, true);
    }
    public void removeFromIndirizzoArray(Indirizzo obj) {
        removeToManyTarget("indirizzoArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Indirizzo> getIndirizzoArray() {
        return (List<Indirizzo>)readProperty("indirizzoArray");
    }


    public void addToLavoratoreArray(Lavoratore obj) {
        addToManyTarget("lavoratoreArray", obj, true);
    }
    public void removeFromLavoratoreArray(Lavoratore obj) {
        removeToManyTarget("lavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lavoratore> getLavoratoreArray() {
        return (List<Lavoratore>)readProperty("lavoratoreArray");
    }


    public void addToPersonafisicaArray(Personafisica obj) {
        addToManyTarget("personafisicaArray", obj, true);
    }
    public void removeFromPersonafisicaArray(Personafisica obj) {
        removeToManyTarget("personafisicaArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Personafisica> getPersonafisicaArray() {
        return (List<Personafisica>)readProperty("personafisicaArray");
    }


    public void addToPersonafisicaArray1(Personafisica obj) {
        addToManyTarget("personafisicaArray1", obj, true);
    }
    public void removeFromPersonafisicaArray1(Personafisica obj) {
        removeToManyTarget("personafisicaArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Personafisica> getPersonafisicaArray1() {
        return (List<Personafisica>)readProperty("personafisicaArray1");
    }


    public void addToPosizionelavoratoreArray(Posizionelavoratore obj) {
        addToManyTarget("posizionelavoratoreArray", obj, true);
    }
    public void removeFromPosizionelavoratoreArray(Posizionelavoratore obj) {
        removeToManyTarget("posizionelavoratoreArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Posizionelavoratore> getPosizionelavoratoreArray() {
        return (List<Posizionelavoratore>)readProperty("posizionelavoratoreArray");
    }



    public Statoarea getToStatoarea() {
        return (Statoarea)readProperty("toStatoarea");
    }


}
