package it.iubar.paghe.logic.anagrafica.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import it.iubar.paghe.logic.anagrafica.Lavoratore;
import it.iubar.paghe.logic.paghe.Assunzione;
import it.iubar.paghe.logic.paghe.Cessazione;
import it.iubar.paghe.logic.paghe.Contrattodettaglio;
import it.iubar.paghe.logic.paghe.Contrattodettagliolivello;
import it.iubar.paghe.logic.paghe.InpsContratto;
import it.iubar.paghe.logic.paghe.InpsQualifica1;
import it.iubar.paghe.logic.paghe.InpsQualifica2;
import it.iubar.paghe.logic.paghe.InpsQualifica3;
import it.iubar.paghe.logic.paghe.InpsSettore;
import it.iubar.paghe.logic.paghe.InpsTipocontribuzione;
import it.iubar.paghe.logic.paghe.InpsTipolavoratore;

/**
 * Class _Subordinato was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Subordinato extends CayenneDataObject {

    public static final String CARTELLINO_PROPERTY = "cartellino";
    public static final String IDASSUNZIONE_PROPERTY = "idassunzione";
    public static final String IDCESSAZIONE_PROPERTY = "idcessazione";
    public static final String IDCONTRATTODETTAGLIO_PROPERTY = "idcontrattodettaglio";
    public static final String IDINPSCONTRATTO_PROPERTY = "idinpscontratto";
    public static final String IDINPSQUALIFICA1_PROPERTY = "idinpsqualifica1";
    public static final String IDINPSQUALIFICA2_PROPERTY = "idinpsqualifica2";
    public static final String IDINPSQUALIFICA3_PROPERTY = "idinpsqualifica3";
    public static final String IDINPSSETTORE_PROPERTY = "idinpssettore";
    public static final String IDINPSTIPOAPPRENDISTATO_PROPERTY = "idinpstipoapprendistato";
    public static final String IDINPSTIPOLAVORATORE_PROPERTY = "idinpstipolavoratore";
    public static final String IDLAVORATORE_PROPERTY = "idlavoratore";
    public static final String IDLIVELLO_PROPERTY = "idlivello";
    public static final String PARTTIMECONTRATTO_PROPERTY = "parttimecontratto";
    public static final String PERIODOAL_PROPERTY = "periodoal";
    public static final String PERIODODAL_PROPERTY = "periododal";
    public static final String SCADENZAQUALIFICA2_PROPERTY = "scadenzaqualifica2";
    public static final String SCADENZAQUALIFICA3_PROPERTY = "scadenzaqualifica3";
    public static final String SCADENZATIPOCONTRIB_PROPERTY = "scadenzatipocontrib";
    public static final String TO_ASSUNZIONE_PROPERTY = "toAssunzione";
    public static final String TO_CESSAZIONE_PROPERTY = "toCessazione";
    public static final String TO_CONTRATTODETTAGLIO_PROPERTY = "toContrattodettaglio";
    public static final String TO_CONTRATTODETTAGLIOLIVELLO_PROPERTY = "toContrattodettagliolivello";
    public static final String TO_INPS_CONTRATTO_PROPERTY = "toInpsContratto";
    public static final String TO_LAVORATORE_PROPERTY = "toLavoratore";
    public static final String TO_QUALIFICA1_PROPERTY = "toQualifica1";
    public static final String TO_QUALIFICA2_PROPERTY = "toQualifica2";
    public static final String TO_QUALIFICA3_PROPERTY = "toQualifica3";
    public static final String TO_SETTORE_PROPERTY = "toSettore";
    public static final String TO_TIPOCONTRIBUZIONE_PROPERTY = "toTipocontribuzione";
    public static final String TO_TIPOLAVORATORE_PROPERTY = "toTipolavoratore";

    public static final String IDLAVORATORE_PK_COLUMN = "IDLAVORATORE";

    public void setCartellino(String cartellino) {
        writeProperty("cartellino", cartellino);
    }
    public String getCartellino() {
        return (String)readProperty("cartellino");
    }

    public void setIdassunzione(Integer idassunzione) {
        writeProperty("idassunzione", idassunzione);
    }
    public Integer getIdassunzione() {
        return (Integer)readProperty("idassunzione");
    }

    public void setIdcessazione(Integer idcessazione) {
        writeProperty("idcessazione", idcessazione);
    }
    public Integer getIdcessazione() {
        return (Integer)readProperty("idcessazione");
    }

    public void setIdcontrattodettaglio(Integer idcontrattodettaglio) {
        writeProperty("idcontrattodettaglio", idcontrattodettaglio);
    }
    public Integer getIdcontrattodettaglio() {
        return (Integer)readProperty("idcontrattodettaglio");
    }

    public void setIdinpscontratto(String idinpscontratto) {
        writeProperty("idinpscontratto", idinpscontratto);
    }
    public String getIdinpscontratto() {
        return (String)readProperty("idinpscontratto");
    }

    public void setIdinpsqualifica1(String idinpsqualifica1) {
        writeProperty("idinpsqualifica1", idinpsqualifica1);
    }
    public String getIdinpsqualifica1() {
        return (String)readProperty("idinpsqualifica1");
    }

    public void setIdinpsqualifica2(String idinpsqualifica2) {
        writeProperty("idinpsqualifica2", idinpsqualifica2);
    }
    public String getIdinpsqualifica2() {
        return (String)readProperty("idinpsqualifica2");
    }

    public void setIdinpsqualifica3(String idinpsqualifica3) {
        writeProperty("idinpsqualifica3", idinpsqualifica3);
    }
    public String getIdinpsqualifica3() {
        return (String)readProperty("idinpsqualifica3");
    }

    public void setIdinpssettore(Integer idinpssettore) {
        writeProperty("idinpssettore", idinpssettore);
    }
    public Integer getIdinpssettore() {
        return (Integer)readProperty("idinpssettore");
    }

    public void setIdinpstipoapprendistato(String idinpstipoapprendistato) {
        writeProperty("idinpstipoapprendistato", idinpstipoapprendistato);
    }
    public String getIdinpstipoapprendistato() {
        return (String)readProperty("idinpstipoapprendistato");
    }

    public void setIdinpstipolavoratore(String idinpstipolavoratore) {
        writeProperty("idinpstipolavoratore", idinpstipolavoratore);
    }
    public String getIdinpstipolavoratore() {
        return (String)readProperty("idinpstipolavoratore");
    }

    public void setIdlavoratore(Integer idlavoratore) {
        writeProperty("idlavoratore", idlavoratore);
    }
    public Integer getIdlavoratore() {
        return (Integer)readProperty("idlavoratore");
    }

    public void setIdlivello(String idlivello) {
        writeProperty("idlivello", idlivello);
    }
    public String getIdlivello() {
        return (String)readProperty("idlivello");
    }

    public void setParttimecontratto(BigDecimal parttimecontratto) {
        writeProperty("parttimecontratto", parttimecontratto);
    }
    public BigDecimal getParttimecontratto() {
        return (BigDecimal)readProperty("parttimecontratto");
    }

    public void setPeriodoal(Date periodoal) {
        writeProperty("periodoal", periodoal);
    }
    public Date getPeriodoal() {
        return (Date)readProperty("periodoal");
    }

    public void setPeriododal(Date periododal) {
        writeProperty("periododal", periododal);
    }
    public Date getPeriododal() {
        return (Date)readProperty("periododal");
    }

    public void setScadenzaqualifica2(Date scadenzaqualifica2) {
        writeProperty("scadenzaqualifica2", scadenzaqualifica2);
    }
    public Date getScadenzaqualifica2() {
        return (Date)readProperty("scadenzaqualifica2");
    }

    public void setScadenzaqualifica3(Date scadenzaqualifica3) {
        writeProperty("scadenzaqualifica3", scadenzaqualifica3);
    }
    public Date getScadenzaqualifica3() {
        return (Date)readProperty("scadenzaqualifica3");
    }

    public void setScadenzatipocontrib(Date scadenzatipocontrib) {
        writeProperty("scadenzatipocontrib", scadenzatipocontrib);
    }
    public Date getScadenzatipocontrib() {
        return (Date)readProperty("scadenzatipocontrib");
    }

    public void setToAssunzione(Assunzione toAssunzione) {
        setToOneTarget("toAssunzione", toAssunzione, true);
    }

    public Assunzione getToAssunzione() {
        return (Assunzione)readProperty("toAssunzione");
    }


    public void setToCessazione(Cessazione toCessazione) {
        setToOneTarget("toCessazione", toCessazione, true);
    }

    public Cessazione getToCessazione() {
        return (Cessazione)readProperty("toCessazione");
    }


    public void setToContrattodettaglio(Contrattodettaglio toContrattodettaglio) {
        setToOneTarget("toContrattodettaglio", toContrattodettaglio, true);
    }

    public Contrattodettaglio getToContrattodettaglio() {
        return (Contrattodettaglio)readProperty("toContrattodettaglio");
    }


    public void setToContrattodettagliolivello(Contrattodettagliolivello toContrattodettagliolivello) {
        setToOneTarget("toContrattodettagliolivello", toContrattodettagliolivello, true);
    }

    public Contrattodettagliolivello getToContrattodettagliolivello() {
        return (Contrattodettagliolivello)readProperty("toContrattodettagliolivello");
    }


    public void setToInpsContratto(InpsContratto toInpsContratto) {
        setToOneTarget("toInpsContratto", toInpsContratto, true);
    }

    public InpsContratto getToInpsContratto() {
        return (InpsContratto)readProperty("toInpsContratto");
    }


    public void setToLavoratore(Lavoratore toLavoratore) {
        setToOneTarget("toLavoratore", toLavoratore, true);
    }

    public Lavoratore getToLavoratore() {
        return (Lavoratore)readProperty("toLavoratore");
    }


    public void setToQualifica1(InpsQualifica1 toQualifica1) {
        setToOneTarget("toQualifica1", toQualifica1, true);
    }

    public InpsQualifica1 getToQualifica1() {
        return (InpsQualifica1)readProperty("toQualifica1");
    }


    public void setToQualifica2(InpsQualifica2 toQualifica2) {
        setToOneTarget("toQualifica2", toQualifica2, true);
    }

    public InpsQualifica2 getToQualifica2() {
        return (InpsQualifica2)readProperty("toQualifica2");
    }


    public void setToQualifica3(InpsQualifica3 toQualifica3) {
        setToOneTarget("toQualifica3", toQualifica3, true);
    }

    public InpsQualifica3 getToQualifica3() {
        return (InpsQualifica3)readProperty("toQualifica3");
    }


    public void setToSettore(InpsSettore toSettore) {
        setToOneTarget("toSettore", toSettore, true);
    }

    public InpsSettore getToSettore() {
        return (InpsSettore)readProperty("toSettore");
    }


    public void setToTipocontribuzione(InpsTipocontribuzione toTipocontribuzione) {
        setToOneTarget("toTipocontribuzione", toTipocontribuzione, true);
    }

    public InpsTipocontribuzione getToTipocontribuzione() {
        return (InpsTipocontribuzione)readProperty("toTipocontribuzione");
    }


    public void setToTipolavoratore(InpsTipolavoratore toTipolavoratore) {
        setToOneTarget("toTipolavoratore", toTipolavoratore, true);
    }

    public InpsTipolavoratore getToTipolavoratore() {
        return (InpsTipolavoratore)readProperty("toTipolavoratore");
    }


}
