package it.iubar.paghe.logic.anagrafica.auto;

/** Class _UtenteRuolo was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _UtenteRuolo extends org.apache.cayenne.CayenneDataObject {

    public static final String CUSTOM_PROPERTY = "custom";
    public static final String IDRUOLO_PROPERTY = "idruolo";
    public static final String IDTARGET_PROPERTY = "idtarget";
    public static final String ULTIMAMODIFICA_PROPERTY = "ultimamodifica";
    public static final String USERNAME_PROPERTY = "username";
    public static final String TO_RUOLO_PROPERTY = "toRuolo";
    public static final String TO_TARGET_PROPERTY = "toTarget";
    public static final String TO_UTENTE_PROPERTY = "toUtente";

    public static final String IDRUOLO_PK_COLUMN = "IDRUOLO";
    public static final String IDTARGET_PK_COLUMN = "IDTARGET";
    public static final String USERNAME_PK_COLUMN = "USERNAME";

    public void setCustom(Short custom) {
        writeProperty("custom", custom);
    }
    public Short getCustom() {
        return (Short)readProperty("custom");
    }
    
    
    public void setIdruolo(Short idruolo) {
        writeProperty("idruolo", idruolo);
    }
    public Short getIdruolo() {
        return (Short)readProperty("idruolo");
    }
    
    
    public void setIdtarget(Short idtarget) {
        writeProperty("idtarget", idtarget);
    }
    public Short getIdtarget() {
        return (Short)readProperty("idtarget");
    }
    
    
    public void setUltimamodifica(java.util.Date ultimamodifica) {
        writeProperty("ultimamodifica", ultimamodifica);
    }
    public java.util.Date getUltimamodifica() {
        return (java.util.Date)readProperty("ultimamodifica");
    }
    
    
    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }
    
    
    public void setToRuolo(it.iubar.paghe.logic.anagrafica.Ruolo toRuolo) {
        setToOneTarget("toRuolo", toRuolo, true);
    }

    public it.iubar.paghe.logic.anagrafica.Ruolo getToRuolo() {
        return (it.iubar.paghe.logic.anagrafica.Ruolo)readProperty("toRuolo");
    } 
    
    
    public void setToTarget(it.iubar.paghe.logic.anagrafica.Target toTarget) {
        setToOneTarget("toTarget", toTarget, true);
    }

    public it.iubar.paghe.logic.anagrafica.Target getToTarget() {
        return (it.iubar.paghe.logic.anagrafica.Target)readProperty("toTarget");
    } 
    
    
    public void setToUtente(it.iubar.paghe.logic.anagrafica.Utente toUtente) {
        setToOneTarget("toUtente", toUtente, true);
    }

    public it.iubar.paghe.logic.anagrafica.Utente getToUtente() {
        return (it.iubar.paghe.logic.anagrafica.Utente)readProperty("toUtente");
    } 
    
    
}
